<html>

<head>
<meta http-equiv="Content-Type" content="text/html; charset=windows-1252">
<meta name="GENERATOR" content="Microsoft FrontPage 6.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
<link rel="stylesheet" type="text/css" href="../CAAScrBase/caav5.css">
<title>Delete Part</title>
</head>

<body>

<table border="0" width="100%">
  <tr>
    <td>
      <h2>Distributive Systems</h2>
    </td>
    <td align="right" valign="top">
      <h2><a name="Top"></a>Delete Part</h2>
    </td>
  </tr>
</table>
<hr>
<!---------------------------------comment------------------------------------->
<table border="0" width="100%">
  <tr>
    <td width="7%" valign="top"><img border="0" src="../CAAScrBase/images/atarget.gif" width="32" height="32"></td>
    <td width="93%">
      <p><a name="Learn"></a>This use case is intended to show you how to
      delete a Group part object and then a Logical line
      object.</p>
      <p>This macro opens the document CAAPsp3DEduIn.CATProduct. Using the root
      node of the document, it initializes the Piping application, creates
      a Group and a Line object and then deletes them.</p>
    </td>
  </tr>
  <tr>
    <td width="7%" valign="top"><img border="0" src="../CAAScrBase/images/ainfo.gif" width="32" height="32"></td>
    <td width="93%">
      <p><a name="How"></a>CAAPspDeletePart is launched in CATIA [<a href="#References">1</a>].
      No open document is needed.</p>
      <p><a href="CAAPspDeletePartSource.htm">CAAPspDeletePart.CATScript</a>
      is located in the CAAScdPspUseCases module. <a href="macros/CAAPspDeletePart.CATScript">Execute
      macro</a> (windows only).</p>
    </td>
  </tr>
  <tr>
    <td width="7%" valign="top"><img border="0" src="../CAAScrBase/images/ascenari.gif" width="32" height="32"></td>
    <td width="93%">
      <p><a name="Step"></a>CAAPspLogicalLine includes the following
      steps:</p>
      <ol>
        <li><a href="#Prolog">Prolog</a></li>
        <li><a href="#Initialize Piping Application">Initialize Piping
          Application</a></li>
        <li><a href="#Create Group">Create Group</a></li>
        <li><a href="#Delete Group">Delete Group Object</a></li>
        <li><a href="#Create Logical Line Instance">Create Logical Line Instance</a></li>
        <li><a href="#Delete Logical Line">Delete Logical Line instance</a></li>
      </ol>
      <h4><a name="Prolog"></a>Prolog</h4>
      <p>The macro first loads Distributive System document
      CAAPsp3DEduIn.CATProduct containing Equipment and Piping Design objects.</p>
      <p><i>Note</i>: To open a different document, modify the variable <i>sDocPath</i>
      to point to the document directory and <i>sDocFullPath</i> to point to
      full path name of the document.</p>
      <pre>   <font color="#008000">... </font>
<font color="#008000">   ' ------------------------------------------------------------------</font>
    <font color="#008000">' Open the Distributive system document </font>
<font color="#0000FF">    Dim </font>objPspDoc<font color="#0000FF"> As </font>Document

    sDocFullPath = CATIA.FileSystem.ConcatenatePaths(sDocPath, _
		      &quot;\online\CAAScdPspUseCases\samples\CAAPspEduIn.CATProduct&quot;)

<font color="#0000FF">    If </font>(CATIA.FileSystem.FileExists(sDocFullPath) = False)<font color="#0000FF"> then </font>
        MsgBox sDocFullPath &amp; &quot; doesn't exist&quot; 
<font color="#0000FF">        Exit Sub</font>
<font color="#0000FF">    End IF</font>
       
    strMessage_g = sDocFullPath
    <font color="#008000">'MsgBox strMessage_g</font>
<font color="#0000FF">    Set </font>objPspDoc = CATIA.Documents.Open(sDocFullPath)
    <font color="#008000">...</font></pre>
      <p>Next, the macro acquires the <i>PspWorkbench</i> object from the
      document using the top node of the object tree in a Distributive
      System document.</p>
      <pre>    <font color="#008000">...</font>
    <font color="#008000">'---------------------------------------------------------</font>
    <font color="#008000">' Find the top node (PspWorkbench) of the Distributive System object tree - .  </font>
    
<font color="#0000FF">    If </font>( Not ( objPspDoc Is Nothing ) )<font color="#0000FF"> Then</font>
<font color="#0000FF">      Set </font>objPrdRoot = objPspDoc.Product
<font color="#0000FF">      If </font>( Not ( objPrdRoot Is Nothing ) )<font color="#0000FF"> Then</font>
<font color="#0000FF">        Set </font>objPspWorkbench = objPrdRoot.GetTechnologicalObject (&quot;PspWorkbench&quot;)
<font color="#0000FF">      End If</font>
<font color="#0000FF">    End If</font>
    <font color="#008000">...</font></pre>
      <h4><a name="Initialize Piping Application"></a>Initialize Piping Application</h4>
      <p>From the <i>objPspWorkbench</i> object, following objects can be obtained.</p>
      <ol>
        <li>Application (CATIAPspApplication) object <i>objPspApplication</i>
          using the <i>
          GetApplication</i> method for the piping application.
        <li>Application factory object (CATIAPspAppfactory) <i>objPspAppFactory</i>
          corresponding to Piping Application by using the <i> GetInterface</i> method.</li>
      </ol>
      <pre><font color="#008000">    ...</font>
<font color="#0000FF">    If </font>( Not ( objPspWorkbench Is Nothing ) )<font color="#0000FF"> Then</font>
<font color="#0000FF">      Set </font>objPspApplication = objPspWorkbench.GetApplication(catPspIDLCATPiping)

<font color="#0000FF">      If </font>( Not(objPspApplication Is Nothing)  )<font color="#0000FF"> Then</font>
        strMessage_g = strMessage_g &amp; &quot;Success in getting objPspApplication&quot; _
                                                       &amp; vbCr      
        objPspApplication.Initialization()             
<font color="#0000FF">      End If</font>
<font color="#0000FF">    End If </font><font color="#008000">'--- If ( Not ( objPspWorkbench Is Nothing )...</font>
<font color="#0000FF">    </font><font color="#008000">...</font>
<font color="#0000FF">    If </font>( Not ( objPspWorkbench Is Nothing ) And _
         Not ( objPspApplication Is Nothing ) )<font color="#0000FF"> Then</font>
<font color="#0000FF">      Dim </font>objLGroups       <font color="#0000FF"> As </font>PspListOfObjects      
<font color="#0000FF">      Dim </font>objPspGroup      <font color="#0000FF"> As </font>PspGroup
                        
<font color="#0000FF">      Set </font>objPspAppFactory = objPspWorkbench.Ge<font color="#0000FF">tInt</font>erface( _
                                &quot;CATIAPspAppFactory&quot;, objPspApplication )
    <font color="#008000">...</font></pre>
      <h4><a name="Create Group"></a>Create Group</h4>
      <p>It then uses Application factory object <i>objPspAppFactory</i> to
      create a Group object <i>objPspGroup</i> by calling its <i>CreateGroup</i>
      function. <i>CreateGroup</i> function takes in GroupType and
      the Group ID of the object as the input parameters and returns the created
      Group object as the output.</p>
      <pre>    <font color="#008000">...   </font>
<font color="#0000FF">      If </font>( Not ( objPspAppFactory Is Nothing ) )<font color="#0000FF"> Then      </font>
<font color="#0000FF">        Dim </font>strGroupType<font color="#0000FF"> As </font>String
<font color="#0000FF">        Dim </font>strGroupID<font color="#0000FF"> As </font>String
        strGroupType = &quot;CATPipSpool&quot;
        strGroupID   = &quot;PipingSpoolID&quot;
<font color="#0000FF">        Set </font>objPspGroup = objPspAppFactory.CreateGroup (objPrdRoot, _            
                           strGroupType, strGroupID)
    <font color="#008000">...</font></pre>
    <h4><a name="Delete Group"></a>Delete Group Object</h4>
    <p>Macro uses Application factory object <i>objPspAppFactory</i> is to
      delete the Group object <i>objPspGroup</i> by calling
      its <i>DeleteGroup</i> function.</p>
      <pre>       <font color="#008000">...</font>
      <font color="#008000">     '-------------------------------------------</font>
        <font color="#008000">   ' Delete group</font>

<font color="#0000FF">           If </font>( Not (objPspGroup Is Nothing) )<font color="#0000FF"> Then</font>
             objPspAppFactory.DeleteGroup objPspGroup
             strMessage_g = strMessage_g &amp; &quot;Deleted Group successfully :&quot; _
                                         &amp; strGroupID  &amp; vbCr
<font color="#0000FF">           End If</font>  
       <font color="#008000">...</font></pre>
<h4><a name="Create Logical Line Instance"></a>Create Logical Line Instance</h4><p>Macro uses Application factory object <i>objPspAppFactory</i>
      to create a Logical Line object <i>objPspLogLine</i> by calling its <i>GetLogicalLine</i>()
      function. <i>GetLogicalLine</i> function takes in the Line ID
      of the object as the input parameter and returns the created Logical Line
      instance as the output.</p>
      <pre>       <font color="#008000">...</font>
<font color="#0000FF">         </font>strLineID = &quot;U1-P103-6in-CS150R-FG&quot;

        <font color="#008000"> ' ---------------------</font>
        <font color="#008000"> ' Create line instance</font>
<font color="#0000FF">         Set </font>objPspLogLine = objPspAppFactory.GetLogicalLine (objPrdRoot, _
                           strLineID )
 
<font color="#0000FF">         If </font>( Not (objPspLogLine Is Nothing) )<font color="#0000FF"> Then</font>
           strMessage_g = strMessage_g &amp; &quot;Create logical line instance ID = &quot; _
                                       &amp;  strLineID &amp; vbCr  
<font color="#0000FF">         End If </font>
      <font color="#008000"> ...</font></pre><h4><a name="Delete Logical Line"></a>Delete Logical Line Instance</h4><p>Macro uses Application factory object <i>objPspAppFactory</i> is to
      delete the Line object <i>objPspLogLine</i> by calling its <i>DeleteLogicalLine</i>
      function.</p><pre>       <font color="#008000">...</font>
         <font color="#008000">'-------------------------------------------</font>
         <font color="#008000">' Delete Line</font>
         <font color="#008000">'-------------------------------------------</font>

<font color="#0000FF">         If </font>( Not (objPspLogLine Is Nothing) )<font color="#0000FF"> Then</font>
           objPspAppFactory.DeleteLogicalLine objPspLogLine
           strMessage_g = strMessage_g &amp; &quot;Deleted Line successfully :&quot; &amp; _
                                          strLineID  &amp; vbCr
<font color="#0000FF">         End If</font>
       <font color="#008000">...</font></pre></td></tr></table><p align="right">[<a href="#Top">Top</a>]</p><hr>
<!-- ------------------------------comment---------------------------- -->
<h4><a name="InShort"></a>In Short</h4><p>This use case shows how to delete a group part object . A message logging the status of the critical steps is
displayed at the end of the use case.</p><p><img border="0" src="images/CAAPspDeletePart_01.jpg" width="636" height="489"></p><p align="right">[<a href="#Top">Top</a>]</p><hr>
<!-- ------------------------------comment---------------------------- -->
<h4><a name="References"></a>References</h4><table border="0" width="100%">
  <tr>
    <td valign="top">[1]</td><td><a href="CAAPspDeletePart.htm">Replaying a macro</a></td></tr><tr>
    <td colspan="2" align="right" width="100%">[<a href="#Top">Top</a>]</td></tr></table><hr>
<!-- ------------------------------comment---------------------------- -->
<p><i>Copyright © 2004, Dassault Systèmes. All rights reserved.</i></p></body></html>
