<html><head><meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"><title>CAAPspDisconnectParts.CATScript</title><link rel="stylesheet" type="text/css" href="../CAAScrBase/caav5.css"></head><body><pre>
<font color="#0000FF">Option Explicit</font>
<font color="#008000">' COPYRIGHT DASSAULT SYSTEMES 2005</font>

<font color="#008000">' *****************************************************************************</font>
<font color="#008000">'   Purpose:      This sample checks how to check if two parts are connected.</font>
<font color="#008000">'                 Furthermore, if the parts are connected they are disconnected.</font>
<font color="#008000">'   Assumption:   Looks for document CAAPspEduIn.CATProduct</font>
<font color="#008000">'                 Looks for objects  V-117 and Gasket-012</font>
<font color="#008000">'               </font>
<font color="#008000">'   Languages:    VBScript</font>
<font color="#008000">'   Locales:      English </font>
<font color="#008000">'   CATIA Level:  V5R15 </font>
<font color="#008000">' *****************************************************************************</font>

<font color="#008000">'--- strMessage_g is a global variable visible to all private Sub/Function</font>

<font color="#0000FF">Dim </font>strMessage_g<font color="#0000FF"> As </font>String


<font color="#0000FF">Sub </font>CATMain()

    <font color="#008000">' ------------------------------------------------------------------------- </font>
    <font color="#008000">' Optional: allows to find the sample wherever it's installed</font>
<font color="#0000FF">    dim </font>sDocPath<font color="#0000FF"> As </font>String 
<font color="#0000FF">    dim </font>sDocFullPath<font color="#0000FF"> As </font>String 
    sDocPath=CATIA.SystemService.Environ("CATDocView")

<font color="#0000FF">    If </font>(Not CATIA.FileSystem.FolderExists(sDocPath))<font color="#0000FF"> Then</font>
      Err.Raise 9999,sDocPath,"No Doc Path Defined"
<font color="#0000FF">    End If</font>

    <font color="#008000">' ------------------------------------------------------------------------- </font>
    <font color="#008000">' Open the Distributive system document </font>
<font color="#0000FF">    Dim </font>objPspDoc<font color="#0000FF"> As </font>Document

    sDocFullPath = CATIA.FileSystem.ConcatenatePaths(sDocPath, _    
       "online\CAAScdPspUseCases\samples\CAAPspEduIn.CATProduct" )
    
    
<font color="#0000FF">    Set </font>objPspDoc = CATIA.Documents.Open(sDocFullPath)


    strMessage_g = _
      "--------------------------------------------------------------------" & vbCr
    strMessage_g = strMessage_g & _
      "Output traces from CAAPspDisconnectParts.CATScript" & vbCrLf


<font color="#0000FF">    Dim </font>objPrdRoot       <font color="#0000FF"> As </font>Product
<font color="#0000FF">    Dim </font>objPspWorkbench  <font color="#0000FF"> As </font>PspWorkbench
    
    <font color="#008000">'-----------------------------------------------</font>
    <font color="#008000">' Find the top node of the Distributive System object tree - .  </font>
    
<font color="#0000FF">    If </font>( Not ( objPspDoc Is Nothing ) )<font color="#0000FF"> Then</font>
<font color="#0000FF">      Set </font>objPrdRoot = objPspDoc.Product 
<font color="#0000FF">      If </font>( Not ( objPrdRoot Is Nothing ) )<font color="#0000FF"> Then</font>
<font color="#0000FF">        Set </font>objPspWorkbench = objPrdRoot.GetTechnologicalObject ("PspWorkbench")
<font color="#0000FF">      End If</font>
<font color="#0000FF">    End If</font>


<font color="#0000FF">    Dim </font>objPspApplication<font color="#0000FF"> As </font>PspApplication
<font color="#0000FF">    Dim </font>objPspAppFactory <font color="#0000FF"> As </font>PspAppFactory
    
    
    
<font color="#0000FF">    Dim </font>ePspIDLDomainID  <font color="#0000FF"> As </font>CatPspIDLDomainID    
<font color="#0000FF">    Dim </font>iIdx           <font color="#0000FF"> As </font>Integer


    ePspIDLDomainID = catPspIDLCATPIP            

    <font color="#008000">'-----------------------------------------------------------------------</font>
    <font color="#008000">' Get PspWorkBench, PspApplication </font>
    <font color="#008000">'-----------------------------------------------------------------------</font>

<font color="#0000FF">    If </font>( objPspWorkbench Is Nothing  )<font color="#0000FF"> Then</font>
      strMessage_g = strMessage_g & "Unable to get PspWorkbench" & vbCr                
    Else
      strMessage_g = strMessage_g & "Success in getting PspWorkbench" & vbCr                           
<font color="#0000FF">    End If</font>

<font color="#0000FF">    If </font>( Not ( objPspWorkbench Is Nothing ) )<font color="#0000FF"> Then</font>
<font color="#0000FF">      Set </font>objPspApplication = objPspWorkbench.GetApplication(catPspIDLCATPiping)

<font color="#0000FF">      If </font>( Not( objPspApplication Is Nothing )  )<font color="#0000FF"> Then        </font>
        strMessage_g = strMessage_g & "Success in getthing objPspApplication" & vbCr      
        objPspApplication.Initialization()             
<font color="#0000FF">      End If</font>
<font color="#0000FF">    End If </font><font color="#008000">'--- If ( Not ( objPspWorkbench Is Nothing )...</font>
    

    <font color="#008000">'-----------------------------------------------------------------------</font>
    <font color="#008000">' Get list of physical (3D) objects in the Piping domain</font>
    <font color="#008000">'-----------------------------------------------------------------------</font>
<font color="#0000FF">    Dim </font>objLPhysicals    <font color="#0000FF"> As </font>PspListOfObjects
<font color="#0000FF">    If </font>( Not ( objPspWorkbench Is Nothing ) And _
         Not ( objPspApplication Is Nothing ) )<font color="#0000FF"> Then</font>
                        
<font color="#0000FF">      Set </font>objPspAppFactory = objPspWorkbench.Ge<font color="#0000FF">tInt</font>erface("CATIAPspAppFactory", _
                                                objPspApplication )      
      
<font color="#0000FF">      If </font>( Not ( objPspAppFactory Is Nothing ) )<font color="#0000FF"> Then      </font>
        
<font color="#0000FF">        Set </font>objLPhysicals = objPspAppFactory.ListPhysicals( objPrdRoot, catPspIDLCATPIP)
        
<font color="#0000FF">      End If</font>

<font color="#0000FF">    End If </font><font color="#008000">'--- If ( Not ( objPspWorkbench Is Nothing ) and objPspApplication</font>

    <font color="#008000">'</font>
    <font color="#008000">' --------------------------------------------------------------</font>
    <font color="#008000">' Get PspConnectable object corresponding to  Valve with ID=V-117 </font>
    <font color="#008000">' and Gasket whose ID = Gasket-012    </font>
    <font color="#008000">' ---------------------------------------------------------------</font>

<font color="#0000FF">    Dim </font>objValveCtbl   <font color="#0000FF"> As </font> PspConnectable
<font color="#0000FF">    Dim </font>objGasketCtbl  <font color="#0000FF"> As </font> PspConnectable
    
<font color="#0000FF">    If </font>( Not ( objLPhysicals Is Nothing ) And _
       ( objLPhysicals.Count &gt; 0 ) )<font color="#0000FF"> Then      </font>
<font color="#0000FF">      Set </font>objValveCtbl  = FindPipingPartByID (objLPhysicals, "V-117")
<font color="#0000FF">      Set </font>objGasketCtbl = FindPipingPartByID (objLPhysicals,"Gasket-012")

<font color="#0000FF">    End If</font>
    
    <font color="#008000">'-----------------------------------------------------------------------</font>
    <font color="#008000">' Get Connnected objects on the valve to see if Gasket-012 is connected </font>
    <font color="#008000">' to V-117</font>
    <font color="#008000">'-----------------------------------------------------------------------</font>

<font color="#0000FF">    If </font>( Not (objValveCtbl Is Nothing)  And _
         Not (objGasketCtbl Is Nothing))<font color="#0000FF"> Then</font>
      strMessage_g = strMessage_g & "Found Valve and Gasket"  & vbCr               
    
<font color="#0000FF">      Dim </font>objLClassFilter       <font color="#0000FF"> As </font>CATIAPspListOfBSTRs
<font color="#0000FF">      Dim </font>objLCntbles           <font color="#0000FF"> As </font>PspListOfObjects
<font color="#0000FF">      Dim </font>objLCntrsOnThisObj    <font color="#0000FF"> As </font>PspListOfObjects
<font color="#0000FF">      Dim </font>objLCntrsOnConnected  <font color="#0000FF"> As </font>PspListOfObjects     
                  
<font color="#0000FF">      Dim </font>iIdxOfGasket        <font color="#0000FF"> As </font>Integer
      
      iIdxOfGasket = 0
<font color="#0000FF">      Set </font>objLClassFilter = Nothing
      objValveCtbl.ListConnectables objLClassFilter, objLCntbles, _
                           objLCntrsOnThisObj,  objLCntrsOnConnected 
              

<font color="#0000FF">      If </font>( Not ( objLCntbles Is Nothing ) )<font color="#0000FF"> Then       </font>
<font color="#0000FF">        Dim </font>objAIDCntbl           <font color="#0000FF"> As </font>PspID
        strMessage_g = strMessage_g & _
          "Number of Connected objects= " &  objLCntbles.Count & vbCr          

<font color="#0000FF">        For </font>iIdx = 1<font color="#0000FF"> To </font>objLCntbles.Count 
<font color="#0000FF">          Set </font>objAIDCntbl = objLCntbles.Item (iIdx, "CATIAPspID")          
<font color="#0000FF">          Dim </font>strCntdID<font color="#0000FF"> As </font>String
<font color="#0000FF">          If </font>( Not (objAIDCntbl Is Nothing) )<font color="#0000FF"> Then</font>
            strCntdID = objAIDCntbl.GetID
<font color="#0000FF">            If </font>( strCntdID = "Gasket-012" ) Then
              iIdxOfGasket = iIdx
<font color="#0000FF">              Exit For          </font><font color="#008000">' Exit out of the for loop</font>
<font color="#0000FF">            End If             </font>
<font color="#0000FF">          End If           </font>
<font color="#0000FF">        Next      </font>
<font color="#0000FF">      End If</font>

      <font color="#008000">'---------------------------------------</font>
      <font color="#008000">' To Disconnect V-117 and Gasket-012</font>
      <font color="#008000">'  get correspoding connectors from the lists objLCntrsOnThisObj</font>
      <font color="#008000">' and objLCntrsOnConnected at location at index=iIdxOfGasket</font>
      <font color="#008000">'---------------------------------------</font>

<font color="#0000FF">      If </font>( iIdxOfGasket &gt; 0 )<font color="#0000FF"> Then</font>
<font color="#0000FF">        Dim </font>objPspCntrValve  <font color="#0000FF"> As </font>PspConnector
<font color="#0000FF">        Dim </font>objPspCntrGasket <font color="#0000FF"> As </font>PspConnector
<font color="#0000FF">        Dim </font>bIsConnected     <font color="#0000FF"> As </font>Boolean

<font color="#0000FF">        Set </font>objPspCntrValve = objLCntrsOnThisObj.Item (iIdxOfGasket, "CATIAPspConnector")          
<font color="#0000FF">        Set </font>objPspCntrGasket = objLCntrsOnConnected.Item (iIdxOfGasket, "CATIAPspConnector")          

<font color="#0000FF">        If </font>( Not(objPspCntrValve Is Nothing)  And _
             Not(objPspCntrGasket Is Nothing))<font color="#0000FF"> Then</font>
          strMessage_g = strMessage_g & "V-117 and Gasket-012 are connected at: "  & vbCr               
          strMessage_g = strMessage_g & "   V-117 ctr       =" & objPspCntrValve.ConnectorName & vbCr               
          strMessage_g = strMessage_g & "   Gasket-012 ctr  =" &  objPspCntrGasket.ConnectorName _
                            & vbCr               
          
          objPspCntrValve.Disconnect objPspCntrGasket
                    
          strMessage_g = strMessage_g & "V-117 and Gasket-012 successfully disconnected"  & vbCr               
                            
<font color="#0000FF">        End If</font>
      Else
        strMessage_g = strMessage_g & "V-117 and Gasket-012 are not connected."  & vbCr                
<font color="#0000FF">      End If  </font><font color="#008000">'--- index of connected object  (iIdxOfGasket ) &gt; 0</font>
<font color="#0000FF">    End if</font>
   
    strMessage_g = strMessage_g & _
      "--------------------------------------------------------------------" & vbCr
    MsgBox strMessage_g

<font color="#0000FF">End Sub</font>

<font color="#008000">' -----------------------------------------------------------------------------</font>
<font color="#008000">' | FindPipingPartByID functions</font>
<font color="#008000">' | </font>
<font color="#008000">' | Input: objLPhysicalsArg        : PspListOfObjects object</font>
<font color="#008000">' |         strIDArg               : ID of an object that looking for</font>
<font color="#008000">' |        </font>
<font color="#008000">' | Output: PspConnectable object having ID = strIDArg</font>
<font color="#008000">' -----------------------------------------------------------------------------</font>

Private Function FindPipingPartByID ( objLPhysicalsArg    <font color="#0000FF"> As </font>PspListOfObjects, _                                     
                                      strIDArg<font color="#0000FF"> As </font>String )  <font color="#0000FF"> As </font>PspConnectable
   
<font color="#0000FF">    Dim </font>intNbPhysical    <font color="#0000FF"> As </font>Integer
<font color="#0000FF">    Dim </font>iIndex           <font color="#0000FF"> As </font>Integer
<font color="#0000FF">    Dim </font>objPspID         <font color="#0000FF"> As </font>PspID
<font color="#0000FF">    Dim </font>strID            <font color="#0000FF"> As </font>String
       
    <font color="#008000">' ------------------------------------------------</font>
    <font color="#008000">' Setting the output of the function to Nothing</font>
    <font color="#008000">'</font>
    
<font color="#0000FF">    Set </font>FindPipingPartByID = Nothing

<font color="#0000FF">    If </font>( Not ( objLPhysicalsArg Is Nothing ) )<font color="#0000FF"> Then  </font>
     <font color="#0000FF"> int</font>NbPhysical = objLPhysicalsArg.Count
      
<font color="#0000FF">      For </font>iIndex = 1 To<font color="#0000FF"> int</font>NbPhysical      
<font color="#0000FF">        Set </font>objPspID = objLPhysicalsArg.Item (iIndex,"CATIAPspID")
 
<font color="#0000FF">        If </font>( Not ( objPspID Is Nothing ))<font color="#0000FF"> Then</font>
           <font color="#008000">'--------------------</font>
           <font color="#008000">' Check if ID matches</font>
<font color="#0000FF">           If </font>( strIDArg = objPspID.GetID )  <font color="#0000FF"> Then                   </font>
<font color="#0000FF">             Set </font>FindPipingPartByID = objLPhysicalsArg.Item (iIndex,"CATIAPspConnectable")
<font color="#0000FF">             Exit For     </font><font color="#008000">' Exit out of the for loop                  </font>
<font color="#0000FF">           End If </font>
<font color="#0000FF">        End IF</font>
<font color="#0000FF">      Next </font><font color="#008000">'----- End of loop index=iIndex</font>
<font color="#0000FF">    End If</font>
        
<font color="#0000FF">End Function                               </font>


</pre></body></html>
