<html><head><meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"><link rel="stylesheet" type="text/css" href="../CAAScrBase/caav5.css"></head><body><pre>
<font color="#008000">' COPYRIGHT DASSAULT SYSTEMES 2001</font>
<font color="#0000FF">Option Explicit</font>

<font color="#008000">' ***********************************************************************</font>
<font color="#008000">'   Purpose     : Create a label on a product.</font>
<font color="#008000">'   Assumptions : A CATProduct document should be active and a component selected.</font>
<font color="#008000">'   Author      : </font>
<font color="#008000">'   Languages   : VBScript</font>
<font color="#008000">'   Locales     : English </font>
<font color="#008000">'   CATIA Level : V5R6 </font>
<font color="#008000">' ***********************************************************************</font>

<font color="#0000FF">Sub </font>CATMain()

    <font color="#008000">' Retrieve the selected component</font>
<font color="#0000FF">    Dim </font>oSelection<font color="#0000FF"> As </font>Selection
<font color="#0000FF">    Set </font>oSelection = CATIA.ActiveDocument.Selection
<font color="#0000FF">    Dim </font>oProduct<font color="#0000FF"> As </font>AnyObject
    On Error Resume Next
<font color="#0000FF">    Set </font>oProduct = oSelection.FindObject("CATIAProduct")
<font color="#0000FF">    If </font>(Err.Number &lt;&gt; 0)<font color="#0000FF"> Then</font>
        MsgBox "No selected product"
    Else
        On Error Goto 0

        <font color="#008000">' Read information on the component</font>
<font color="#0000FF">        Dim </font>dPosition(11)
        oProduct.Position.GetComponents dPosition
<font color="#0000FF">        Dim </font>sTextString<font color="#0000FF"> As </font>String
        sTextString = oProduct.Name & " / " & oProduct.PartNumber

        <font color="#008000">' Retrieve the marker3Ds collection</font>
<font color="#0000FF">        Dim </font>cMarker3Ds<font color="#0000FF"> As </font>AnyObject
<font color="#0000FF">        Set </font>cMarker3Ds = oProduct.GetTechnologicalObject("Marker3Ds")

        <font color="#008000">' Create the marker3D</font>
<font color="#0000FF">        Dim </font>dPosition1(2)
        dPosition1(0) = dPosition(0)
        dPosition1(1) = dPosition(1)
        dPosition1(2) = dPosition(2)
<font color="#0000FF">        Dim </font>dPosition2(2)
        dPosition2(0) = dPosition(0) + 100.
        dPosition2(1) = dPosition(1) + 100.
        dPosition2(2) = dPosition(2) + 100.
<font color="#0000FF">        Dim </font>oMarker3D<font color="#0000FF"> As </font>Marker3D
<font color="#0000FF">        Set </font>oMarker3D = cMarker3Ds.Add3DText (dPosition2, sTextString, dPosition1, oProduct)
        oMarker3D.TextSize = 6.
        oMarker3D.Update

<font color="#0000FF">    End If</font>

<font color="#0000FF">End Sub</font>
</pre></body></html>


