<html><head><meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"><title>CAAKiiMechanismSolve.CATScript</title><link rel="stylesheet" type="text/css" href="../CAAScrBase/caav5.css"></head><body><pre>
<font color="#008000">'COPYRIGHT DASSAULT SYSTEMES 2000-2001</font>
<font color="#0000FF">Option Explicit</font>
<font color="#0000FF">Dim </font>Language<font color="#0000FF"> as </font>String
Language="VBSCRIPT"

<font color="#008000">'*****************************************************************************</font>
<font color="#008000">' Purpose:      This macro calls the kinematics solver </font>
<font color="#008000">'               and applies the computed motion to a </font>
<font color="#008000">'               part of the mechanism</font>
<font color="#008000">'               in a specific product document</font>
<font color="#008000">' Assumptions:  The product document used as input is result of the </font>
<font color="#008000">'               CAAKiiMechanismCreation use case</font>
<font color="#008000">' Author:       </font>
<font color="#008000">' Languages:    VBScript</font>
<font color="#008000">' Version:      V5R6</font>
<font color="#008000">' Locales:      US English</font>
<font color="#008000">'*****************************************************************************</font>

<font color="#0000FF">Sub </font>CATMain()

    <font color="#008000">'==================================================================</font>
    <font color="#008000">' 1-Prolog</font>
    <font color="#008000">'==================================================================</font>
    <font color="#008000">'------------------------------------------------------------------</font>
    <font color="#008000">' 1.a-Declare required variables: command set, motion matrix</font>
    <font color="#008000">'------------------------------------------------------------------</font>
<font color="#0000FF">    Dim </font>dValcmd(1)<font color="#0000FF"> As </font>Double
<font color="#0000FF">    Dim </font>dMotion(11)<font color="#0000FF"> As </font>Double

    <font color="#008000">'------------------------------------------------------------------</font>
    <font color="#008000">' 1.b-Retrieve the root product</font>
    <font color="#008000">'------------------------------------------------------------------</font>
<font color="#0000FF">    Dim </font>oRootProduct<font color="#0000FF"> As </font>AnyObject
<font color="#0000FF">    Set </font>oRootProduct = CATIA.ActiveDocument.Product

    <font color="#008000">'------------------------------------------------------------------</font>
    <font color="#008000">' 1.c-Retrieve the Mechanisms as a TechnologicalObject of the Product</font>
    <font color="#008000">'------------------------------------------------------------------</font>
<font color="#0000FF">    Dim </font>cTheMechanisms<font color="#0000FF"> As </font>AnyObject
<font color="#0000FF">    Set </font>cTheMechanisms = oRootProduct.GetTechnologicalObject("Mechanisms")

    <font color="#008000">'------------------------------------------------------------------</font>
    <font color="#008000">' 1.d-Take 1st mechanism found, and first moving part</font>
    <font color="#008000">'------------------------------------------------------------------</font>
<font color="#0000FF">    Dim </font>oFirstMechanism<font color="#0000FF"> As </font>Mechanism
<font color="#0000FF">    Set </font>oFirstMechanism = cTheMechanisms.Item(1)


    <font color="#008000">'==================================================================</font>
    <font color="#008000">' 2-Retrieve number of moving parts, and first one</font>
    <font color="#008000">'==================================================================</font>
<font color="#0000FF">    Dim </font>iNbProd<font color="#0000FF"> As </font>Integer
    iNbProd = oFirstMechanism.NbProducts

<font color="#0000FF">    Dim </font>oMovingPart<font color="#0000FF"> as </font>Product
<font color="#0000FF">    Set </font>oMovingPart = oFirstMechanism.GetProduct(1)


    <font color="#008000">'==================================================================</font>
    <font color="#008000">' 3-Retrieve current command values</font>
    <font color="#008000">'==================================================================</font>
    oFirstMechanism.GetCommandValues dValcmd


    <font color="#008000">'==================================================================</font>
    <font color="#008000">' 4-Solve for other command values</font>
    <font color="#008000">'==================================================================</font>
    <font color="#008000">'------------------------------------------------------------------</font>
    <font color="#008000">' 4.a-Create another command set</font>
    <font color="#008000">'------------------------------------------------------------------</font>
    dValcmd(0) = dValcmd(0) + 10

    <font color="#008000">'------------------------------------------------------------------</font>
    <font color="#008000">' 4.b-Apply the command set </font>
    <font color="#008000">'------------------------------------------------------------------</font>
    oFirstMechanism.PutCommandValues dValcmd


    <font color="#008000">'==================================================================</font>
    <font color="#008000">' 5-Retrieve motion for a part after solving and apply it</font>
    <font color="#008000">'==================================================================</font>
    <font color="#008000">'------------------------------------------------------------------</font>
    <font color="#008000">' 5.a-Retrieve motion for a part after solving</font>
    <font color="#008000">'------------------------------------------------------------------</font>
    oFirstMechanism.GetProductMotion oMovingPart,dMotion
    <font color="#008000">'------------------------------------------------------------------</font>
    <font color="#008000">' 5.b-Apply the motion to the part </font>
    <font color="#008000">'------------------------------------------------------------------</font>
    oMovingPart.Move.Apply dMotion

<font color="#0000FF">End Sub</font>
</pre></body></html>


