<HTML>

<HEAD>
<TITLE>Creating Spot Welding Connection Mesh Parts</TITLE>
<META HTTP-EQUIV="Content-Language" CONTENT="en-us">
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<META CONTENT="Microsoft FrontPage 6.0" NAME="GENERATOR">
<META CONTENT="FrontPage.Editor.Document" NAME="ProgId">
<link rel="stylesheet" type="text/css" href="../CAAScrBase/caav5.css">
<script language="JavaScript" src="../CAAScrJavaScript/submit.js"></SCRIPT>
</HEAD>

<BODY>

<TABLE WIDTH="100%" BORDER="0">
	<TR>
		<TD>
		<H2>Analysis Modeler</H2>
		</TD>
		<TD VALIGN="top" ALIGN="right">
		<H2><A NAME="Top"></A>Creating Spot Welding Connection Mesh Parts</H2>
		</TD>
	</TR>
</TABLE>
<HR>
<!---------------------------------comment------------------------------------->
<TABLE WIDTH="100%" BORDER="0">
	<TR>
		<TD VALIGN="top" WIDTH="7%">
		<img height="32" src="../CAAScrBase/images/atarget.gif" width="32" border="0"></TD>
		<TD WIDTH="93%">
		<P><A NAME="Learn"></A>This use case shows you how to create surface welding 
		connection mesh part. This scenario requires &quot;FEM Surface (FMS)&quot;.</P>
		<P>The macro opens an analysis document. Spot welding connection mesh can 
		be created on point analysis connection and point analysis connection within 
		one part. In this macro the mesh is created on point analysis connection 
		which already exists in the document. The point analysis connection is applied 
		as support to the mesh part and it is updated to generate mesh.</P>
		<P ALIGN="center"><img src="images/SpotWeldingMesh.gif" border="2"></P>
		<P>&nbsp;</P>
		</TD>
	</TR>
	<TR>
		<TD VALIGN="top" WIDTH="7%">
		<img height="32" src="../CAAScrBase/images/ainfo.gif" width="32" border="0"></TD>
		<TD WIDTH="93%">
		<P><A NAME="How"></A>CAAAniMeshSpotWelding is launched in CATIA [<A HREF="#References">1</A>]. 
		No open document is needed.</P>
		<P><a href="CAAAniMeshSpotWeldingSource.htm">CAAAniMeshSpotWelding.catvbs</A> 
		is located in the CAAScdAniUseCases module.
		<a href="macros/CAAAniMeshSpotWelding.catvbs">Execute macro</A> (Windows 
		only).</P>
		<P ALIGN="center">&nbsp;</P>
		</TD>
	</TR>
	<TR>
		<TD VALIGN="top" WIDTH="7%">
		<img height="32" src="../CAAScrBase/images/ascenari.gif" width="32" border="0"></TD>
		<TD WIDTH="93%">
		<P><A NAME="Step"></A>CAAAniMeshSpotWelding includes the following steps:</P>
		<OL>
			<LI><A HREF="#prolog">Prolog</A></LI>
			<LI><A HREF="#Reference">Extracting from the Part Document the Reference 
			Object for Meshing</A></LI>
			<LI><A HREF="#Navigate">Creating Mesh Part and Assigning Values to its 
			Attributes</A></LI>
			<LI><A HREF="#Epilog">Epilog</A></LI>
		</OL>
		<H4><A NAME="prolog"></A>Prolog</H4>
		<TABLE CLASS="code">
			<TR>
				<TD>
				<PRE>...</PRE>
				<PRE><FONT COLOR="#008000">&#39; ----------------------------------------------------------- </FONT>
<FONT COLOR="#008000">&#39; Optional: allows to find the sample wherever it&#39;s installed</FONT>
  sDocPath=CATIA.SystemService.Environ(&quot;CATDocView&quot;)

<FONT COLOR="#0000FF">    If </FONT>(Not CATIA.FileSystem.FolderExists(sDocPath))<FONT COLOR="#0000FF"> Then</FONT>
      Err.Raise 9999,,&quot;No Doc Path Defined&quot;
<FONT COLOR="#0000FF">    End If</FONT>
<FONT COLOR="#008000">&#39; ----------------------------------------------------------- </FONT>
<FONT COLOR="#008000">&#39;Open the Analysis document</FONT> 
sFilePath = CATIA.FileSystem.ConcatenatePaths(sDocPath, &quot;online\CAAScdAniUseCases\samples\WeldConnections.CATAnalysis&quot;)
<FONT COLOR="#0000FF">Set</FONT> oAnalysisDocument = CATIA.Documents.Open(sFilePath)</PRE>
				<PRE><B>...</B></PRE>
				</TD>
			</TR>
		</TABLE>
		<P>Open the Analysis document. The Analysis document is retrieve in the 
		documentation installation path, this path has already been stored in the
		<CODE>sDocPath</CODE> variable. In the collection of documents, two documents 
		can be retrieved; the Analysis document and the Part document.&nbsp; </P>
		<H4><A NAME="Reference"></A><B>Extracting the Reference Object from the 
		Part Document for&nbsp; Meshing</B></H4>
		<TABLE CLASS="code">
			<TR>
				<TD>
				<PRE>...</PRE>
				<PRE>
<FONT COLOR="#008000">&#39;Retrieve the analysis Manager </FONT>
<FONT COLOR="#0000FF">Set </FONT>oAnalysisManagar = oAnalysisDocument.Analysis
<FONT COLOR="#0000FF">Set </FONT>oAnalysisSet = oAnalysisManagar.AnalysisSets

<FONT COLOR="#008000">&#39;Retrieve the part document and product</FONT>
<FONT COLOR="#0000FF">Set </FONT>oAnalysisLinkedDocuments = oAnalysisManagar.LinkedDocuments
<FONT COLOR="#0000FF">Set </FONT>partDocument = oAnalysisLinkedDocuments.Item(1)
<FONT COLOR="#0000FF">Set </FONT>product = partDocument.Product

<FONT COLOR="#008000">&#39;Retrieve the analysis model</FONT>
<FONT COLOR="#0000FF">Set </FONT>oAnalysisModels = oAnalysisManagar.AnalysisModels
<FONT COLOR="#0000FF">Set </FONT>oAnalysisModel = oAnalysisModels.Item(1)

<FONT COLOR="#008000">&#39;Retrieve the mesh manager and list of mesh parts</FONT>
<FONT COLOR="#0000FF">Set </FONT>oAnalysisMeshManager = oAnalysisModel.MeshManager 
<FONT COLOR="#0000FF">Set </FONT>oAnalysisMeshParts = oAnalysisMeshManager.AnalysisMeshParts


<FONT COLOR="#008000">&#39;Retrieve the connection design manager and connection</FONT>
<FONT COLOR="#0000FF">Set </FONT>connection = oAnalysisSet.ItemByType(&quot;ConnectionDesignManager&quot;)
<FONT COLOR="#0000FF">Set </FONT>connSet = connection.AnalysisSets
<FONT COLOR="#0000FF">Set </FONT>conn = connSet.ItemByType(&quot;ConnectionDesignSet&quot;)
<FONT COLOR="#0000FF">Set </FONT>entity = conn.AnalysisEntities
<FONT COLOR="#0000FF">Set </FONT>surfConn  = entity.Item(1)
<FONT COLOR="#0000FF">Set </FONT>reference1 = oAnalysisManagar.CreateReferenceFromObject(surfConn)

...</PRE>
				</TD>
			</TR>
		</TABLE>
		<P>According to the general
		<a href="../CAAScdAniTechArticles/CAAAniTocAnalysisDocument.htm">
		Analysis Document</A> structure, this macro uses some standard procedures 
		to navigate or retrieve the required objects. First, from the <B>Document</B>, 
		we find the <B>Analysis Manager Object</B>, the <B>Analysis Models</B> and 
		the <B>Mesh Manager Objects</B>. </P>
		<P>The extraction of pre-defined geometric elements is done with the help 
		of Reference interface. This is equivalent to the selection of a B-Rep elements 
		inside the interactive application.</P>
		<H4><A NAME="Navigate"></A>Creating Mesh Part and Assigning Values to its 
		Attributes</H4>
		<TABLE CLASS="code">
			<TR>
				<TD>
				<PRE>...  </PRE>
				<PRE><FONT COLOR="#008000">&#39;Add new surface analysis connection mesh to the list of mesh parts</FONT>
<FONT COLOR="#0000FF">Set </FONT>surfWeld = oAnalysisMeshParts.Add (&quot;MSHPartConnWeldSurf&quot;) 

<FONT COLOR="#008000">&#39;Assign previously created reference as support</FONT>
surfWeld.AddSupportFromReference NOTHING, reference1


<FONT COLOR="#008000">&#39;Assign values to its global specifications</FONT>
spotWeldMesh.SetGlobalSpecification &quot;MaximalGap&quot;, &quot;10.0 mm&quot;
spotWeldMesh.SetGlobalSpecification &quot;MeshStep&quot;, &quot;10.0 mm&quot;
spotWeldMesh.SetGlobalSpecification &quot;StopUpdateOnError&quot;, 1
spotWeldMesh.SetGlobalSpecification &quot;SpotDiameter&quot;, &quot;2.0 mm&quot; 
spotWeldMesh.SetGlobalSpecification &quot;MiddleCombination&quot;, 3

<FONT COLOR="#008000">&#39;Update Mesh</FONT>
spotWeldMesh.Update

...</PRE>
				</TD>
			</TR>
		</TABLE>
		<H4><A NAME="Epilog"></A>Epilog</H4>
		<TABLE CLASS="code">
			<TR>
				<TD>
				<PRE>...</PRE>
				End Sub
				<PRE>...</PRE>
				</TD>
			</TR>
		</TABLE>
		<P>To run the macro interactively CATDocView environment 
		variable must be defined.</P>
		</TD>
	</TR>
</TABLE>
<!---------------------------------comment------------------------------------->
<P ALIGN="center">
<img height="32" src="../CAAScrBase/images/aendtask.gif" width="64" border="0"></P>
<P ALIGN="right">[<A HREF="#Top">Top</A>]</P>
<HR>
<!---------------------------------comment------------------------------------->
<H4><A NAME="InShort"></A>In Short</H4>
<P>This use case has shown how to create spot welding connection mesh parts and 
how to assign values to its global attributes.</P>
<P ALIGN="right">[<A HREF="#Top">Top</A>]</P>
<HR>
<!---------------------------------comment------------------------------------->
<H4><A NAME="References"></A>References</H4>
<TABLE WIDTH="100%" BORDER="0">
	<TR>
		<TD VALIGN="top" WIDTH="74">[1]</TD>
		<TD WIDTH="93%">
		<a href="../CAAScdInfUseCases/CAAInfLauchMacro.htm">Replaying 
		a Macro</A></TD>
	</TR>
	<TR>
		<TD ALIGN="right" COLSPAN="2">[<A HREF="#Top">Top</A>]</TD>
	</TR>
</TABLE>
<HR>
<!---------------------------------comment------------------------------------->
<P><I>Copyright © 2001, Dassault Systèmes. All rights reserved.</I></P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>

</BODY>

</HTML>
