<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML>

<HEAD>
<TITLE>Creating 1D Mesh</TITLE>
<META HTTP-EQUIV="Content-Language" CONTENT="en-us">
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<META CONTENT="Microsoft FrontPage 6.0" NAME="GENERATOR">
<META CONTENT="FrontPage.Editor.Document" NAME="ProgId">
<link href="../CAAScrBase/caav5.css" type="text/css" rel="stylesheet">
<script language="JavaScript" src="../CAAScrJavaScript/submit.js"></SCRIPT>
</HEAD>

<BODY>

<TABLE WIDTH="100%" BORDER="0">
	<TR>
		<TD>
		<H2>Analysis Modeler</H2>
		</TD>
		<TD VALIGN="top" ALIGN="right">
		<H2><A NAME="Top"></A>Creating and applying user material</H2>
		</TD>
	</TR>
</TABLE>
<HR>
<!---------------------------------comment------------------------------------->
<TABLE WIDTH="100%" BORDER="0">
	<TR>
		<TD VALIGN="top" WIDTH="7%">
		<img src="../CAAScrBase/images/atarget.gif" height="32" width="32" border="0"></TD>
		<TD WIDTH="93%">
		<P><A NAME="Learn"></A>This use case shows how to create a user material 
		and how to apply analysis material property to it.</P>
		<P>This macro opens an Analysis document. It opens a material catalog 
		retrieves a material. Then it creates an analysis material valuating all 
		its parameters and apply the analysis material to the user material.</P>
		<P ALIGN="center">
		<SRC="images/UserMaterial.gif">
		<p ALIGN="center">
		<img border="0" src="images/UserMaterial.gif"></p>
		<P>&nbsp;</P>
		</TD>
	</TR>
	<TR>
		<TD VALIGN="top" WIDTH="7%">
		<img height="32" src="../CAAScrBase/images/ainfo.gif" width="32" border="0"></TD>
		<TD WIDTH="93%">
		<P><A NAME="How"></A>CAAAniMesh1D is launched in CATIA [<A HREF="#References">1</A>]. 
		No open document is needed.</P>
		<P><a href="CAAAniApplyUserMaterialSource.htm">CAAAniUserMaterial.CATScript</A> is located 
		in the CAAScdAniUseCases module.
		<a href="macros/CAAAniUserMaterial.CATScript">Execute 
		macro</a> (Windows only).</P>
		</TD>
	</TR>
	<TR>
		<TD VALIGN="top" WIDTH="7%">
		<img height="32" src="../CAAScrBase/images/ascenari.gif" width="32" border="0"></TD>
		<TD WIDTH="93%">
		<P><a NAME="Step"></a>CAAAniMesh1D includes the following steps:</P>
		<ol>
			<LI><a HREF="#prolog">Prolog</a></LI>
			<LI><a HREF="#NewUser">Adding a New User Material</a></LI>
			<LI><a HREF="#LoadMat">Loading the Material Catalog and retrieving a 
			Material</a></LI>
			<LI><a HREF="#AnaMat">Creating an Analysis Material and Valuating its properties</a></LI>
			<LI><a HREF="#Epilog">Epilog</a></LI>
		</ol>
		<H4><a NAME="prolog"></a>Prolog</H4>
		<table CLASS="code">
			<TR>
				<TD>
				<PRE>...</PRE>
				<PRE>
<FONT COLOR="#0000FF">Sub </FONT>CATMain()

<FONT COLOR="#008000">'----------------------------------------------------------- </FONT>
<FONT COLOR="#008000">'Optional: allows to find the sample wherever it&#39;s installed</FONT>
sDocPath=CATIA.SystemService.Environ("CATDocView")
<FONT COLOR="#0000FF">If </FONT>(Not CATIA.FileSystem.FolderExists(sDocPath))<FONT COLOR="#0000FF"> Then</FONT>
Err.Raise 9999,,"No Doc Path Defined"
<FONT COLOR="#0000FF">End If</FONT>
<FONT COLOR="#008000">'----------------------------------------------------------- </FONT></PRE>
				<PRE>
<FONT COLOR="#008000">'Open the Analysis document</FONT> 
sFilePath = CATIA.FileSystem.ConcatenatePaths(sDocPath, &quot;online\CAAScdAniUseCases\samples\Beam.CATAnalysis&quot;)
<FONT COLOR="#0000FF">Set</FONT> oAnalysisDocument = CATIA.Documents.Open(sFilePath)</PRE>
				<PRE>
...</PRE>
				</TD>
			</TR>
		</table>
		<P>Open the Analysis document. The Analysis document is fetched in the 
		documentation installation path, this path has already been stored in 
		the <CODE>sDocPath</CODE> 
		variable. In the collection of documents, two documents can be 
		retrieved: the Analysis document and the Part document. </P>
		<h4><a NAME="NewUser"></a>Adding a new user material</h4>
		<table CLASS="code">
			<TR>
				<TD>
				<PRE>...</PRE>
				<PRE>
<FONT COLOR="#008000">'Retrieve the Analysis Manager and Analysis Model</FONT>
<FONT COLOR="#0000FF">Set</FONT> oAnalysisManager = oAnalysisDocument.Analysis</PRE>
				<PRE>
<FONT COLOR="#008000">'Retrieve the analysis model from the list of models</FONT>
<FONT COLOR="#0000FF">Set</FONT> oAnalysisModels = oAnalysisManager.AnalysisModels
<FONT COLOR="#0000FF">Set</FONT> oAnalysisModel = oAnalysisManager.Item(1)</PRE>
				<PRE>
<FONT COLOR="#008000">'Retrieve the material set from list of analysis sets
</FONT><font color="#0000FF">Set </font>oAnalysisSets = oAnalysisModel.AnalysisSets<FONT COLOR="#008000"> 
</FONT><font color="#0000FF">Set </font>oAnalysisSet = oAnalysisSets.ItemByType(&quot;MaterialSet&quot;)</PRE>
				<PRE>
<FONT COLOR="#008000">'Add an new user material
</FONT><font color="#0000FF">Set </font>oAnalysisEntities = oAnalysisSet.AnalysisEntities<FONT COLOR="#008000">
</FONT><font color="#0000FF">Set </font>oAnalysisEntity1 = oAnalysisEntities.Add(&quot;SAMUserMaterial&quot;)
</PRE>
				<PRE>
...</PRE>
				</TD>
			</TR>
		</table>
		<P>According to the general
		<a href="../CAAScdAniTechArticles/CAAAniTocAnalysisDocument.htm">
		Analysis Document</a> structure, this macro uses some standard 
		procedures to navigate or retrieve the required objects. First, from the <B>
		Document</B>, we find the <B>Analysis Manager Object</B>, the <B>
		Analysis Models</B> and <b>Analysis Set. </b>We retrieve material set 
		from the list of analysis sets. A new user material is added to this 
		list.</P>
		<h4><a NAME="LoadMat"></a><a HREF="#LoadMat">Loading a Material Catalog and 
		Applying Analysis Properties</a></h4>
		<table CLASS="code">
			<TR>
				<TD>
				<PRE>...
<font color="#008000">'Load the catalog of materials
</font>MaterialFile = CATIA.FileSystem.ConcatenatePaths(sDocPath, &quot;online\CAAScdAniUseCases\samples\CatalogForAutomation.CATMaterial&quot;)
Set oMaterial_document = CATIA.Documents.Open(MaterialFile)

<font color="#008000">'Load the catalog of materials</font>
<font color="#0000FF">Set</font> cFamilies_list = oMaterial_document.Families

<font color="#008000">'Retrieve the first family of the library
</font><font color="#0000FF">Dim</font><font color="#008000"> </font>ifamily_no<font color="#0000FF"> As</font> Integer
ifamily_no = 1
<font color="#0000FF">Set</font> oFirst_family = cFamilies_list.Item(iFamily_no)

<font color="#008000">'Retrieve the list of materials from the family</font>
<font color="#0000FF">Set</font> cMaterials_list = oFirst_family.Materials

<font color="#0000FF">Dim</font> imaterial_no <font color="#0000FF">As </font>Integer
imaterial_no = 1

<font color="#0000FF">Set</font> oMaterial1 = cMaterials_list.Item(imaterial_no)
...</PRE>
				</TD>
			</TR>
		</table>
		<p>Here we load the material catalog specifying its full path. Inside 
		the material catalog the materials are arranged as families and lists. 
		We retrieve the first family and first list.</p>
		<h4><a NAME="AnaMat"></a><a HREF="#AnaMat">Creating an Analysis Material 
		and Valuating its Properties</a></h4>
		<table CLASS="code" id="table1">
			<TR>
				<TD>
				<PRE>...
<font color="#008000">'Retrieve a material from the list and create analysis material </font>
imaterial_no = 1
<font color="#0000FF">Set</font> oMaterial1 = cMaterials_list.Item(imaterial_no)
<font color="#0000FF">Set</font> anlysisMaterial = oMaterial1.CreateAnalysisData(&quot;SAMAnisotropicMaterial&quot;)

anlysisMaterial.PutValue &quot;SAMShearModulus_11&quot;, &quot;1e+10&quot;
anlysisMaterial.PutValue &quot;SAMShearModulus_12&quot;, &quot;1e+10&quot;
anlysisMaterial.PutValue &quot;SAMShearModulus_1Z&quot;, &quot;1e+10&quot;
anlysisMaterial.PutValue &quot;SAMShearModulus_22&quot;, &quot;1e+10&quot;
anlysisMaterial.PutValue &quot;SAMShearModulus_2Z&quot;, &quot;1e+10&quot;
anlysisMaterial.PutValue &quot;SAMShearModulus_33&quot;, &quot;1e+10&quot;
anlysisMaterial.PutValue &quot;SAMDensity&quot;, &quot;7860&quot;
anlysisMaterial.PutValue &quot;SAMThermalExpansion_X&quot;, &quot;1-e5&quot;
anlysisMaterial.PutValue &quot;SAMThermalExpansion_Y&quot;, &quot;1-e5&quot;
anlysisMaterial.PutValue &quot;SAMThermalExpansion_Z&quot;, &quot;1-e5&quot;
anlysisMaterial.PutValue &quot;SAMTensileStressLimit&quot;, &quot;1e+11&quot;
anlysisMaterial.PutValue &quot;SAMCompressiveStressLimit&quot;, &quot;2e+11&quot;
anlysisMaterial.PutValue &quot;SAMShearStressLimit&quot;, &quot;1e+10&quot;<font color="#008000">
</font>
<font color="#008000">'Apply the material on the User Material</font>
linkMode = 0
Set oManager = oAnalysisManager.GetItem(&quot;CATMatManagerVBExt&quot;)
oManager.ApplyMaterialOnUserMaterial oAnalysisEntity1, oMaterial1, linkMode </PRE>
				<PRE>...</PRE>
				</TD>
			</TR>
		</table>
		<p>We retrieve a material from the list and we can create an analysis 
		material of any of the supported types thanks to the method 
		CreateAnalysisData. We can call PutValue method on analysis material to 
		set appropriate values to its parameters. Finally we apply this analysis 
		material on the user material thanks to the method 
		ApplyMaterialOnUserMaterial.</p>
		<h4><a NAME="Epilog"></a>Epilog</h4>
		<table CLASS="code">
			<TR>
				<TD>
				<PRE>...
 End Sub
...</PRE>
				</TD>
			</TR>
		</table>
		<P>&nbsp;<P>&nbsp;</TD>
	</TR>
</TABLE>
<!---------------------------------comment------------------------------------->
<P ALIGN="center">
<img height="32" src="../CAAScrBase/images/aendtask.gif" width="64" border="0"></P>
<P ALIGN="right">[<A HREF="#Top">Top</A>]</P>
<HR>
<!---------------------------------comment------------------------------------->
<H4><A NAME="InShort"></A>In Short</H4>
<P>This use case shows how to add a new user material into the model. It also 
shows how to retrieve a material from the catalog and create and valuate the 
analysis material.</P>
<P ALIGN="right">[<A HREF="#Top">Top</A>]</P>
<HR>
<!---------------------------------comment------------------------------------->
<H4><A NAME="References"></A>References</H4>
<TABLE WIDTH="100%" BORDER="0">
	<TR>
		<TD VALIGN="top" WIDTH="7%">[1]</TD>
		<TD WIDTH="93%">
		<a href="../CAAScdInfUseCases/CAAInfLauchMacro.htm">Replaying 
		a Macro</A></TD>
	</TR>
	<TR>
		<TD ALIGN="right" COLSPAN="2">[<A HREF="#Top">Top</A>]</TD>
	</TR>
</TABLE>
<HR>
<!---------------------------------comment------------------------------------->
<P><I>Copyright © 2001, Dassault Systèmes. All rights reserved.</I></P>

</BODY>

</HTML>
