<HTML>

<HEAD>
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>CAAAniMeshOctTriangle.catvbs</TITLE>
<link rel="stylesheet" type="text/css" href="../CAAScrBase/caav5.css">
</HEAD>

<BODY>

<PRE>
<FONT COLOR="#008000">' COPYRIGHT DASSAULT SYSTEMES 2000</FONT>

<FONT COLOR="#008000">' ***********************************************************************</FONT>
<FONT COLOR="#008000">'   Purpose:      Open an analysis document</FONT>
<FONT COLOR="#008000">'                 Create an octree triangle mesh  </FONT>
<FONT COLOR="#008000">'                 assign the surface as support</FONT>
<FONT COLOR="#008000">'                 specify the global specifications and assign values</FONT>
<FONT COLOR="#008000">'   Assumptions:   Looks for Surface.CATAnalysis in the directory</FONT>
<FONT COLOR="#008000">'   Author:       bmw</FONT>
<FONT COLOR="#008000">'   Languages:    VBScript</FONT>
<FONT COLOR="#008000">'   Locales:      English </FONT>
<FONT COLOR="#008000">'   CATIA Level:  V5R16</FONT>
<FONT COLOR="#008000">' ***********************************************************************</FONT>

<FONT COLOR="#008000">' ----------------------------------------------------------- </FONT>
<FONT COLOR="#008000">' Optional: allows to find the sample wherever it's installed</FONT>
  sDocPath=CATIA.SystemService.Environ("CATDocView")

<FONT COLOR="#0000FF">    If </FONT>(Not CATIA.FileSystem.FolderExists(sDocPath))<FONT COLOR="#0000FF"> Then</FONT>
      Err.Raise 9999,,"No Doc Path Defined"
<FONT COLOR="#0000FF">    End If</FONT>
<FONT COLOR="#008000">' ----------------------------------------------------------- </FONT>

<FONT COLOR="#0000FF">Sub </FONT>CATMain()

<FONT COLOR="#008000">'Open the analysis document</FONT>
sFilePath = CATIA.FileSystem.ConcatenatePaths(sDocPath, &quot;online\CAAScdAniUseCases\samples\Surface.CATAnalysis&quot;)
<FONT COLOR="#0000FF">Set</FONT> oAnalysisDocument = CATIA.Documents.Open(sFilePath)

<FONT COLOR="#008000">' Retrieve the Analysis Manager and Analysis Model</FONT>
<FONT COLOR="#0000FF">Set </FONT>oAnalysisManager = oAnalysisDocument.Analysis

<FONT COLOR="#008000">' Retrieve the part document and product from Analysis manager</FONT>
<FONT COLOR="#0000FF">Set </FONT>oAnalysisLinkedDocuments = oAnalysisManager.LinkedDocuments
<FONT COLOR="#0000FF">Set </FONT>partDocument1 = oAnalysisLinkedDocuments.Item(1)
<FONT COLOR="#0000FF">Set </FONT>Product = partDocument1.Product

<FONT COLOR="#008000">' Retrieve the analysis model from the list of models</FONT>
<FONT COLOR="#0000FF">Set </FONT>oAnalysisModels = oAnalysisManager.AnalysisModels
<FONT COLOR="#0000FF">Set </FONT>oAnalysisModel = oAnalysisModels.Item(1)

<FONT COLOR="#008000">' Retrieve mesh manager and mesh part </FONT>
<FONT COLOR="#0000FF">Set </FONT>meshManagar = oAnalysisModel.MeshManager
<FONT COLOR="#0000FF">Set </FONT>meshPart = meshManagar.AnalysisMeshParts

<FONT COLOR="#008000">' Retrieve publications from product and retrieve the published face.</FONT>
<FONT COLOR="#0000FF">Set </FONT>Publications = Product.Publications
<FONT COLOR="#0000FF">Set </FONT>pubSurf = Publications.Item("Round Hole.1")
<FONT COLOR="#0000FF">Set </FONT>pubEdge = Publications.Item("Edge")


<FONT COLOR="#008000">' Add the new Octree Triangle part to the list of mesh parts</FONT>
<FONT COLOR="#0000FF">Set </FONT>octreePart = meshPart.Add ("MSHPartOctree2D") 

<FONT COLOR="#008000">' Add the support from the published surface</FONT>
octreePart.AddSupportFromPublication Product, pubSurf

<FONT COLOR="#008000">' Set the global Specifications</FONT>
octreePart.SetGlobalSpecification "SizeValue", "10.0 mm"
octreePart.SetGlobalSpecification "AbsoluteSageValue", "3.0 mm"
octreePart.SetGlobalSpecification "ElementOrder", "Parabolic"
octreePart.SetGlobalSpecification "MinSizeForSags", "0.5 mm"
octreePart.SetGlobalSpecification "MinGeometrySize", "0.5 mm"
octreePart.SetGlobalSpecification "AbsoluteSag", 1
octreePart.SetGlobalSpecification "AbsoluteSagValue", "1.1 mm"
octreePart.SetGlobalSpecification "ProportionalSag", 1
octreePart.SetGlobalSpecification "ProportionalSagValue", 0.5
octreePart.SetGlobalSpecification "MaxWarpAngle", "1.0 rad"
octreePart.SetGlobalSpecification "Criteria", "Shape"
octreePart.SetGlobalSpecification "MeshGeometryViolation", "1.2 mm"
octreePart.SetGlobalSpecification "InteriorSize", 2
octreePart.SetGlobalSpecification "InteriorSizeValue", "5.0 mm"
octreePart.SetGlobalSpecification "MinJacobian", 0.3
octreePart.SetGlobalSpecification "MaxAttempts", 2

<FONT COLOR="#008000">' Add the domain specifications as local specifications and assign it attributes</FONT>
<FONT COLOR="#0000FF">Set </FONT>meshspecs1 = octreePart.AnalysisMeshLocalSpecifications
<FONT COLOR="#0000FF">Set </FONT>spec1 = meshspecs1.Add("MSHLocalMeshSize")
spec1.SetAttribute "MSHMeshSizeMag", "1.0 mm"
spec1.AddSupportFromPublication "ConnectorList", Product, pubEdge

<FONT COLOR="#008000">'Update mesh part</FONT>
octreePart.Update

<FONT COLOR="#0000FF">End Sub</FONT>
</PRE>

</BODY>

</HTML>
