<HTML>

<HEAD>
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>CAAAniMeshAdvSurf.catvbs</TITLE>
<link rel="stylesheet" type="text/css" href="../CAAScrBase/caav5.css">
</HEAD>

<BODY>

<PRE>
<FONT COLOR="#008000">' COPYRIGHT DASSAULT SYSTEMES 2000</FONT>

<FONT COLOR="#008000">' ***********************************************************************</FONT>
<FONT COLOR="#008000">'   Purpose:      Open an analysis document</FONT>
<FONT COLOR="#008000">'                 Create an advanced surface mesh  </FONT>
<FONT COLOR="#008000">'                 assign the surface as support</FONT>
<FONT COLOR="#008000">'                 specify the global specifications</FONT>
<FONT COLOR="#008000">'                 create a local specifications and add domain specifications</FONT>
<FONT COLOR="#008000">'                 set attributes of domain specifications</FONT>
<FONT COLOR="#008000">'   Assumptions:   Looks for Pad.CATAnalysis in the directory</FONT>
<FONT COLOR="#008000">'   Author:       bmw</FONT>
<FONT COLOR="#008000">'   Languages:    VBScript</FONT>
<FONT COLOR="#008000">'   Locales:      English </FONT>
<FONT COLOR="#008000">'   CATIA Level:  V5R16</FONT>
<FONT COLOR="#008000">' ***********************************************************************</FONT>

<FONT COLOR="#0000FF">Sub </FONT>CATMain()
<FONT COLOR="#008000">' ----------------------------------------------------------- </FONT>
<FONT COLOR="#008000">' Optional: allows to find the sample wherever it's installed</FONT>
  sDocPath=CATIA.SystemService.Environ("CATDocView")

<FONT COLOR="#0000FF">  If </FONT>(Not CATIA.FileSystem.FolderExists(sDocPath))<FONT COLOR="#0000FF"> Then</FONT>
      Err.Raise 9999,,"No Doc Path Defined"
<FONT COLOR="#0000FF">    End If</FONT>
<FONT COLOR="#008000">' ----------------------------------------------------------- </FONT>


<FONT COLOR="#008000">' Open the Analysis document </FONT>
sFilePath = CATIA.FileSystem.ConcatenatePaths(sDocPath, &quot;online\CAAScdAniUseCases\samples\Surface.CATAnalysis&quot;)
<FONT COLOR="#0000FF">Set</FONT> oAnalysisDocument = CATIA.Documents.Open(sFilePath)


<FONT COLOR="#008000">' Retrieve the Analysis Manager and Analysis Model</FONT>
<FONT COLOR="#0000FF">Set </FONT>oAnalysisManager = oAnalysisDocument.Analysis

<FONT COLOR="#008000">' Retreive the part document from Analysis manager</FONT>
<FONT COLOR="#0000FF">Set </FONT>oAnalysisLinkedDocuments = oAnalysisManager.LinkedDocuments
<FONT COLOR="#0000FF">Set </FONT>partDocument = oAnalysisLinkedDocuments.Item(1)
<FONT COLOR="#0000FF">Set </FONT>product = partDocument.Product


<FONT COLOR="#008000">' Retrieve the analysis model from the list of models</FONT>
<FONT COLOR="#0000FF">Set </FONT>oAnalysisModels = oAnalysisManager.AnalysisModels
<FONT COLOR="#0000FF">Set </FONT>oAnalysisModel = oAnalysisModels.Item(1)

<FONT COLOR="#008000">' Retrieve mesh manager and mesh part </FONT>
<FONT COLOR="#0000FF">Set </FONT>meshManager = oAnalysisModel.MeshManager
<FONT COLOR="#0000FF">Set </FONT>meshParts = meshManager.AnalysisMeshParts


<FONT COLOR="#008000">' Retrieve publications from product and retrieve the published face.</FONT>
<FONT COLOR="#0000FF">Set </FONT>publications1 = product.Publications
<FONT COLOR="#0000FF">Set </FONT>pubEdge = publications1.Item("Edge")
<FONT COLOR="#0000FF">Set </FONT>pubSurf = publications1.Item("Round Hole.1")


<FONT COLOR="#008000">' Add the new Advanced surface mesh part to the list of mesh parts</FONT>
<FONT COLOR="#0000FF">Set </FONT>surfPart = meshParts.Add ("MSHPartSmartSurf") 

<FONT COLOR="#008000">' Add reference previously created</FONT>
surfPart.AddSupportFromPublication product, pubSurf


<FONT COLOR="#008000">' Set the global Specifications</FONT>
surfPart.SetGlobalSpecification "GlobalMethod", "Frontal triangle"
surfPart.SetGlobalSpecification "GlobalSize", "20.0 mm"
surfPart.SetGlobalSpecification "MinimumSize", "1.0 mm"
surfPart.SetGlobalSpecification "ElementOrder", "Parabolic"
surfPart.SetGlobalSpecification "FaceAngle", "0.0 deg"
surfPart.SetGlobalSpecification "CurveAngle", "0.0 deg"
surfPart.SetGlobalSpecification "DetailsElimination", 1
surfPart.SetGlobalSpecification "StripOptimization", 1
surfPart.SetGlobalSpecification "CleanSize", "1.0 mm"
surfPart.SetGlobalSpecification "Offset", "0.0 mm"
surfPart.SetGlobalSpecification "OffsetFromThickness", "0.0 mm"
surfPart.SetGlobalSpecification "MinimizeTriangles", 1.
surfPart.SetGlobalSpecification "MinSizeForSag", "1.0 mm"
surfPart.SetGlobalSpecification "CurveCaptureTol", "1.0 mm"
surfPart.SetGlobalSpecification "OptimizeRegularity", 1
surfPart.SetGlobalSpecification "MeshRelSagValue", "1.0 mm"
surfPart.SetGlobalSpecification "MeshRelSag", 1
surfPart.SetGlobalSpecification "ConstraintSagValue", "1.0 mm"
surfPart.SetGlobalSpecification "CurveCapture", 1
surfPart.SetGlobalSpecification "MeshCapture", 1
surfPart.SetGlobalSpecification "MeshCapturTol", "1.0 mm"
surfPart.SetGlobalSpecification "MeshAbsSag", 2
surfPart.SetGlobalSpecification "MeshAbsSagValue", "1.0 mm"


<FONT COLOR="#008000">' Add the domain specifications as local specifications and assign values to its attributes</FONT>
<FONT COLOR="#0000FF">Set </FONT>meshSpecs = surfPart.AnalysisMeshLocalSpecifications
<FONT COLOR="#0000FF">Set </FONT>spec = meshSpecs.Add("MSHDistributionElement")
spec.SetAttribute "NbElements", 50
spec.SetAttribute "Type", "Isometric"
spec.AddSupportFromPublication "Supports", product, pubEdge

<FONT COLOR="#008000">'Update the mesh part</FONT>
surfPart.Update

<FONT COLOR="#0000FF">End Sub</FONT>


</PRE>

</BODY>

</HTML>
