<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML>

<HEAD>
<TITLE>Creating 1D Mesh</TITLE>
<META HTTP-EQUIV="Content-Language" CONTENT="en-us">
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<META CONTENT="Microsoft FrontPage 12.0" NAME="GENERATOR">
<META CONTENT="FrontPage.Editor.Document" NAME="ProgId">
<link href="../CAAScrBase/caav5.css" type="text/css" rel="stylesheet">
<script language="JavaScript" src="../CAAScrJavaScript/submit.js"></SCRIPT>
</HEAD>

<BODY>

<TABLE WIDTH="100%" BORDER="0">
	<TR>
		<TD>
		<H2>Analysis Modeler</H2>
		</TD>
		<TD VALIGN="top" ALIGN="right">
		<H2><A NAME="Top"></A>Creating 1D Mesh</H2>
		</TD>
	</TR>
</TABLE>
<HR>
<!---------------------------------comment------------------------------------->
<TABLE WIDTH="100%" BORDER="0">
	<TR>
		<TD VALIGN="top" WIDTH="7%">
		<img src="../CAAScrBase/images/atarget.gif" height="32" width="32" border="0"></TD>
		<TD WIDTH="93%">
		<P><A NAME="Learn"></A>This use case shows how to create 1D mesh parts in 
		an existing analysis document. This scenario requires "FEM Surface (FMS)" 
		product.</P>
		<P>This macro opens an Analysis document. It creates 1D (or beam) mesh part 
		and and sets global specifications associated with this mesh part. </P>
		<P ALIGN="center"><img src="images/BeamMesh.gif" border="2"></P>
		<P>&nbsp;</P>
		</TD>
	</TR>
	<TR>
		<TD VALIGN="top" WIDTH="7%">
		<img height="32" src="../CAAScrBase/images/ainfo.gif" width="32" border="0"></TD>
		<TD WIDTH="93%">
		<P><A NAME="How"></A>CAAAniMesh1D is launched in CATIA [<A HREF="#References">1</A>]. 
		No open document is needed.</P>
		<P><a href="CAAAniMesh1DSource.htm">CAAAniMesh1DSource.catvbs</A> is located 
		in the CAAScdAniUseCases module. <a href="macros/CAAAniMesh1D.catvbs">Execute 
		macro</A> (Windows only).</P>
		</TD>
	</TR>
	<TR>
		<TD VALIGN="top" WIDTH="7%">
		<img height="32" src="../CAAScrBase/images/ascenari.gif" width="32" border="0"></TD>
		<TD WIDTH="93%">
		<P><A NAME="Step"></A>CAAAniMesh1D includes the following steps:</P>
		<OL>
			<LI><A HREF="#prolog">Prolog</A></LI>
			<LI><A HREF="#Reference">Extracting the List of Mesh Parts and Publications</A></LI>
			<LI><A HREF="#Navigate">Creating Mesh part and Assigning Values to its 
			Attributes</A></LI>
			<LI><A HREF="#Epilog">Epilog</A></LI>
		</OL>
		<H4><A NAME="prolog"></A>Prolog</H4>
		<TABLE CLASS="code">
			<TR>
				<TD>
				<PRE>...</PRE>
				<PRE>
<FONT COLOR="#0000FF">Sub </FONT>CATMain()

<FONT COLOR="#008000">'----------------------------------------------------------- </FONT>
<FONT COLOR="#008000">'Optional: allows to find the sample wherever it&#39;s installed</FONT>
sDocPath=CATIA.SystemService.Environ("CATDocView")
<FONT COLOR="#0000FF">If </FONT>(Not CATIA.FileSystem.FolderExists(sDocPath))<FONT COLOR="#0000FF"> Then</FONT>
Err.Raise 9999,,"No Doc Path Defined"
<FONT COLOR="#0000FF">End If</FONT>
<FONT COLOR="#008000">'----------------------------------------------------------- </FONT></PRE>
				<PRE>
<FONT COLOR="#008000">'Open the Analysis document</FONT> 
sFilePath = CATIA.FileSystem.ConcatenatePaths(sDocPath, &quot;online\CAAScdAniUseCases\samples\Beam.CATAnalysis&quot;)
<FONT COLOR="#0000FF">Set</FONT> oAnalysisDocument = CATIA.Documents.Open(sFilePath)</PRE>
				<PRE>
...</PRE>
				</TD>
			</TR>
		</TABLE>
		<P>Open the Analysis document. The Analysis document is fetched in the documentation 
		installation path, this path has already been stored in the <CODE>sDocPath</CODE> 
		variable. In the collection of documents, two documents can be retrieved: 
		the Analysis document and the Part document. </P>
		<H4><A NAME="Reference"></A>Extracting the List of Mesh Parts and Publications</H4>
		<TABLE CLASS="code">
			<TR>
				<TD>
				<PRE>...</PRE>
				<PRE>
<FONT COLOR="#008000">'Retrieve the Analysis Manager and Analysis Model</FONT>
<FONT COLOR="#0000FF">Set</FONT> oAnalysisManager = oAnalysisDocument.Analysis</PRE>
				<PRE>
<FONT COLOR="#008000">'Retreive the part document from Analysis manager</FONT>
<FONT COLOR="#0000FF">Set</FONT> oAnalysisLinkedDocument = oAnalysisManager.LinkedDocuments
<FONT COLOR="#0000FF">Set</FONT> partDocument = oAnalysisLinkedDocuments.Item(1)
<FONT COLOR="#0000FF">Set</FONT> product = partDocument.Product
			</PRE>
				<PRE>
<FONT COLOR="#008000">'Retrieve the analysis model from the list of models</FONT>
<FONT COLOR="#0000FF">Set</FONT> oAnalysisModels = oAnalysisManager.AnalysisModels
<FONT COLOR="#0000FF">Set</FONT> oAnalysisModel = oAnalysisManager.Item(1)</PRE>
				<PRE>
<FONT COLOR="#008000">'Retrieve mesh manager and mesh part </FONT>
<FONT COLOR="#0000FF">Set </FONT>oAnalysisMeshManager = oAnalysisModel.MeshManager
<FONT COLOR="#0000FF">Set </FONT>oAnalysisMeshParts = oAnalysisMeshManager.AnalysisMeshParts
</PRE>
				<PRE>
<FONT COLOR="#008000">'Retrieve publications from product and retrieve the published face.</FONT>
<FONT COLOR="#0000FF">Set </FONT>publications = product.Publications
<FONT COLOR="#0000FF">Set </FONT>pubLine = publications.Item("Line.3")</PRE>
				<PRE>
...</PRE>
				</TD>
			</TR>
		</TABLE>
		<P>According to the general
		<a href="../CAAScdAniTechArticles/CAAAniTocAnalysisDocument.htm">
		Analysis Document</A> structure, this macro uses some standard procedures 
		to navigate or retrieve the required objects. First, from the <B>Document</B>, 
		we find the <B>Analysis Manager Object</B>, the <B>Analysis Models</B> and 
		the <B>Mesh Manager Objects</B>. The extraction of pre-defined geometric 
		elements is done with the help of Reference interface. This is equivalent 
		to the selection of a B-Rep element inside the interactive applications. 
		In this macro the reference is created from the published face.</P>
		<H4><A NAME="Navigate"></A>Creating the Mesh Part and Assigning Values to 
		its Attributes.</H4>
		<TABLE CLASS="code">
			<TR>
				<TD>
				<PRE>...
<FONT COLOR="#008000">'Add the new beam mesh part to the list of mesh parts</FONT>
<FONT COLOR="#0000FF">Set </FONT>beamPart = oAnalysisMeshParts.Add("MSHPart1D")

beamPart.AddSupportFromPublication product, pubLine
beamPart.SetGlobalSpecification "SizeValue", "10.0 mm"
beamPart.SetGlobalSpecification "AbsoluteSag", 1
beamPart.SetGlobalSpecification "AbsoluteSagValue", "1.1 mm"
beamPart.SetGlobalSpecification "MinimumSizeValue", "1.1 mm"
beamPart.SetGlobalSpecification "ElementOrder", "Parabolic"
beamPart.SetGlobalSpecification "MeshCapture", 1
beamPart.SetGlobalSpecification "MeshCaptureTol", "1.1 mm"
beamPart.SetGlobalSpecification "CurveAngle", "40 deg"

<FONT COLOR="#008000">&#39;Update the mesh part</FONT>
beamPart.Update 

...</PRE>
				<PRE></PRE>
				</TD>
			</TR>
		</TABLE>
		<P>Calling update on the mesh part computes the mesh.</P>
		<H4><A NAME="Epilog"></A>Epilog</H4>
		<TABLE CLASS="code">
			<TR>
				<TD>
				<PRE>...
 End Sub
...</PRE>
				</TD>
			</TR>
		</TABLE>
		<P>To run the macro interactively CATDocView 
		environment variables must be defined. After running the macro the mesh may not be immediately visible,
                the user has to go to the Advanced Meshing Tools workbench to see the mesh.</TD>
	</TR>
</TABLE>
<!---------------------------------comment------------------------------------->
<P ALIGN="center">
<img height="32" src="../CAAScrBase/images/aendtask.gif" width="64" border="0"></P>
<P ALIGN="right">[<A HREF="#Top">Top</A>]</P>
<HR>
<!---------------------------------comment------------------------------------->
<H4><A NAME="InShort"></A>In Short</H4>
<P>This use case has shown how to create a 1D mesh part and how to assign values 
to its global specifications.</P>
<P ALIGN="right">[<A HREF="#Top">Top</A>]</P>
<HR>
<!---------------------------------comment------------------------------------->
<H4><A NAME="References"></A>References</H4>
<TABLE WIDTH="100%" BORDER="0">
	<TR>
		<TD VALIGN="top" WIDTH="7%">[1]</TD>
		<TD WIDTH="93%">
		<a href="../CAAScdInfUseCases/CAAInfLauchMacro.htm">Replaying 
		a Macro</A></TD>
	</TR>
	<TR>
		<TD ALIGN="right" COLSPAN="2">[<A HREF="#Top">Top</A>]</TD>
	</TR>
</TABLE>
<HR>
<!---------------------------------comment------------------------------------->
<P><I>Copyright © 2001, Dassault Systèmes. All rights reserved.</I></P>

</BODY>

</HTML>
