<html>

 <head>
 <meta name="GENERATOR" content="Microsoft FrontPage 5.0">
 <meta name="ProgId" content="FrontPage.Editor.Document">
 <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
 <title>CAAAniPreproOnVirtual.catvbs</title>
 <link rel="stylesheet" type="text/css" href="../CAAScrBase/caav5.css">
 </head>

 <body>

 <pre style="margin-top: 0; margin-bottom: 0">Language=&quot;VBSCRIPT&quot;
<font color="#008000">' COPYRIGTH DASSAULT SYSTEMES 2000</font>

<font color="#008000">' ***********************************************************************</font>
<font color="#008000">'   Purpose:      Create a New Analysis document.</font>
<font color="#008000">'                 Import on a CATPart document with some publication defined </font>
<font color="#008000">'                 Define all preprocessing data based on publications:</font>
<font color="#008000">'                 This sample includes some rigid virtual parts that are clampled.</font>
<font color="#008000">'                 Launch the Computation.</font>
<font color="#008000">'   Assumtions:   Looks for FlangeForVirtualUsage.CATPart stored in the DocView   </font>
<font color="#008000">'   Author: </font>
<font color="#008000">'   Languages:    VBScript</font>
<font color="#008000">'   Locales:      English </font>
<font color="#008000">'   CATIA Level:  V5R13</font>
<font color="#008000">' ***********************************************************************</font>

<font color="#0000FF">Sub </font>CATMain()
<font color="#008000">' ----------------------------------------------------------- </font>
<font color="#008000">' Optional: allows to find the sample wherever it's installed</font>

  sDocPath=CATIA.SystemService.Environ(&quot;CATDocView&quot;)
  sSep=CATIA.SystemService.Environ(&quot;ADL_ODT_SLASH&quot;)

<font color="#0000FF">    If </font>(Not CATIA.FileSystem.FolderExists(sDocPath))<font color="#0000FF"> Then</font>
      Err.Raise 9999,,&quot;No Doc Path Defined&quot;
<font color="#0000FF">    End If</font>
<font color="#008000">' ----------------------------------------------------------- </font>
<font color="#008000">' Get the collection of documents in session</font>
<font color="#0000FF">    Set </font>documents1 = CATIA.<font color="#FF0000">Documents</font>

<font color="#008000">' Only one Analysis Document is required</font>
<font color="#008000">' Create the CATAnalysis Document </font>
<font color="#0000FF">    Set </font>TheAnalysisDocument = documents1.<font color="#FF0000">Add</font>(&quot;Analysis&quot;)

<font color="#008000">' if WB name already is &quot;GPSCfg&quot;, not to use StartWorkbench</font>
    WBName = CATIA.GetWorkbenchId
<font color="#0000FF">    if </font>(WBName &lt;&gt; &quot;GPSCfg&quot;) Then
	CATIA.<font color="#FF0000">StartWorkbench</font>(&quot;GPSCfg&quot;)
<font color="#0000FF">    End If</font>
 
<font color="#008000">'_____________________________________________________________________________________</font>
<font color="#008000">' Start to scan the existing structure of analysis document:  Retrieve the AnalysisManager</font>
<font color="#008000">' and link the analysis to a Part Document</font></pre>

 <pre style="margin-top: 0; margin-bottom: 0"><font color="#008000">' We call the Import on CATAnalysisImport which implements CATISamImportDefine</font>
    
<font color="#0000FF">    Set </font>analysisManager1 = TheAnalysisDocument.Analysis</pre>

 <pre style="margin-top: 0; margin-bottom: 0">    Dim arrayOfVariantOfShort1(0)
    analysisManager1.<font color="#FF0000">ImportDefineFile</font> (sDocPath &amp; sSep  &amp; &quot;online&quot; &amp; sSep &amp; &quot;CAAScdAniUseCases&quot; &amp; sSep &amp; &quot;samples&quot; &amp; sSep  &amp; &quot;FlangeForVirtualUsage.CATPart&quot;),</pre>

 <pre style="margin-top: 0; margin-bottom: 0">				       &quot;CATAnalysisImport&quot;, arrayOfVariantOfShort1 

<font color="#008000">' _____________________________________________________________________________________</font>
<font color="#008000">' Reframe All.</font>
<font color="#0000FF">  Set </font>specsAndGeomWindow1 = CATIA.ActiveWindow
<font color="#0000FF">  Set </font>viewer3D1 = specsAndGeomWindow1.ActiveViewer
  viewer3D1.Reframe 

<font color="#008000">' _____________________________________________________________________________________</font>
<font color="#008000">' Scan the analysis document:  Retrieve the Pointed documents to extract the reference for preprocessing</font>
<font color="#0000FF">    Set </font>analysisLinkedDocuments1 = analysisManager1.<font color="#FF0000">LinkedDocuments</font>
    CATIA.SystemService.Print analysisLinkedDocuments1.Name

<font color="#0000FF">   If </font>(analysisLinkedDocuments1.Count &lt;&gt; 1 )<font color="#0000FF"> Then</font>
      Err.Raise 9999,,&quot;NbDoc Lié NE 1&quot;
<font color="#0000FF">   End If</font>

<font color="#008000">' _____________________________________________________________________________________</font>
<font color="#008000">' Retrieve the CATPart Document and associated collection of publications for preprocessing.</font>
<font color="#0000FF">   Set </font>TheDoc = analysisLinkedDocuments1.Item(1)
   CATIA.SystemService.Print TheDoc.FullName

<font color="#0000FF">   Set </font>product1 = TheDoc.Product
<font color="#0000FF">   Set </font>publications1 = product1.<font color="#FF0000">Publications</font>

<font color="#008000">' _____________________________________________________________________________________</font>
<font color="#008000">' Create a Modal Case in the current analysis model.</font>
<font color="#0000FF">   Set </font>analysisModels1 = analysisManager1.AnalysisModels
<font color="#0000FF">   Set </font>analysisModel1 = analysisModels1.Item(1)

<font color="#0000FF">   Set </font>analysisCases1 = analysisModel1.AnalysisCases
<font color="#0000FF">   Set </font>analysisCase1 = analysisCases1.<font color="#FF0000">Add</font>()
<font color="#0000FF">   Set </font>analysisSets1 = analysisCase1.AnalysisSets

<font color="#0000FF">   Set </font>analysisSet1 = analysisSets1.<font color="#FF0000">Add</font>(&quot;RestraintSet&quot;, catAnalysisSetIn)
<font color="#0000FF">   Set </font>analysisSet2 = analysisSets1.<font color="#FF0000">Add</font>(&quot;MassSet&quot;, catAnalysisSetIn)
<font color="#0000FF">   Set </font>analysisSet3 = analysisCase1.<font color="#FF0000">AddSolution</font>(&quot;FrequencySet&quot;)
<font color="#0000FF">   Set </font>analysisSet6 = analysisSets1.<font color="#FF0000">Add</font>(&quot;SensorSet&quot;,catAnalysisSetOut)

<font color="#008000">' _____________________________________________________________________________________</font>
<font color="#008000">' Create a property set from the Analysis Model to create some Rigid Virtal Parts</font>
<font color="#0000FF">   Set </font>analysisSets2 = analysisModel1.AnalysisSets

<font color="#0000FF">   Set </font>analysisSet4 = analysisSets2.<font color="#FF0000">ItemByType</font>(&quot;PropertySet&quot;)
<font color="#0000FF">   Set </font>analysisEntities1 = analysisSet4.AnalysisEntities

<font color="#0000FF">   Set </font>analysisEntity1 = analysisEntities1.<font color="#FF0000">Add</font>(&quot;SAMVirPartRigid&quot;)
<font color="#0000FF">   Set </font>publication1 = publications1.<font color="#FF0000">Item</font>(&quot;SmallHole&quot;)
   analysisEntity1.<font color="#FF0000">AddSupportFromPublication</font> product1, publication1

<font color="#0000FF">   Set </font>analysisEntity2 = analysisEntities1.<font color="#FF0000">Add</font>(&quot;SAMVirPartRigid&quot;)
<font color="#0000FF">   Set </font>publication2 = publications1.<font color="#FF0000">Item</font>(&quot;SmallHole1&quot;)
   analysisEntity2.<font color="#FF0000">AddSupportFromPublication</font> product1, publication2

<font color="#0000FF">   Set </font>analysisEntity3 = analysisEntities1.<font color="#FF0000">Add</font>(&quot;SAMVirPartRigid&quot;)
<font color="#0000FF">   Set </font>publication3 = publications1.<font color="#FF0000">Item</font>(&quot;SmallHole3&quot;)
   analysisEntity3.<font color="#FF0000">AddSupportFromPublication</font> product1, publication3

<font color="#0000FF">   Set </font>analysisEntity4 = analysisEntities1.<font color="#FF0000">Add</font>(&quot;SAMVirPartRigid&quot;)
<font color="#0000FF">   Set </font>publication4 = publications1.<font color="#FF0000">Item</font>(&quot;SmallHole2&quot;)
   analysisEntity4.<font color="#FF0000">AddSupportFromPublication</font> product1, publication4

<font color="#008000">' _____________________________________________________________________________________</font>
<font color="#008000">' Clamp the Rigid Virtal Parts</font>

<font color="#0000FF">   Set </font>analysisEntities2 = analysisSet1.AnalysisEntities
<font color="#0000FF">   Set </font>analysisEntity5 = analysisEntities2.<font color="#FF0000">Add</font>(&quot;SAMClamp&quot;)
<font color="#0000FF">   Set </font>reference1 = analysisManager1.<font color="#FF0000">CreateReferenceFromObject</font>(analysisEntity4)
   analysisEntity5.<font color="#FF0000">AddSupportFromReference</font> reference1, reference1

<font color="#0000FF">   Set </font>analysisEntity6 = analysisEntities2.<font color="#FF0000">Add</font>(&quot;SAMClamp&quot;)
<font color="#0000FF">   Set </font>reference2 = analysisManager1.<font color="#FF0000">CreateReferenceFromObject</font>(analysisEntity3)
   analysisEntity6.<font color="#FF0000">AddSupportFromReference</font> reference2, reference2

<font color="#0000FF">   Set </font>analysisEntity7 = analysisEntities2.<font color="#FF0000">Add</font>(&quot;SAMClamp&quot;)
<font color="#0000FF">   Set </font>reference3 = analysisManager1.<font color="#FF0000">CreateReferenceFromObject</font>(analysisEntity2)
   analysisEntity7.<font color="#FF0000">AddSupportFromReference</font> reference3, reference3

<font color="#0000FF">   Set </font>analysisEntity8 = analysisEntities2.<font color="#FF0000">Add</font>(&quot;SAMClamp&quot;)
<font color="#0000FF">   Set </font>reference4 = analysisManager1.<font color="#FF0000">CreateReferenceFromObject</font>(analysisEntity1)
   analysisEntity8.<font color="#FF0000">AddSupportFromReference</font> reference4, reference4

<font color="#008000">' _____________________________________________________________________________________</font>
<font color="#008000">' Distribute some Masses on top of the Part</font>

<font color="#0000FF">   Set </font>analysisEntities3 = analysisSet2.AnalysisEntities
<font color="#0000FF">   Set </font>analysisEntity9 = analysisEntities3.<font color="#FF0000">Add</font>(&quot;SAMDistributedMass&quot;)
<font color="#0000FF">   Set </font>publication5 = publications1.<font color="#FF0000">Item</font>(&quot;TopFace&quot;)
   analysisEntity9.<font color="#FF0000">AddSupportFromPublication</font> product1, publication5

<font color="#0000FF">   Set </font>basicComponents1 = analysisEntity9.BasicComponents
<font color="#0000FF">   Set </font>basicComponent1 = basicComponents1.<font color="#FF0000">GetItem</font>(&quot;SAMMassMag&quot;)
   basicComponent1.<font color="#FF0000">SetValue</font> &quot;&quot;, 0, 0, 0, 25.000000


<font color="#008000">' _____________________________________________________________________________________</font>
<font color="#008000">' Read the Value of the Mass</font>
  CATIA.SystemService.Print &quot; Mass Applied of the Part: &quot; &amp; basicComponent1.<font color="#FF0000">GetValue</font> (&quot;&quot;,0,0,0)

<font color="#008000">' _____________________________________________________________________________________</font>
<font color="#008000">' Launch Computation.</font>
  analysisCase1.Compute

<font color="#008000">'------------------------------- END   END   END   ----------------------------</font>
  CATIA.DisplayFileAlerts = False
<font color="#008000">'  TheAnalysisDocument.Close</font>

<font color="#0000FF">End Sub</font>

</pre>

 </body>

</html>
