<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<HTML>

<HEAD>
<TITLE>Creating Advanced Surface Mesh Parts</TITLE>
<META HTTP-EQUIV="Content-Language" CONTENT="en-us">
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<META CONTENT="Microsoft FrontPage 6.0" NAME="GENERATOR">
<META CONTENT="FrontPage.Editor.Document" NAME="ProgId">
<link href="../CAAScrBase/caav5.css" type="text/css" rel="stylesheet">
<script language="JavaScript" src="../CAAScrJavaScript/submit.js"></SCRIPT>
</HEAD>

<BODY>

<TABLE WIDTH="100%" BORDER="0">
	<TR>
		<TD>
		<H2>Analysis Modeler</H2>
		</TD>
		<TD VALIGN="top" ALIGN="right">
		<H2><A NAME="Top"></A>Creating Advanced Surface Mesh Parts</H2>
		</TD>
	</TR>
</TABLE>
<HR>
<!---------------------------------comment------------------------------------->
<TABLE WIDTH="100%" BORDER="0">
	<TR>
		<TD VALIGN="top" WIDTH="7%">
		<img height="32" src="../CAAScrBase/images/atarget.gif" width="32" border="0"></TD>
		<TD WIDTH="93%">
		<P><A NAME="Learn"></A>This use case shows you how to create Advanced surface 
		mesh part on an existing analysis document. This scenario requires "FEM 
		Surface (FMS)" product.</P>
		<P>This macro opens an existing Analysis document. Advanced surface mesh 
		part is created and global specifications associated with this mesh part 
		are set. The local specification: <I>MSHDistributionElement</I> is created 
		around the edge of the hole. The mesh part is updated to generate mesh.</P>
		<P ALIGN="center">&nbsp;</P>
		<P ALIGN="center"><img src="images/SurfaceMesh.gif" border="2"></P>
		<P>&nbsp;</P>
		</TD>
	</TR>
	<TR>
		<TD VALIGN="top" WIDTH="7%">
		<img height="32" src="../CAAScrBase/images/ainfo.gif" width="32" border="0"></TD>
		<TD WIDTH="93%">
		<P><A NAME="How"></A>CAAAniMeshAdvSurf is launched in CATIA [<A HREF="#References">1</A>]. 
		No open document is needed.</P>
		<P><a href="CAAAniMeshAdvSurfSource.htm">CAAAniMeshAdvSurf.catvbs</A> is 
		located in the CAAScdAniUseCases module.
		<a href="macros/CAAAniMeshAdvSurf.catvbs">Execute macro</A> (Windows only).</P>
		<P ALIGN="center">&nbsp;</P>
		</TD>
	</TR>
	<TR>
		<TD VALIGN="top" WIDTH="7%">
		<img height="32" src="../CAAScrBase/images/ascenari.gif" width="32" border="0"></TD>
		<TD WIDTH="93%">
		<P><A NAME="Step"></A>CAAAniMeshAdvSurf includes the following steps:</P>
		<OL>
			<LI><A HREF="#prolog">Prolog</A></LI>
			<LI><A HREF="#Reference">Extracting the List of Mesh Parts and Publications</A></LI>
			<LI><A HREF="#Navigate">Creating Mesh part and Assigning Values to its 
			Attributes</A></LI>
			<LI><A HREF="#Epilog">Epilog</A></LI>
		</OL>
		<H4><A NAME="prolog"></A>Prolog</H4>
		<TABLE CLASS="code">
			<TR>
				<TD>
				<PRE>...</PRE>
				<PRE><FONT COLOR="#008000">' ----------------------------------------------------------- </FONT>
<FONT COLOR="#008000">' Optional: allows to find the sample wherever it's installed</FONT>
  sDocPath=CATIA.SystemService.Environ("CATDocView")

<FONT COLOR="#0000FF">  If </FONT>(Not CATIA.FileSystem.FolderExists(sDocPath))<FONT COLOR="#0000FF"> Then</FONT>
      Err.Raise 9999,,"No Doc Path Defined"
<FONT COLOR="#0000FF">    End If</FONT>
<FONT COLOR="#008000">' ----------------------------------------------------------- </FONT>
<FONT COLOR="#008000">'Open the Analysis document</FONT> 
sFilePath = CATIA.FileSystem.ConcatenatePaths(sDocPath, &quot;online\CAAScdAniUseCases\samples\Surface.CATAnalysis&quot;)
<FONT COLOR="#0000FF">Set</FONT> oAnalysisDocument = CATIA.Documents.Open(sFilePath)</PRE>
				<PRE>...</PRE>
				</TD>
			</TR>
		</TABLE>
		<P>Open the Analysis document. The Analysis document is retrieved in the 
		documentation installation path, this path has already been stored in the
		<CODE>sDocPath</CODE> variable. In the collection of documents, two documents 
		can be retrieved; the Analysis document and the Part document. </P>
		<H4><A NAME="Reference"></A>Extracting the List of Mesh Parts and Publications</H4>
		<TABLE CLASS="code">
			<TR>
				<TD>
				<PRE>...</PRE>
				<PRE>
<FONT COLOR="#008000">'Retrieve the Analysis Manager and Analysis Model</FONT>
<FONT COLOR="#0000FF">Set</FONT> oAnalysisManager = oAnalysisDocument.Analysis</PRE>
				<PRE>
<FONT COLOR="#008000">'Retreive the part document from Analysis manager</FONT>
<FONT COLOR="#0000FF">Set</FONT> oAnalysisLinkedDocument = oAnalysisManager.LinkedDocuments
<FONT COLOR="#0000FF">Set</FONT> partDocument = oAnalysisLinkedDocuments.Item(1)
<FONT COLOR="#0000FF">Set</FONT> product = partDocument.Product
			</PRE>
				<PRE>
<FONT COLOR="#008000">'Retrieve the analysis model from the list of models</FONT>
<FONT COLOR="#0000FF">Set</FONT> oAnalysisModels = oAnalysisManager.AnalysisModels
<FONT COLOR="#0000FF">Set</FONT> oAnalysisModel = oAnalysisManager.Item(1)</PRE>
				<PRE>
<FONT COLOR="#008000">'Retrieve mesh manager and mesh part </FONT>
<FONT COLOR="#0000FF">Set </FONT>oAnalysisMeshManager = oAnalysisModel.MeshManager
<FONT COLOR="#0000FF">Set </FONT>oAnalysisMeshParts = oAnalysisMeshManager.AnalysisMeshParts
</PRE>
				<PRE>
<FONT COLOR="#008000">'Retrieve publications from product and retrieve the published surface and edge</FONT>
<FONT COLOR="#0000FF">Set</FONT> publications1 = product.Publications
<FONT COLOR="#0000FF">Set</FONT> pubEdge = publications1.Item("Edge")
<FONT COLOR="#0000FF">Set</FONT> pubSurf = publications1.Item("Round Hole.1")</PRE>
				<PRE>
...</PRE>
				</TD>
			</TR>
		</TABLE>
		<P>According to the general
		<a href="../CAAScdAniTechArticles/CAAAniTocAnalysisDocument.htm">
		Analysis Document</A> structure, this macro uses some standard procedures 
		to navigate or retrieve the required objects. First, from the <B>Document</B>, 
		we find the <B>Analysis Manager Object</B>, the <B>Analysis Models</B> and 
		the <B>Mesh Manager Objects</B>. The extraction of pre-defined geometric 
		elements is done by using the Reference interface. This is equivalent to 
		the selection of a B-Rep element inside the interactive application. Here 
		the reference is created from a published face.</P>
		<H4><A NAME="Navigate"></A>Creating the Mesh Part and Assigning Values to 
		its Attributes.</H4>
		<TABLE CLASS="code">
			<TR>
				<TD>
				<PRE>...
<FONT COLOR="#008000">'Add the new Advanced surface mesh part to the list of mesh parts</FONT>
<FONT COLOR="#0000FF">Set </FONT>surfPart = meshParts.Add ("MSHPartSmartSurf")</PRE>
				<PRE>
<FONT COLOR="#008000">'Add support from the published surface</FONT>
surfPart.AddSupportFromPublication product, pubSurf</PRE>
				<P><FONT FACE="Courier New"><FONT COLOR="#008000">'Set the global 
				Specifications</FONT><BR>
				surfPart.SetGlobalSpecification "GlobalMethod", "Frontal triangle"<BR>
				surfPart.SetGlobalSpecification "GlobalSize", "20.0 mm"<BR>
				surfPart.SetGlobalSpecification "MinimumSize", "1.0 mm"<BR>
				surfPart.SetGlobalSpecification "ElementOrder", "Parabolic"<BR>
				surfPart.SetGlobalSpecification "FaceAngle", "0.0 deg"<BR>
				surfPart.SetGlobalSpecification "CurveAngle", "0.0 deg"<BR>
				surfPart.SetGlobalSpecification "DetailsElimination", 1<BR>
				surfPart.SetGlobalSpecification "StripOptimization", 1<BR>
				surfPart.SetGlobalSpecification "CleanSize", "1.0 mm"<BR>
				surfPart.SetGlobalSpecification "Offset", "0.0 mm"<BR>
				surfPart.SetGlobalSpecification "OffsetFromThickness", "0.0 mm"<BR>
				surfPart.SetGlobalSpecification "MinimizeTriangles", 1.<BR>
				surfPart.SetGlobalSpecification "MinSizeForSag", "1.0 mm"<BR>
				surfPart.SetGlobalSpecification "CurveCaptureTol", "1.0 mm"<BR>
				surfPart.SetGlobalSpecification "OptimizeRegularity", 1<BR>
				surfPart.SetGlobalSpecification "MeshRelSagValue", "1.0 mm"<BR>
				surfPart.SetGlobalSpecification "MeshRelSag", 1<BR>
				surfPart.SetGlobalSpecification "ConstraintSagValue", "1.0 mm"<BR>
				surfPart.SetGlobalSpecification "CurveCapture", 1<BR>
				surfPart.SetGlobalSpecification "MeshCapture", 1<BR>
				surfPart.SetGlobalSpecification "MeshCapturTol", "1.0 mm"<BR>
				surfPart.SetGlobalSpecification "MeshAbsSag", 2<BR>
				surfPart.SetGlobalSpecification "MeshAbsSagValue", "1.0 mm"<BR>
				<BR>
				<BR>
				<FONT COLOR="#008000">'Add the domain specifications as local specifications 
				and assign values to its attributes</FONT><BR>
				<FONT COLOR="#0000FF">Set </FONT>meshSpecs = surfPart.AnalysisMeshLocalSpecifications<BR>
				<FONT COLOR="#0000FF">Set </FONT>spec = meshSpecs.Add("MSHDistributionElement")<BR>
				spec.SetAttribute "NbElements", 50<BR>
				spec.SetAttribute "Type", "Isometric"<BR>
				spec.AddSupportFromPublication "Supports", product, pubEdge<BR>
				<BR>
				<FONT COLOR="#008000">&#39;Update the mesh part</FONT><BR>
				surfPart.Update<BR>
&nbsp;</FONT></P>
				<P>...</P>
				<PRE></PRE>
				</TD>
			</TR>
		</TABLE>
		<P>Here parameters are set with their respective units, this helps in 
		setting up of the parameters independent of the unit settings. Calling update on the mesh part computes the mesh.</P>
		<H4><A NAME="Epilog"></A>Epilog</H4>
		<TABLE CLASS="code">
			<TR>
				<TD>
				<PRE>...
 End Sub
...</PRE>
				</TD>
			</TR>
		</TABLE>
		<P>To run the macro interactively CATDocView 
		environment variable must be defined.</TD>
	</TR>
</TABLE>
<!---------------------------------comment------------------------------------->
<P ALIGN="center">
<img height="32" src="../CAAScrBase/images/aendtask.gif" width="64" border="0"></P>
<P ALIGN="right">[<A HREF="#Top">Top</A>]</P>
<HR>
<!---------------------------------comment------------------------------------->
<H4><A NAME="InShort"></A>In Short</H4>
<P>This use case has shown how to create advanced surface mesh parts and how to 
assign values to its local and global specifications.</P>
<P ALIGN="right">[<A HREF="#Top">Top</A>]</P>
<HR>
<!---------------------------------comment------------------------------------->
<H4><A NAME="References"></A>References</H4>
<TABLE WIDTH="100%" BORDER="0">
	<TR>
		<TD VALIGN="top" WIDTH="7%">[1]</TD>
		<TD WIDTH="93%">
		<a href="../CAAScdInfUseCases/CAAInfLauchMacro.htm">Replaying 
		a Macro</A></TD>
	</TR>
	<TR>
		<TD ALIGN="right" COLSPAN="2">[<A HREF="#Top">Top</A>]</TD>
	</TR>
</TABLE>
<HR>
<!---------------------------------comment------------------------------------->
<P><I>Copyright © 2001, Dassault Systèmes. All rights reserved.</I></P>

</BODY>

</HTML>
