<HTML>

<HEAD>
<TITLE>Creating Assembled Solution</TITLE>
<META HTTP-EQUIV="Content-Language" CONTENT="en-us">
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<META CONTENT="Microsoft FrontPage 6.0" NAME="GENERATOR">
<META CONTENT="FrontPage.Editor.Document" NAME="ProgId">
<link rel="stylesheet" type="text/css" href="../CAAScrBase/caav5.css">
<script language="JavaScript" src="../CAAScrJavaScript/submit.js"></SCRIPT>
</HEAD>

<BODY>

<TABLE WIDTH="100%" BORDER="0">
	<TR>
		<TD>
		<H2>Analysis Modeler</H2>
		</TD>
		<TD VALIGN="top" ALIGN="right">
		<H2><A NAME="Top"></A>Creating Assembled Solution</H2>
		</TD>
	</TR>
</TABLE>
<HR>
<!---------------------------------comment------------------------------------->
<TABLE WIDTH="100%" BORDER="0">
	<TR>
		<TD VALIGN="top" WIDTH="7%">
		<img height="32" src="../CAAScrBase/images/atarget.gif" width="32" border="0"></TD>
		<TD WIDTH="93%">
		<P><A NAME="Learn"></A>This use case shows you how to create an 
		assembled solution. Here use of Edit/Search... capability through VB is also 
		demonstrated.</P>
		<P>This macro opens an analysis assembly document and creates two 
		assembled solutions. In the first assembled solution a V4 imported 
		solution is added and in the second a static case is added. Both of 
		these solutions are selected using the Edit/Search... capability. 
		Assembled solution ( also called displacement assembly) is created in 
		assembled analysis. This solution is concatenation of several solutions 
		computed in the sub-analysis. This scenario is available only in 
		Generative Assembly Structural Analysis (GAS) product.</P>
		<P>&nbsp;</P>
		<P ALIGN="center"><img src="images/AsmbldSol.jpg" border="2"></P>
		<P>&nbsp;</P>
		</TD>
	</TR>
	<TR>
		<TD VALIGN="top" WIDTH="7%">
		<img height="32" src="../CAAScrBase/images/ainfo.gif" width="32" border="0"></TD>
		<TD WIDTH="93%">
		<P><A NAME="How"></A>CAAAniPreProAsmbldSol is launched in CATIA [<A HREF="#References">1</A>].No open document is needed.</P>
		<P><FONT COLOR="#FB7203"><a href="CAAAniPreProAsmbldSolSource.htm">CAAAniPreProAsmbldSol.catvbs</A></FONT>
		</A>is located in the CAAScdAniUseCases module.
		<a href="macros/CAAAniPreProAsmbldSol.catvbs">Execute macro</A> (Windows 
		only).</P>
		<P ALIGN="center">&nbsp;</P>
		</TD>
	</TR>
	<TR>
		<TD VALIGN="top" WIDTH="7%">
		<img height="32" src="../CAAScrBase/images/ascenari.gif" width="32" border="0"></TD>
		<TD WIDTH="93%">
		<P><A NAME="Step"></A>CAAAniPreProAsmbldSol includes the following steps:</P>
		<OL>
			<LI><A HREF="#prolog">Prolog</A></LI>
			<LI><A HREF="#Reference">Extracting the analysis documents and analysis models</A></LI>
			<LI><A HREF="#Navigate">Adding the assembled solution set</A></LI>
			<LI><A HREF="#Search">Searching through the selection and applying the selected objects</A></LI>
			<LI><A HREF="#Epilog">Epilog</A></LI>
		</OL>
		<H4><A NAME="prolog"></A>Prolog</H4>
		<TABLE CLASS="code">
			<TR>
				<TD>
				<PRE>...</PRE>
				<PRE><font color="#008000">' ----------------------------------------------------------- </font>
<font color="#008000">' Optional: allows to find the sample wherever it's installed</font>
sDocPath=CATIA.SystemService.Environ("CATDocView")
sSep=CATIA.SystemService.Environ("ADL_ODT_SLASH")

<font color="#0000FF">If </font>(Not CATIA.FileSystem.FolderExists(sDocPath))<font color="#0000FF"> Then</font>
Err.Raise 9999,,"No Doc Path Defined"
<font color="#0000FF">End If</font>
<font color="#008000">' ----------------------------------------------------------- </font>
<FONT COLOR="#008000">' Open the Analysis document</FONT> 
<font color="#0000FF">Set </font>analysisDocument1 = CATIA.Documents.Open(sDocPath & sSep & "online" & sSep & "CAAScdAniUseCases" &
						 sSep & "samples" & sSep & "Assembled_Loads_Slutions.CATAnalysis")
...</PRE>
				</TD>
			</TR>
		</TABLE>
		<P>Open the Analysis document. The Analysis document is retrieved in the 
		documentation installation path, this path has already been stored in the
		<CODE>sDocPath</CODE> variable. In the collection of documents, two documents 
		can be retrieved; the Analysis document and the Part document.</P>
		<H4><A NAME="Reference"></A><B>Extracting the analysis documents and 
		analysis models</B></H4>
		<TABLE CLASS="code">
			<TR>
				<TD>
				<PRE>...</PRE>
				<PRE>
<font color="#008000">'Retrieve the Analysis Manageer from tha analysis document</font>
<font color="#0000FF">Set </font>analysisManager1 = analysisDocument1.Analysis

<font color="#008000">'Retrieve the product document from the linked document</font>
<font color="#0000FF">Set </font>analysisLinkedDocuments1 = analysisManager1.LinkedDocuments
<font color="#0000FF">Set </font>productDocument1 = analysisLinkedDocuments1.Item(1)

<font color="#008000">'From product document retrieve products</font>
<font color="#0000FF">Set </font>product1 = productDocument1.Product
<font color="#0000FF">Set </font>products1 = product1.Products
<font color="#0000FF">Set </font>product2 = products1.Item("Analysis1.1")

<font color="#008000">'Retrieve the analysis models and the first model</font>
<font color="#0000FF">Set </font>analysisModels1 = analysisManager1.AnalysisModels
<font color="#0000FF">Set </font>analysisModel1 = analysisModels1.Item(1)

...</PRE>
				</TD>
			</TR>
		</TABLE>
		<P>According to the general
		<a href="../CAAScdAniTechArticles/CAAAniTocAnalysisDocument.htm">
		Analysis Document</A> structure, this macro uses some standard procedures 
		to navigate or retrieve the required objects. First, from the <B>Document</B>, 
		we find the <B>Analysis Manager Object</B>, and&nbsp; <B>Analysis Models</B>. 
		From analysis models we retrieve the <B>Analysis Cases.</B></P>
		<H4><A NAME="Navigate"></A>Adding the assembled load set</H4>
		<TABLE CLASS="code">
			<TR>
				<TD>
				<PRE>...  </PRE>
				<PRE><FONT COLOR="#008000">'Retrieve the analysis cases from analysis model</FONT>
&nbsp;<FONT COLOR="#0000FF">Set </FONT>analysisCases1 = analysisModel1.AnalysisCases
&nbsp;
<FONT COLOR="#008000">'Retrieve the second object that is Solution Case.1 </FONT>
<FONT COLOR="#008000">'from the list of analysis cases</FONT>
<FONT COLOR="#0000FF">Set </FONT>analysisCase1 = analysisCases1.Item(2)
&nbsp;
<FONT COLOR="#008000">'Retrieve the analysis case</FONT>
<FONT COLOR="#0000FF">Set </FONT>analysisSets1 = analysisCase1.AnalysisSets
&nbsp;
<FONT COLOR="#008000">'Add two Assembled solution sets</FONT>
<FONT COLOR="#0000FF">Set </FONT>analysisSet1 = analysisSets1.Add(&quot;ElfAssembledSet&quot;, catAnalysisSetOut)
<FONT COLOR="#0000FF">Set </FONT>analysisSet2 = analysisSets1.Add(&quot;ElfAssembledSet&quot;, catAnalysisSetOut)
&nbsp;
<FONT COLOR="#008000">'Retrieve the basic component from the analysis set</FONT>
<FONT COLOR="#0000FF">Set </FONT>basicComponents1 = analysisSet1.BasicComponents
<FONT COLOR="#0000FF">Set </FONT>basicComponent1 = basicComponents1.GetItem(&quot;ElfAssemblyPtr.1&quot;)
&nbsp;
<FONT COLOR="#008000">'Retrieve the basic component from the analysis set</FONT>
<FONT COLOR="#0000FF">Set </FONT>basicComponents2 = analysisSet2.BasicComponents
<FONT COLOR="#0000FF">Set </FONT>basicComponent2 = basicComponents2.GetItem(&quot;ElfAssemblyPtr.1&quot;)</PRE>
				<PRE>...</PRE>
				</TD>
			</TR>
		</TABLE>
		<H4><SPAN STYLE="font-weight: 400"><FONT COLOR="#000000">Here we 
		retrieve the solution case, in which we want to add the assembled load. 
		First the list of cases is retrieved from analysis model. The index 
		of the analysis case is same as that of the position in which it appears 
		in specification tree. Once we get the desired solution case we retrieve 
		the set and add assembled solution to it. To add analysis sets to 
		assembled solution</FONT></SPAN></H4>
		<H4><A NAME="Search"></A>Searching through the selection and applying the selected objects</H4>
		<TABLE CLASS="code">
			<TR>
				<TD>
				<PRE>...  </PRE>
				<PRE><font color="#008000">'Search and select</font>
<font color="#0000FF">Set </font>selection1 = analysisDocument1.Selection
selection1.Search "Name=*DISP*,all"

<font color="#008000">'Retrieve the analysis manager object from the analysis document</font>
<font color="#0000FF">Set </font>documents1 = CATIA.Documents
<font color="#0000FF">Set </font>analysisDocument2 = documents1.Item("Analysis1.CATAnalysis")
<font color="#0000FF">Set </font>analysisManager2 = analysisDocument2.Analysis


<font color="#008000">'Go through the selections and find out the the analysis set</font>
<font color="#008000">'create a reference from the analysis set and add it to the basic component</font>
<font color="#0000FF">For </font>i =1<font color="#0000FF"> To </font>selection1.Count
<font color="#0000FF">          Set </font>element = selection1.Item(i)
           IF (element.Type = "AnalysisSet" ) Then 'DO NOTHING
             <font color="#0000FF"> Set </font>Reference = analysisManager2.CreateReferenceFromObject(element.Value)
              basicComponent1.AddSupportFromProduct product2, Reference
         END IF
       
<font color="#0000FF">Next</font>

<font color="#008000">'Search and select</font>
selection1.Clear
selection1.Search "Name=*Static Case*,all"

<font color="#008000">'Remove the last static case, since this is at the same</font>
<font color="#008000">'level in the analysis assembly</font>
selection1.Remove2(selection1.Count)

<font color="#008000">'Go through the selections and find out the the analysis set</font>
<font color="#008000">'create a reference from the analysis set and add it to the basic component</font>
<font color="#0000FF">For </font>i =1<font color="#0000FF"> To </font>selection1.Count
<font color="#0000FF">          Set </font>element = selection1.Item(i)
           IF (element.Type = "AnalysisSet" ) Then 'DO NOTHING
<font color="#0000FF">               Set </font>Reference = analysisManager2.CreateReferenceFromObject(element.Value)
               basicComponent2.AddSupportFromProduct product2, Reference
         END IF
       
<font color="#0000FF">Next</font>

<font color="#008000">'update the two analysis sets</font>
analysisSet1.Update
analysisSet2.Update

</PRE>
				<PRE>...</PRE>
				</TD>
			</TR>
		</TABLE>
		<H4><SPAN STYLE="font-weight: 400"><FONT COLOR="#000000">The selection 
		interface allows the user to search objects by providing a search 
		string. This is equivalent of selecting objects interactively through edit 
		search. Here it is important to understand that all the objects which match the search 
		criterion will be selected, this may include objects which do not 
		qualify to be set as support to assembled solutions. Hence we add only 
		the element of type analysis set. First we search for 
		the V4 imported mesh and set as support to the assembled solution and 
		again we search for the static case solution which is set as support to 
		the second assembled solution. </FONT></SPAN></H4>
		<H4><A NAME="Epilog"></A>Epilog</H4>
		<TABLE CLASS="code">
			<TR>
				<TD>
				<PRE>...</PRE>
				 End Sub
				<PRE>...</PRE>
				</TD>
			</TR>
		</TABLE>
		</TD>
	</TR>
</TABLE>
<!---------------------------------comment------------------------------------->
<P ALIGN="center">
<img height="32" src="../CAAScrBase/images/aendtask.gif" width="64" border="0"></P>
<P ALIGN="right">[<A HREF="#Top">Top</A>]</P>
<HR>
<!---------------------------------comment------------------------------------->
<H4><A NAME="InShort"></A>In Short</H4>
<P>This use case has shown how to create assembled solution and how to select 
object using the selection interface.</P>
<P ALIGN="right">[<A HREF="#Top">Top</A>]</P>
<HR>
<!---------------------------------comment------------------------------------->
<H4><A NAME="References"></A>References</H4>
<TABLE WIDTH="100%" BORDER="0">
	<TR>
		<TD VALIGN="top" WIDTH="74">[1]</TD>
		<TD WIDTH="93%">
		<a href="../CAAScdInfUseCases/CAAInfLauchMacro.htm">Replaying 
		a Macro</A></TD>
	</TR>
	<TR>
		<TD ALIGN="right" COLSPAN="2">[<A HREF="#Top">Top</A>]</TD>
	</TR>
</TABLE>
<HR>
<!---------------------------------comment------------------------------------->
<P><I>Copyright © 2001, Dassault Systèmes. All rights reserved.</I></P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>
<P>&nbsp;</P>

</BODY>

</HTML>

