<HTML>

<HEAD>
<META HTTP-EQUIV="Content-Type" CONTENT="text/html; charset=iso-8859-1">
<TITLE>CAAAniMeshTetraFiller.catvbs</TITLE>
<link rel="stylesheet" type="text/css" href="../CAAScrBase/caav5.css">
</HEAD>

<BODY>

<PRE>
<FONT COLOR="#008000">' COPYRIGHT DASSAULT SYSTEMES 2000</FONT>

<FONT COLOR="#008000">' ***********************************************************************</FONT>
<FONT COLOR="#008000">'   Purpose:  Create a tetrahedron filler mesh part</FONT>
<FONT COLOR="#008000">'                   assign the support as surface mesh part</FONT>
<FONT COLOR="#008000">'                   specify the global specifications           </FONT>
<FONT COLOR="#008000">'   Assumptions:  Looks for Surface Mesh.1 in the analysis doc</FONT>
<FONT COLOR="#008000">'   Author:       bmw</FONT>
<FONT COLOR="#008000">'   Languages:    VBScript</FONT>
<FONT COLOR="#008000">'   Locales:      English </FONT>
<FONT COLOR="#008000">'   CATIA Level:  V5R16</FONT>
<FONT COLOR="#008000">' ***********************************************************************</FONT>


<FONT COLOR="#0000FF">Sub </FONT>CATMain()

<FONT COLOR="#008000">' ----------------------------------------------------------- </FONT>
<FONT COLOR="#008000">' Optional: allows to find the sample wherever it's installed</FONT>
  sDocPath=CATIA.SystemService.Environ("CATDocView")

<FONT COLOR="#0000FF">    If </FONT>(Not CATIA.FileSystem.FolderExists(sDocPath))<FONT COLOR="#0000FF"> Then</FONT>
      Err.Raise 9999,,"No Doc Path Defined"
<FONT COLOR="#0000FF">    End If</FONT>
<FONT COLOR="#008000">' ----------------------------------------------------------- </FONT>


<FONT COLOR="#008000">' Open the CATAnalysis Document</FONT>
sFilePath = CATIA.FileSystem.ConcatenatePaths(sDocPath, &quot;online\CAAScdAniUseCases\samples\Cube_R13_Freq.CATAnalysis&quot;)
<FONT COLOR="#0000FF">Set</FONT> oAnalysisDocument = CATIA.Documents.Open(sFilePath)


<FONT COLOR="#008000">'Retrieve the Analysis Manager and Analysis Model</FONT>
<FONT COLOR="#0000FF">Set </FONT>oAnalysisManager = oAnalysisDocument.Analysis

<FONT COLOR="#008000">'Retrieve the part document and product</FONT>
<FONT COLOR="#0000FF">Set </FONT>oAnalysisLinkedDocuments = oAnalysisManager.LinkedDocuments
<FONT COLOR="#0000FF">Set </FONT>partDocument = oAnalysisLinkedDocuments.Item(1)
<FONT COLOR="#0000FF">Set </FONT>product = partDocument.Product

<FONT COLOR="#008000">'Retrieve the analysis model from list of models</FONT>
<FONT COLOR="#0000FF">Set </FONT>oAnalysisModels = oAnalysisManager.AnalysisModels
<FONT COLOR="#0000FF">Set </FONT>oAnalysisModel = oAnalysisModels.Item(1)

<FONT COLOR="#008000">' Retrieve mesh manager and mesh part from the list of mesh parts specifying its name</FONT>
<FONT COLOR="#0000FF">Set </FONT>oAnalysisMeshManager = oAnalysisModel.MeshManager 
<FONT COLOR="#0000FF">Set </FONT>oAnalysisMeshParts = oAnalysisMeshManager.AnalysisMeshParts
<FONT COLOR="#0000FF">Set </FONT>oAnalysisMeshPart = oAnalysisMeshParts.Item("Surface Mesh.1")

<FONT COLOR="#008000">' Create Reference from the mesh part.</FONT>
<FONT COLOR="#0000FF">Set </FONT>reference1 = oAnalysisManager.CreateReferenceFromObject(oAnalysisMeshPart)

<FONT COLOR="#008000">' Add the new Tetrahedron Filler mesh part to the list of mesh parts</FONT>
<FONT COLOR="#0000FF">Set </FONT>tetraFiller = oAnalysisMeshParts.Add ("MSHPartGHS3D") 


<FONT COLOR="#008000">' Add reference previously created</FONT>
tetraFiller.AddSupportFromReference NOTHING, reference1

<FONT COLOR="#008000">' Set the global Specifications</FONT>
tetraFiller.SetGlobalSpecification "Propagation", 1.5
tetraFiller.SetGlobalSpecification "ElementOrder", "Parabolic"

<FONT COLOR="#008000">'Update the mesh part</FONT>
tetraFiller.Update

<FONT COLOR="#0000FF">End Sub</FONT>



</PRE>

</BODY>

</HTML>
