<html><head><meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"><title>CAAPstAddComponent.CATScript</title><link rel="stylesheet" type="text/css" href="../CAAScrBase/caav5.css"></head><body><pre>
<font color="#0000FF">Option Explicit</font>
<font color="#008000">' COPYRIGHT DASSAULT SYSTEMES 2000</font>

<font color="#008000">' *****************************************************************************</font>
<font color="#008000">'   Purpose:       Create A Product Structure document containing</font>
<font color="#008000">'                        two parts and multiply the instances of one of these parts,</font>
<font color="#008000">'                        creating identical products differing only in their position.</font>
<font color="#008000">'   Assumtions:   Looks for CAAPstHull.CATPart and</font>
<font color="#008000">'                        CAAPstFunnel.CATPart in the CATDocView   </font>
<font color="#008000">'   Author: </font>
<font color="#008000">'   Languages:   VBScript</font>
<font color="#008000">'   Locales:        English </font>
<font color="#008000">'   CATIA Level:  V5R6 </font>
<font color="#008000">' *****************************************************************************</font>


<font color="#0000FF">Sub </font>CATMain()

    <font color="#008000">' -----------------------------------------------------------------------------------------------</font>
    <font color="#008000">' Optional: allows to find the sample wherever it's installed</font>
<font color="#0000FF">    Dim </font>sDocPath<font color="#0000FF"> As </font>String
    sDocPath=CATIA.SystemService.Environ("CATDocView")
<font color="#0000FF">    If </font>(Not CATIA.FileSystem.FolderExists(sDocPath))<font color="#0000FF"> Then</font>
      Err.Raise 9999,,"No Doc Path Defined"
<font color="#0000FF">    End If</font>
    <font color="#008000">' ------------------------------------------------------------------------------------------------ </font>
   
    <font color="#008000">'Create a new product document object by adding a document with the Product</font>
    <font color="#008000">'type to the document collection of the CATIA application. </font>
<font color="#0000FF">    Dim </font>oProductDoc<font color="#0000FF"> As </font>Document
<font color="#0000FF">    Set </font>oProductDoc = CATIA.Documents.Add("Product")

    <font color="#008000">'Retrieve the Titanic as the root product.</font>
<font color="#0000FF">    Dim </font>oTitanic<font color="#0000FF"> As </font>Product
<font color="#0000FF">    Set </font>oTitanic = oProductDoc.Product

    <font color="#008000">'Declare the Titanic's part number and name.</font>
    oTitanic.PartNumber = "Titanic"
    oTitanic.Name = "Steam_Ship_Titanic"
    
    <font color="#008000">'Retrieve the product's collection of the Titanic.</font>
<font color="#0000FF">    Dim </font>oTitanicProducts<font color="#0000FF"> As </font>Products
<font color="#0000FF">    Set </font>oTitanicProducts = oTitanic.Products
 
    <font color="#008000">'Add the hull as a new component in the collection with its part number </font>
    <font color="#008000">'and name. </font>
<font color="#0000FF">    Dim </font>oHull<font color="#0000FF"> As </font>Product
<font color="#0000FF">    Set </font> oHull = oTitanicProducts.AddNewProduct("Hull_Type")
    oHull.PartNumber = "Titanic's_Hull"
    oHull.Name = "Unsinkable_Hull"

    <font color="#008000">'Add a master shape representation to the hull using an existing part and</font>
    <font color="#008000">'reframe the viewer.</font>
    oHull.AddMasterShapeRepresentation sDocPath & "CAAPstHull.CATPart"
    CATIA.ActiveWindow.ActiveViewer.Reframe
    
    <font color="#008000">'Add the first funnel to the Titanic's product collection, with part number</font>
    <font color="#008000">'and name.</font>
<font color="#0000FF">    Dim </font>oFunnel1<font color="#0000FF"> As </font>Product
<font color="#0000FF">    Set </font>oFunnel1 = oTitanicProducts.AddNewProduct("Funnel_Type")
    oFunnel1.PartNumber = "Titanic's_Funnel"
    oFunnel1.Name = "Fore_Funnel"

    <font color="#008000">'Add a master shape representation to the funnel using an existing part</font>
    oFunnel1.AddMasterShapeRepresentation sDocPath & "CAAPstFunnel.CATPart"
 
    <font color="#008000">'Define the initial positioning parameters for the Funnel1 instances.</font>
<font color="#0000FF">    Dim </font>iMatrix(11)
    iMatrix(0) = 1.0
    iMatrix(1) = 0.0
    iMatrix(2) = 0.0
    iMatrix(3) = 0.0
    iMatrix(4) = 1.0
    iMatrix(5) = 0.0
    iMatrix(6) = 0.0
    iMatrix(7) = 0.0
    iMatrix(8) = 1.0
    iMatrix(9) = 0.0
    iMatrix(10) = 0.0
    iMatrix(11) = 0.0    
    
    <font color="#008000">'Get the reference of the Funnel product</font>
<font color="#0000FF">    Dim </font>oFunnelRef<font color="#0000FF"> As </font>Product
<font color="#0000FF">    Set </font>oFunnelRef = oFunnel1.ReferenceProduct

    <font color="#008000">'Add a second component using the existing Funnel product's reference.</font>
<font color="#0000FF">    Dim </font>oFunnel2<font color="#0000FF"> As </font>Product
<font color="#0000FF">    Set </font>oFunnel2 = oTitanicProducts.AddComponent(oFunnelRef)
    oFunnel2.Name = "Second_Funnel"
    <font color="#008000">'Associate the new product with a different position from its reference</font>
    iMatrix(9) = -40.0
    oFunnel2.Move.Apply iMatrix

    <font color="#008000">'Add a third component using the existing Funnel product's reference.</font>
<font color="#0000FF">    Dim </font>oFunnel3<font color="#0000FF"> As </font>Product
<font color="#0000FF">    Set </font>oFunnel3 = oTitanicProducts.AddComponent(oFunnelRef)
    oFunnel3.Name = "Third_Funnel"
    <font color="#008000">'Associate the new product with a different position from its reference</font>
    iMatrix(9) = -80.0
    oFunnel3.Move.Apply iMatrix

    <font color="#008000">'Add a fourth component using the existing Funnel product's reference.</font>
<font color="#0000FF">    Dim </font>oFunnel4<font color="#0000FF"> As </font>Product
<font color="#0000FF">    Set </font>oFunnel4 = oTitanicProducts.AddComponent(oFunnelRef)
    oFunnel4.Name = "Fourth_Funnel"
    <font color="#008000">'Associate the new product with a different position from its reference</font>
    iMatrix(9) = -120.0
    oFunnel4.Move.Apply iMatrix
     
<font color="#0000FF">End Sub</font>

</pre></body></html>


