<html><head><meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"><title>CAAPstAddNewProduct.CATScript</title><link rel="stylesheet" type="text/css" href="../CAAScrBase/caav5.css"></head><body><pre>
<font color="#0000FF">Option Explicit</font>
<font color="#008000">' COPYRIGHT DASSAULT SYSTEMES 2000</font>

<font color="#008000">' *****************************************************************************</font>
<font color="#008000">'   Purpose:       Create A Product Structure document containing</font>
<font color="#008000">'                        two parts.</font>
<font color="#008000">'   Assumtions:   Looks for CAAPstPad1_1.CATPart and</font>
<font color="#008000">'                        CAAPstPad1_2.CATPart in the CATDocView   </font>
<font color="#008000">'   Author: </font>
<font color="#008000">'   Languages:   VBScript</font>
<font color="#008000">'   Locales:        English </font>
<font color="#008000">'   CATIA Level:  V5R6 </font>
<font color="#008000">' *****************************************************************************</font>


<font color="#0000FF">Sub </font>CATMain()

    <font color="#008000">' -----------------------------------------------------------------------------------------------</font>
    <font color="#008000">' Optional: allows to find the sample wherever it's installed</font>
<font color="#0000FF">    Dim </font>sDocPath<font color="#0000FF"> As </font>String
    sDocPath=CATIA.SystemService.Environ(&quot;CATDocView&quot;)
<font color="#0000FF">    If </font>(Not CATIA.FileSystem.FolderExists(sDocPath))<font color="#0000FF"> Then</font>
      Err.Raise 9999,,&quot;No Doc Path Defined&quot;
<font color="#0000FF">    End If</font>
    <font color="#008000">' ------------------------------------------------------------------------------------------------ </font>
   
    <font color="#008000">'Create a new product document by adding a document with the Product type</font>
    <font color="#008000">'to the document collection of the CATIA application. </font>
<font color="#0000FF">    Dim </font>oProductDoc<font color="#0000FF"> As </font>Document
<font color="#0000FF">    Set </font>oProductDoc = CATIA.Documents.Add(&quot;Product&quot;)

    <font color="#008000">'Retrieve the root product.</font>
<font color="#0000FF">    Dim </font>oRootProduct<font color="#0000FF"> As </font>Product
<font color="#0000FF">    Set </font>oRootProduct = oProductDoc.Product

    <font color="#008000">'Declare the root product's part number and name.</font>
    oRootProduct.PartNumber = &quot;Root&quot;
    oRootProduct.Name = &quot;The_Root_Product&quot;

    <font color="#008000">'Retrieve the product's collection under the root product.</font>
<font color="#0000FF">    Dim </font>oRootChildren<font color="#0000FF"> As </font>Products
<font color="#0000FF">    Set </font>oRootChildren = oRootProduct.Products

    <font color="#008000">'Add a new product to the collection. This adds both a product reference</font>
    <font color="#008000">'and a product component.</font>
<font color="#0000FF">    Dim </font>oChildProduct1<font color="#0000FF"> As </font>Product
<font color="#0000FF">    Set </font>oChildProduct1 = oRootChildren.AddNewProduct(&quot;Child_1_Type&quot;)

    <font color="#008000">'Declare the part number and name for this product.</font>
    oChildProduct1.PartNumber = &quot;Child_001&quot;
    oChildProduct1.Name = &quot;1st_Child&quot;

    <font color="#008000">'Add a representation to this product using an existing part and reframe</font>
    <font color="#008000">'the viewer to display the part completely.</font>
    oChildProduct1.AddMasterShapeRepresentation sDocPath &amp; &quot;CAAPstPad1_1.CATPart&quot;
    CATIA.ActiveWindow.ActiveViewer.Reframe

    <font color="#008000">'Add another product to the root product's collection.  This adds both</font>
    <font color="#008000">'a product reference and a product component.</font>
<font color="#0000FF">    Dim </font>oChildProduct2<font color="#0000FF"> As </font>Product
<font color="#0000FF">    Set </font>oChildProduct2 = oRootChildren.AddNewProduct(&quot;Child_2_Type&quot;)

    <font color="#008000">'Declare the part number and name for this product.</font>
    oChildProduct2.PartNumber = &quot;Child_002&quot;
    oChildProduct2.Name = &quot;2nd_Child&quot;

    <font color="#008000">'Add a representation to this product using an existing part and reframe</font>
    <font color="#008000">'the viewer to display the part completely.</font>
    oChildProduct2.AddMasterShapeRepresentation sDocPath &amp; _
       &quot;\online\CAAScdPstUseCases\samples\CAAPstPad1_2.CATPart&quot;
    CATIA.ActiveWindow.ActiveViewer.Reframe()
     
<font color="#0000FF">End Sub</font>

</pre></body></html>


