<html>

<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<meta name="GENERATOR" content="Microsoft FrontPage 4.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
<title>Adding an External Component</title>
<link rel="stylesheet" type="text/css" href="../CAAScrBase/caav5.css">
<script language="JavaScript" src="../CAAScrJavaScript/submit.js"></script>
</head>

<body>

<table border="0" width="100%">
  <tr>
    <td>
      <h2>Product Structure</h2>
    </td>
    <td align="right" valign="top">
      <h2><a name="Top"></a>Adding an External Component</h2>
    </td>
  </tr>
</table>
<hr>
<! ---------------------------------comment------------------------------------->
<table border="0" width="100%">
  <tr>
    <td valign="top"><img border="0" src="../CAAScrBase/images/atarget.gif" height="32"></td>
    <td>
      <p><a name="Learn"></a>This macro shows you how to create a simple product
      structure that imports an existing Part from an external Part document. It
      assumes that the CATDocView has been initialized so that it references the
      path leading to the part document, CAAPstHull.CATPart.&nbsp;</p>
      <! ---------------------------------comment------------------------------------->
      <p>Here is an image of the resulting product structure:</p>
      <table border="0" cellpadding="0" cellspacing="0" width="100%">
        <tr>
          <td width="100%"><img border="0" src="image/CAAPstAddExternalComponent.jpg" height="278"></td>
        </tr>
      </table>
      <p>&nbsp;</p>
    </td>
  </tr>
  <tr>
    <td valign="top"><img border="0" src="../CAAScrBase/images/ainfo.gif" height="32"></td>
    <td>
      <p><a name="How"></a>CAAPstAddExternalComponent is launched in CATIA [<a href="#References">1</a>].
      No previously opened document is needed.</p>
      <p><a href="CAAPstAddExternalComponentSource.htm" target="Source">CAAPstAddExternalComponent.CATScript
      </a>is located in the CAAScdPstUseCases module. <a href="macros/CAAPstAddExternalComponent.CATScript">Execute
      macro</a> (Windows only).</p>
    </td>
  </tr>
  <tr>
    <td valign="top"><img border="0" src="../CAAScrBase/images/ascenari.gif" height="32"></td>
    <td>
      <p><a name="Step"></a>CAAPstAddExternalComponent includes three steps:</p>
      <ol>
        <li><a href="#Prolog">Prolog</a></li>
        <li><a href="#OpenPartDoc">Open the Part Document</a></li>
        <li><a href="#ImportPartDoc">Import the Part Document as a Product in
          the Collection of Products</a></li>
      </ol>
      <h4><a name="Prolog"></a>Prolog</h4>
      <table class="code">
        <tr>
          <td>
            <pre>  ...
      <font color="#008000">'Create a new product document object by adding a document with the Product
      'type to the document collection of the CATIA application. 
      </font><font color="#0000FF">Dim</font> oProductDoc <font color="#0000FF">As</font> Document
      <font color="#0000FF">Set</font> oProductDoc = CATIA.Documents.<b>Add</b>(&quot;Product&quot;)<font color="#008000"> 

      'Retrieve the root product.
      </font><font color="#0000FF">Dim</font> oRoot <font color="#0000FF">As</font> Product
      <font color="#0000FF">Set</font> oRoot = oProductDoc.Product<font color="#008000">

      'Retrieve the root product collection of products.
      </font><font color="#0000FF">Dim</font> oRootCol <font color="#0000FF">As</font> Products
      <font color="#0000FF">Set</font> oRootCol = oRoot.Products<font color="#008000">      </font>
  ...</pre>
          </td>
        </tr>
      </table>
      <p>A new Product document is created using the <code>Add</code> method of
      the documents collection (<i>Documents o</i>bject). Next, the root product
      of the document is retrieved using the <code>Product</code> property of
      the <i>ProductDocument </i>object.&nbsp; Finally, the product's collection
      is retrieved using the <code>Products</code> property of the <i>Product </i>object.</p>
      <h4><a name="OpenPartDoc"></a>Open the Part Document</h4>
      <table class="code">
        <tr>
          <td>
            <pre>  ...
      <font color="#008000">'Open the Part Document
      </font><font color="#0000FF">Dim</font> oPartDoc <font color="#0000FF">As</font> Document
      <font color="#0000FF">Set</font> oPartDoc = CATIA.Documents.<b>Open</b>(sDocPath &amp; &quot;CAAPstHull.CATPart&quot;)<font color="#008000">
</font>  ...</pre>
          </td>
        </tr>
      </table>
      <p>The Part document to be imported is opened using the <code>Open</code>
      method of the<i> Documents </i>object.</p>
      <h4><a name="ImportPartDoc"></a>Import the Part Document as a Product in
      the Collection of Products</h4>
      <table class="code">
        <tr>
          <td>
            <pre>  ...
      <font color="#008000">'Add a new component from the already opened part document.
      </font><font color="#0000FF">Dim</font> oNewComponent <font color="#0000FF">As</font> Product
      <font color="#0000FF">Set</font> oNewComponent = oRootCol.<b>AddExternalComponent</b>(oPartDoc)
  ...</pre>
          </td>
        </tr>
      </table>
      <p>A new part is imported under the product collection using the <code>AddExternalComponent</code>
      method of the <i>Products </i>object.</p>
    </td>
  </tr>
</table>
<! ---------------------------------comment------------------------------------->
<p align="center"><img border="0" src="../CAAScrBase/images/aendtask.gif" height="32"></p>
<p align="right">[<a href="#Top">Top</a>]</p>
<hr>
<! ---------------------------------comment------------------------------------->
<h4><a name="InShort"></a>In Short</h4>
<p>This use case has shown how to create a simple product structure that imports
an existing Part from an external Part document. Specifically, it has
illustrated using:</p>
<ul>
  <li>The <code>Add</code> method the <i>Documents </i>object to create a new
    Product document.</li>
  <li>The <code>Product</code> property of the <i>ProductDocument </i>object to
    retrieve the root product of the document.</li>
  <li>The <code>Products</code> property of the <i>Product </i>object to
    retrieve the product collection.</li>
  <li>The <code>Open</code> method of the <i>Documents</i> object to open an
    existing external Part document.</li>
  <li>The <code>AddExternalComponent</code> method of the <i>Products </i>object
    to import the part as a product under the product collection.</li>
</ul>
<p align="right">[<a href="#Top">Top</a>]</p>
<hr>
<! ---------------------------------comment------------------------------------->
<h4><a name="References"></a>References</h4>
<table border="0" width="100%">
  <tr>
    <td valign="top">[1]</td>
    <td><a href="../CAAScdInfUseCases/CAAInfLauchMacro.htm">Replaying
      a macro</a></td>
  </tr>
  <tr>
    <td colspan="2" align="right">[<a href="#Top">Top</a>]</td>
</table>
<hr>
<! ---------------------------------comment------------------------------------->
<p><i>Copyright © 2001, Dassault Systèmes. All rights reserved.</i></p>

</body>
