<html>
<head>
 <meta name="Generator" content="mihGene v1.1">
 <meta http-equiv="Expires" content="Tue, 04 Dec 1993 21:29:02 GMT">
 <title>OSMInterfaces SceneWorkbench (Object)</title>
<link rel="Stylesheet" type="text/css" href="../../../caav5.css">
<script language="Javascript" src="../_index/jslink.js"></script> 
<script language="Javascript" src="jsFwLink.js"></script> 
<script language="Javascript" type="text/javascript" src="../_index/jsTree.js"></script>  
</head>
<body>
<pre><a href="../_index/main.htm">All Frameworks</a>  <a href="../_index/tree.htm">Object Hierarchy</a>  <a href="../OSMInterfaces.htm">This Framework</a>  <a href="../_index/CAAHomeIdx.htm">Indexes</a>  <script type="text/javascript"> 
 var test=locateObject('SceneWorkbench','interface','0'); 
 if(test==1){ 
     document.write("<a href=\"#\" onclick=\"openLinkNP('SceneWorkbench','interface','0');return false\">Previous</a> "); 
 } 
 test=locateObject('SceneWorkbench','interface','1'); 
 if(test==1){ 
     document.write("<a href=\"#\" onclick=\"openLinkNP('SceneWorkbench','interface','1');return false\">Next</a> "); 
 } 
 </script> 
</pre>
<hr>
<h1>SceneWorkbench<font size=-1> (Object)</font></h1>
<script type="text/javascript" > 
 generatedFatherClass('interface_SceneWorkbench_21176','SceneWorkbench','0');</script>
<b><i>   Represent the access point to scenes management.</i></b><br>
<hr>
<dl>
 <h2><a name="PropertyIndex"></a>Property Index</h2>
 <dt>
    <a href="#WorkScenes"><b>WorkScenes</b></a>
<dd>  Returns the Scenes collection.
</dl>
<dl>
</dl>
 <h2><a name="Properties"></a>Properties</h2> <br>
<a name="WorkScenes"><dt>

<table><tr><td>o Property <b>WorkScenes</b>(<td>) As <script type="text/javascript"> activateLink('Scenes','Scenes')</script>  (Read Only)</table></dt>
<dl>
  <dd>
 Returns the Scenes collection.
 
<dl>
  <dt> <b>Example:</b> 
  <dd>      This example retrieves the WorkScenes collection of the active document.
    <pre>
    Dim TheWorkSceneWorkbench As Workbench
    Set TheWorkSceneWorkbench = CATIA.ActiveDocument.GetWorkbench ( "SceneWorkbench" )
    Dim TheScenesList As WorkScenes
    Set TheScenesList = TheWorkSceneWorkbench.<font color="red">WorkScenes</font>
    </pre>
</dl>
</dl>

</body>
<hr><p><i>
Copyright &#169; 1999-2011, Dassault Syst&#232;mes. All rights reserved.</i></p>
</html>
