<html>

<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<meta name="GENERATOR" content="Microsoft FrontPage 4.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
<title>Creating an ArrangementPathway Object</title>
<link rel="stylesheet" type="text/css" href="../CAAScrBase/caav5.css">
<script language="JavaScript" src="../CAAScrJavaScript/submit.js"></script>
</head>

<body>

<table border="0" width="100%">
  <tr>
    <td>
      <h2>Arrangement</h2>
    </td>
    <td align="right" valign="top">
      <h2><a name="Top"></a>Creating an ArrangementPathway Object</h2>
    </td>
  </tr>
</table>
<hr>
<!----------------------------------comment------------------------------------->
<table border="0" width="100%">
  <tr>
    <td width="7%" valign="top"><img border="0" src="../CAAScrBase/images/atarget.gif" width="32" height="32"></td>
    <td width="93%">
      <p><a name="Learn"></a>This macro shows you how to create an <i>ArrangementPathway</i>
      under a product.</p>
      <p>This macro opens a new product document and retrieves the <a href="#" onclick="javascript:CAAlink('IDL', 'CATArrangementInterfaces', 'ArrangementPathways');return false;"><i>ArrangementPathways</i></a>
      collection from the root <a href="#" onclick="javascript:CAAlink('IDL', 'ProductStructureInterfaces', 'Product');return false;"><i>Product</i></a>
      via the <a href="#" onclick="javascript:CAAlink('IDL', 'CATArrangementInterfaces', 'ArrangementProduct');return false;"><i>ArrangementProduct</i></a>
      object. It then adds an <a href="#" onclick="javascript:CAAlink('IDL', 'CATArrangementInterfaces', 'ArrangementPathway');return false;"><i>ArrangementPathway</i></a>
      object. Once the <i>ArrangementPathway</i> object is created, the
      individual <a href="#" onclick="javascript:CAAlink('IDL', 'CATArrangementInterfaces', 'ArrangementNode');return false;"><i>ArrangementNode</i></a>'s
      that make up the object are retrieved and the bend radius is applied on
      them.</p>
      <p align="center"><img border="0" src="images/CAAArrCreatePathway.jpg" width="471" height="325"></p>
      <p>&nbsp;</p>
    </td>
  </tr>
  <tr>
    <td width="7%" valign="top"><img border="0" src="../CAAScrBase/images/ainfo.gif" width="32" height="32"></td>
    <td width="93%">
      <p><a name="How"></a>CAAArrCreatePathway is launched in CATIA [<a href="#References">1</a>].
      No open document is needed.</p>
      <p><a href="CAAArrCreatePathwaySource.htm">CAAArrCreatePathway.CATScript </a>is
      located in the CAAScdArrUseCases module. <a href="macros/CAAArrCreatePathway.CATScript">Execute
      macro</a> (Windows only).</p>
      <p align="center">&nbsp;</p>
    </td>
  </tr>
  <tr>
    <td width="7%" valign="top"><img border="0" src="../CAAScrBase/images/ascenari.gif" width="32" height="32"></td>
    <td width="93%">
      <p><a name="Step"></a>CAAArrCreatePathway includes the following steps:</p>
      <ol>
        <li><a href="#prolog">Prolog</a></li>
        <li><a href="#Reference">Obtaining the ArrangementProduct Object and the
          Associated Movable Object from the Root Product</a></li>
        <li><a href="#Navigate">Creating the ArrangementPathway Object under the
          ArrangementPathways Collection Object</a></li>
        <li><a href="#bound">Modifying Properties (Defining a Round Section,
          Changing the Visualization Mode and Bend Radii of the Nodes) of the
          Newly Created ArrangementPathway Object</a></li>
        <li><a href="#Epilog">Epilog</a></li>
      </ol>
      <h4><a name="prolog"></a>Prolog</h4>
      <table class="code">
        <tr>
          <td>
            <pre>  ...
   <font color="#008000">'----------------------------------------------</font>
   <font color="#008000">'Create a new product document</font>
<font color="#0000FF">   Dim </font>objProdDoc       <font color="#0000FF"> As </font>ProductDocument
<font color="#0000FF">   Dim </font>objRootProd      <font color="#0000FF"> As </font>Product
<font color="#0000FF">   Set </font>objProdDoc      = CATIA.Documents.Add(&quot;Product&quot;)
<font color="#0000FF">   Set </font>objRootProd     = objProdDoc.Product
   ...</pre>
          </td>
        </tr>
      </table>
      <p>Once the new product document has been created, fetch the <i>ArrangementProduct</i>
      and the associated movable object from the root product of the new product
      document.</p>
      <h4><a name="Reference"></a>Obtaining the ArrangementProduct Object and
      the Associated Movable Object from the Root Product</h4>
      <table class="code">
        <tr>
          <td>
            <pre>...
   <font color="#008000">'----------------------------------------------</font>
   <font color="#008000">'Retrieving Root Product's Relative Axis and Position Information</font>
<font color="#0000FF">   Dim </font>objMove          <font color="#0000FF"> As </font>Move
<font color="#0000FF">   Set </font>objMove      = objRootProd.Move

   <font color="#008000">'----------------------------------------------</font>
   <font color="#008000">' Get ArrangementProduct</font>
<font color="#0000FF">   Dim </font>objArrProd       <font color="#0000FF"> As </font>ArrangementProduct
<font color="#0000FF">   Set </font>objArrProd   = objRootProd.GetTechnologicalObject(&quot;ArrangementProduct&quot;)
...</pre>
          </td>
        </tr>
      </table>
      <p>The <i>ArrangementPathways</i> object is a collection object that
      manages <i>ArrangementPathway</i> object's under a given <i>ArrangementProduct</i>.
      The movable object serves as the relative axis for the new <i>ArrangementPathway</i>
      object to be created.</p>
      <h4><a name="Navigate"></a>Creating the ArrangementPathway Object under
      the ArrangementPathways Collection Object</h4>
      <table class="code">
        <tr>
          <td>
            <pre>...
   <font color="#008000">' Create ArrangementPathway under the Root Product</font>
<font color="#0000FF">   Dim </font>dblPathwayPoints(75)     <font color="#0000FF"> As </font>Double
<font color="#0000FF">   Dim </font>dblMathDirection(3)       <font color="#0000FF"> As </font>Double
<font color="#0000FF">   Dim </font>objArrPathway            <font color="#0000FF"> As </font>ArrangementPathway


   dblPathwayPoints(0)   =  300.0
   dblPathwayPoints(1)   =  100.0
   dblPathwayPoints(2)   =  0.0

   dblPathwayPoints(3)   =  441.42
   dblPathwayPoints(4)   =  158.58
   dblPathwayPoints(5)   =  1.25

...

   dblPathwayPoints(72)  =  300.0
   dblPathwayPoints(73)  =  100.0
   dblPathwayPoints(74)  =  30

   dblMathDirection(0) = 1.0
   dblMathDirection(1) = 0.0
   dblMathDirection(2) = 0.0

<font color="#0000FF">   Set </font>objArrPathway        = objArrProd.ArrangementPathways.AddPathway(objMove, _
                                                                        dblPathwayPoints, _
                                                                        dblMathDirection)
  ...</pre>
          </td>
        </tr>
      </table>
      <p>The newly created <i>ArrangementPathway</i> object is visualized as a
      curve and does not have any section definition. In addition the nodes do
      not have any bend radius.&nbsp;</p>
      <h4><a name="bound"></a>Modifying Properties (Defining a Round Section,
      Changing the Visualization Mode and Bend Radii of the Nodes) of the Newly
      Created ArrangementPathway Object</h4>
      <table class="code">
        <tr>
          <td>
            <pre>  ...
   <font color="#008000">'----------------------------------------------</font> <font color="#008000">
   ' Change Properties of ArrangementPathway
   </font>objArrPathway.SectionType     = CatArrangementRouteSectionRound
   objArrPathway.SectionDiameter = 10.0
   objArrPathway.VisuMode        = CatArrangementRouteVisuModeSolid

   <font color="#008000">' Define Bend Radius of Nodes</font>
   <font color="#008000">'----------------------------------------------</font> <font color="#008000">
 </font><font color="#0000FF">  Dim </font>intK<font color="#0000FF"> As </font>Integer   
<font color="#0000FF">   For </font>intK = 1<font color="#0000FF"> To </font>objArrPathway.Nodes.Count
   objArrPathway.Nodes.Item(intK).BendRadius = 10.0
<font color="#0000FF">   Next</font>
  ...</pre>
          </td>
        </tr>
      </table>
      <p>Here we define a round section and change the visualization mode to <code>CatArrangementRouteVisuModeSolid</code>.
      A bend radius of 10 mm is then applied to each of the <i>ArrangementNodes</i>
      that makes up the object.</p>
      <h4><a name="Epilog"></a>Epilog</h4>
      <table class="code">
        <tr>
          <td>
            <pre>...
 End Sub</pre>
          </td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<!----------------------------------comment------------------------------------->
<p align="center"><img border="0" src="../CAAScrBase/images/aendtask.gif" width="64" height="32"></p>
<p align="right">[<a href="#Top">Top</a>]</p>
<hr>
<!----------------------------------comment------------------------------------->
<h4><a name="InShort"></a>In Short</h4>
<p>This use case has shown how to create an <i>ArrangementPathway</i> object
within a product document.</p>
<p align="right">[<a href="#Top">Top</a>]</p>
<hr>
<!----------------------------------comment------------------------------------->
<h4><a name="References"></a>References</h4>
<table border="0" width="100%">
  <tr>
    <td valign="top">[1]</td>
    <td><a href="../CAAScdInfUseCases/CAAInfLauchMacro.htm">Replaying
      a Macro</a></td>
  </tr>
  <tr>
    <td valign="top">[2]</td>
    <td><i><a href="#" onclick="javascript:CAAlink('IDL', 'CATArrangementInterfaces', 'ArrangementPathways');return false;">ArrangementPathways</a>,
      <a href="#" onclick="javascript:CAAlink('IDL', 'ProductStructureInterfaces', 'Product');return false;">Product</a>,
      <a href="#" onclick="javascript:CAAlink('IDL', 'CATArrangementInterfaces', 'ArrangementProduct');return false;">ArrangementProduct</a>,
      <a href="#" onclick="javascript:CAAlink('IDL', 'CATArrangementInterfaces', 'ArrangementPathway');return false;">ArrangementPathway</a>,
      <a href="#" onclick="javascript:CAAlink('IDL', 'CATArrangementInterfaces', 'ArrangementNode');return false;">ArrangementNode</a></i></td>
  </tr>
  <tr>
    <td colspan="2" align="right">[<a href="#Top">Top</a>]</td>
</table>
<hr>
<!----------------------------------comment------------------------------------->
<p><i>Copyright © 2000, Dassault Systèmes. All rights reserved.</i></p>

</body>

</html>
