<html><head><meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"><title>CAAArrCreateContourArea.CATScript</title><link rel="stylesheet" type="text/css" href="../CAAScrBase/caav5.css"></head><body><pre>
<font color="#0000FF">Option Explicit</font>
<font color="#008000">'// COPYRIGHT DASSAULT SYSTEMES  2000</font>
<font color="#008000">'******************************************************************************</font>
<font color="#008000">' Purpose:       This CATScript demonstrates how to create an Area with</font>
<font color="#008000">'                a contour.</font>
<font color="#008000">' Assumptions:   This assumes that a macro is being executed interactively.</font>
<font color="#008000">' Author     :               </font>
<font color="#008000">' Languages  :   VBScript</font>
<font color="#008000">' CATIA Level:   V5R6</font>
<font color="#008000">' Locale     :   English</font>
<font color="#008000">'******************************************************************************</font>


<font color="#0000FF">Sub </font>CATMain()
   
   <font color="#008000">' On Error Resume Next</font>

   <font color="#008000">'----------------------------------------------</font>
   <font color="#008000">'Create a new product document</font>
<font color="#0000FF">   Dim </font>objProdDoc       <font color="#0000FF"> As </font>ProductDocument
<font color="#0000FF">   Dim </font>objRootProd      <font color="#0000FF"> As </font>Product
<font color="#0000FF">   Set </font>objProdDoc      = CATIA.Documents.Add("Product")
<font color="#0000FF">   Set </font>objRootProd     = objProdDoc.Product

   <font color="#008000">'----------------------------------------------</font>
   <font color="#008000">'Retrieving Root Product's Relative Axis and Position Information</font>
<font color="#0000FF">   Dim </font>objMove          <font color="#0000FF"> As </font>Move
<font color="#0000FF">   Dim </font>objPosition      <font color="#0000FF"> As </font>Position
<font color="#0000FF">   Set </font>objMove      = objRootProd.Move
<font color="#0000FF">   Set </font>objPosition  = objRootProd.Position

   <font color="#008000">'----------------------------------------------</font>
   <font color="#008000">' Get ArrangementProduct</font>
<font color="#0000FF">   Dim </font>objArrProd       <font color="#0000FF"> As </font>ArrangementProduct
<font color="#0000FF">   Set </font>objArrProd   = objRootProd.GetTechnologicalObject("ArrangementProduct")

   <font color="#008000">'----------------------------------------------</font>
   <font color="#008000">' Create Area without a contour under the Root Product</font>
<font color="#0000FF">   Dim </font>objArea        <font color="#0000FF"> As </font>ArrangementArea
<font color="#0000FF">   Dim </font>dblAreaPos(11) <font color="#0000FF"> As </font>Double

   objPosition.GetComponents dblAreaPos
<font color="#0000FF">   Set </font>objArea     = objArrProd.ArrangementAreas.AddArea(objMove, dblAreaPos, 50.0)

   <font color="#008000">'----------------------------------------------</font>
   <font color="#008000">' Create Rectangle</font>
<font color="#0000FF">   Dim </font>objRectangle     <font color="#0000FF"> As </font>ArrangementRectangle
<font color="#0000FF">   Dim </font>objArrProd1      <font color="#0000FF"> As </font>ArrangementProduct
<font color="#0000FF">   Dim </font>objAreaProd1     <font color="#0000FF"> As </font>Product
<font color="#0000FF">   Dim </font>objMove1         <font color="#0000FF"> As </font>Move
<font color="#0000FF">   Dim </font>objPosition1     <font color="#0000FF"> As </font>Position
<font color="#0000FF">   Dim </font>dblRectPos(11)   <font color="#0000FF"> As </font>Double

<font color="#0000FF">   Set </font>objAreaProd1  = objArea.GetTechnologicalObject("Product")
<font color="#0000FF">   Set </font>objArrProd1   = objArea.GetTechnologicalObject("ArrangementProduct")
<font color="#0000FF">   Set </font>objMove1      = objAreaProd1.Move
<font color="#0000FF">   Set </font>objPosition1  = objAreaProd1.Position

   objPosition1.GetComponents dblRectPos
   dblRectPos(9)  = 100.0
   dblRectPos(10) = 100.0
   dblRectPos(11) = 0.0
<font color="#0000FF">   Set </font>objRectangle = objArrProd1.ArrangementRectangles.AddRectangle (objMove1,dblRectPos, 50.0, 50.0)   

   <font color="#008000">'---------------------------------------------</font>
   <font color="#008000">' Add Rectangular contour to Area                    </font>
   objArea.ArrangementContours.AddRectangularContour(objRectangle)

<font color="#0000FF">End Sub </font>

</pre></body></html>


