<html><head><meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"><title>CAAArrCreateItemReservation.CATScript</title><link rel="stylesheet" type="text/css" href="../CAAScrBase/caav5.css"></head><body><pre>
<font color="#0000FF">Option Explicit</font>
<font color="#008000">'// COPYRIGHT DASSAULT SYSTEMES  2000</font>
<font color="#008000">'******************************************************************************</font>
<font color="#008000">' Purpose:       This CATScript demonstrates how to create an Item Reservation.</font>
<font color="#008000">'                and change it's visualization to "Flat" mode.</font>
<font color="#008000">' Assumptions:   This assumes that a macro is being executed interactively.</font>
<font color="#008000">'                </font>
<font color="#008000">' Author     :                              </font>
<font color="#008000">' Languages  :   VBScript</font>
<font color="#008000">' CATIA Level:   V5R6</font>
<font color="#008000">' Locale     :   English</font>
<font color="#008000">'******************************************************************************</font>


<font color="#0000FF">Sub </font>CATMain()
   
   <font color="#008000">' On Error Resume Next</font>

   <font color="#008000">'----------------------------------------------</font>
   <font color="#008000">'Create a new product document</font>
<font color="#0000FF">   Dim </font>objProdDoc       <font color="#0000FF"> As </font>ProductDocument
<font color="#0000FF">   Dim </font>objRootProd      <font color="#0000FF"> As </font>Product
<font color="#0000FF">   Set </font>objProdDoc      = CATIA.Documents.Add("Product")
<font color="#0000FF">   Set </font>objRootProd     = objProdDoc.Product

   <font color="#008000">'----------------------------------------------</font>
   <font color="#008000">'Retrieving Root Product's Relative Axis and Position Information</font>
<font color="#0000FF">   Dim </font>objMove          <font color="#0000FF"> As </font>Move
<font color="#0000FF">   Dim </font>objPosition      <font color="#0000FF"> As </font>Position
<font color="#0000FF">   Set </font>objMove      = objRootProd.Move
<font color="#0000FF">   Set </font>objPosition  = objRootProd.Position


   <font color="#008000">'----------------------------------------------</font>
   <font color="#008000">' Get ArrangementProduct</font>
<font color="#0000FF">   Dim </font>objArrProd       <font color="#0000FF"> As </font>ArrangementProduct
<font color="#0000FF">   Set </font>objArrProd   = objRootProd.GetTechnologicalObject("ArrangementProduct")


   <font color="#008000">'----------------------------------------------</font>
   <font color="#008000">' Create Item Reservation under the Root Product</font>
<font color="#0000FF">   Dim </font>dblItemResPos(11) <font color="#0000FF"> As </font>Double
<font color="#0000FF">   Dim </font>objItemRes    <font color="#0000FF"> As </font>ArrangementItemReservation

   objPosition.GetComponents dblItemResPos
<font color="#0000FF">   Set </font>objItemRes      = objArrProd.ArrangementItemReservations.AddItemReservation(objMove, dblItemResPos, 200.0, 500.0, 200.0, 500.0, 0.0, 0.0)

   <font color="#008000">'----------------------------------------------</font>
   <font color="#008000">' Change Properties of ArrangementItemReservation</font>
   objItemRes.VisuMode = CatArrangementItemReservationVisuModeFlat

<font color="#0000FF">End Sub </font>

</pre></body></html>


