<html><head><meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"><title>CAAArrCreatePathway.CATScript</title><link rel="stylesheet" type="text/css" href="../CAAScrBase/caav5.css"></head><body><pre>
<font color="#0000FF">Option Explicit</font>
<font color="#008000">'// COPYRIGHT DASSAULT SYSTEMES  2000</font>
<font color="#008000">'******************************************************************************</font>
<font color="#008000">' Purpose:       This CATScript demonstrates how to create an ArrangementPathway</font>
<font color="#008000">'                and change it's visualization to "Solid" mode, define a</font>
<font color="#008000">'                round section data and apply a constant bend radius of 10 mm.</font>
<font color="#008000">' Assumptions:   This assumes that a macro is being executed interactively.</font>
<font color="#008000">' Author     :                              </font>
<font color="#008000">' Languages  :   VBScript</font>
<font color="#008000">' CATIA Level:   V5R6</font>
<font color="#008000">' Locale     :   English</font>
<font color="#008000">'******************************************************************************</font>


<font color="#0000FF">Sub </font>CATMain()
   
   <font color="#008000">' On Error Resume Next</font>

   <font color="#008000">'----------------------------------------------</font>
   <font color="#008000">'Create a new product document</font>
<font color="#0000FF">   Dim </font>objProdDoc       <font color="#0000FF"> As </font>ProductDocument
<font color="#0000FF">   Dim </font>objRootProd      <font color="#0000FF"> As </font>Product
<font color="#0000FF">   Set </font>objProdDoc      = CATIA.Documents.Add("Product")
<font color="#0000FF">   Set </font>objRootProd     = objProdDoc.Product

   <font color="#008000">'----------------------------------------------</font>
   <font color="#008000">'Retrieving Root Product's Relative Axis and Position Information</font>
<font color="#0000FF">   Dim </font>objMove          <font color="#0000FF"> As </font>Move
<font color="#0000FF">   Set </font>objMove      = objRootProd.Move

   <font color="#008000">'----------------------------------------------</font>
   <font color="#008000">' Get ArrangementProduct</font>
<font color="#0000FF">   Dim </font>objArrProd       <font color="#0000FF"> As </font>ArrangementProduct
<font color="#0000FF">   Set </font>objArrProd   = objRootProd.GetTechnologicalObject("ArrangementProduct")


   <font color="#008000">'----------------------------------------------</font>
   <font color="#008000">' Create ArrangementPathway under the Root Product</font>
<font color="#0000FF">   Dim </font>dblPathwayPoints(75)     <font color="#0000FF"> As </font>Double
<font color="#0000FF">   Dim </font>dblMathDirection(3)      <font color="#0000FF"> As </font>Double
<font color="#0000FF">   Dim </font>objArrPathway            <font color="#0000FF"> As </font>ArrangementPathway

   dblPathwayPoints(0)   =  300.0
   dblPathwayPoints(1)   =  100.0
   dblPathwayPoints(2)   =  0.0

   dblPathwayPoints(3)   =  441.42
   dblPathwayPoints(4)   =  158.58
   dblPathwayPoints(5)   =  1.25

   dblPathwayPoints(6)   =  500.0
   dblPathwayPoints(7)   =  300.0
   dblPathwayPoints(8)   =  2.5

   dblPathwayPoints(9)   =  441.42
   dblPathwayPoints(10)  =  441.42
   dblPathwayPoints(11)  =  3.75

   dblPathwayPoints(12)   =  300.0
   dblPathwayPoints(13)  =  500.0
   dblPathwayPoints(14)  =  5.0

   dblPathwayPoints(15)  =   158.58
   dblPathwayPoints(16)  =  441.42
   dblPathwayPoints(17)  =  6.25

   dblPathwayPoints(18)  =  100.0
   dblPathwayPoints(19)  =  300.0
   dblPathwayPoints(20)  =  7.5 

   dblPathwayPoints(21)  =  158.58
   dblPathwayPoints(22)  =  158.58
   dblPathwayPoints(23)  =  8.75

   dblPathwayPoints(24)  =  300.0
   dblPathwayPoints(25)  =  100.0
   dblPathwayPoints(26)  =  10

   dblPathwayPoints(27)   =  441.42
   dblPathwayPoints(28)   =  158.58
   dblPathwayPoints(29)   =  11.25

   dblPathwayPoints(30)   =  500.0
   dblPathwayPoints(31)   =  300.0
   dblPathwayPoints(32)   =  12.5

   dblPathwayPoints(33)   =  441.42
   dblPathwayPoints(34)  =  441.42
   dblPathwayPoints(35)  =  13.75

   dblPathwayPoints(36)   =  300.0
   dblPathwayPoints(37)  =  500.0
   dblPathwayPoints(38)  =  15.0

   dblPathwayPoints(39)  =   158.58
   dblPathwayPoints(40)  =  441.42
   dblPathwayPoints(41)  =  16.25

   dblPathwayPoints(42)  =  100.0
   dblPathwayPoints(43)  =  300.0
   dblPathwayPoints(44)  =  17.5  

   dblPathwayPoints(45)  =  158.58
   dblPathwayPoints(46)  =  158.58
   dblPathwayPoints(47)  =  18.75

   dblPathwayPoints(48)  =  300.0
   dblPathwayPoints(49)  =  100.0
   dblPathwayPoints(50)  =  20

   dblPathwayPoints(51)   =  441.42
   dblPathwayPoints(52)   =  158.58
   dblPathwayPoints(53)   =  21.25

   dblPathwayPoints(54)   =  500.0
   dblPathwayPoints(55)   =  300.0
   dblPathwayPoints(56)   =  22.5

   dblPathwayPoints(57)   =  441.42
   dblPathwayPoints(58)  =  441.42
   dblPathwayPoints(59)  =  23.75

   dblPathwayPoints(60)   =  300.0
   dblPathwayPoints(61)  =  500.0
   dblPathwayPoints(62)  =  25.0

   dblPathwayPoints(63)  =   158.58
   dblPathwayPoints(64)  =  441.42
   dblPathwayPoints(65)  =  26.25

   dblPathwayPoints(66)  =  100.0
   dblPathwayPoints(67)  =  300.0
   dblPathwayPoints(68)  =  27.5 

   dblPathwayPoints(69)  =  158.58
   dblPathwayPoints(70)  =  158.58
   dblPathwayPoints(71)  =  28.75

   dblPathwayPoints(72)  =  300.0
   dblPathwayPoints(73)  =  100.0
   dblPathwayPoints(74)  =  30

   dblMathDirection(0) = 1.0
   dblMathDirection(1) = 0.0
   dblMathDirection(2) = 0.0

<font color="#0000FF">   Set </font>objArrPathway             = objArrProd.ArrangementPathways.AddPathway(objMove,dblPathwayPoints, dblMathDirection)

   <font color="#008000">'----------------------------------------------</font>
   <font color="#008000">' Change Properties of ArrangementPathway</font>
   objArrPathway.SectionType     = CatArrangementRouteSectionRound
   objArrPathway.SectionDiameter = 10.0
   objArrPathway.VisuMode        = CatArrangementRouteVisuModeSolid

   <font color="#008000">'----------------------------------------------</font>
   <font color="#008000">' Define Bend Radius of Nodes</font>
<font color="#0000FF">   Dim </font>intK<font color="#0000FF"> As </font>Integer   
<font color="#0000FF">   For </font>intK = 1<font color="#0000FF"> To </font>objArrPathway.ArrangementNodes.Count
     objArrPathway.ArrangementNodes.Item(intK).BendRadius = 10.0
<font color="#0000FF">   Next</font>

<font color="#0000FF">End Sub </font>

</pre></body></html>


