<html>

<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<meta name="GENERATOR" content="Microsoft FrontPage 4.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
<title>Creating an ArrangementArea Object with a Rectangular Contour</title>
<link rel="stylesheet" type="text/css" href="../CAAScrBase/caav5.css">
<script language="JavaScript" src="../CAAScrJavaScript/submit.js"></script>
</head>

<body>

<table border="0" width="100%">
  <tr>
    <td>
      <h2>Arrangement</h2>
    </td>
    <td align="right" valign="top">
      <h2><a name="Top"></a>Creating an ArrangementArea Object with a
      Rectangular Contour</h2>
    </td>
  </tr>
</table>
<hr>
<!----------------------------------comment------------------------------------->
<table border="0" width="100%">
  <tr>
    <td width="7%" valign="top"><img border="0" src="../CAAScrBase/images/atarget.gif" width="32" height="32"></td>
    <td width="93%">
      <p><a name="Learn"></a>This macro shows you how to create an <a href="#" onclick="javascript:CAAlink('IDL', 'CATArrangementInterfaces', 'ArrangementArea');return false;"><i>ArrangementArea</i></a>
      object with a rectangular contour in a product document.</p>
      <p>This macro opens a new product document and retrieves the <a href="#" onclick="javascript:CAAlink('IDL', 'CATArrangementInterfaces', 'ArrangementItemAreas');return false;"><i>ArrangementItemAreas</i></a>
      collection from the root <a href="#" onclick="javascript:CAAlink('IDL', 'ProductStructureInterfaces', 'Product');return false;"><i>Product</i></a>
      via the <a href="#" onclick="javascript:CAAlink('IDL', 'CATArrangementInterfaces', 'ArrangementProduct');return false;"><i>ArrangementProduct</i></a>
      object. It then adds an <a href="#" onclick="javascript:CAAlink('IDL', 'CATArrangementInterfaces', 'ArrangementArea');return false;"><i>ArrangementArea</i></a>
      object. The Arrangement object so created does not have a contour. To add
      a contour, the <a href="#" onclick="javascript:CAAlink('IDL', 'CATArrangementInterfaces', 'ArrangementRectangles');return false;"><i>ArrangementRectangles</i></a>
      collection oject is then retrieved from the newly created <i>ArrangementArea</i>
      and a new <a href="#" onclick="javascript:CAAlink('IDL', 'CATArrangementInterfaces', 'ArrangementRectangle');return false;"><i>ArrangementRectangle</i></a>
      object is created and then added to the <i>ArrangementArea</i> as a
      rectangular contour.</p>
      <p align="center"><img border="2" src="images/CAAArrCreateContourArea.jpg" width="426" height="414"></p>
      <p>&nbsp;</p>
    </td>
  </tr>
  <tr>
    <td width="7%" valign="top"><img border="0" src="../CAAScrBase/images/ainfo.gif" width="32" height="32"></td>
    <td width="93%">
      <p><a name="How"></a>CAAArrCreateContourArea is launched in CATIA [<a href="#References">1</a>].
      No open document is needed.</p>
      <p><a href="CAAArrCreateContourAreaSource.htm">CAAArrCreateContourArea.CATScript</a>
      is located in the CAAScdArrUseCases module. <a href="macros/CAAArrCreateContourArea.CATScript">Execute
      macro</a> (Windows only).</p>
      <p align="center">&nbsp;</p>
    </td>
  </tr>
  <tr>
    <td width="7%" valign="top"><img border="0" src="../CAAScrBase/images/ascenari.gif" width="32" height="32"></td>
    <td width="93%">
      <p><a name="Step"></a>CAAArrCreateItemReservation includes the following
      steps:</p>
      <ol>
        <li><a href="#prolog">Prolog</a></li>
        <li><a href="#Reference">Obtaining the ArrangementProduct Object and the
          Associated Movable Object from the Root Product</a></li>
        <li><a href="#Create">Creating the ArrangementArea Object under the
          ArrangementAreas Collection Object</a></li>
        <li><a href="#CreateRectangle">Creating the ArrangementRectangle Object</a></li>
        <li><a href="#AddRectangle">Adding a Rectangular Contour to the
          ArrangementArea Object</a></li>
        <li><a href="#Epilog">Epilog</a></li>
      </ol>
      <h4><a name="prolog"></a>Prolog</h4>
      <table class="code">
        <tr>
          <td>
            <pre>  ...
   <font color="#008000">'----------------------------------------------</font>
   <font color="#008000">'Create a new product document</font>
<font color="#0000FF">   Dim </font>objProdDoc       <font color="#0000FF"> As </font>ProductDocument
<font color="#0000FF">   Dim </font>objRootProd      <font color="#0000FF"> As </font>Product
<font color="#0000FF">   Set </font>objProdDoc      = CATIA.Documents.Add(&quot;Product&quot;)
<font color="#0000FF">   Set </font>objRootProd     = objProdDoc.Product
   ...</pre>
          </td>
        </tr>
      </table>
      <p>Once the new product document has been created, fetch the <i>ArrangementProduct</i>
      and the associated movable object from the root product of the new product
      document.</p>
      <h4><a name="Reference"></a>Obtaining the ArrangementProduct Object and
      the Associated Movable Object from the Root Product</h4>
      <table class="code">
        <tr>
          <td>
            <pre>...
   <font color="#008000">'----------------------------------------------</font>
   <font color="#008000">'Retrieving Root Product's Relative Axis and Position Information</font>
<font color="#0000FF">   Dim </font>objMove          <font color="#0000FF"> As </font>Move
<font color="#0000FF">   Dim </font>objPosition      <font color="#0000FF"> As </font>Position
<font color="#0000FF">   Set </font>objMove      = objRootProd.Move
<font color="#0000FF">   Set </font>objPosition  = objRootProd.Position

   <font color="#008000">'----------------------------------------------</font>
   <font color="#008000">' Get ArrangementProduct</font>
<font color="#0000FF">   Dim </font>objArrProd       <font color="#0000FF"> As </font>ArrangementProduct
<font color="#0000FF">   Set </font>objArrProd   = objRootProd.GetTechnologicalObject(&quot;ArrangementProduct&quot;)
...</pre>
          </td>
        </tr>
      </table>
      <p>The <i>ArrangementAreas</i> object is a collection object that manages <i>ArrangementArea</i>
      object's under a given <i>ArrangementProduct</i>. The movable object
      serves as the relative axis for the new <i>ArrangementArea</i> object to
      be created.</p>
      <h4><a name="Create"></a>Creating the ArrangementArea Object under the
      ArrangementAreas Collection Object</h4>
      <table class="code">
        <tr>
          <td>
            <pre>...
   <font color="#008000">'----------------------------------------------</font>
   <font color="#008000">' Create Area without a contour under the Root Product</font>
<font color="#0000FF">   Dim </font>objArea    <font color="#0000FF"> As </font>ArrangementArea
   <font color="#0000FF">Dim </font>dblAreaPos(11) <font color="#0000FF"> As </font>Double

   objPosition.GetComponents dblAreaPos
<font color="#0000FF">   Set </font>objArea     = objArrProd.ArrangementAreas.AddArea(objMove, dblAreaPos, 50.0)
...</pre>
          </td>
        </tr>
      </table>
      <p>The newly created <i>ArrangementArea</i> object is displayed without a
      contour at this point.</p>
      <h4><a name="CreateRectangle"></a>Creating the ArrangementRectangle Object</h4>
      <table class="code">
        <tr>
          <td>
            <pre>...
   <font color="#008000">'----------------------------------------------</font>
   <font color="#008000">' Create Rectangle</font>
<font color="#0000FF">   Dim </font>objRectangle     <font color="#0000FF"> As </font>ArrangementRectangle
   <font color="#0000FF">Dim </font>objArrProd1      <font color="#0000FF"> As </font>ArrangementProduct
<font color="#0000FF">   Dim </font>objAreaProd1     <font color="#0000FF"> As </font>Product
<font color="#0000FF">   Dim </font>objMove1         <font color="#0000FF"> As </font>Move
<font color="#0000FF">   Dim </font>objPosition1     <font color="#0000FF"> As </font>Position
 <font color="#0000FF">  Dim </font>dblRectPos(11)   <font color="#0000FF"> As </font>Double

<font color="#0000FF">   Set </font>objAreaProd1  = objArea.GetTechnologicalObject(&quot;Product&quot;)
   <font color="#0000FF">Set </font>objArrProd1   = objArea.GetTechnologicalObject(&quot;ArrangementProduct&quot;)
<font color="#0000FF">   Set </font>objMove1      = objAreaProd1.Move
<font color="#0000FF">   Set </font>objPosition1  = objAreaProd1.Position
<font color="#0000FF"> </font>
   objPosition1.GetComponents dblRectPos
   dblRectPos(9)  = 100.0
   dblRectPos(10) = 100.0
   dblRectPos(11) = 0.0
<font color="#0000FF">   Set </font>objRectangle = objArrProd1.ArrangementRectangles.AddRectangle (objMove1,dblRectPos, 50.0, 50.0)
...</pre>
          </td>
        </tr>
      </table>
      <p>Note that the <i>ArrangementRectangle</i> object is created using the <i>ArrangementArea</i>
      as the movable object.</p>
      <h4><a name="AddRectangle"></a>Adding a Rectangular Contour to the
      ArrangementArea Object</h4>
      <table class="code">
        <tr>
          <td>
            <pre>...
   <font color="#008000">'---------------------------------------------</font>
   <font color="#008000">' Add Rectangular contour to Area                    </font>
   objArea.ArrangementContours.AddRectangularContour(objRectangle)
...</pre>
          </td>
        </tr>
      </table>
      <p>The <i>ArrangementArea</i> object is now displayed with its boundary as
      shown in the image above.</p>
      <h4><a name="Epilog"></a>Epilog</h4>
      <table class="code">
        <tr>
          <td>
            <pre>...
 End Sub</pre>
          </td>
        </tr>
      </table>
    </td>
  </tr>
</table>
<!----------------------------------comment------------------------------------->
<p align="center"><img border="0" src="../CAAScrBase/images/aendtask.gif" width="64" height="32"></p>
<p align="right">[<a href="#Top">Top</a>]</p>
<hr>
<!----------------------------------comment------------------------------------->
<h4><a name="InShort"></a>In Short</h4>
<p>This use case has shown how to create an <i>ArrangementArea</i> object with a
rectangular contour within a product document.</p>
<p align="right">[<a href="#Top">Top</a>]</p>
<hr>
<!----------------------------------comment------------------------------------->
<h4><a name="References"></a>References</h4>
<table border="0" width="100%">
  <tr>
    <td valign="top">[1]</td>
    <td><a href="../CAAScdInfUseCases/CAAInfLauchMacro.htm">Replaying
      a Macro</a></td>
  </tr>
  <tr>
    <td valign="top">[2]</td>
    <td><i><a href="#" onclick="javascript:CAAlink('IDL', 'CATArrangementInterfaces', 'ArrangementItemAreas');return false;">ArrangementItemAreas</a>,
      <a href="#" onclick="javascript:CAAlink('IDL', 'ProductStructureInterfaces', 'Product');return false;">Product</a>,
      <a href="#" onclick="javascript:CAAlink('IDL', 'CATArrangementInterfaces', 'ArrangementProduct');return false;">ArrangementProduct</a>,
      <a href="#" onclick="javascript:CAAlink('IDL', 'CATArrangementInterfaces', 'ArrangementArea');return false;">ArrangementArea</a>,
      <a href="#" onclick="javascript:CAAlink('IDL', 'CATArrangementInterfaces', 'ArrangementRectangles');return false;">ArrangementRectangles</a>,
      <a href="#" onclick="javascript:CAAlink('IDL', 'CATArrangementInterfaces', 'ArrangementRectangle');return false;">ArrangementRectangle</a></i></td>
  </tr>
  <tr>
    <td colspan="2" align="right">[<a href="#Top">Top</a>]</td>
</table>
<hr>
<!----------------------------------comment------------------------------------->
<p><i>Copyright © 2000, Dassault Systèmes. All rights reserved.</i></p>

</body>

</html>
