<html><head><meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"><title>CAAArrCreateBoundary.CATScript</title><link rel="stylesheet" type="text/css" href="../CAAScrBase/caav5.css"></head><body><pre>
<font color="#0000FF">Option Explicit</font>
<font color="#008000">'// COPYRIGHT DASSAULT SYSTEMES  2000</font>
<font color="#008000">'******************************************************************************</font>
<font color="#008000">' Purpose:       This CATScript demonstrates how to create an ArrangementBoundary</font>
<font color="#008000">'                and change it's visualization to "Solid" mode, define a</font>
<font color="#008000">'                Rectangular section data and apply a constant bend radius of 25 mm.</font>
<font color="#008000">' Assumptions:   This assumes that a macro is being executed interactively.</font>
<font color="#008000">' Author     :                               </font>
<font color="#008000">' Languages  :   VBScript</font>
<font color="#008000">' CATIA Level:   V5R6</font>
<font color="#008000">' Locale     :   English</font>
<font color="#008000">'******************************************************************************</font>


<font color="#0000FF">Sub </font>CATMain()
   
   <font color="#008000">' On Error Resume Next</font>

   <font color="#008000">'----------------------------------------------</font>
   <font color="#008000">'Create a new product document</font>
<font color="#0000FF">   Dim </font>objProdDoc       <font color="#0000FF"> As </font>ProductDocument
<font color="#0000FF">   Dim </font>objRootProd      <font color="#0000FF"> As </font>Product
<font color="#0000FF">   Set </font>objProdDoc      = CATIA.Documents.Add("Product")
<font color="#0000FF">   Set </font>objRootProd     = objProdDoc.Product

   <font color="#008000">'----------------------------------------------</font>
   <font color="#008000">'Retrieving Root Product's Relative Axis and Position Information</font>
<font color="#0000FF">   Dim </font>objMove          <font color="#0000FF"> As </font>Move
<font color="#0000FF">   Set </font>objMove      = objRootProd.Move

   <font color="#008000">'----------------------------------------------</font>
   <font color="#008000">' Get ArrangementProduct</font>
<font color="#0000FF">   Dim </font>objArrProd       <font color="#0000FF"> As </font>ArrangementProduct
<font color="#0000FF">   Set </font>objArrProd   = objRootProd.GetTechnologicalObject("ArrangementProduct")

   <font color="#008000">'----------------------------------------------</font>
   <font color="#008000">' Create ArrangementBoundary under the Root Product</font>
<font color="#0000FF">   Dim </font>dblBoundaryPoints(75)     <font color="#0000FF"> As </font>Double
<font color="#0000FF">   Dim </font>dblMathDirection(3)       <font color="#0000FF"> As </font>Double
<font color="#0000FF">   Dim </font>objArrBoundary            <font color="#0000FF"> As </font>ArrangementBoundary


   dblBoundaryPoints(0)   =  300.0
   dblBoundaryPoints(1)   =  100.0
   dblBoundaryPoints(2)   =  0.0

   dblBoundaryPoints(3)   =  441.42
   dblBoundaryPoints(4)   =  158.58
   dblBoundaryPoints(5)   =  1.25

   dblBoundaryPoints(6)   =  500.0
   dblBoundaryPoints(7)   =  300.0
   dblBoundaryPoints(8)   =  2.5

   dblBoundaryPoints(9)   =  441.42
   dblBoundaryPoints(10)  =  441.42
   dblBoundaryPoints(11)  =  3.75

   dblBoundaryPoints(12)   =  300.0
   dblBoundaryPoints(13)  =  500.0
   dblBoundaryPoints(14)  =  5.0

   dblBoundaryPoints(15)  =   158.58
   dblBoundaryPoints(16)  =  441.42
   dblBoundaryPoints(17)  =  6.25

   dblBoundaryPoints(18)  =  100.0
   dblBoundaryPoints(19)  =  300.0
   dblBoundaryPoints(20)  =  7.5 

   dblBoundaryPoints(21)  =  158.58
   dblBoundaryPoints(22)  =  158.58
   dblBoundaryPoints(23)  =  8.75

   dblBoundaryPoints(24)  =  300.0
   dblBoundaryPoints(25)  =  100.0
   dblBoundaryPoints(26)  =  10

   dblBoundaryPoints(27)   =  441.42
   dblBoundaryPoints(28)   =  158.58
   dblBoundaryPoints(29)   =  11.25

   dblBoundaryPoints(30)   =  500.0
   dblBoundaryPoints(31)   =  300.0
   dblBoundaryPoints(32)   =  12.5

   dblBoundaryPoints(33)   =  441.42
   dblBoundaryPoints(34)  =  441.42
   dblBoundaryPoints(35)  =  13.75

   dblBoundaryPoints(36)   =  300.0
   dblBoundaryPoints(37)  =  500.0
   dblBoundaryPoints(38)  =  15.0

   dblBoundaryPoints(39)  =   158.58
   dblBoundaryPoints(40)  =  441.42
   dblBoundaryPoints(41)  =  16.25

   dblBoundaryPoints(42)  =  100.0
   dblBoundaryPoints(43)  =  300.0
   dblBoundaryPoints(44)  =  17.5  

   dblBoundaryPoints(45)  =  158.58
   dblBoundaryPoints(46)  =  158.58
   dblBoundaryPoints(47)  =  18.75

   dblBoundaryPoints(48)  =  300.0
   dblBoundaryPoints(49)  =  100.0
   dblBoundaryPoints(50)  =  20

   dblBoundaryPoints(51)   =  441.42
   dblBoundaryPoints(52)   =  158.58
   dblBoundaryPoints(53)   =  21.25

   dblBoundaryPoints(54)   =  500.0
   dblBoundaryPoints(55)   =  300.0
   dblBoundaryPoints(56)   =  22.5

   dblBoundaryPoints(57)   =  441.42
   dblBoundaryPoints(58)  =  441.42
   dblBoundaryPoints(59)  =  23.75

   dblBoundaryPoints(60)   =  300.0
   dblBoundaryPoints(61)  =  500.0
   dblBoundaryPoints(62)  =  25.0

   dblBoundaryPoints(63)  =   158.58
   dblBoundaryPoints(64)  =  441.42
   dblBoundaryPoints(65)  =  26.25

   dblBoundaryPoints(66)  =  100.0
   dblBoundaryPoints(67)  =  300.0
   dblBoundaryPoints(68)  =  27.5 

   dblBoundaryPoints(69)  =  158.58
   dblBoundaryPoints(70)  =  158.58
   dblBoundaryPoints(71)  =  28.75

   dblBoundaryPoints(72)  =  300.0
   dblBoundaryPoints(73)  =  100.0
   dblBoundaryPoints(74)  =  30


   dblMathDirection(0) = 1.0
   dblMathDirection(1) = 0.0
   dblMathDirection(2) = 0.0

<font color="#0000FF">   Set </font>objArrBoundary             = objArrProd.ArrangementBoundaries.AddBoundary(objMove,dblBoundaryPoints, dblMathDirection)

   <font color="#008000">'----------------------------------------------</font>
   <font color="#008000">' Change Properties of ArrangementBoundary</font>
   objArrBoundary.SectionType     = CatArrangementRouteSectionRectangular
   objArrBoundary.SectionWidth    = 10.0
   objArrBoundary.SectionHeight   = 10.0 
   objArrBoundary.VisuMode        = CatArrangementRouteVisuModeSolid

   <font color="#008000">'----------------------------------------------</font>
   <font color="#008000">' Define Bend Radius of Nodes</font>
<font color="#0000FF">   Dim </font>intK <font color="#0000FF"> As </font>Integer
<font color="#0000FF">   For </font>intK = 1<font color="#0000FF"> To </font>objArrBoundary.ArrangementNodes.Count  
     objArrBoundary.ArrangementNodes.Item(intK).BendRadius = 10.0
<font color="#0000FF">   Next</font>

<font color="#0000FF">End Sub </font>

</pre></body></html>


