<html>

<head>
<meta http-equiv="Content-Language" content="en_us">
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<meta name="GENERATOR" content="Microsoft FrontPage 12.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
<title>Creating Copings</title>
<link rel="stylesheet" type="text/css" href="../CAAScrBase/caav5.css">
<script type="text/javascript" src="../CAAScrJavaScript/submit.js"></script>
</head>

<body>

<table border="0" width="100%">
	<tr>
		<td>
		<h2>Structure Design</h2>
		</td>
		<td align="right" valign="top">
		<h2><a name="Top"></a>Creating Copings</h2>
		</td>
	</tr>
</table>
<hr>
<!-- -------------------------------comment--------------------------------- -->
<table border="0" width="100%">
	<tr>
		<td width="7%" valign="top">
		<img alt="Target Icon" src="../CAAScrBase/images/atarget.gif" width="32" height="32"></td>
		<td width="93%">
		<p><a name="Learn"></a>This macro shows you how to apply coping between structure objects. Here we will see three    
            Cases.</p>
            <ol>
            <li>Creating Coping on Plate, when it is limited by another plate and surface.</li>
            <li>Creating Coping on Stiffener, when it is limited by stiffeners and Plate.</li>
            <li>Creating Coping on Stiffener, when it is limited by lateral face of a Plate.</li>
            </ol>
		<p>
		<img alt="Starting Product" src="images/CAAScdStrCoping01.png" width="559" height="235">
		</p>
		<!-- -------------------------------comment--------------------------------- -->
		</td>
	</tr>
	<tr>
		<td width="7%" valign="top">
		<img alt="Information Icon" src="../CAAScrBase/images/ainfo.gif" width="32" height="32"></td>
		<td width="93%">
		<p><a name="How"></a>CAAStrCreateCoping is launched in CATIA [<a href="#References">1</a>]. 
		Some documents are needed.</p>
		<ul>
			<li><a href="CAAStrCreationOfCopingSource.htm" target="Source">CAAStrCreateCoping.CATScript</a> 
			is located in the CAAScdStrUseCases module.
			<a href="macros/CAAStrCreateCoping.CATScript">Execute macro</a> (Windows 
			only).</li>
			<li>The document Product1.CATProduct is located in the CAAScdStrUseCases module in the samples directory. Part1.CATPart is linked to the previous document and it contains the grid used by the macro.</li>
			<li>The CATPart containing the section is located in the samples directory.</li>
		</ul>
		</td>
	</tr>
	<tr>
		<td width="7%" valign="top">
		<img alt="Scenario Icon" src="../CAAScrBase/images/ascenari.gif" width="32" height="32"></td>
		<td width="93%">
		<p><a name="Step"></a>CAAStrCreateCoping includes five steps:</p>
		<ol>
			<li><a href="#Prolog">Prolog</a></li>
			<li><a href="#Step1">Retrieving the Factory from Object on which Coping Is to Be Done</a></li>
			<li><a href="#Step2">Defining the Limits</a></li>
			<li><a href="#Step3">Creating Coping</a></li>
			<li><a href="#Step4">Creating Coping for Case2 and Case3</a></li>
		</ol>
		<!-- -------------------------------comment--------------------------------- -->
		<h4><a name="Prolog"></a>Prolog</h4>
		<pre class="code">Sub CATMain()
Dim StrWorkbench As StrWorkbench
Dim strFactory As StrObjectFactory

Set doc = CATIA.ActiveDocument
Dim rootProduct As Product
Set rootProduct = doc.Product
   
Set StrWorkbench = doc.GetWorkbench("StrWorkbench")
    
Dim strPlates As strPlates
Set strPlates = rootProduct.GetTechnologicalObject("StructurePlates")
   
Dim strMembers As strMembers
Set strMembers = rootProduct.GetTechnologicalObject("StructureMembers")</pre>
		<!-- -------------------------------comment--------------------------------- -->
		<h4><a name="Step1"></a>Retrieving the Factory from Object on which Coping Is to Be Done</h4>
		<p>This step describes how to get Structure Feature Factory. The Factory object is retrieved by adding object to nibble to the selection list.</p>
		<pre class="code">'Get The Factory from Selection Method
Dim PlateToNibble As StrPlate
Set PlateToNibble = strPlates.Item("Deck_014.2")

Dim PlateSelection As Selection
Set PlateSelection = CATIA.ActiveDocument.Selection
PlateSelection.Add PlateToNibble
  
Dim FactoryForPlate As StrFeatureFactory
Set FactoryForPlate = PlateSelection.FindObject("CATIAStrFeatureFactory")</pre>
		<!-- -------------------------------comment--------------------------------- -->
		<h4><a name="Step2"></a>Defining the Limits</h4>
<p>The limits are defined by adding them to list of variant which can contain only one element at a time.</p>
		<pre class="code">'Define the Limits for PlateToNibble
Dim Limitplate1 As StrPlate
Set Limitplate1 = strPlates.Item("Shell_002.1")

Dim LimitSurface1 As Reference
Set LimitSurface1 = rootProduct.CreateReferenceFromName("Product1/Part1.1/!Extrude.1")

Dim Listoflimits1(0) As Variant
Dim Listoflimits2(0) As Variant

Set Listoflimits1(0) = Limitplate1
Set Listoflimits2(0) = LimitSurface1</pre>
		<!-- -------------------------------comment--------------------------------- -->
		<h4><a name="Step3"></a>Creating Coping</h4>
<p>Create Coping by passing list of limits containing one element and Type. Coping SubType can also be defined later.</p>
		<pre class="code">'Create Nibbling by defining Type and SubType
Dim NibblingFeature1, NibblingFeature2 As StrNibblingFeature

Set NibblingFeature1 = FactoryForPlate.AddNibbling(Listoflimits1, "Remove")
NibblingFeature1.SubType = "ButtButt"

Set NibblingFeature2 = FactoryForPlate.AddNibbling(Listoflimits2, "Remove")
NibblingFeature2.SubType = "CurrCurr"</pre>
		<!-- -------------------------------comment--------------------------------- -->
		<h4><a name="Step4"></a>Creating Coping for Case2 and Case3</h4>
<p>In Case2: we will apply coping on Member when it is  limited by 2 Members and One Plate.</p>
		<pre class="code">'Case2: When Member is limited by 2 Members and One Plate

'Get the Factory from Selection Method
Dim MembertoNibble1 As StrMember
Set MembertoNibble1 = strMembers.Item("BottShell_LStf_003.1")

Dim MemberSelection As Selection
Set MemberSelection = CATIA.ActiveDocument.Selection
MemberSelection.Add MembertoNibble1

Dim FactoryForMember As StrFeatureFactory
Set FactoryForMember = MemberSelection.FindObject("CATIAStrFeatureFactory")

'Define the Limits for MembertoNibble1
Dim L1 As StrMember
Set L1 = strMembers.Item("Shell_VStf_006.1")

Dim L2 As StrMember
Set L2 = strMembers.Item("Shell_VStf_005.1")

Dim L3 As StrPlate
Set L3 = strPlates.Item("Shell_002.1")

Dim Listoflimits3(0) As Variant
Dim Listoflimits4(0) As Variant
Dim Listoflimits5(0) As Variant

Set Listoflimits5(0) = L3
Set Listoflimits3(0) = L1
Set Listoflimits4(0) = L2

'Create Nibbling by defining Type and SubType
Dim NibblingFeature3, NibblingFeature4, NibblingFeature5 As StrNibblingFeature

Set NibblingFeature3 = FactoryForMember.AddNibbling(Listoflimits3, "WeldCut")
Set NibblingFeature4 = FactoryForMember.AddNibbling(Listoflimits4, "LongPoint")
NibblingFeature4.Type = "ShortPoint"
Set NibblingFeature5 = FactoryForMember.AddNibbling(Listoflimits5, "Remove")</pre>
<p>In case3 we will define the extrapolation offset for the lateral face of stiffener.</p>
<pre class="code">'Case3: When Member is limited by Lateral Face of Plate

'Get the Factory from Selection Method
Dim MembertoNibble2 As StrMember
Set MembertoNibble2 = strMembers.Item("Deck_TStf_005.1")

Dim Member2Sel As Selection
Set Member2Sel = CATIA.ActiveDocument.Selection
Member2Sel.Add MembertoNibble2

Dim FactoryForMember2 As StrFeatureFactory
Set FactoryForMember2 = Member2Sel.FindObject ("CATIAStrFeatureFactory")

'Define the Limits for MembertoNibble2
Dim L4 As StrPlate
Set L4 = strPlates.Item("Deck_014.2")

Dim ListofLimits6(0) As Variant
Set ListofLimits6(0) = L4

'Create Nibbling by defining the Extrapolation Offset
Dim NibblingFeature6 As StrNibblingFeature
Set NibblingFeature6 = FactoryForMember2.AddNibbling(ListofLimits6, "Remove")
NibblingFeature6.GetOffsetForExtrapolate ("25mm")	</pre>
		<!-- -------------------------------comment--------------------------------- -->
		</td>
	</tr>
</table>
<!-- -------------------------------comment--------------------------------- -->
<p align="center">
<img alt="End Task Icon" src="../CAAScrBase/images/aendtask.gif" width="64" height="32"></p>
<p align="right">[<a href="#Top">Top</a>]</p>
<hr>
<!-- -------------------------------comment--------------------------------- -->
<h4><a name="InShort"></a>In Short</h4>
<p>This use case has shown how to create coping between structure objects.</p>
<p align="right">[<a href="#Top">Top</a>]</p>
<hr>
<!-- -------------------------------comment--------------------------------- -->
<h4><a name="References"></a>References</h4>
<table border="0" width="100%">
	<tr>
		<td valign="top" width="40">[1]</td>
		<td><a href="../CAAScdInfUseCases/CAAInfLauchMacro.htm">Replaying 
		a macro</a></td>
	</tr>
	<tr>
		<td colspan="2" align="right">[<a href="#Top">Top</a>]</td>
	</tr>
</table>
<hr>
<!-- -------------------------------comment--------------------------------- -->
<p><i>Copyright © 1999-2010, Dassault Systèmes. All rights reserved.</i></p>

</body>

</html>
