<html><head><meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"><title>CAAStrCreationOfStructureObjects.CATScript</title><link rel="stylesheet" type="text/css" href="../CAAScrBase/caav5.css"></head><body><pre>
<font color="#0000FF">Option Explicit</font>
<font color="#008000">' COPYRIGTH DASSAULT SYSTEMES 2000</font>

<font color="#008000">' ***********************************************************************</font>
<font color="#008000">'   Purpose:      Create structure objects</font>
<font color="#008000">'   Assumtions:   </font>
<font color="#008000">'   Author: </font>
<font color="#008000">'   Languages:    VBScript</font>
<font color="#008000">'   Locales:      English </font>
<font color="#008000">'   CATIA Level:  V5R6 </font>
<font color="#008000">' ***********************************************************************</font>

<font color="#0000FF">Sub </font>CATMain()

<font color="#0000FF">    Dim </font>doc<font color="#0000FF"> As </font>Document

<font color="#0000FF">    Dim </font>StrWorkbench<font color="#0000FF"> As </font>StrWorkbench
<font color="#0000FF">    Dim </font>strFactory<font color="#0000FF"> As </font>StrObjectFactory

<font color="#0000FF">    Set </font>doc = CATIA.ActiveDocument
<font color="#0000FF">    Dim </font>rootProduct<font color="#0000FF"> As </font>Product
<font color="#0000FF">    Set </font>rootProduct = doc.Product

<font color="#0000FF">    Set </font>StrWorkbench = doc.GetWorkbench("StrWorkbench")
<font color="#0000FF">    Set </font>strFactory = rootProduct.GetTechnologicalObject("StructureObjectFactory")

<font color="#0000FF">    Dim </font>documents<font color="#0000FF"> As </font>Documents
<font color="#0000FF">    Set </font>documents = CATIA.Documents

    <font color="#008000">'============================================================</font>
    <font color="#008000">' extremities definition for columns</font>
    <font color="#008000">'============================================================</font>

    <font color="#008000">' column 1</font>
<font color="#0000FF">    Dim </font>reference11<font color="#0000FF"> As </font>Reference
<font color="#0000FF">    Set </font>reference11 = rootProduct.CreateReferenceFromName("Produit1/grid/!Selection_BorderFVertex:(BEdge:(Brp:(GSMIntersect.12;(Brp:(GSMPlane.3);Brp:(GSMIntersect.10;(Brp:(GSMPlane.1);Brp:(GSMPlane.2)))));None:(Limits1:();Limits2:()));GSMIntersect.12)")
<font color="#0000FF">    Dim </font>extremity11<font color="#0000FF"> As </font>AnyObject
<font color="#0000FF">    Set </font>extremity11 = strFactory.AddDefExtFromReference(reference11, 0)

<font color="#0000FF">    Dim </font>reference12<font color="#0000FF"> As </font>Reference
<font color="#0000FF">    Set </font>reference12 = rootProduct.CreateReferenceFromName("Produit1/grid/!Selection_BorderFVertex:(BEdge:(Brp:(GSMIntersect.11;(Brp:(xy-plane);Brp:(GSMIntersect.10;(Brp:(GSMPlane.1);Brp:(GSMPlane.2)))));None:(Limits1:();Limits2:()));GSMIntersect.11)")
<font color="#0000FF">    Dim </font>extremity12<font color="#0000FF"> As </font>AnyObject
<font color="#0000FF">    Set </font>extremity12 = strFactory.AddDefExtFromReference(reference12, 0)

    <font color="#008000">' column 2</font>
<font color="#0000FF">    Dim </font>reference21<font color="#0000FF"> As </font>Reference
<font color="#0000FF">    Set </font>reference21 = rootProduct.CreateReferenceFromName("Produit1/grid/!Selection_BorderFVertex:(BEdge:(Brp:(GSMIntersect.9;(Brp:(GSMPlane.3);Brp:(GSMIntersect.7;(Brp:(GSMPlane.1);Brp:(zx-plane)))));None:(Limits1:();Limits2:()));GSMIntersect.9)")
<font color="#0000FF">    Dim </font>extremity21<font color="#0000FF"> As </font>AnyObject
<font color="#0000FF">    Set </font>extremity21 = strFactory.AddDefExtFromReference(reference21, 0)

<font color="#0000FF">    Dim </font>reference22<font color="#0000FF"> As </font>Reference
<font color="#0000FF">    Set </font>reference22 = rootProduct.CreateReferenceFromName("Produit1/grid/!Selection_BorderFVertex:(BEdge:(Brp:(GSMIntersect.8;(Brp:(xy-plane);Brp:(GSMIntersect.7;(Brp:(GSMPlane.1);Brp:(zx-plane)))));None:(Limits1:();Limits2:()));GSMIntersect.8)")
<font color="#0000FF">    Dim </font>extremity22<font color="#0000FF"> As </font>AnyObject
<font color="#0000FF">    Set </font>extremity22 = strFactory.AddDefExtFromReference(reference22, 0)

    <font color="#008000">' column 3</font>
<font color="#0000FF">    Dim </font>reference31<font color="#0000FF"> As </font>Reference
<font color="#0000FF">    Set </font>reference31 = rootProduct.CreateReferenceFromName("Produit1/grid/!Selection_BorderFVertex:(BEdge:(Brp:(GSMIntersect.5;(Brp:(xy-plane);Brp:(GSMIntersect.4;(Brp:(yz-plane);Brp:(GSMPlane.2)))));None:(Limits1:();Limits2:()));GSMIntersect.5)")
<font color="#0000FF">    Dim </font>extremity31<font color="#0000FF"> As </font>AnyObject
<font color="#0000FF">    Set </font>extremity31 = strFactory.AddDefExtFromReference(reference31, 0)

<font color="#0000FF">    Dim </font>reference32<font color="#0000FF"> As </font>Reference
<font color="#0000FF">    Set </font>reference32 = rootProduct.CreateReferenceFromName("Produit1/grid/!Selection_BorderFVertex:(BEdge:(Brp:(GSMIntersect.6;(Brp:(GSMPlane.3);Brp:(GSMIntersect.4;(Brp:(yz-plane);Brp:(GSMPlane.2)))));None:(Limits1:();Limits2:()));GSMIntersect.6)")
<font color="#0000FF">    Dim </font>extremity32<font color="#0000FF"> As </font>AnyObject
<font color="#0000FF">    Set </font>extremity32 = strFactory.AddDefExtFromReference(reference32, 0)

    <font color="#008000">' column 4</font>
<font color="#0000FF">    Dim </font>reference41<font color="#0000FF"> As </font>Reference
<font color="#0000FF">    Set </font>reference41 = rootProduct.CreateReferenceFromName("Produit1/grid/!Selection_BorderFVertex:(BEdge:(Brp:(GSMIntersect.3;(Brp:(GSMPlane.3);Brp:(GSMIntersect.1;(Brp:(yz-plane);Brp:(zx-plane)))));None:(Limits1:();Limits2:()));GSMIntersect.3)")
<font color="#0000FF">    Dim </font>extremity41<font color="#0000FF"> As </font>AnyObject
<font color="#0000FF">    Set </font>extremity41 = strFactory.AddDefExtFromReference(reference41, 0)

<font color="#0000FF">    Dim </font>reference42<font color="#0000FF"> As </font>Reference
<font color="#0000FF">    Set </font>reference42 = rootProduct.CreateReferenceFromName("Produit1/grid/!Selection_BorderFVertex:(BEdge:(Brp:(GSMIntersect.2;(Brp:(xy-plane);Brp:(GSMIntersect.1;(Brp:(yz-plane);Brp:(zx-plane)))));None:(Limits1:();Limits2:()));GSMIntersect.2)")
<font color="#0000FF">    Dim </font>extremity42<font color="#0000FF"> As </font>AnyObject
<font color="#0000FF">    Set </font>extremity42 = strFactory.AddDefExtFromReference(reference42, 0)

    <font color="#008000">'============================================================</font>
    <font color="#008000">' columns creation</font>
    <font color="#008000">'============================================================</font>

<font color="#0000FF">    dim </font>sectionName<font color="#0000FF"> as </font>string
    sectionName = InputBox("Section path","Parameters", "e:\tmp\HEA100.CATPart")
    
    <font color="#008000">' column 1    </font>
<font color="#0000FF">    Dim </font>docSection1<font color="#0000FF"> As </font>Document
<font color="#0000FF">    Set </font>docSection1 = documents.Read(sectionName)

<font color="#0000FF">    Dim </font>section1<font color="#0000FF"> As </font>StrSection
<font color="#0000FF">    Set </font>section1 = strFactory.AddSection(docSection1)

<font color="#0000FF">    dim </font>member1<font color="#0000FF"> as </font>StrMember
<font color="#0000FF">    Set </font>member1 = strFactory.AddMember(section1, "catStrCenterCenter", 0, extremity11, extremity12, "Column")
        
    <font color="#008000">' column 2</font>
<font color="#0000FF">    Dim </font>docSection2<font color="#0000FF"> As </font>Document
<font color="#0000FF">    Set </font>docSection2 = documents.Read(sectionName)

<font color="#0000FF">    Dim </font>section2<font color="#0000FF"> As </font>StrSection
<font color="#0000FF">    Set </font>section2 = strFactory.AddSection(docSection2)

<font color="#0000FF">    dim </font>member2<font color="#0000FF"> as </font>StrMember
<font color="#0000FF">    Set </font>member2 = strFactory.AddMember(section2, "catStrCenterCenter", 0, extremity21, extremity22, "Column")
        
    <font color="#008000">' column 3</font>
<font color="#0000FF">    Dim </font>docSection3<font color="#0000FF"> As </font>Document
<font color="#0000FF">    Set </font>docSection3 = documents.Read(sectionName)

<font color="#0000FF">    Dim </font>section3<font color="#0000FF"> As </font>StrSection
<font color="#0000FF">    Set </font>section3 = strFactory.AddSection(docSection3)

<font color="#0000FF">    dim </font>member3<font color="#0000FF"> as </font>StrMember
<font color="#0000FF">    Set </font>member3 = strFactory.AddMember(section3, "catStrCenterCenter", 0, extremity31, extremity32, "Column")
        
    <font color="#008000">' column 4</font>
<font color="#0000FF">    Dim </font>docSection4<font color="#0000FF"> As </font>Document
<font color="#0000FF">    Set </font>docSection4 = documents.Read(sectionName)

<font color="#0000FF">    Dim </font>section4<font color="#0000FF"> As </font>StrSection
<font color="#0000FF">    Set </font>section4 = strFactory.AddSection(docSection4)

<font color="#0000FF">    dim </font>member4<font color="#0000FF"> as </font>StrMember
<font color="#0000FF">    Set </font>member4 = strFactory.AddMember(section4, "catStrCenterCenter", 0, extremity41, extremity42, "Column")

    <font color="#008000">'============================================================</font>
    <font color="#008000">' end plates creation</font>
    <font color="#008000">'============================================================</font>

<font color="#0000FF">    Dim </font>plate1<font color="#0000FF"> As </font>StrPlate
<font color="#0000FF">    Set </font>plate1 = strFactory.AddRectangularEndPlate(member1, catEndExtremity, 0.005, 0.2, 0.2, catStrStandardOrientation, "EndPlate")
	
<font color="#0000FF">    Dim </font>plate2<font color="#0000FF"> As </font>StrPlate
<font color="#0000FF">    Set </font>plate2 = strFactory.AddRectangularEndPlate(member2, catEndExtremity, 0.005, 0.2, 0.2, catStrStandardOrientation, "EndPlate")
	
<font color="#0000FF">    Dim </font>plate3<font color="#0000FF"> As </font>StrPlate
<font color="#0000FF">    Set </font>plate3 = strFactory.AddRectangularEndPlate(member3, catStartExtremity, 0.005, 0.2, 0.2, catStrStandardOrientation, "EndPlate")
	
<font color="#0000FF">    Dim </font>plate4<font color="#0000FF"> As </font>StrPlate
<font color="#0000FF">    Set </font>plate4 = strFactory.AddRectangularEndPlate(member4, catEndExtremity, 0.005, 0.2, 0.2, catStrStandardOrientation, "EndPlate")

    <font color="#008000">'============================================================</font>
    <font color="#008000">' plate creation</font>
    <font color="#008000">'============================================================</font>

<font color="#0000FF">    Dim </font>contour(3)<font color="#0000FF"> As </font>Reference

<font color="#0000FF">    Set </font>contour(0) = rootProduct.CreateReferenceFromName("Produit1/Column_2/!Selection_FVertex:(Vertex:(Neighbours:(Face:(Brp:(StructuralRib.1;0:(Brp:(Sketch.1;1)));None:());Face:(Brp:(StructuralRib.1;1);None:());Face:(Brp:(StructuralRib.1;0:(Brp:(Sketch.1;20)));None:())));StructuralRib.1)")
<font color="#0000FF">    Set </font>contour(1) = rootProduct.CreateReferenceFromName("Produit1/Column_4/!Selection_FVertex:(Vertex:(Neighbours:(Face:(Brp:(StructuralRib.1;0:(Brp:(Sketch.1;1)));None:());Face:(Brp:(StructuralRib.1;2);None:());Face:(Brp:(StructuralRib.1;0:(Brp:(Sketch.1;20)));None:())));StructuralRib.1)")
<font color="#0000FF">    Set </font>contour(2) = rootProduct.CreateReferenceFromName("Produit1/Column_5/!Selection_FVertex:(Vertex:(Neighbours:(Face:(Brp:(StructuralRib.1;0:(Brp:(Sketch.1;10)));None:());Face:(Brp:(StructuralRib.1;1);None:());Face:(Brp:(StructuralRib.1;0:(Brp:(Sketch.1;11)));None:())));StructuralRib.1)")
	Set contour(3) = rootProduct.CreateReferenceFromName("Produit1/Column_3/!Selection_FVertex:(Vertex:(Neighbours:(Face:(Brp:(StructuralRib.1;0:(Brp:(Sketch.1;11)));None:());Face:(Brp:(StructuralRib.1;1);None:());Face:(Brp:(StructuralRib.1;0:(Brp:(Sketch.1;12)));None:())));StructuralRib.1)")

<font color="#0000FF">    Dim </font>support<font color="#0000FF"> As </font>Reference
<font color="#0000FF">    Set </font>support = rootProduct.CreateReferenceFromName("Produit1/grid/!Plane.3")

<font color="#0000FF">    Dim </font>plate<font color="#0000FF"> As </font>StrPlate
<font color="#0000FF">    Set </font>plate = strFactory.AddPlate(support, 0.005, catStrStandardOrientation, contour, 0.0, "PlateType")

<font color="#0000FF">End Sub</font>



</pre></body></html>


