<html>

<head>
<meta http-equiv="Content-Language" content="en">
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<meta name="GENERATOR" content="Microsoft FrontPage 12.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
<title>CAAStrEditCutout.CATScript</title>
<link rel="stylesheet" type="text/css" href="../CAAScrBase/caav5.css">
</head>

<body>
<pre>
<font color="#0000FF">Sub</font> CATMain()
<font color="#0000FF">Dim</font> StrWorkbench <font color="#0000FF">As</font> StrWorkbench
<font color="#0000FF">Dim</font> strFactory <font color="#0000FF">As</font> StrObjectFactory

<font color="#0000FF">Set</font> doc = CATIA.ActiveDocument
<font color="#0000FF">Dim</font> rootProduct <font color="#0000FF">As</font> Product
<font color="#0000FF">Set</font> rootProduct = doc.Product
   
<font color="#0000FF">Set</font> StrWorkbench = doc.GetWorkbench(&quot;StrWorkbench&quot;)
    
<font color="#0000FF">Dim</font> strPlates <font color="#0000FF">As</font> strPlates
<font color="#0000FF">Set</font> strPlates = rootProduct.GetTechnologicalObject(&quot;StructurePlates&quot;)
   
<font color="#0000FF">Dim</font> selection1 <font color="#0000FF">As</font> Selection
<font color="#0000FF">Set</font> selection1 = doc.Selection

selection1.Search &quot;Name='StrCutout.1',all&quot;

<font color="#0000FF">Dim</font> CutoutToEdit <font color="#0000FF">As</font> StrCutoutFeature
<font color="#0000FF">Set</font> CutoutToEdit = selection1.Item(1).Value

<font color="#008000">'Get the Cutout Type</font>
<font color="#0000FF">Dim</font> FormingMode <font color="#0000FF">As</font> String
FromingMode = CutoutToEdit.CutoutType

<font color="#008000">'Get the Current Contour</font>
<font color="#0000FF">Dim</font> CurrentContour <font color="#0000FF">As</font> Reference
<font color="#0000FF">Set</font> CurrentContour = CutoutToEdit.Contour

<font color="#008000">'Get the Current Direction Element</font>
<font color="#0000FF">Dim</font> CurrentDirElement <font color="#0000FF">As</font> Reference
<font color="#0000FF">Set</font> CurrentDirElement = CutoutToEdit.DirectionElement

<font color="#008000">'Set the New Direction Element</font>
<font color="#0000FF">Set</font> documents1 = CATIA.Documents
<font color="#0000FF">Set</font> partDocument1 = documents1.Item(&quot;Grid.CATPart&quot;)
<font color="#0000FF">Set</font> part1 = partDocument1.Part

<font color="#0000FF">Set</font> Newdir = part1.FindObjectByName(&quot;Sketch.4&quot;)
<font color="#0000FF">Set</font> NewDirElement = part1.CreateReferenceFromObject(Newdir)
CutoutToEdit.DirectionElement = NewDirElement

<font color="#008000">'Set the New Contour</font>
<font color="#0000FF">Dim</font> NewContour <font color="#0000FF">As</font> Reference
<font color="#0000FF">Set</font> NewContour = rootProduct.CreateReferenceFromName(&quot;Product1/Grid/!Sketch.2&quot;)
CutoutToEdit.Contour = NewContour

<font color="#0000FF">End Sub</font>
</pre>

</body>

</html>
