<html>

<head>
<meta http-equiv="Content-Language" content="en">
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<meta name="GENERATOR" content="Microsoft FrontPage 12.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
<title>CAAStrCreateCutout.CATScript</title>
<link rel="stylesheet" type="text/css" href="../CAAScrBase/caav5.css">
</head>

<body>
<pre>
<font color="#0000FF">Sub</font> CATMain()

<font color="#0000FF">Dim</font> doc <font color="#0000FF">As</font> Document

  <font color="#0000FF">Dim</font> StrWorkbench <font color="#0000FF">As</font> StrWorkbench
  <font color="#0000FF">Dim</font> strFactory <font color="#0000FF">As</font> StrObjectFactory

  <font color="#0000FF">Set</font> doc = CATIA.ActiveDocument
  <font color="#0000FF">Dim</font> rootProduct <font color="#0000FF">As</font> Product
  <font color="#0000FF">Set</font> rootProduct = doc.Product
   
  <font color="#0000FF">Set</font> StrWorkbench = doc.GetWorkbench(&quot;StrWorkbench&quot;)
    
  <font color="#0000FF">Dim</font> strPlates <font color="#0000FF">As</font> strPlates
  <font color="#0000FF">Set</font> strPlates = rootProduct.GetTechnologicalObject(&quot;StructurePlates&quot;)

 <font color="#0000FF"> Dim</font> sketch <font color="#0000FF">As</font> Reference
  <font color="#0000FF">Set</font> sketch1 = rootProduct.CreateReferenceFromName(&quot;Product1/Grid/!Sketch.1&quot;)

<font color="#008000">  '*************************First Cutout**************************************************</font>
  <font color="#0000FF">Dim</font> PlateToCut1 <font color="#0000FF">As</font> StrPlate
  <font color="#0000FF">Set</font> PlateToCut1 = strPlates.Item(&quot;Plate_052&quot;)

  <font color="#0000FF">Dim</font> Selection1 <font color="#0000FF">As</font> Selection
  <font color="#0000FF">Set</font> Selection1 = CATIA.ActiveDocument.Selection
  Selection1.Add PlateToCut1
  
  <font color="#0000FF">Dim</font> Factory1 <font color="#0000FF">As</font> StrFeatureFactory
  <font color="#0000FF">Set</font> Factory1 = Selection1.FindObject(&quot;CATIAStrFeatureFactory&quot;)

  <font color="#0000FF">Dim</font> dir1 <font color="#0000FF">As</font> Reference
  <font color="#0000FF">Set</font> dir1 = rootProduct.CreateReferenceFromName(&quot;Product1/Grid/!Sketch.3&quot;)

  <font color="#0000FF">Dim</font> Cutout1 <font color="#0000FF">As</font> StrCutoutFeature
  <font color="#0000FF">Set</font> Cutout1 = Factory1.AddCutoutWithAfterFormingMode(sketch1, dir1)
 
<font color="#008000">  '*************************Second  Cutout**************************************************</font>
  <font color="#0000FF">Dim</font> PlateToCut2 <font color="#0000FF">As</font> StrPlate
  <font color="#0000FF">Set</font> PlateToCut2 = strPlates.Item(&quot;Plate_053&quot;)

  <font color="#0000FF">Dim</font> Selection2 <font color="#0000FF">As</font> Selection
  <font color="#0000FF">Set</font> Selection2 = CATIA.ActiveDocument.Selection
  Selection2.Add PlateToCut2

  <font color="#0000FF">Dim</font> Factory2 <font color="#0000FF">As</font> StrFeatureFactory
  <font color="#0000FF">Set</font> Factory2 = Selection2.FindObject(&quot;CATIAStrFeatureFactory&quot;)

  <font color="#0000FF">Dim</font> Sur1 <font color="#0000FF">As</font> Reference
  <font color="#0000FF">Set</font> Sur1 = rootProduct.CreateReferenceFromName(&quot;Product1/Grid/!Extrude.1&quot;)

  <font color="#0000FF">Dim</font> Cutout2 <font color="#0000FF">As</font> StrCutoutFeature
  <font color="#0000FF">Set</font> Cutout2 = Factory2.AddCutoutWithBeforeFormingMode(sketch1, Sur1)

<font color="#0000FF">End Sub</font>
</pre>

</body>

</html>
