<html><head><meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"><title>CAAStrModificationOfStructureObjects.CATScript</title><link rel="stylesheet" type="text/css" href="../CAAScrBase/caav5.css"></head><body><pre>
<font color="#008000">'// COPYRIGHT DASSAULT SYSTEMES 2000</font>
<font color="#008000">'//============================================================================</font>
<font color="#008000">'//</font>
<font color="#008000">'// Language="VBSCRIPT"</font>
<font color="#008000">'// Sample of macro of using structural vb objects</font>
<font color="#008000">'//</font>
<font color="#008000">'//============================================================================</font>
<font color="#008000">'//</font>
<font color="#008000">'// Alain DEBUISSON			le 07/11/2000		creation </font>
<font color="#008000">'//</font>
<font color="#008000">'//============================================================================</font>

<font color="#0000FF">Sub </font>CATMain()

<font color="#0000FF">    Dim </font>doc<font color="#0000FF"> As </font>Document

<font color="#0000FF">    Dim </font>StrWorkbench<font color="#0000FF"> As </font>StrWorkbench
<font color="#0000FF">    Dim </font>strFactory<font color="#0000FF"> As </font>StrObjectFactory

<font color="#0000FF">    Set </font>doc = CATIA.ActiveDocument
<font color="#0000FF">    Dim </font>rootProduct<font color="#0000FF"> As </font>Product
<font color="#0000FF">    Set </font>rootProduct = doc.Product
	dim strMembers<font color="#0000FF"> as </font>StrMembers

<font color="#0000FF">    Set </font>strWorkbench = doc.GetWorkbench("StrWorkbench")
<font color="#0000FF">    Set </font>strMembers = rootProduct.GetTechnologicalObject("StructureMembers")

	<font color="#008000">'============================================================</font>
	<font color="#008000">' looking for a member</font>
	<font color="#008000">'============================================================</font>

	dim member<font color="#0000FF"> as </font>StrMember
	set member = strMembers.Item("Column_3")

	<font color="#008000">'============================================================</font>
	<font color="#008000">' rotate a member</font>
	<font color="#008000">'============================================================</font>

	member.Rotate(45.0)

	<font color="#008000">'============================================================</font>
	<font color="#008000">' anchor point modification</font>
	<font color="#008000">'============================================================</font>

	member.CurrentAnchorPointName = "catStrTopCenter"

	<font color="#008000">'============================================================</font>
	<font color="#008000">' looking for a plate</font>
	<font color="#008000">'============================================================</font>

	dim strPlates<font color="#0000FF"> as </font>StrPlates
<font color="#0000FF">    Set </font>strPlates = rootProduct.GetTechnologicalObject("StructurePlates")

	dim plate<font color="#0000FF"> as </font>StrPlates
	set plate = strPlates.Item("PlateType_12")
	
	<font color="#008000">'============================================================</font>
	<font color="#008000">' inverse material orientation</font>
	<font color="#008000">'============================================================</font>

	plate.ReverseDirection
	
	<font color="#008000">'============================================================</font>
	<font color="#008000">' thickness modification</font>
	<font color="#008000">'============================================================</font>

	plate.StandardThickness = 0.020

	<font color="#008000">'============================================================</font>
	<font color="#008000">' update</font>
	<font color="#008000">'============================================================</font>

	rootProduct.Update
	
<font color="#0000FF">End Sub</font>



</pre></body></html>


