<html>

<head>
<meta http-equiv="Content-Language" content="en_us">
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<meta name="GENERATOR" content="Microsoft FrontPage 12.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
<title>Modifying Cutouts</title>
<link rel="stylesheet" type="text/css" href="../CAAScrBase/caav5.css">
<script type="text/javascript" src="../CAAScrJavaScript/submit.js"></script>
</head>

<body>

<table border="0" width="100%">
	<tr>
		<td>
		<h2>Structure Design</h2>
		</td>
		<td align="right" valign="top">
		<h2><a name="Top"></a>Modifying Cutouts</h2>
		</td>
	</tr>
</table>
<hr>
<!-- -------------------------------comment--------------------------------- -->
<table border="0" width="100%">
	<tr>
		<td width="7%" valign="top">
		<img alt="Target Icon" src="../CAAScrBase/images/atarget.gif" width="32" height="32"></td>
		<td width="93%">
		<p><a name="Learn"></a>This macro shows you how to edit existing cutout 
		on Structure Objects.</p>
		<p>This macro replaces the contour and direction used for creating existing 
		cutout.</p>
		<p>
		<img alt="Starting Product" src="images/CAAScdStrCutout02.png" width="429" height="317">
		</p>
		<!-- -------------------------------comment--------------------------------- -->
		</td>
	</tr>
	<tr>
		<td width="7%" valign="top">
		<img alt="Information Icon" src="../CAAScrBase/images/ainfo.gif" width="32" height="32"></td>
		<td width="93%">
		<p><a name="How"></a>CAAStrEditCutout is launched in CATIA [<a href="#References">1</a>]. 
		Some documents are needed.</p>
		<ul>
			<li>You have to run CreateCutout.CATScript macro before running this 
			macro.</li>
			<li><a href="CAAStrModificationOfCutoutSource.htm" target="Source">CAAStrEditCutout.CATScript</a> 
			is located in the CAAScdStrUseCases module.
			<a href="macros/CAAStrEditCutout.CATScript">Execute macro</a> (Windows 
			only).</li>
			<li>The document Product1.CATProduct is located in the CAAScdStrUseCases 
			module in the samples directory. Grid.CATPart is linked to the previous 
			document and it contains the grid, sketches and surfaces used by the 
			macro.</li>
			<li>The CATPart containing the section is located in the samples directory.</li>
		</ul>
		</td>
	</tr>
	<tr>
		<td width="7%" valign="top">
		<img alt="Scenario Icon" src="../CAAScrBase/images/ascenari.gif" width="32" height="32"></td>
		<td width="93%">
		<p><a name="Step"></a>CAAStrEditCutout includes three steps:</p>
		<ol>
			<li><a href="#Prolog">Prolog</a></li>
			<li><a href="#Step1">Retrieving Existing Cutout</a></li>
			<li><a href="#Step2">Modifying the Cutout</a></li>
		</ol>
		<!-- -------------------------------comment--------------------------------- -->
		<h4><a name="Prolog"></a>Prolog</h4>
		<pre class="code">Dim doc As Document

Dim StrWorkbench As StrWorkbench
Dim strFactory As StrObjectFactory

Set doc = CATIA.ActiveDocument

Dim rootProduct As Product
Set rootProduct = doc.Product
   
Set StrWorkbench = doc.GetWorkbench(&quot;StrWorkbench&quot;)
    
Dim strPlates As strPlates
Set strPlates = rootProduct.GetTechnologicalObject(&quot;StructurePlates&quot;)</pre>
		<!-- -------------------------------comment--------------------------------- -->
		<h4><a name="Step1"></a>Retrieving Existing Cutout</h4>
		<p>The Existing cutout can be searched by using the search method on selection.&#8221;StrCutout.1&#8221; 
		is searched for in the entire product.</p>
		<p>We will modify the first cutout retrieved.</p>
		<pre class="code">Dim selection1 As Selection
Set selection1 = doc.Selection

selection1.Search &quot;Name=&#39;StrCutout.1&#39;,all&quot;

Dim CutoutToEdit As StrCutoutFeature
Set CutoutToEdit = selection1.Item(1).Value</pre>
		<!-- -------------------------------comment--------------------------------- -->
		<h4><a name="Step2"></a>Modifying the Cutout</h4>
		<p>Replace the existing contour of the cutout with a new one and also change 
		the direction.</p>
		<pre class="code">&#39;Get the Cutout Type
Dim FormingMode As String
FromingMode = CutoutToEdit.CutoutType

&#39;Get the Current Contour
Dim CurrentContour As Reference
Set CurrentContour = CutoutToEdit.Contour

&#39;Get the Current Direction Element
Dim CurrentDirElement As Reference
Set CurrentDirElement = CutoutToEdit.DirectionElement

&#39;Set the New Direction Element

Set documents1 = CATIA.Documents
Set partDocument1 = documents1.Item(&quot;Grid.CATPart&quot;)
Set part1 = partDocument1.Part

Set Newdir = part1.FindObjectByName(&quot;Sketch.4&quot;)
Set NewDirElement = part1.CreateReferenceFromObject(Newdir)
CutoutToEdit.DirectionElement = NewDirElement

&#39;Set the New Contour
Dim NewContour As Reference
Set NewContour = rootProduct.CreateReferenceFromName(&quot;Product1/Grid/!Sketch.2&quot;)
CutoutToEdit.Contour = NewContour

End Sub</pre>
		<!-- -------------------------------comment--------------------------------- -->
		</td>
	</tr>
</table>
<!-- -------------------------------comment--------------------------------- -->
<p align="center">
<img alt="End Task Icon" src="../CAAScrBase/images/aendtask.gif" width="64" height="32"></p>
<p align="right">[<a href="#Top">Top</a>]</p>
<hr>
<!-- -------------------------------comment--------------------------------- -->
<h4><a name="InShort"></a>In Short</h4>
<p>This use case has shown how to edit Cutouts on structure Objects.</p>
<p align="right">[<a href="#Top">Top</a>]</p>
<hr>
<!-- -------------------------------comment--------------------------------- -->
<h4><a name="References"></a>References</h4>
<table border="0" width="100%">
	<tr>
		<td valign="top" width="40">[1]</td>
		<td><a href="../CAAScdInfUseCases/CAAInfLauchMacro.htm">Replaying 
		a macro</a></td>
	</tr>
	<tr>
		<td colspan="2" align="right">[<a href="#Top">Top</a>]</td>
	</tr>
</table>
<hr>
<!-- -------------------------------comment--------------------------------- -->
<p><i>Copyright © 1999-2010, Dassault Systèmes. All rights reserved.</i></p>

</body>

</html>
