<html>

<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<meta name="GENERATOR" content="Microsoft FrontPage 4.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
<title>Creating Structure Foundations</title>
<link rel="stylesheet" type="text/css" href="../CAAScrBase/caav5.css">
<script language="JavaScript" src="../CAAScrJavaScript/submit.js"></script>
</head>

<body>

<table border="0" width="100%">
  <tr>
    <td>
      <h2>Structure Design</h2>
    </td>
    <td align="right" valign="top">
      <h2><a name="Top"></a>Creating Structure Foundations</h2>
    </td>
  </tr>
</table>
<hr>
<! ---------------------------------comment------------------------------------->
<table border="0" width="100%">
  <tr>
    <td width="7%" valign="top"><img border="0" src="../CAAScrBase/images/atarget.gif" width="32" height="32"></td>
    <td width="93%">
      <p><a name="Learn"></a>This macro shows you how to create structure
      foundation.</p>
      <! ---------------------------------comment------------------------------------->
      <p>It extends a root product in a product document</p>
      <p>&nbsp;</p>
    </td>
  </tr>
  <tr>
    <td width="7%" valign="top"><img border="0" src="../CAAScrBase/images/ainfo.gif" width="32" height="32"></td>
    <td width="93%">
      <p><a name="How"></a>CAAStrCreationOfStructureFoundation is launched in
      CATIA [<a href="#References">1</a>]. Some documents are needed.</p>
      <ul>
        <li><a href="CAAStrCreationOfStructureFoundationSource.htm" target="Source">CAAStrCreationOfStructureFoundation.CATScript</a>
          is located in the CAAScdStrUseCases module. <a href="macros/CAAStrCreationOfStructureObjects.CATScript">Execute
          macro</a> (windows only).</li>
        <li>You need to create first a new empty Product Document</li>
      </ul>
      <p>&nbsp;</td>
  </tr>
  <tr>
    <td width="7%" valign="top"><img border="0" src="../CAAScrBase/images/ascenari.gif" width="32" height="32"></td>
    <td width="93%">
      <p><a name="Step"></a>CAAStrCreationOfStructureFoundation includes five
      steps:</p>
      <ol>
        <li><a href="#Prolog">Prolog</a></li>
        <li><a href="#Step1">Creating Foundation</a></li>
        <li><a href="#step2">Retreiving the created Foundation in the assembly</a></li>
      </ol>
      <h4>&nbsp;</h4>
      <h4><a name="Prolog"></a>Prolog</h4>
      <table class="code">
        <tr>
          <td>
            <pre>  ...
    <font color="#0000FF">Dim </font>doc<font color="#0000FF"> As </font>Document

<font color="#0000FF">    Dim </font>StrWorkbench<font color="#0000FF"> As </font>StrWorkbench
<font color="#0000FF">    Dim </font>strFactory<font color="#0000FF"> As </font>StrObjectFactory

<font color="#0000FF">    Set </font>doc = CATIA.ActiveDocument
<font color="#0000FF">    Dim </font>rootProduct<font color="#0000FF"> As </font>Product
<font color="#0000FF">    Set </font>rootProduct = doc.Product

<font color="#0000FF">    Dim </font>products <font color="#0000FF">As </font>Products
    <font color="#0000FF">Set </font>products = rootProduct.Products

    <font color="#0000FF">Dim </font>component <font color="#0000FF">As </font>Product
    <font color="#0000FF">Set </font>component = products.AddNewProduct(&quot;Foundation&quot;)

    <font color="#0000FF">Set </font>strFactory = component.GetTechnologicalObject(&quot;StructureObjectFactory&quot;)

  ...</pre>
          </td>
        </tr>
      </table>
      <p>This step describes how to get the structure object factory.</p>
      <h4><a name="Step1"></a>Creating structure foundation&nbsp;</h4>
      <table class="code">
        <tr>
          <td>
            <pre>  ...
    <font color="#0000FF">Dim </font>foundation <font color="#0000FF">As </font>StrFoundation 
    <font color="#0000FF">Set </font>foundation = strFactory.ExtendProductAsFoundation(&quot;&quot;)
  ...</pre>
          </td>
        </tr>
      </table>
      <p>The foundation is created by extending the product with structure data.</p>
      <p>&nbsp;</p>
      <h4><a name="step2"></a>Retreiving the created Foundation in the assembly</h4>
      <table class="code">
        <tr>
          <td>
            <pre>  ...
    <font color="#0000FF">Dim </font>foundations <font color="#0000FF">As </font>StrFoundations
    <font color="#0000FF">Set </font>foundations = rootProduct.GetTechnologicalObject(&quot;StructureFoundations&quot;)		
	
    <font color="#0000FF">Set </font>foundation = foundations.Item(1)

  ...</pre>
          </td>
        </tr>
      </table>
      <p>The foundation is retreived thanks to the collection of foundations.</p>
      <p>&nbsp;</p>
      <p>&nbsp;</p>
    </td>
  </tr>
</table>
<! ---------------------------------comment------------------------------------->
<p align="center"><img border="0" src="../CAAScrBase/images/aendtask.gif" width="64" height="32"></p>
<p align="right">[<a href="#Top">Top</a>]</p>
<hr>
<! ---------------------------------comment------------------------------------->
<h4><a name="InShort"></a>In Short</h4>
<p>This use case has shown how to create structure objects</p>
<p align="right">[<a href="#Top">Top</a>]</p>
<hr>
<! ---------------------------------comment------------------------------------->
<h4><a name="References"></a>References</h4>
<table border="0" width="100%">
  <tr>
    <td valign="top" width="40">[1]</td>
    <td width="735"><a href="../CAAScdInfUseCases/CAAInfLauchMacro.htm">Replaying
      a macro</a></td>
  </tr>
  <tr>
    <td colspan="2" align="right">[<a href="#Top">Top</a>]</td>
</table>
<hr>
<! ---------------------------------comment------------------------------------->
<p><i>Copyright © 2001, Dassault Systèmes. All rights reserved.</i></p>

</body>
