<html>

<head>
<meta http-equiv="Content-Language" content="en">
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<meta name="GENERATOR" content="Microsoft FrontPage 12.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
<title>Creating Openings</title>
<link rel="stylesheet" type="text/css" href="../CAAScrBase/caav5.css">
<script type="text/javascript" src="../CAAScrJavaScript/submit.js"></script>
</head>

<body>

<table border="0" width="100%">
	<tr>
		<td>
		<h2>Structure Function Design Modeler</h2>
		</td>
		<td align="right" valign="top">
		<h2><a name="Top"></a>Creating Standard Openings</h2>
		</td>
	</tr>
</table>
<hr>
<!---------------------------------comment----------------------------------->
<table border="0" width="100%">
	<tr>
		<td width="7%" valign="top">
		<img alt="Target Icon" src="../CAAScrBase/images/atarget.gif" width="32" height="32"></td>
		<td width="93%"><a name="Learn"></a>This macro shows you how to create standard 
		openings on an SDD Plate. Here we will use &#8220;Rect&#8221; profile and MidDist-MidDist 
		Strategy.
		<p>
		<img alt="Starting Part" src="images/CAASdd004.png" width="559" height="195">
		</p>
		</td>
	</tr>
	<tr>
		<td width="7%" valign="top">
		<img alt="Information Icon" src="../CAAScrBase/images/ainfo.gif" width="32" height="32"></td>
		<td width="93%"><a name="How"></a>
		<a name="How" href="macros/CAASddMidDist_MidDist.CATScript">CAASddMidDist_MidDist</a> 
		is launched in CATIA [<a href="#References">1</a>]. Some documents are needed.
		<ul>
			<li><a href="CAASddCreateStdOpeningSource.htm">CAASddMidDist_MidDist.CATScript</a> 
			is located in the CAAScdSddUseCases module.
			<a href="macros/CAASddMidDist_MidDist.CATScript">Execute macro</a> (Windows 
			only).</li>
			<li>The document Product1.CATProduct is located in the CAAScdSddUseCases 
			module in the samples directory. Design_Unit_002.CATPart is linked to 
			the previous document and contains data required for the macro.</li>
			<li>The CATPart containing the section is located in the samples directory.</li>
		</ul>
		</td>
	</tr>
	<tr>
		<td width="7%" valign="top">
		<img border="0" src="../CAAScrBase/images/ascenari.gif" width="32" height="32"></td>
		<td width="93%"><a name="Step"></a>CAASddCreateOpening includes five steps:<ol>
			<li><a href="#Step1">Prolog</a></li>
			<li><a href="#Step2">Get the Factory and Two Managers( Contour Manager 
			and Position Strategy Manager)</a></li>
			<li><a href="#Step3">Select the Contour and Set Contour Parameters</a></li>
			<li><a href="#Step4">Define the Position Strategy and Prepare Lists 
			for U References and V References</a></li>
			<li><a href="#Step5">Create Standard Opening by Setting PositionStrategyParms</a></li>
		</ol>
		<!---------------------------------comment----------------------------------->
		<h4><a name="Step1"></a>Prolog</h4>
		<p>The macro first loads CAASCH_Detail01.CATProduct that contains three 
		schematic component symbols.</p>
		<pre class="code"><font color="#0000FF">Set</font> documents1 = CATIA.Documents
<font color="#0000FF">Set</font> PartDocument1 = documents1.Item(&quot;Design_Unit_002.CATPart&quot;)
<font color="#0000FF">Set</font> Part1 = PartDocument1.Part
<font color="#0000FF">Set</font> plate = Part1.FindObjectByName(&quot;Deck_002&quot;)
<font color="#0000FF">Set</font> plateref = Part1.CreateReferenceFromObject(plate)
</pre>
		<!---------------------------------comment----------------------------------->
		<h4><a name="Step2"></a>Get the Factory and Two Managers (Contour Manager 
		and Position Strategy Manager)</h4>
		<p>First retrieve the Factor from the part. Then retrieve the SfmOpeningContoursMgr 
		and SfmPositioningStrategyManager.</p>
		<pre class="code"><font color="#0000FF">Dim</font> Factory <font color="#0000FF">As</font> SfmFunctionFactory
<font color="#0000FF">Set</font> Factory = Part1.GetCustomerFactory(&quot;SfmFunctionFactory&quot;)

<font color="#0000FF">Dim</font> ObjSfmContourMgr <font color="#0000FF">As</font> SfmOpeningContoursMgr
<font color="#0000FF">Set</font> ObjSfmContourMgr = Factory.GetOpeningMgr(Part1, &quot;SfmOpeningContoursMgr&quot;)
 
<font color="#0000FF">Dim</font> ObjSfmPosStrategyMgr <font color="#0000FF">As</font> SfmPositioningStrategyManager
<font color="#0000FF">Set</font> ObjSfmPosStrategyMgr = Factory.GetOpeningMgr(Part1, &quot;SfmPositioningStrategyManager&quot;)</pre>
		<!---------------------------------comment----------------------------------->
		<h4><a name="Step3"></a>Select the Contour and Set Contour Parameters</h4>
		<pre class="code"><font color="#008800">&#39;Define the Contour</font>
 <font color="#0000FF">Dim</font> oListContourNames() <font color="#0000FF">As</font> Variant
 ObjSfmContourMgr.GetAvailableStdOpeningContours oListContourNames

 <font color="#0000FF">Dim</font> NbOfContour <font color="#0000FF">As</font> Long
 NbOfContour = UBound(oListContourNames)

<font color="#008800">&#39;Display List of contours</font>
 <font color="#0000FF">For</font> i = 0 <font color="#0000FF">To</font> NbOfContour
 <font color="#0000FF">MsgBox</font> oListContourNames(i)
 <font color="#0000FF">Next</font>

 <font color="#008800">&#39;Set the Required Contour and Set its Contour Parameters</font>
 <font color="#0000FF">Dim</font> oListCkeParms <font color="#0000FF">As</font> SfmStandardContourParameters
 <font color="#0000FF">Set</font> oListCkeParms = ObjSfmContourMgr.GetStdOpeningContourParams(&quot;Sfm_Rect&quot;)

 <font color="#0000FF">Dim</font> NbOfParam <font color="#0000FF">As</font> Long
 NbOfParam = oListCkeParms.Count

 <font color="#0000FF">Dim</font> ContourParam <font color="#0000FF">As</font> Parameter
 <font color="#0000FF">Dim</font> ContourParamName <font color="#0000FF">As</font> String

 <font color="#0000FF">For</font> i = 1 <font color="#0000FF">To</font> NbOfParam
  <font color="#0000FF">Set</font> ContourParam = oListCkeParms.Item(i)
  ContourParamName = oListCkeParms.Item(i).Name
  <font color="#008800">&#39;MsgBox ContourParamName</font>

  <font color="#0000FF">If</font> ContourParamName = &quot;Sfm_Width&quot; <font color="#0000FF">Then</font>
    ContourParam.ValuateFromString (&quot;1000mm&quot;)
  <font color="#0000FF">End If</font>
  <font color="#0000FF">If</font> ContourParamName = &quot;Sfm_Height&quot; <font color="#0000FF">Then</font>
    ContourParam.ValuateFromString (&quot;2000mm&quot;)
  <font color="#0000FF">End If</font>
  <font color="#0000FF">If</font> ContourParamName = &quot;Sfm_CornerRadius&quot; <font color="#0000FF">Then</font>
    ContourParam.ValuateFromString (&quot;10mm&quot;)
   <font color="#0000FF">End If</font>
 <font color="#0000FF">Next</font></pre>
		<!---------------------------------comment----------------------------------->
		<h4><a name="Step4"></a>Define the Position Strategy and Prepare lists for 
		U References and V References</h4>
		<p>Use ObjSfmPosStrategyMgr to GetPositioningStrategyParams.</p>
		<p>Since MidDist-MidDist strategy is selected, you need to prepare List 
		of U References and V References. Both these lists will contain even number 
		of reference Planes</p>
		<pre class="code"><font color="#008800">&#39;Define the Position Strategy</font>
<font color="#0000FF">Dim</font> PositionStrategyParms <font color="#0000FF">As</font> SfmStandardPosStrategyParameters
<font color="#0000FF">Set</font> PositionStrategyParms = ObjSfmPosStrategyMgr.GetPositioningStrategyParams(&quot;CATSfmPosMidDistMidDist&quot;)

<font color="#008800">&#39;Prepare a List of U &amp; V Reference</font>
 <font color="#0000FF">Dim</font> UrefList <font color="#0000FF">As</font> SfmReferences
 <font color="#0000FF">Dim</font> Uref1 <font color="#0000FF">As</font> Reference
 <font color="#0000FF">Set</font> Uref1 = Part1.FindObjectByName(&quot;CROSS.95&quot;)
 <font color="#0000FF">Set</font> Uref2 = Part1.FindObjectByName(&quot;CROSS.50&quot;)
 <font color="#0000FF">Set</font> Uref3 = Part1.FindObjectByName(&quot;CROSS.25&quot;)
 <font color="#0000FF">Set</font> Uref4 = Part1.FindObjectByName(&quot;CROSS.40&quot;)
 <font color="#0000FF">Set</font> UrefList = Factory.SfmReferences
 UrefList.Add Uref1
 UrefList.Add Uref2
 UrefList.Add Uref3
 UrefList.Add Uref4
 
 <font color="#0000FF">Dim</font> VrefList <font color="#0000FF">As</font> SfmReferences
 <font color="#0000FF">Dim</font> Vref1 <font color="#0000FF">As</font> Reference
 <font color="#0000FF">Set</font> Vref1 = Part1.FindObjectByName(&quot;LONG.0&quot;)
 <font color="#0000FF">Set</font> Vref2 = Part1.FindObjectByName(&quot;LONG.10&quot;)
 <font color="#0000FF">Set</font> VrefList = Factory.SfmReferences
 VrefList.Add Vref1
 VrefList.Add Vref2
 
 <font color="#0000FF">Dim</font> NbofURef <font color="#0000FF">As</font> Long
 NbofURef = UrefList.Count
 
 <font color="#0000FF">Dim</font> NbofVRef <font color="#0000FF">As</font> Long
 NbofVRef = VrefList.Count</pre>
		<!---------------------------------comment----------------------------------->
		<h4><a name="Step5"></a>Create Standard Opening by setting PositionStrategyParms</h4>
		<ol>
			<li>An intermediate list for U references is created (URefListint).</li>
			<li>Inside the For loop, this intermediate list will hold first two 
			U references. The For loop moves in step of 2.</li>
			<li>SetPosParamData Method is called on PositonStrategyParams to set 
			the data.</li>
			<li>Create Standard Opening by defining required parameters. It is called 
			on Factory.</li>
			<li>Clear the current intermediate list. It will be populated again 
			with next two elements in next loop.</li>
		</ol>
		<pre class="code"><font color="#0000FF">Dim</font> StdOpening <font color="#0000FF">As</font> SfmStandardOpening
<font color="#0000FF">Dim</font> URefListint <font color="#0000FF">As</font> SfmReferences
<font color="#0000FF">Set</font> URefListint = Factory.SfmReferences

<font color="#0000FF">For</font> nUrefCnt = 1 <font color="#0000FF">To</font> NbofURef Step 2
    <font color="#0000FF">If</font> (nUrefCnt + 1) $lt;= NbofURef <font color="#0000FF">Then</font>
       URefListint.Add UrefList.Item (nUrefCnt)
       URefListint.Add UrefList.Item (nUrefCnt + 1)
       PositionStrategyParms.SetPosParamData &quot;CATSfmPosMidDistMidDist&quot;, 20, URefListint, 1, VrefList, 2
       <font color="#0000FF">Set</font> StdOpening = Factory.CreateStandardOpening (&quot;FunctionalOpening&quot;, &quot;Sfm_Rect&quot;, oListCkeParms,     &quot;CATSfmPosMidDistMidDist&quot;, PositionStrategyParms, plateref)
     URefListint.ClearList
  <font color="#0000FF">End If</font>
<font color="#0000FF">Next</font>

Part1.Update</pre>
		<p><strong>Note</strong>: Scripts for creation of Standard Openings using 
		other positioning Strategies are also provided:</p>
		<ul>
			<li>CAASddHalfHeight_MidDist.CATScript</li>
			<li>CAASddHalfHeight_Offset.CATScript</li>
			<li>CAASddMidDist_Offset.CATScript</li>
			<li>CAASddOffset_Offset.CATScript</li>
		</ul>
		</td>
	</tr>
	<tr>
		<td>&nbsp;</td>
		<td align="center">
		<img alt="End Icon" src="../CAAScrBase/images/aendtask.gif" width="64" height="32"></td>
	</tr>
</table>
<p align="right">[<a href="#Top">Top</a>]</p>
<hr>
<!---------------------------------comment----------------------------------->
<h4><a name="InShort"></a>In Short</h4>
<p>This use case has shown how to create standard openings using the MidDist-MidDist 
strategy.</p>
<p align="right">[<a href="#Top">Top</a>]</p>
<hr>
<!---------------------------------comment----------------------------------->
<h4><a name="References"></a>References</h4>
<table border="0" width="100%">
	<tr>
		<td valign="top">[1]</td>
		<td><a href="../CAAScdInfUseCases/CAAInfLauchMacro.htm">Replaying 
		a Macro</a></td>
	</tr>
	<tr>
		<td valign="top"></td>
		<td></td>
	</tr>
	<tr>
		<td colspan="2" align="right">[<a href="#Top">Top</a>]</td>
	</tr>
</table>
<hr>
<!---------------------------------comment----------------------------------->
<p><i>Copyright © 2010, Dassault Systèmes. All rights reserved.</i></p>

</body>

</html>
