<html>

<head>
<meta http-equiv="Content-Language" content="en">
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<meta name="GENERATOR" content="Microsoft FrontPage 12.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
<title>CAASddCreateOpening.CATScript</title>
<link rel="stylesheet" type="text/css" href="../CAAScrBase/caav5.css">
</head>

<body>
<pre>
<font color="#0000FF">Option Explicit</font>
Language=&quot;VBSCRIPT&quot;
<font color="#008000">' COPYRIGHT DASSAULT SYSTEMES 2010</font>

<font color="#008000">' *****************************************************************************</font>
<font color="#008000">'   Purpose:      Edit standard openings on an SDD Plate.</font>
<font color="#008000">'   Languages:    VBScript</font>
<font color="#008000">'   Locales:      English </font>
<font color="#008000">'   CATIA Level:  V5R21 </font>
<font color="#008000">' *****************************************************************************</font>

<font color="#0000FF">Sub</font> CATMain()

  <font color="#0000FF">Set</font> documents1 = CATIA.Documents
  <font color="#0000FF">Set</font> PartDocument1 = documents1.Item(&quot;Design_Unit_002.CATPart&quot;)
  <font color="#0000FF">Set</font> Part1 = PartDocument1.Part
  <font color="#0000FF">Set</font> plate = Part1.FindObjectByName(&quot;Deck_002&quot;)
  <font color="#0000FF">Set</font> plateref = Part1.CreateReferenceFromObject(plate)
  <font color="#0000FF">Dim</font> Factory <font color="#0000FF">As</font> SfmFunctionFactory
  <font color="#0000FF">Set</font> Factory = Part1.GetCustomerFactory(&quot;SfmFunctionFactory&quot;)

  <font color="#0000FF">Dim</font> ObjSfmContourMgr <font color="#0000FF">As</font> SfmOpeningContoursMgr
  <font color="#0000FF">Set</font> ObjSfmContourMgr = Factory.GetOpeningMgr(Part1, &quot;SfmOpeningContoursMgr&quot;)

  <font color="#0000FF">Dim</font> ObjSfmPosStrategyMgr <font color="#0000FF">As</font> SfmPositioningStrategyManager
  <font color="#0000FF">Set</font> ObjSfmPosStrategyMgr = Factory.GetOpeningMgr(Part1, &quot;SfmPositioningStrategyManager&quot;)


  <font color="#008800">'Prepare a List of U &amp; V Reference</font>
  <font color="#0000FF">Dim</font> UrefList <font color="#0000FF">As</font> SfmReferences
  <font color="#0000FF">Dim</font> Uref1 <font color="#0000FF">As</font> Reference
  <font color="#0000FF">Set</font> Uref1 = Part1.FindObjectByName(&quot;CROSS.95&quot;)
  <font color="#0000FF">Set</font> Uref2 = Part1.FindObjectByName(&quot;CROSS.50&quot;)
  <font color="#0000FF">Set</font> Uref3 = Part1.FindObjectByName(&quot;CROSS.25&quot;)
  <font color="#0000FF">Set</font> Uref4 = Part1.FindObjectByName(&quot;CROSS.40&quot;)
  <font color="#0000FF">Set</font> UrefList = Factory.SfmReferences
  UrefList.Add Uref1
  UrefList.Add Uref2
  UrefList.Add Uref3
  UrefList.Add Uref4

  <font color="#0000FF">Dim</font> VrefList <font color="#0000FF">As</font> SfmReferences
  <font color="#0000FF">Dim</font> Vref1 <font color="#0000FF">As</font> Reference
  <font color="#0000FF">Set</font> Vref1 = Part1.FindObjectByName(&quot;LONG.0&quot;)
  <font color="#0000FF">Set</font> VrefList = Factory.SfmReferences
  VrefList.Add Vref1


  <font color="#0000FF">Dim</font> NbofURef <font color="#0000FF">As</font> Long
  NbofURef = UrefList.Count

  <font color="#0000FF">Dim</font> NbofVRef <font color="#0000FF">As</font> Long
  NbofVRef = VrefList.Count

  <font color="#008800">'Define the Contour</font>

  <font color="#0000FF">Dim</font> oListContourNames() <font color="#0000FF">As</font> Variant
  ObjSfmContourMgr.GetAvailableStdOpeningContours oListContourNames
  <font color="#0000FF">Dim</font> NbOfContour <font color="#0000FF">As</font> Long
  NbOfContour = UBound(oListContourNames)
  <font color="#008800">'Display List of contours
  'For i = 0 To NbOfContour
  'MsgBox oListContourNames(i)
  'Next</font>

  <font color="#008800">'Select Contour from List</font>
  <font color="#0000FF">Dim</font> oListCkeParms <font color="#0000FF">As</font> SfmStandardContourParameters
  <font color="#0000FF">Set</font> oListCkeParms = ObjSfmContourMgr.GetStdOpeningContourParams(&quot;Sfm_Rect&quot;)
  <font color="#008800">'Display List of Parameters for Selected Contour</font>
  <font color="#0000FF">Dim</font> NbOfParam <font color="#0000FF">As</font> Long
  NbOfParam = oListCkeParms.Count
  <font color="#0000FF">Dim</font> ContourParam <font color="#0000FF">As</font> Parameter
  <font color="#0000FF">Dim</font> ContourParamName <font color="#0000FF">As</font> String
  <font color="#0000FF">For</font> i = 1<font color="#0000FF"> To</font> NbOfParam
    <font color="#0000FF">Set</font> ContourParam = oListCkeParms.Item(i)
    ContourParamName = oListCkeParms.Item(i).Name
    <font color="#008800">'MsgBox ContourParamName</font>
    <font color="#008800">'Set Contour Parameter Values</font>
    <font color="#0000FF">If</font> ContourParamName = &quot;Sfm_Width&quot; <font color="#0000FF">Then</font>
      ContourParam.ValuateFromString (&quot;1000mm&quot;)
    <font color="#0000FF">End If</font>
    <font color="#0000FF">If</font> ContourParamName = &quot;Sfm_Height&quot; <font color="#0000FF">Then</font>
      ContourParam.ValuateFromString (&quot;2000mm&quot;)
    <font color="#0000FF">End If</font>
    <font color="#0000FF">If</font> ContourParamName = &quot;Sfm_CornerRadius&quot; <font color="#0000FF">Then</font>
      ContourParam.ValuateFromString (&quot;10mm&quot;)
    <font color="#0000FF">End If</font>
  <font color="#0000FF">Next</font>

  <font color="#008800">'Define The Postition Strategy</font>

  <font color="#0000FF">Dim</font> PositionStrategyParms <font color="#0000FF">As</font> SfmStandardPosStrategyParameters
  <font color="#0000FF">Set</font> PositionStrategyParms = ObjSfmPosStrategyMgr.GetPositioningStrategyParams(&quot;CATSfmPosOffsetOffset&quot;)


  <font color="#0000FF">Dim</font> StdOpening <font color="#0000FF">As</font> SfmStandardOpening

  <font color="#0000FF">Dim</font> URefListint <font color="#0000FF">As</font> SfmReferences
  <font color="#0000FF">Set</font> URefListint = Factory.SfmReferences

  <font color="#0000FF">For</font> nUrefCnt = 1 <font color="#0000FF">To</font> NbofURef
    URefListint.Add UrefList.Item(nUrefCnt)
    PositionStrategyParms.SetPosParamData &quot;CATSfmPosOffsetOffset&quot;, 20, URefListint, 1, VrefList, 2
    <font color="#0000FF">Set</font> StdOpening = Factory.CreateStandardOpening(&quot;FunctionalOpening&quot;, &quot;Sfm_Rect&quot;, oListCkeParms, &quot;CATSfmPosOffsetOffset&quot;, PositionStrategyParms, plateref)
    URefListint.ClearList
    Part1.Update
  <font color="#0000FF">Next</font>

<font color="#0000FF">End Sub</font>
</pre>

</body>

</html>
