<html>

<head>
<meta http-equiv="Content-Language" content="en">
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<meta name="GENERATOR" content="Microsoft FrontPage 12.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
<title>CAASddCreateOpening.CATScript</title>
<link rel="stylesheet" type="text/css" href="../CAAScrBase/caav5.css">
</head>

<body>
<pre>
<font color="#0000FF">Option Explicit</font>
Language=&quot;VBSCRIPT&quot;
<font color="#008000">' COPYRIGHT DASSAULT SYSTEMES 2010</font>

<font color="#008000">' *****************************************************************************</font>
<font color="#008000">'   Purpose:      Create openings on an SDD Plate.</font>
<font color="#008000">'   Languages:    VBScript</font>
<font color="#008000">'   Locales:      English </font>
<font color="#008000">'   CATIA Level:  V5R21 </font>
<font color="#008000">' *****************************************************************************</font>

<font color="#0000FF">Sub</font> CATMain() 

  <font color="#0000FF">Set</font> documents1 = CATIA.Documents
  <font color="#0000FF">Set</font> partDocument1 = documents1.Item(&quot;Design_Unit_004.CATPart&quot;)
  <font color="#0000FF">Set</font> part1 = partDocument1.Part
  <font color="#0000FF">Set</font> plate= part1.FindObjectByName(&quot;Deck_005&quot;)
  <font color="#0000FF">Set</font> plateref=part1.CreateReferenceFromObject(plate)

  <font color="#008000">'Create Opening Using Sketch Mode</font>
  <font color="#0000FF">Set</font> sketch= part1.FindObjectByName(&quot;Sketch.19&quot;)
  <font color="#0000FF">Set</font> sketchref=part1.CreateReferenceFromObject(sketch)
  <font color="#0000FF">Set</font> Factory = part1.GetCustomerFactory(&quot;SfmFunctionFactory&quot;)
  <font color="#0000FF">Set</font> OpeningUsingSketch=Factory.CreateOpening(&quot;FunctionalOpening&quot;,1,sketchref, plateref) part1.Update

  <font color="#008000">'Create Opening Using 3D Object Mode</font>
  <font color="#0000FF">Set</font> Object = part1.FindObjectByName(&quot;Volume Extrude.1&quot;)
  <font color="#0000FF">Set</font> ObjectRef = part1.CreateReferenceFromObject(Object)
  <font color="#0000FF">Set</font> OpeningUsing3DObj = Factory.CreateOpening(&quot;FunctionalOpening&quot;,0,ObjectRef, plateref) part1.Update

<font color="#0000FF">End Sub</font>
</pre>

</body>

</html>
