<html>

<head>
<meta http-equiv="Content-Language" content="en">
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<meta name="GENERATOR" content="Microsoft FrontPage 12.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
<title>Modifying Standard Openings</title>
<link rel="stylesheet" type="text/css" href="../CAAScrBase/caav5.css">
<script type="text/javascript" src="../CAAScrJavaScript/submit.js"></script>
</head>

<body>

<table border="0" width="100%">
	<tr>
		<td>
		<h2>Structure Function Design Modeler</h2>
		</td>
		<td align="right" valign="top">
		<h2><a name="Top"></a>Modifying Standard Openings</h2>
		</td>
	</tr>
</table>
<hr>
<!---------------------------------comment----------------------------------->
<table border="0" width="100%">
	<tr>
		<td width="7%" valign="top">
		<img alt="Target Icon" src="../CAAScrBase/images/atarget.gif" width="32" height="32"></td>
		<td width="93%"><a name="Learn"></a>This macro shows you how to edit existing 
		standard opening on an SDD plate. Here the macro will first create several 
		standard Openings using Offset-Offset Strategy. The same macro will then 
		edit the last created standard Opening, by modifying its contour parameters, 
		offsets from references etc
		<p>
		<img alt="Starting Part" src="images/CAASdd005.png" width="559" height="195"></p>
		</td>
	</tr>
	<tr>
		<td width="7%" valign="top">
		<img alt="Information Icon" src="../CAAScrBase/images/ainfo.gif" width="32" height="32"></td>
		<td width="93%"><a name="How"></a>
		<a name="How" href="macros/CAASddOffset_Offset.CATScript">CAASddOffset_Offset</a> 
		is launched in CATIA [<a href="#References">1</a>]. Some documents are needed.
		<ul>
			<li><a href="CAASddEditStdOpeningSource.htm">CAASddOffset_Offset.CATScript</a> 
			is located in the CAAScdSddUseCases module.
			<a href="macros/CAASddOffset_Offset.CATScript">Execute macro</a> (Windows 
			only).</li>
			<li>The document Product1.CATProduct is located in the CAAScdSddUseCases 
			module in the samples directory. Design_Unit_002.CATPart is linked to 
			the previous document and it contains data required for the macro.</li>
			<li>The CATPart containing the section is located in the samples directory.</li>
		</ul>
		</td>
	</tr>
	<tr>
		<td width="7%" valign="top">
		<img border="0" src="../CAAScrBase/images/ascenari.gif" width="32" height="32"></td>
		<td width="93%"><a name="Step"></a>CAASddOffset_Offset includes six steps:<ol>
			<li><a href="#Step1">Prolog</a></li>
			<li><a href="#Step2">Prepare U and V References List</a></li>
			<li><a href="#Step3">Define Contour Parameters</a></li>
			<li><a href="#Step4">Define Position Strategy and Create Standard Opening</a></li>
			<li><a href="#Step5">Edit Contour Parameters and Redefine Them</a></li>
			<li><a href="#Step6">Edit Position Parameter Data</a></li>
		</ol>
		<!---------------------------------comment----------------------------------->
		<h4><a name="Step1"></a>Prolog</h4>
		<pre class="code"><font color="#0000FF">Set</font> documents1 = CATIA.Documents
<font color="#0000FF">Set</font> PartDocument1 = documents1.Item(&quot;Design_Unit_002.CATPart&quot;)
<font color="#0000FF">Set</font> Part1 = PartDocument1.Part
<font color="#0000FF">Set</font> plate = Part1.FindObjectByName(&quot;Deck_002&quot;)
<font color="#0000FF">Set</font> plateref = Part1.CreateReferenceFromObject(plate)

<font color="#008800">&#39;Get the Factory and Managers</font>

<font color="#0000FF">Dim</font> Factory <font color="#0000FF">As</font> SfmFunctionFactory
<font color="#0000FF">Set</font> Factory = Part1.GetCustomerFactory(&quot;SfmFunctionFactory&quot;)

<font color="#0000FF">Dim</font> ObjSfmContourMgr <font color="#0000FF">As</font> SfmOpeningContoursMgr
<font color="#0000FF">Set</font> ObjSfmContourMgr = Factory.GetOpeningMgr(Part1, &quot;SfmOpeningContoursMgr&quot;)
 
<font color="#0000FF">Dim</font> ObjSfmPosStrategyMgr <font color="#0000FF">As</font> SfmPositioningStrategyManager
<font color="#0000FF">Set</font> ObjSfmPosStrategyMgr = Factory.GetOpeningMgr(Part1,&quot;SfmPositioningStrategyManager&quot;)</pre>
		<!---------------------------------comment----------------------------------->
		<h4><a name="Step2"></a>Prepare U and V References List</h4>
		<pre class="code"><font color="#008800">&#39;Prepare a List of U &amp; V Reference</font>
 <font color="#0000FF">Dim</font> UrefList <font color="#0000FF">As</font> SfmReferences
 <font color="#0000FF">Dim</font> Uref1 <font color="#0000FF">As</font> Reference
 <font color="#0000FF">Set</font> Uref1 = Part1.FindObjectByName(&quot;CROSS.95&quot;)
 <font color="#0000FF">Set</font> Uref2 = Part1.FindObjectByName(&quot;CROSS.50&quot;)
 <font color="#0000FF">Set</font> Uref3 = Part1.FindObjectByName(&quot;CROSS.25&quot;)
 <font color="#0000FF">Set</font> Uref4 = Part1.FindObjectByName(&quot;CROSS.40&quot;)
 <font color="#0000FF">Set</font> UrefList = Factory.SfmReferences
 UrefList.Add Uref1
 UrefList.Add Uref2
 UrefList.Add Uref3
 UrefList.Add Uref4
 
 <font color="#0000FF">Dim</font> VrefList <font color="#0000FF">As</font> SfmReferences
 <font color="#0000FF">Dim</font> Vref1 <font color="#0000FF">As</font> Reference
 <font color="#0000FF">Set</font> Vref1 = Part1.FindObjectByName(&quot;LONG.0&quot;)
 <font color="#0000FF">Set</font> VrefList = Factory.SfmReferences
 VrefList.Add Vref1

 
 <font color="#0000FF">Dim</font> NbofURef <font color="#0000FF">As</font> Long
 NbofURef = UrefList.Count
 
 <font color="#0000FF">Dim</font> NbofVRef <font color="#0000FF">As</font> Long
 NbofVRef = VrefList.Count</pre>
		<!---------------------------------comment----------------------------------->
		<h4><a name="Step3"></a>Define Contour Parameters</h4>
		<pre class="code"><font color="#008800">&#39;Define the Contour</font>
 <font color="#0000FF">Dim</font> oListContourNames() <font color="#0000FF">As</font> Variant
 ObjSfmContourMgr.GetAvailableStdOpeningContours oListContourNames
 <font color="#0000FF">Dim</font> NbOfContour <font color="#0000FF">As</font> Long
 NbOfContour = UBound(oListContourNames)

 <font color="#008800">&#39;Select Contour from List</font>
 <font color="#0000FF">Dim</font> oListCkeParms <font color="#0000FF">As</font> SfmStandardContourParameters
 <font color="#0000FF">Set</font> oListCkeParms = ObjSfmContourMgr.GetStdOpeningContourParams(&quot;Sfm_Rect&quot;)

<font color="#008800">&#39;Display List of Parameters for Selected Contour</font>
 <font color="#0000FF">Dim</font> NbOfParam <font color="#0000FF">As</font> Long
 NbOfParam = oListCkeParms.Count
 <font color="#0000FF">Dim</font> ContourParam <font color="#0000FF">As</font> Parameter
 <font color="#0000FF">Dim</font> ContourParamName <font color="#0000FF">As</font> String
 <font color="#0000FF">For</font> i = 1 <font color="#0000FF">To</font> NbOfParam
  <font color="#0000FF">Set</font> ContourParam = oListCkeParms.Item(i)
  ContourParamName = oListCkeParms.Item(i).Name

<font color="#008800">&#39;Set Contour Parameter Values</font>
  <font color="#0000FF">If</font> ContourParamName = &quot;Sfm_Width&quot; <font color="#0000FF">Then</font>
    ContourParam.ValuateFromString (&quot;1500mm&quot;)
    <font color="#0000FF">End If</font>
  <font color="#0000FF">If</font> ContourParamName = &quot;Sfm_Height&quot; <font color="#0000FF">Then</font>
    ContourParam.ValuateFromString (&quot;2000mm&quot;)
     <font color="#0000FF">End If</font>
  <font color="#0000FF">If</font> ContourParamName = &quot;Sfm_CornerRadius&quot; <font color="#0000FF">Then</font>
    ContourParam.ValuateFromString (&quot;10mm&quot;)
     <font color="#0000FF">End If</font>
 <font color="#0000FF">Next</font></pre>
		<!---------------------------------comment----------------------------------->
		<h4><a name="Step4"></a>Define Position Strategy and Create Standard Opening</h4>
		<pre class="code"><font color="#008800">&#39;Define the Position Strategy</font>

<font color="#0000FF">Dim</font> PositionStrategyParms <font color="#0000FF">As</font> SfmStandardPosStrategyParameters
<font color="#0000FF">Set</font> PositionStrategyParms = ObjSfmPosStrategyMgr.GetPositioningStrategyParams(&quot;CATSfmPosOffsetOffset&quot;)


<font color="#0000FF">Dim</font> StdOpening <font color="#0000FF">As</font> SfmStandardOpening

<font color="#0000FF">Dim</font> URefListint <font color="#0000FF">As</font> SfmReferences
<font color="#0000FF">Set</font> URefListint = Factory.SfmReferences

<font color="#0000FF">For</font> nUrefCnt = 1 <font color="#0000FF">To</font> NbofURef
     URefListint.Add UrefList.Item(nUrefCnt)
     PositionStrategyParms.SetPosParamData &quot;CATSfmPosOffsetOffset&quot;, 20, URefListint, 1, VrefList, 2
     <font color="#0000FF">Set</font> StdOpening = Factory.CreateStandardOpening(&quot;FunctionalOpening&quot;, &quot;Sfm_Rect&quot;, oListCkeParms, &quot;CATSfmPosOffsetOffset&quot;, PositionStrategyParms, plateref)
     URefListint.ClearList
     Part1.Update
     
<font color="#0000FF">Next</font></pre>
		<!---------------------------------comment----------------------------------->
		<h4><a name="Step5"></a>Edit Contour Parameters and Redefine Them</h4>
		<ol>
			<li>StdOpening in the last step will have information related to last 
			standard opening created.</li>
			<li>On this last opening, use method &#8220;GetContour&#8221; to get the Contour 
			Parameter name and it&#8217;s corresponding value.</li>
			<li>Run a for loop, and modify the corresponding contour parameters.</li>
			<li>In this case, we have set &#8220;sfm_Rect&#8221; as contour, which has three 
			parameters. The FOR loop will run for three times and will now take 
			new values, that are set.</li>
		</ol>
		<pre class="code"><font color="#0000FF">Dim</font> GetName <font color="#0000FF">As</font> String
<font color="#0000FF">Dim</font> GetParam <font color="#0000FF">As</font> SfmStandardContourParameters

&#8216;Use GetContour Method on stdOpening to get Contour Params for last Opening
StdOpening.GetContour GetName, GetParam

<font color="#0000FF">Dim</font> Nb <font color="#0000FF">As</font> Long
Nb = GetParam.Count

<font color="#0000FF">Dim</font> ParamName1 <font color="#0000FF">As</font> String
<font color="#0000FF">Dim</font> ParamValue1 <font color="#0000FF">As</font> Parameter


<font color="#0000FF">For</font> i = 1 <font color="#0000FF">To</font> Nb
<font color="#0000FF">Set</font> ParamValue1 = GetParam.Item(i)
ParamName1 = ParamValue1.Name


<font color="#0000FF">If</font> ParamName1 = &quot;Sfm_Width&quot; <font color="#0000FF">Then</font>
    ParamValue1.ValuateFromString (&quot;1000mm&quot;)
    <font color="#0000FF">End If</font>
  <font color="#0000FF">If</font> ParamName1 = &quot;Sfm_Height&quot; <font color="#0000FF">Then</font>
    ParamValue1.ValuateFromString (&quot;1000mm&quot;)
     <font color="#0000FF">End If</font>
  <font color="#0000FF">If</font> ParamName1 = &quot;Sfm_CornerRadius&quot; <font color="#0000FF">Then</font>
    ParamValue1.ValuateFromString (&quot;25mm&quot;)
     <font color="#0000FF">End If</font>
 <font color="#0000FF">Next</font></pre>
		<!---------------------------------comment----------------------------------->
		<h4><a name="Step6"></a>Edit Position Parameter Data</h4>
		<ol>
			<li>StdOpening will have information related to last standard opening 
			created.</li>
			<li>On this last opening, use method &#8220;GetPositioningStrategy&#8221; to get 
			the StrategyName and StrategyParms.</li>
			<li>Create an intermediate list for URefListint1.</li>
			<li>Add to this list new cross plane CROSS.70, which will replace CROSS.40.</li>
			<li>Set the &#8220;SetPosParamData&#8221; on StarategyParams with new URef, modified 
			angle, U offset and V offset values. Re-Generate the Standard Opening.</li>
		</ol>
		<pre class="code"><font color="#0000FF">Dim</font> pName <font color="#0000FF">As</font> String
<font color="#0000FF">Dim</font> pStrategyParams <font color="#0000FF">As</font> SfmStandardPosStrategyParameters

&#8216;Get the Current Strategy Name and StrategyParams using GetPositioningStrategy
StdOpening.GetPositioningStrategy pName, pStrategyParams

<font color="#0000FF">Dim</font> UrefNew <font color="#0000FF">As</font> Reference
Set UrefNew = Part1.FindObjectByName(&quot;CROSS.70&quot;)

<font color="#0000FF">Dim</font> URefListint1 <font color="#0000FF">As</font> SfmReferences
Set URefListint1 = Factory.SfmReferences
URefListint1.Add UrefNew 

pStrategyParams.SetPosParamData &quot;CATSfmPosOffsetOffset&quot;, 40, URefListint1, 25, VrefList, 30

StdOpening.SetPositioningStrategy pName, pStrategyParams

part1.Update</pre>
		</td>
	</tr>
	<tr>
		<td>&nbsp;</td>
		<td align="center">
		<img alt="End Icon" src="../CAAScrBase/images/aendtask.gif" width="64" height="32"></td>
	</tr>
</table>
<p align="right">[<a href="#Top">Top</a>]</p>
<hr>
<!---------------------------------comment----------------------------------->
<h4><a name="InShort"></a>In Short</h4>
<p>This use case has shown how to edit standard openings.</p>
<p align="right">[<a href="#Top">Top</a>]</p>
<hr>
<!---------------------------------comment----------------------------------->
<h4><a name="References"></a>References</h4>
<table border="0" width="100%">
	<tr>
		<td valign="top">[1]</td>
		<td><a href="../CAAScdInfUseCases/CAAInfLauchMacro.htm">Replaying 
		a Macro</a></td>
	</tr>
	<tr>
		<td valign="top"></td>
		<td></td>
	</tr>
	<tr>
		<td colspan="2" align="right">[<a href="#Top">Top</a>]</td>
	</tr>
</table>
<hr>
<!---------------------------------comment----------------------------------->
<p><i>Copyright © 2010, Dassault Systèmes. All rights reserved.</i></p>

</body>

</html>
