<html><head><meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"><title>CAAAsmCstOnPublish.CATScript</title><link rel="stylesheet" type="text/css" href="../CAAScrBase/caav5.css"></head><body><pre>
<font color="#0000FF">Option Explicit</font>
<font color="#008000">' COPYRIGTH DASSAULT SYSTEMES 2001</font>

<font color="#008000">' ***********************************************************************</font>
<font color="#008000">'   Purpose:      Creates constraints between assembly Parts using Publications</font>
<font color="#008000">'   Assumtions:   Looks for CstOnProduct.CATProduct in the DocView   </font>
<font color="#008000">'   Author: </font>
<font color="#008000">'   Languages:    VBScript</font>
<font color="#008000">'   Locales:      English </font>
<font color="#008000">'   CATIA Level:  V5R6 </font>
<font color="#008000">' ***********************************************************************</font>


<font color="#0000FF">Sub </font>CATMain()


    <font color="#008000">' ----------------------------------------------------------- </font>
    <font color="#008000">' Optional: allows to find the sample wherever it's installed</font>
<font color="#0000FF">    dim </font>sDocPath<font color="#0000FF"> As </font>String 
    sDocPath=CATIA.SystemService.Environ("CATDocView")
<font color="#0000FF">    If </font>(Not CATIA.FileSystem.FolderExists(sDocPath))<font color="#0000FF"> Then</font>
      Err.Raise 9999,,"No Doc Path Defined"
<font color="#0000FF">    End If</font>
    <font color="#008000">' ----------------------------------------------------------- </font>

    <font color="#008000">' Open the Product document </font>
<font color="#0000FF">    Dim </font>sFilePath
    sFilePath = CATIA.FileSystem.ConcatenatePaths(sDocPath, _
                 "online\CAAScdAsmUseCases\samples\CstOnPublish.CATProduct")

<font color="#0000FF">    Dim </font>oDoc<font color="#0000FF"> As </font>Document
<font color="#0000FF">    set </font>oDoc = CATIA.Documents.Open(sFilePath)

<font color="#008000">'</font>
<font color="#008000">' --------------------------</font>
<font color="#008000">' Get the different products</font>
<font color="#008000">' --------------------------</font>
<font color="#0000FF">Dim </font>oRootProduct<font color="#0000FF"> As </font>Product
<font color="#0000FF">Set </font>oRootProduct=CATIA.ActiveDocument.Product

<font color="#0000FF">Dim </font>oPlate<font color="#0000FF"> As </font>Product
<font color="#0000FF">Set </font>oPlate = CATIA.ActiveDocument.Product.Products.Item  ( "Plate.1" ) 

<font color="#0000FF">Dim </font>oScrew1<font color="#0000FF"> As </font>Product
<font color="#0000FF">Set </font>oScrew1 = CATIA.ActiveDocument.Product.Products.Item  ( "Screw.1" ) 

<font color="#0000FF">Dim </font>oScrew2<font color="#0000FF"> As </font>Product
<font color="#0000FF">Set </font>oScrew2 = CATIA.ActiveDocument.Product.Products.Item  ( "Screw.2" ) 

<font color="#008000">' --------------------------------------</font>
<font color="#008000">' Declare variables to handle publications</font>
<font color="#008000">' --------------------------------------</font>
<font color="#0000FF">Dim </font>oPlatePub<font color="#0000FF"> As </font>Publication
<font color="#0000FF">Dim </font>oPlateRef<font color="#0000FF"> As </font>Reference

<font color="#0000FF">Dim </font>oScrewPub<font color="#0000FF"> As </font>Publication
<font color="#0000FF">Dim </font>oScrewRef<font color="#0000FF"> As </font>Reference

<font color="#008000">' --------------------------------------</font>
<font color="#008000">' Get the Constraints collection </font>
<font color="#008000">' --------------------------------------</font>
<font color="#0000FF">Dim </font>oConstraints0<font color="#0000FF"> As </font>Collection
<font color="#0000FF">Set </font>oConstraints0 = oRootProduct.Connections  ( "CATIAConstraints" ) 

<font color="#008000">' --------------------------------------</font>
<font color="#008000">' Create offset constraint between plate  </font>
<font color="#008000">' top face and screws heads bottom faces</font>
<font color="#008000">' --------------------------------------</font>
<font color="#0000FF">set </font>oPlatePub = oPlate.Publications.Item("Top")
<font color="#0000FF">Set </font>oPlateRef = oPlatePub.Valuation

<font color="#008000">'  ---&gt; Plate\Top Screw1\HeadBottom </font>

<font color="#0000FF">Set </font>oScrewPub = oScrew1.Publications.Item("HeadBottom")
<font color="#0000FF">Set </font>oScrewRef = oScrewPub.Valuation

<font color="#0000FF">Dim </font>oConstraint1<font color="#0000FF"> As </font>Constraint
<font color="#0000FF">Set </font>oConstraint1 = oConstraints0.AddBiEltCst  ( catCstTypeDistance, oPlateRef, oScrewRef ) 

oConstraint1.Dimension.Value = 2.000000
oConstraint1.Orientation = CATCstOrientOpposite

<font color="#008000">'  ---&gt; Plate\Top Screw2\HeadBottom </font>

<font color="#0000FF">Set </font>oScrewPub = oScrew2.Publications.Item("HeadBottom")
<font color="#0000FF">Set </font>oScrewRef = oScrewPub.Valuation

<font color="#0000FF">Dim </font>oConstraint2<font color="#0000FF"> As </font>Constraint
<font color="#0000FF">Set </font>oConstraint2 = oConstraints0.AddBiEltCst  ( catCstTypeDistance, oPlateRef, oScrewRef ) 

oConstraint2.Dimension.Value = 2.000000
oConstraint2.Orientation = CATCstOrientOpposite

<font color="#008000">' --------------------------------------------</font>
<font color="#008000">' Create offset constraint between plate  </font>
<font color="#008000">' holes positioning points and screws axis</font>
<font color="#008000">' --------------------------------------------</font>

<font color="#008000">'  ---&gt; Plate\Hole1 Screw1\Axis </font>

<font color="#0000FF">set </font>oPlatePub = oPlate.Publications.Item("Hole1")
<font color="#0000FF">Set </font>oPlateRef = oPlatePub.Valuation

<font color="#0000FF">Set </font>oScrewPub = oScrew1.Publications.Item("Axis")
<font color="#0000FF">Set </font>oScrewRef = oScrewPub.Valuation

<font color="#0000FF">Dim </font>oConstraint3<font color="#0000FF"> As </font>Constraint
<font color="#0000FF">Set </font>oConstraint3 = oConstraints0.AddBiEltCst(catCstTypeOn, oPlateRef, oScrewRef )

<font color="#008000">'  ---&gt; Plate\Hole2 Screw2\Axis </font>

<font color="#0000FF">set </font>oPlatePub = oPlate.Publications.Item("Hole2")
<font color="#0000FF">Set </font>oPlateRef = oPlatePub.Valuation

<font color="#0000FF">Set </font>oScrewPub = oScrew2.Publications.Item("Axis")
<font color="#0000FF">Set </font>oScrewRef = oScrewPub.Valuation

<font color="#0000FF">Dim </font>oConstraint4<font color="#0000FF"> As </font>Constraint
<font color="#0000FF">Set </font>oConstraint4 = oConstraints0.AddBiEltCst(catCstTypeOn, oPlateRef, oScrewRef )


<font color="#008000">' --------------------------------------</font>
<font color="#008000">' Update the Product ..</font>
<font color="#008000">' --------------------------------------</font>
oRootProduct.Update 

MsgBox "Click OK to replace the screw by another standard screw ..."

<font color="#008000">' --------------------------------------</font>
<font color="#008000">' Replace the screw by another one: constraints on </font>
<font color="#008000">' published elements are autoatically reconnected ...</font>
<font color="#008000">' --------------------------------------</font>
<font color="#0000FF">Set </font>oScrew1 = CATIA.ActiveDocument.Product.Products.ReplaceComponent ( _
      oScrew1,                                                         _
      sDocPath & "\online\CAAScdAsmUseCases\samples\NewScrew.CATPart", _
      True)

<font color="#008000">' --------------------------------------</font>
<font color="#008000">' Update the Product with the new Parts</font>
<font color="#008000">' --------------------------------------</font>
oRootProduct.Update 

<font color="#0000FF">End Sub</font>
</pre></body></html>
