<html><head><meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"><title>CAAAsmCreateAssyHole.CATScript</title><link rel="stylesheet" type="text/css" href="../CAAScrBase/caav5.css"></head><body><pre>
<font color="#008000">' COPYRIGTH DASSAULT SYSTEMES 2004</font>
<font color="#0000FF">Option Explicit</font>

<font color="#008000">' ***********************************************************************</font>
<font color="#008000">'   Purpose:      Creates and modifies an assembly hole</font>
<font color="#008000">'   Assumtions:   Looks for AssemblyHole.CATProduct in the DocView   </font>
<font color="#008000">'   Languages:    VBSCRIPT</font>
<font color="#008000">'   Locales:      English </font>
<font color="#008000">'   CATIA Level:  V5R13</font>
<font color="#008000">' ***********************************************************************</font>


<font color="#0000FF">Sub </font>CATMain()


<font color="#008000">' ----------------------------------------------------------- </font>
<font color="#008000">' Optional: allows to find the sample wherever it's installed</font>
<font color="#008000">' ----------------------------------------------------------- </font>

<font color="#0000FF">dim </font>sDocPath<font color="#0000FF"> As </font>String 
sDocPath=CATIA.SystemService.Environ("CATDocView")

<font color="#0000FF">If </font>(Not CATIA.FileSystem.FolderExists(sDocPath))<font color="#0000FF"> Then</font>
  Err.Raise 9999,,"No Doc Path Defined"
<font color="#0000FF">End If</font>

<font color="#008000">' ----------------------------------------------------------- </font>
<font color="#008000">' Open the Product document </font>
<font color="#008000">' ----------------------------------------------------------- </font>

<font color="#0000FF">Dim </font>sFilePath
sFilePath = CATIA.FileSystem.ConcatenatePaths(sDocPath, _
            "online\CAAScdAsmUseCases\samples\AssemblyHole.CATProduct")

<font color="#0000FF">Dim </font>oDoc<font color="#0000FF"> As </font>Document
<font color="#0000FF">set </font>oDoc = CATIA.Documents.Open(sFilePath)

<font color="#008000">' --------------------------</font>
<font color="#008000">' Get the different products</font>
<font color="#008000">' --------------------------</font>

<font color="#0000FF">Dim </font>oRootProduct<font color="#0000FF"> As </font>Product
<font color="#0000FF">Set </font>oRootProduct = CATIA.ActiveDocument.Product

<font color="#0000FF">Dim </font>oSkeletton<font color="#0000FF"> As </font>Product
<font color="#0000FF">Set </font>oSkeletton = oRootProduct.Products.Item  ( "Skeletton.1" ) 

<font color="#0000FF">Dim </font>oPlaque1<font color="#0000FF"> As </font>Product
<font color="#0000FF">Set </font>oPlaque1 = oRootProduct.Products.Item  ( "Plaque1.1" ) 

<font color="#0000FF">Dim </font>oPlaque2<font color="#0000FF"> As </font>Product
<font color="#0000FF">Set </font>oPlaque2 = oRootProduct.Products.Item  ( "Plaque2.1" ) 

<font color="#008000">' -----------------------------------------</font>
<font color="#008000">' Get the positioning sketch to create hole </font>
<font color="#008000">' -----------------------------------------</font>

<font color="#0000FF">Dim </font>oSkelDocument<font color="#0000FF"> As </font>PartDocument
<font color="#0000FF">Set </font>oSkelDocument = CATIA.Documents.Item("Skeletton.CATPart")

<font color="#0000FF">Dim </font>oBody<font color="#0000FF"> As </font>Body
<font color="#0000FF">Set </font>oBody = oSkelDocument.Part.Bodies.Item("PartBody")

<font color="#0000FF">Dim </font>oPosSketch<font color="#0000FF"> As </font>Sketch
<font color="#0000FF">Set </font>oPosSketch = oBody.Sketches.Item("Positioning sketch for assembly hole")

<font color="#008000">' -----------------------------------------</font>
<font color="#008000">' Get the AssemblyFeatures technical object </font>
<font color="#008000">' -----------------------------------------</font>

<font color="#0000FF">Dim </font>oAssemblyFeatures<font color="#0000FF"> As </font>AssemblyFeatures
<font color="#0000FF">Set </font>oAssemblyFeatures = oRootProduct.GetTechnologicalObject("AssemblyFeatures")

<font color="#008000">' -------------------------------------------------------------</font>
<font color="#008000">' Create assembly hole</font>
<font color="#008000">'   positioning sketch : oPosSketch</font>
<font color="#008000">'   instance containing the positioning sketch : oSkeletton</font>
<font color="#008000">'   instance defining the positioning of the hole : oSkeletton</font>
<font color="#008000">'   depth : 10 mm</font>
<font color="#008000">' -------------------------------------------------------------</font>

<font color="#0000FF">Dim </font>oAssemblyHole<font color="#0000FF"> As </font>AssemblyHole
<font color="#0000FF">Set </font>oAssemblyHole = oAssemblyFeatures.AddAssemblyHole(oPosSketch, oSkeletton, 10.000000, oSkeletton)

<font color="#008000">' ------------------------------------------------------------</font>
<font color="#008000">' Affects parts to the assembly hole : Plaque1.1 and Plaque2.1</font>
<font color="#008000">' ------------------------------------------------------------</font>

oAssemblyHole.AddAffectedComponent oPlaque1
oAssemblyHole.AddAffectedComponent oPlaque2

<font color="#008000">' --------------------------------------------</font>
<font color="#008000">' modify the hole parameters</font>
<font color="#008000">'   - diameter 10 mm</font>
<font color="#008000">'   - counterbored</font>
<font color="#008000">'   - V-bottom</font>
<font color="#008000">'   - length</font>
<font color="#008000">' --------------------------------------------</font>

<font color="#0000FF">Dim </font>oDiameter<font color="#0000FF"> As </font>Length
<font color="#0000FF">Set </font>oDiameter = oAssemblyHole.Diameter
oDiameter.Value = 10.000000

oAssemblyHole.Type = catCounterboredHole
oAssemblyHole.AnchorMode = catExtremPointHoleAnchor

<font color="#0000FF">Dim </font>oHeadDiameter<font color="#0000FF"> As </font>Length
<font color="#0000FF">Set </font>oHeadDiameter = oAssemblyHole.HeadDiameter
oHeadDiameter.Value = 15.000000

<font color="#0000FF">Dim </font>oHeadDepth<font color="#0000FF"> As </font>Length
<font color="#0000FF">Set </font>oHeadDepth = oAssemblyHole.HeadDepth
oHeadDepth.Value = 5.000000

<font color="#0000FF">Dim </font>oBottomLimit<font color="#0000FF"> As </font>Limit
<font color="#0000FF">Set </font>oBottomLimit = oAssemblyHole.BottomLimit
oBottomLimit.LimitMode = catOffsetLimit

<font color="#0000FF">Dim </font>oDepth<font color="#0000FF"> As </font>Length
<font color="#0000FF">Set </font>oDepth = oBottomLimit.Dimension
oDepth.Value = 30.000000

oAssemblyHole.BottomType = catVHoleBottom

<font color="#0000FF">Dim </font>oBottomAngle<font color="#0000FF"> As </font>Angle
<font color="#0000FF">Set </font>oBottomAngle = oAssemblyHole.BottomAngle
oBottomAngle.Value = 120.000000

<font color="#008000">' --------------------------------------</font>
<font color="#008000">' Update the Product</font>
<font color="#008000">' --------------------------------------</font>

oRootProduct.Update 

<font color="#008000">' --------------------------------------</font>
<font color="#008000">' The end...</font>
<font color="#008000">' --------------------------------------</font>

<font color="#0000FF">End Sub</font>
</pre></body></html>
