<html>
<head>
 <meta name="Generator" content="mihGene v1.1">
 <meta http-equiv="Expires" content="Tue, 04 Dec 1993 21:29:02 GMT">
 <title>InfInterfaces Selection (Object)</title>
<link rel="Stylesheet" type="text/css" href="../../../caav5.css">
<script language="Javascript" src="../_index/jslink.js"></script> 
<script language="Javascript" src="jsFwLink.js"></script> 
<script language="Javascript" type="text/javascript" src="../_index/jsTree.js"></script>  
</head>
<body>
<pre><a href="../_index/main.htm">All Frameworks</a>  <a href="../_index/tree.htm">Object Hierarchy</a>  <a href="../InfInterfaces.htm">This Framework</a>  <a href="../_index/CAAHomeIdx.htm">Indexes</a>  <script type="text/javascript"> 
 var test=locateObject('Selection','interface','0'); 
 if(test==1){ 
     document.write("<a href=\"#\" onclick=\"openLinkNP('Selection','interface','0');return false\">Previous</a> "); 
 } 
 test=locateObject('Selection','interface','1'); 
 if(test==1){ 
     document.write("<a href=\"#\" onclick=\"openLinkNP('Selection','interface','1');return false\">Next</a> "); 
 } 
 </script> 
</pre>
<hr>
<h1>Selection<font size=-1> (Object)</font></h1>
<script type="text/javascript" > 
 generatedFatherClass('interface_Selection_15704','Selection','0');</script>
<b><i> Represents the selection.</i></b><br>

 The Selection object contains the features the end user selected, usually with the mouse, and which are
 candidates as subjects for the next action.</br></br>
 A feature possess parent objects in the specification tree (hierarchy). For example, the Pad below possess
 parent objects in the specification tree:
 <pre>
   +--------+ 
   !Product3!
   +--------+
       !
       +- Product2 (Product2.1)
       !     !
       !     +- Product1 (Product1.1)    
       !           !
       !           +- Part1 (Part1.1)       
       !                !
       !                +- Part1
       !                     !
       !                     +- PartBody
       !                           !                      +------------------+
       !                           +- Pad.1               ! Selected feature !
       !                                !                 +------------------+
       !                                +- Sketch.1 
       +- Part2 (Part2.1)
 </pre>
 For a given selected feature, its parent objects which are exposed to automation can be accessed through a
 recursive call to the <a href="#" onClick="openLink('AnyObject','Parent');return false">AnyObject.Parent</a> property. When a given feature is selected, there are three possibilities:
 <ul>
 <li>The feature is exposed to automation (a 
<a href="#" onClick="openLink('Pad','');return false">Pad</a> for example, <b>this is the common case</b>): the feature can be accessed by all Selection object methods</li>
 <li>The feature is not exposed to automation, but at least one of its parent objects is exposed to automation
 (a DMU Navigator URL for example: the Hyperlink is not exposed to automation, but the root Product, which
 contains the Hyperlink, is exposed to automation):
 <ul>
 <li>no access is given to the feature through the 
<a href="#" onClick="openLink('','Count2');return false">Count2</a> and 
<a href="#" onClick="openLink('','Item2');return false">Item2</a> methods of the Selection  object</li>
 <li>nevertheless, the first parent object of the feature, which is exposed to automation (the root Product in our
 example) can be accessed through the 
<a href="#" onClick="openLink('','Item2');return false">Item2</a> and 
<a href="#" onClick="openLink('','Count2');return false">Count2</a> methods</li> <li>The 
<a href="#" onClick="openLink('','Search');return false">Search</a>, 
<a href="#" onClick="openLink('','Delete');return false">Delete</a>, 
<a href="#" onClick="openLink('','VisProperties');return false">VisProperties</a>, 
<a href="#" onClick="openLink('','Copy');return false">Copy</a>, 
<a href="#" onClick="openLink('','Cut');return false">Cut</a>, 
<a href="#" onClick="openLink('','Paste');return false">Paste</a> and 
<a href="#" onClick="openLink('','PasteSpecial');return false">PasteSpecial</a> methods of the Selection object, take into account the feature.<br> For example, if the user:
 <ul>
 <li>Puts a DMU Navigator URL in the clipboard</li>
 <li>Runs a script calling the PasteSpecial method</li>
 </ul>
 then, during the paste, the DMU Navigator URL will be pasted</li></ul>
 </li>
 <li>The feature is not exposed to automation, and he has no parent object which is exposed to automation (a
 ResourcesList object of a .CATProcess for example):
 <ul>
 <li>no access is given to the feature through the 
<a href="#" onClick="openLink('','Count2');return false">Count2</a> and 
<a href="#" onClick="openLink('','Item2');return false">Item2</a> methods of the Selection object</li>
 <li>no access is given neither to any parent object of the feature through the 
<a href="#" onClick="openLink('','Item2');return false">Item2</a> and 
<a href="#" onClick="openLink('','Count2');return false">Count2</a> methods</li>
 <li>The 
<a href="#" onClick="openLink('','Search');return false">Search</a>, 
<a href="#" onClick="openLink('','Delete');return false">Delete</a>, 
<a href="#" onClick="openLink('','VisProperties');return false">VisProperties</a>, 
<a href="#" onClick="openLink('','Copy');return false">Copy</a>, 
<a href="#" onClick="openLink('','Cut');return false">Cut</a>, 
<a href="#" onClick="openLink('','Paste');return false">Paste</a> and 
<a href="#" onClick="openLink('','PasteSpecial');return false">PasteSpecial</a> methods of the Selection object take into account the feature.<br> For example, if the user:
 <ul>
 <li>Go to the "DPM - Process and Resource Definition" workshop</li>
 <li>Puts a ResourcesList object in the clipboard</li>
 <li>Runs a script calling the Selection.PasteSpecial method</li>
 </ul>
 then, during the paste, the ResourcesList object will be pasted.</li>
 </ul></li>
 </ul>
 <b>Note</b>: The 
<a href="#" onClick="openLink('Selection','');return false">Selection</a> object can be accessed through the 
<a href="#" onClick="openLink('Document','Selection');return false">Document.Selection</a> property . However, when the active window contains the tree described above, the 
<a href="#" onClick="openLink('Selection','');return false">Selection</a> object to use is the one associated to the Product3 
<a href="#" onClick="openLink('Document','');return false">Document</a> , which can be accessed through the application of the 
<a href="#" onClick="openLink('Document','Selection');return false">Document.Selection</a> to this document. You will, for example, determine the 
<a href="#" onClick="openLink('Selection','');return false">Selection</a> object the following way:
 <pre>
 Set ActiveProductDocument = CATIA.ActiveDocument 
 Set Product3 = ActiveProductDocument.Product     
 Set Product3Products = Product3.Products 
 Set Product2Dot1 = Product3Products.Item("Product2.1") : Set Product2 = Product2Dot1.ReferenceProduct     
 Set ProductDocument2 = Product2.Parent
 Set Product2Products = Product2.Products 
 Set Product1Dot1 = Product2Products.Item("Product1.1") : Set Product1 = Product1Dot1.ReferenceProduct     
 Set ProductDocument1 = Product1.Parent
 Set Product1Products = Product1.Products 
 Set Part1Dot1 = Product1Products.Item("Part1.1") : Set Part1 = Part1Dot1.ReferenceProduct     
 Set PartDocument1 = Part1.Parent
 <font color="red">Set Selection = ActiveProductDocument.Selection</font>
 </pre>
 Another 
<a href="#" onClick="openLink('Selection','');return false">Selection</a> object, such as: <pre> Set ProductDocument2Selection = ProductDocument2.Selection
 Set ProductDocument1Selection = ProductDocument1.Selection
 Set PartDocument1Selection = PartDocument1.Selection
 </pre>(lets take ProductDocument2Selection for example) can only be used if, among the different 
<a href="#" onClick="openLink('Window','');return false">Window</a> , there is at least one whose root 
<a href="#" onClick="openLink('Document','');return false">Document</a> is ProductDocument2 . Otherwise, results are unpredictable.
<hr>
<dl>
 <h2><a name="PropertyIndex"></a>Property Index</h2>
 <dt>
    <a href="#Count"><b>Count</b></a>
<dd>  
 <dt>
    <a href="#Count2"><b>Count2</b></a>
<dd>  Returns the number of SelectedElement objects contained by the current selection.
 <dt>
    <a href="#VisProperties"><b>VisProperties</b></a>
<dd>  Manages graphic properties on current selection.
</dl>
<dl>
 <h2><a name="MethodIndex"></a>Method Index</h2>
 <dt>
    <a href="#Add"><b>Add</b></a>
<dd>  Creates a SelectedElement object which Value property is the given automation object, and adds it to the selection.
 <dt>
    <a href="#Clear"><b>Clear</b></a>
<dd>  Clears the selection.
 <dt>
    <a href="#Copy"><b>Copy</b></a>
<dd>  Copies, in a copy and paste operation.
 <dt>
    <a href="#Cut"><b>Cut</b></a>
<dd>  Cuts, in a cut and paste operation.
 <dt>
    <a href="#Delete"><b>Delete</b></a>
<dd>  Deletes all selected objects.
 <dt>
    <a href="#FilterCorrespondence"><b>FilterCorrespondence</b></a>
<dd>  Specifies if the automation objects appearing as Value property of SelectedElement objects fit a given filter.
 <dt>
    <a href="#FindObject"><b>FindObject</b></a>
<dd>  Finds an object in the current selection and deletes it from the selection.
 <dt>
    <a href="#IndicateOrSelectElement2D"><b>IndicateOrSelectElement2D</b></a>
<dd>  Runs an interactive command enabling both indication and selection, 2D version.
 <dt>
    <a href="#IndicateOrSelectElement3D"><b>IndicateOrSelectElement3D</b></a>
<dd>  Runs an interactive command enabling both indication and selection, 3D version.
 <dt>
    <a href="#Item"><b>Item</b></a>
<dd>  
 <dt>
    <a href="#Item2"><b>Item2</b></a>
<dd>  Returns the iIndex-th SelectedElement object contained by the current selection.
 <dt>
    <a href="#Paste"><b>Paste</b></a>
<dd>  Puts the contents of the clipboard in the document at the indicated location.
 <dt>
    <a href="#PasteSpecial"><b>PasteSpecial</b></a>
<dd>  Puts the contents of the clipboard in the document at the indicated location, according to the specified format.
 <dt>
    <a href="#Remove"><b>Remove</b></a>
<dd>  
 <dt>
    <a href="#Remove2"><b>Remove2</b></a>
<dd>  Removes the iIndex-th SelectedElement object contained by the current selection.
 <dt>
    <a href="#Search"><b>Search</b></a>
<dd>  Finds an object in the document using the Edit/Search grammar.
 <dt>
    <a href="#SelectElement2"><b>SelectElement2</b></a>
<dd>  Runs an interactive selection command.
 <dt>
    <a href="#SelectElement3"><b>SelectElement3</b></a>
<dd>  Runs an interactive selection command, exhaustive version.
 <dt>
    <a href="#SelectElement4"><b>SelectElement4</b></a>
<dd>  Runs an interactive selection command, enabling the selection in a non active document.
</dl>
 <h2><a name="Properties"></a>Properties</h2> <br>
<a name="Count"><dt>

<table><tr><td>o Property <b>Count</b>(<td>) As <script type="text/javascript"> activateLink('long','long')</script>  (Read Only)</table></dt>
<dl>
  <dd>
 
<dl>
  <dt> <b>Deprecated:</b> 
  <dd>  V5R16 #Count2 . The Count and Item Methods have been replaced by the Count2 and Item2 methods because
 they did not process correctly features which are not exposed to automation (such as a ResourcesList feature of a
 .CATProcess document).
</dl>
</dl>
<a name="Count2"><dt>

<table><tr><td>o Property <b>Count2</b>(<td>) As <script type="text/javascript"> activateLink('long','long')</script>  (Read Only)</table></dt>
<dl>
  <dd>
 Returns the number of SelectedElement objects contained by the current selection.
 <br><b>Role</b>: This method returns the number of 
<a href="#" onClick="openLink('SelectedElement','');return false">SelectedElement</a> objects contained by the Selection.  The Value property of a given 
<a href="#" onClick="openLink('SelectedElement','');return false">SelectedElement</a> object is an automation object associated to a selected feature.
</dl>
<a name="VisProperties"><dt>

<table><tr><td>o Property <b>VisProperties</b>(<td>) As <script type="text/javascript"> activateLink('VisPropertySet','VisPropertySet')</script>  (Read Only)</table></dt>
<dl>
  <dd>
 Manages graphic properties on current selection.
 <br><b>Role</b>: Gives a VisPropertySet automation object so that graphic properties of the selected objects can
 be read or modified.<br>
 <b>Note:</b> After the execution of the VisProperties methods which update graphic properties of the features,
 selected features which are not exposed to automation will be updated. After the execution of the VisProperties
 methods which consult the selection to give the graphic properties, selected features which are not exposed to
 automation will be consulted.
 <! @sample>
 <dl>
 <dt><b>Example:</b>
 <dd>
 This example sets in no show all elements of the current selection:
 <pre>
 Dim Selection,VisPropertySet
 Set Selection = CATIA.ActiveDocument.Selection
 Set VisPropertySet = Selection.<font color="red">VisProperties</font>
 VisPropertySet.SetShow catVisPropertiesNoShowAttr
 </pre>
 </dl>
</dl>
 <h2><a name="Methods"></a>Methods</h2> <br>
<a name="Add"><dt>

<table><tr><td>o Sub <b>Add</b>(<td><script type="text/javascript"> activateLink('AnyObject','AnyObject')</script> <td><tt>iObject</tt>)</table></dt>
<dl>
  <dd>
 Creates a SelectedElement object which Value property is the given automation object, and adds it to the selection.</br>
 <b>Note</b>: In a product structure aggregating a "Part1 (Part1.1)" Part document, if you double-clic Part1 in the
 spectification tree:
 <ul>
 <li>the "Part Design" workbench becomes active</li>
 <li>the Part1 node is inside a blue button</li>
 </ul>
 Here, Part1 is the UI Active Object.</br>
 Some editors, such as 
<a href="#" onClick="openLink('CatalogDocument','');return false">CatalogDocument</a> editors, do not possess any UI Active Object.</br> When this method is used in a CATAnalysis context, a CATPart (such as Part1 in our example) must be UI active. Otherwise, Selection.Add does not work correctly (the 3D is not highlighted properly).</br>
 <b>Role</b>: Creates a 
<a href="#" onClick="openLink('SelectedElement','');return false">SelectedElement</a> object and adds it to the current selection. Depending on the  type of the parent 
<a href="#" onClick="openLink('Document','');return false">Document</a> of the 
<a href="#" onClick="openLink('Selection','');return false">Selection</a> object: <ul>
 <li>if it is one of the following:
 <ul>
 <li>
CATIAPartDocument</li> <li>
CATIADrawingDocument</li> <li>
CATIAMaterialDocument</li> <li>
CATIAAnalysisDocument</li> <li>
CATIAFunctionalDocument</li> </ul>
 then, regarding the created 
<a href="#" onClick="openLink('SelectedElement','');return false">SelectedElement</a> , the 
<a href="#" onClick="openLink('SelectedElement','Value');return false">SelectedElement.Value</a> property will be equal to <tt>iObject</tt></li>
 <li>Otherwise:
 <ul>
 <li>first case: the specification tree contains a path:
 <ul>
 <li>whose leaf node is <tt>iObject</tt></li>
 <li>the UI Active Object belongs to the path</li>
 </ul>
 then, the method will create a 
<a href="#" onClick="openLink('SelectedElement','');return false">SelectedElement</a> object corresponding to this path.</li> <li>Otherwise: the method will create a 
<a href="#" onClick="openLink('SelectedElement','');return false">SelectedElement</a> object corresponding to the first path, in the specification tree, whose leaf node is <tt>iLeafNode</tt></li>
 </ul></li></ul>
 <! @sample>
 <dl>
 <dt><b>Example:</b>
 <dd>
 This example creates a 
<a href="#" onClick="openLink('SelectedElement','');return false">SelectedElement</a> object, which Value property is the <tt>ObjectToAdd</tt> automation object, the 
<a href="#" onClick="openLink('SelectedElement','');return false">SelectedElement</a> being added to the current selection.   <pre>
 CATIA.ActiveDocument.Selection.<font color="red">Add</font>(ObjectToAdd)
 </pre>
 </dl>
</dl>
<a name="Clear"><dt>

<table><tr><td>o Sub <b>Clear</b>(<td>)</table></dt>
<dl>
  <dd>
 Clears the selection.
 <! @sample>
 <dl>
 <dt><b>Example:</b>
 <dd>
 This example clears the selection. The selection is then empty.
 <pre>
 CATIA.ActiveDocument.Selection.<font color="red">Clear</font>()
 </pre>
 </dl>
</dl>
<a name="Copy"><dt>

<table><tr><td>o Sub <b>Copy</b>(<td>)</table></dt>
<dl>
  <dd>
 Copies, in a copy and paste operation.
 <br><b>Role</b>: Puts the contents of the selection in the clipboard,
 but leaves the selected elements in the document,
 and clears the selection.
 This is the programming equivalent of the Copy command from the
 Edit menu.<br>
 <b>Note</b>: The method (and the script execution) fails if one of the following errors occurs:
 <ul>
 <li>The CSO is empty. The Copy operation could not be performed.</li>
 <li>No CSO element remains after the filtering through the UI active object. The Copy operation could not be performed.</li>
 </ul>
 <b>Note:</b> If a selected feature is not exposed to automation, it will be copied into the clipboard all the
 way.
 <! @sample>
 <dl>
 <dt><b>Example:</b>
 <dd>
 This example copies, in a copy and paste operation. A selected DMU Navigator URL will be put into the clipboard
 although it is not exposed to automation.
 <pre>
 CATIA.ActiveDocument.Selection.<font color="red">Copy</font>()
 </pre>
 </dl>
</dl>
<a name="Cut"><dt>

<table><tr><td>o Sub <b>Cut</b>(<td>)</table></dt>
<dl>
  <dd>
 Cuts, in a cut and paste operation.
 <br><b>Role</b>: Puts the contents of the selection in the clipboard, and removes the selected elements from the
 document,
 and clears the selection.
 This is the programming equivalent of the Cut command from the
 Edit menu.<br>
 <b>Note</b>: The method (and the script execution) fails if one of the following errors occurs:
 <ul>
 <li>The CSO is empty. The Cut operation could not be performed.</li>
 <li>No CSO element remains after the filtering through the UI active object. The Cut operation could not be performed.</li>
 </ul>
 <b>Note:</b> If a selected feature is not exposed to automation, it will be copied into the clipboard and removed
 from the document all the way.
 <! @sample>
 <dl>
 <dt><b>Example:</b>
 <dd>
 This example cuts, in a cut and paste opertation. A selected DMU Navigator URL will be put into the clipboard and
 removed from the document, although it is not exposed to automation.
 <pre>
 CATIA.ActiveDocument.Selection.<font color="red">Cut</font>()
 </pre>
 </dl>
</dl>
<a name="Delete"><dt>

<table><tr><td>o Sub <b>Delete</b>(<td>)</table></dt>
<dl>
  <dd>
 Deletes all selected objects.
 <br><b>Role</b>: For all the 
<a href="#" onClick="openLink('SelectedElement','');return false">SelectedElement</a> objects contained by the selection, the  
<a href="#" onClick="openLink('SelectedElement','Value');return false">SelectedElement.Value</a> automation object is deleted from the document.<br>  <b>Note:</b> If a selected feature is not exposed to automation, it will deleted all the way.
 <! @sample>
 <dl>
 <dt><b>Example:</b>
 <dd>
 This example deletes all the selected objects. A selected DMU Navigator URL will be removed from the document,
 although it is not exposed to automation.
 <pre>
 CATIA.ActiveDocument.Selection.<font color="red">Delete</font>()
 </pre>
 </dl>
</dl>
<a name="FilterCorrespondence"><dt>

<table><tr><td>o Func <b>FilterCorrespondence</b>(<td><script type="text/javascript"> activateLink('CATSafeArrayVariant','CATSafeArrayVariant')</script> <td><tt>iFilterType</tt>) As <script type="text/javascript"> activateLink('boolean','boolean')</script> </table></dt>
<dl>
  <dd>
 Specifies if the automation objects appearing as Value property of SelectedElement objects fit a given filter.
 <br><b>Role</b>: <tt>FilterCorrespondence</tt> filters the selection with respect to provided automation 
 types. The use of this method coupled with the use of the 
<a href="#" onClick="openLink('','SelectElement2');return false">SelectElement2</a> will enable to offer a multi-selection written programmatically, which is the common way to write multi-selection is CATIA.<br>
 It will enable, for example, to write a script reproducing the functionalities of the "Fillet" command of the
 "Part Design" workbench.</br>
 This method, called before a loop onto 
<a href="#" onClick="openLink('','SelectElement2');return false">SelectElement2</a> calls, will enable if all the selection objects correspond to the filter (which will be the same as the filter given to 
<a href="#" onClick="openLink('','SelectElement2');return false">SelectElement2</a> ), to take them into account, and, otherwise, to clear the selection.</br>
 This multi-selection written programmatically will generally be used coupled with the fact that already selected
 elements remain selected during the selections.
 
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iFilterType</tt>
   <dd> An array of strings constants to be used as a filter for the kind of element to which current selection object
 must correspond. See the iFilterType parameter of the </dd>
</dl>
<a href="#" onClick="openLink('','SelectElement2');return false">SelectElement2</a> method. 
    <dt><tt> oAllFit</tt>
   <dd> All current selection objects fit the iFilterType filter, i.e. regarding each of the current selection objects, 
 they all fit one of the iFilterType string constant.
 </dd>
  <dt> <b>Example:</b> 
  <dd>  The following example scripts an edge fillet creation command. It supposes that a part is currently edited, 
 containing a Pad. It loops onto the following:
 <ul>
 <li>it asks the end user to select an edge (see 
<a href="#" onClick="openLink('TriDimFeatEdge','');return false">TriDimFeatEdge</a> ). If the selected edge has not already been selected, the selected edge is added to the selection, otherwise it is removed from the selection</li>
 <li>it asks the end user if another edge has to be selected</li>
 </ul>
 until the answer of the user to the preceding question is no.<br>
 Then, it creates an edge fillet (see 
<a href="#" onClick="openLink('ConstRadEdgeFillet','');return false">ConstRadEdgeFillet</a> ) taking into account all the selected edges as fillet specifications.<br>
 <br><b>Note</b>: The edges which were selected before the script execution are taken into account. Nevertheless,
 if, before the script execution, the selection contained an object which was not a 
<a href="#" onClick="openLink('TriDimFeatEdge','');return false">TriDimFeatEdge</a> element, the selection is cleared before the first selection proposal.
 <br><b>Note</b>: During the selection of a given edge, the edges already selected remain highlighted. 
 <pre>
 Dim Document,Part,Selection,ShapeFactory,EdgeSaveAllocatedCount,EdgeIndex,AllEdgesHaveBeenSelected,AllFit
 Dim EdgeSaveCount,SelectedEdge,SelectedElementBelongsToSaveVariables,AlreadySelectedEdgeIndex
 Dim OtherEdgeAnswer,Fillet
 Set Document = CATIA.ActiveDocument : Set Part = Document.Part : Set Selection = Document.Selection
 Set ShapeFactory = Part.ShapeFactory 
 ReDim InputObjectType(0) : InputObjectType(0)="TriDimFeatEdge" : EdgeSaveCount = 0
'We determine if the selection contains an object which is not a TriDimFeatEdge element
 AllFit = Selection.<font color="red">FilterCorrespondence</font>(InputObjectType)
'If the selection contains an object which is not a TriDimFeatEdge element, we clear the selection
 if (Not AllFit) then Selection.Clear
 EdgeSaveAllocatedCount = Selection.Count+10 : ReDim EdgeSave(EdgeSaveAllocatedCount-1)
'We loop onto interactive selections
 AllEdgesHaveBeenSelected = false
 do while (Not AllEdgesHaveBeenSelected)
'  We save the selection content in save variables.
'  This corresponds to the fact that:
'    - we want that, during the following call to SelectElement2, the TriDimFeatEdge elements previously selected
'      remain highlighted
'    - this is done using the False value for the iObjectSelectionBeforeCommandUsePossibility
'      parameter of the SelectElement2 method, the selection containing the TriDimFeatEdge elements. It requires that
'      the selection content be saved
     if (EdgeSaveAllocatedCount &lt; Selection.Count) then
         EdgeSaveAllocatedCount = EdgeSaveAllocatedCount + 10 : ReDim EdgeSave(EdgeSaveAllocatedCount-1)
     end if
     for EdgeIndex = 0 to Selection.Count2-1
         Set EdgeSave(EdgeIndex) = Selection.Item2(EdgeIndex+1).Value
     next 
     EdgeSaveCount = Selection.Count
'  We propose to the user that he select an edge
     Status=Selection.SelectElement2(InputObjectType,"Select an edge",false)
     if (Status="Cancel") then
         Selection.Clear : Exit Sub
     end if
'  We save the selected edge in a dedicated variable
     Set SelectedEdge = Selection.Item2(1).Value
'  We merge the selected element with the save variables, and put the result in the selection.
'  At first, we determine if the selected edge already belongs to the EdgeSave array
     EdgeIndex = 0 : SelectedElementBelongsToSaveVariables = False
     do while ((EdgeIndex &lt; EdgeSaveCount) And (Not SelectedElementBelongsToSaveVariables))
         if (EdgeSave(EdgeIndex).Name=SelectedEdge.Name) then
             SelectedElementBelongsToSaveVariables = True
             AlreadySelectedEdgeIndex = EdgeIndex
         end if
         EdgeIndex = EdgeIndex + 1
     loop
'  Effective merge
     if (Not SelectedElementBelongsToSaveVariables) then
'      The selected element does not belong to the save variables. We add the save variables to the selection
         for EdgeIndex = 0 to EdgeSaveCount-1
             Selection.Add EdgeSave(EdgeIndex)
         next 
     else
'      We remove the selected element from the save variables
         for EdgeIndex = AlreadySelectedEdgeIndex to EdgeSaveCount-2
             Set EdgeSave(EdgeIndex) = EdgeSave(EdgeIndex+1)
         next
         EdgeSaveCount = EdgeSaveCount - 1
'      We clear the selection
         Selection.Clear
'      We add the save variables to the selection
         for EdgeIndex = 0 to EdgeSaveCount -1
             Selection.Add EdgeSave(EdgeIndex)
         next
     end if
'  We ask the end user if another edge has to be selected
     OtherEdgeAnswer = msgbox ("do you want to select another edge?",3,"Edge Fillet Definition")
     if (OtherEdgeAnswer = 2) then Exit Sub
     if (OtherEdgeAnswer = 7) then AllEdgesHaveBeenSelected = true
 loop
'We create an edge fillet taking into account all the selected edges as fillet specifications
 if (Selection.Count &gt; 0) then
     Set Fillet = ShapeFactory.AddNewEdgeFilletWithConstantRadius(Selection.Item(1).Value, 1, 5.0)
     Fillet.EdgePropagation = 1
     for EdgeIndex = 2 to Selection.Count
         Fillet.AddObjectToFillet Selection.Item(EdgeIndex).Value
     next
     Part.Update : Selection.Clear : Selection.Add Fillet
 end if
 </pre>
</dl>
</dl>
<a name="FindObject"><dt>

<table><tr><td>o Func <b>FindObject</b>(<td><script type="text/javascript"> activateLink('CATBSTR','CATBSTR')</script> <td><tt>iObjectType</tt>) As <script type="text/javascript"> activateLink('AnyObject','AnyObject')</script> </table></dt>
<dl>
  <dd>
 Finds an object in the current selection and deletes it from the selection.
 <br><b>Role</b>: Determines the first automation object specified in 
<a href="#" onClick="openLink('SelectedElement','Value');return false">SelectedElement.Value</a> (for the 
<a href="#" onClick="openLink('SelectedElement','');return false">SelectedElement</a> objects contained in the current selection), or which is a Parent (see  
<a href="#" onClick="openLink('AnyObject','Parent');return false">AnyObject.Parent</a> ) of the automation object specified in 
<a href="#" onClick="openLink('SelectedElement','Value');return false">SelectedElement.Value</a> , which type is equal to the type specified in input. It returns directly the automation object and deletes the corresponding
 
<a href="#" onClick="openLink('SelectedElement','');return false">SelectedElement</a> object from the current selection.<br> <b>Note:</b> If the string specified in input is he "CATIAProduct" string, the possible automation object
 specified in 
<a href="#" onClick="openLink('SelectedElement','LeafProduct');return false">SelectedElement.LeafProduct</a> is also looked at. <! @sample>
 <dl>
 <dt><b>Example:</b>
 <dd>
 This example searches a Pad object in the
 current selection and puts it into <tt>FoundObject</tt>.
 <pre>
 Dim FoundObject As AnyObject
 Set FoundObject = CATIA.ActiveDocument.Selection.<font color="red">FindObject</font>("CATIAPad")
 </pre>
 </dl>
</dl>
<a name="IndicateOrSelectElement2D"><dt>

<table><tr><td>o Func <b>IndicateOrSelectElement2D</b>(<td><script type="text/javascript"> activateLink('CATBSTR','CATBSTR')</script> <td><tt>iMessage</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('CATSafeArrayVariant','CATSafeArrayVariant')</script> <td><tt>iFilterType</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('boolean','boolean')</script> <td><tt>iObjectSelectionBeforeCommandUsePossibility</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('boolean','boolean')</script> <td><tt>iTooltip</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('boolean','boolean')</script> <td><tt>iTriggeringOnMouseMove</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('boolean','boolean')</script> <td><tt>oObjectSelected</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('CATSafeArrayVariant','CATSafeArrayVariant')</script> <td><tt>oDocumentWindowLocation</tt>) As <script type="text/javascript"> activateLink('CATBSTR','CATBSTR')</script> </table></dt>
<dl>
  <dd>
 Runs an interactive command enabling both indication and selection, 2D version.
 <br><b>Role</b>: <tt>IndicateOrSelectElement2D</tt> asks the end user to select either a location into the window,
 or a feature (in the geometry or in the specification tree).<br>
 During execution, when entering this method, the active document must be a 2D document. See 
 
<a href="#" onClick="openLink('Document','Indicate2D');return false">Document.Indicate2D</a> and 
<a href="#" onClick="openLink('','SelectElement3');return false">SelectElement3</a> 
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iMessage</tt>
   <dd> A string which instructs the user that he must select a location into the document window or select an object.
 </dd>
    <dt><tt> iFilterType</tt>
   <dd> An array of strings constants defining the automation object types with which the selection will be filtered.
 </dd>
    <dt><tt> iObjectSelectionBeforeCommandUsePossibility</tt>
   <dd> Enables the script to support the possibility, for the user, to select a required object before running the script.
 See </dd>
</dl>
<a href="#" onClick="openLink('','SelectElement2');return false">SelectElement2</a> . 
    <dt><tt> iTooltip</tt>
   <dd> Displays a tooltip as soon as an object is located under the mouse without being selected. 
 </dd>
    <dt><tt> iTriggeringOnMouseMove</tt>
   <dd> Triggers as soon as a mouse move event is detected. This option beeing set, oOutputState may be valued to
 "MouseMove".
 </dd>
    <dt><tt> oObjectSelected</tt>
   <dd>  Flag précising if the user choosed the selection or the indication. 
 </dd>
    <dt><tt> oDocumentWindowLocation</tt>
   <dd>  An array made of 2 doubles: X, Y - coordinates array of the location the user specified in the document window.
 This parameter is valuated only if oObjectSelected equals to false.
 </dd>
    <dt><tt> oOutputState</tt>
   <dd> The state of the interactive command once IndicateOrSelectElement2D  returns. The possible values are the same than
 the values described regarding the oOutputState parameter of the </dd>
<a href="#" onClick="openLink('','SelectElement2');return false">SelectElement2</a> method, except that the "MouseMove" value can also be returned.
 
  <dt> <b>Example:</b> 
  <dd>  The following example suppose a drawing is currently edited. It creates a point (see 
<a href="#" onClick="openLink('Point2D','');return false">Point2D</a> ), and asks the end user to click to define the circle center.</br>
 When it is done, as the mouse moves without clicking the left button, the script determines the location into
 the drawing window, and the script creates a temporary circle as a feedback.</br>
 A click into the document window or the selection of a point creates definitively the circle 
 (see 
<a href="#" onClick="openLink('Circle2D','');return false">Circle2D</a> ) located at the specified location (whether the location is a location into the drawing window or whether it is the existing point location).
 <pre>
 Dim Document,Selection,DrawingSheets,DrawingSheet,DrawingViews,WindowLocation(1),DrawingView,Factory2D,Radius,Circle2D
 Dim HardCodedPoint,Status,XCenter,YCenter,InputObjectType(0),TempCircleHasBeenCreatedAtLeastOnce,ExistingPoint
 Dim ObjectSelected
 Set Document = CATIA.ActiveDocument : Set Selection = Document.Selection : Set DrawingSheets  = Document.Sheets 
 Set DrawingSheet = DrawingSheets.ActiveSheet : Set DrawingViews = DrawingSheet.Views
 Set DrawingView = DrawingViews.ActiveView : Set Factory2D = DrawingView.Factory2D
'We create a point
 Set HardCodedPoint = Factory2D.CreatePoint(700.,400.)
 HardCodedPoint.ReportName = 1 : HardCodedPoint.Construction = False
'We propose to the user to click to define the circle center
 Status=Document.Indicate2D("click to define the circle center",WindowLocation)
 if (Status = "Cancel" Or Status = "Undo" Or Status = "Redo") then Exit Sub
 XCenter = WindowLocation(0) : YCenter = WindowLocation(1)
'We propose to the user that he specify a location into the drawing window or a point
 InputObjectType(0)="Point2D"
 Status = "MouseMove" : TempCircleHasBeenCreatedAtLeastOnce = 0
 Status=Selection.<font color="red">IndicateOrSelectElement2D</font>("select a point or click to locate the circle radius point", _ 
                                            InputObjectType,false,false,true, _ 
                                            ObjectSelected,WindowLocation)
' We loop onto mouse moves without click
 do while (Status = "MouseMove")
     if (TempCircleHasBeenCreatedAtLeastOnce) then 
         Selection.Add Circle2D : Selection.Delete
     end if
     Radius = Sqr(((WindowLocation(0)-XCenter)*(WindowLocation(0)-XCenter))+ _ 
                  ((WindowLocation(1)-YCenter)*(WindowLocation(1)-YCenter)))
     Set Circle2D = Factory2D.CreateClosedCircle(XCenter,YCenter,Radius)
     TempCircleHasBeenCreatedAtLeastOnce = 1
     Status=Selection.<font color="red">IndicateOrSelectElement2D</font>("select a point or click to locate the circle radius point", _ 
                                            InputObjectType,false,false,true, _ 
                                            ObjectSelected,WindowLocation)
 loop
'We go out if necessary
 if (Status = "Cancel" Or Status = "Undo" Or Status = "Redo") then 
     if (TempCircleHasBeenCreatedAtLeastOnce) then 
         Selection.Add Circle2D : Selection.Add HardCodedPoint : Selection.Delete
     end if
     Exit Sub
 end if
'We determine the possible selected point coordinates
 if (ObjectSelected) then
     Set ExistingPoint = Selection.Item2(1).Value : ExistingPoint.GetCoordinates WindowLocation : Selection.Clear
 end if
'We clean-up the temporary circle
 if (TempCircleHasBeenCreatedAtLeastOnce) then 
     Selection.Add Circle2D : Selection.Delete
 end if
'We create the circle
 Radius = Sqr(((WindowLocation(0)-XCenter)*(WindowLocation(0)-XCenter))+ _ 
              ((WindowLocation(1)-YCenter)*(WindowLocation(1)-YCenter)))
 Set Circle2D = Factory2D.CreateClosedCircle(XCenter,YCenter,Radius) : Selection.Add Circle2D
 </pre>
</dl>
</dl>
<a name="IndicateOrSelectElement3D"><dt>

<table><tr><td>o Func <b>IndicateOrSelectElement3D</b>(<td><script type="text/javascript"> activateLink('AnyObject','AnyObject')</script> <td><tt>iPlanarGeometricObject</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('CATBSTR','CATBSTR')</script> <td><tt>iMessage</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('CATSafeArrayVariant','CATSafeArrayVariant')</script> <td><tt>iFilterType</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('boolean','boolean')</script> <td><tt>iObjectSelectionBeforeCommandUsePossibility</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('boolean','boolean')</script> <td><tt>iTooltip</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('boolean','boolean')</script> <td><tt>iTriggeringOnMouseMove</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('boolean','boolean')</script> <td><tt>oObjectSelected</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('CATSafeArrayVariant','CATSafeArrayVariant')</script> <td><tt>oWindowLocation2D</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('CATSafeArrayVariant','CATSafeArrayVariant')</script> <td><tt>oWindowLocation3D</tt>) As <script type="text/javascript"> activateLink('CATBSTR','CATBSTR')</script> </table></dt>
<dl>
  <dd>
 Runs an interactive command enabling both indication and selection, 3D version.
 <br><b>Role</b>: <tt>IndicateOrSelectElement3D</tt> asks the end user to select either a location into the window,
 or a feature (in the geometry or in the specification tree).<br>
 During execution, when entering this method, the active document must be a 3D document. See 
 
<a href="#" onClick="openLink('Document','Indicate3D');return false">Document.Indicate3D</a> and 
<a href="#" onClick="openLink('','SelectElement3');return false">SelectElement3</a> 
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iPlanarGeometricObject</tt>
   <dd> A planar geometric object.
 </dd>
    <dt><tt> iMessage</tt>
   <dd> A string which instructs the user that he must select a location into the document window or select an object.
 </dd>
    <dt><tt> iFilterType</tt>
   <dd> An array of strings constants defining the automation object types with which the selection will be filtered.
 </dd>
    <dt><tt> iObjectSelectionBeforeCommandUsePossibility</tt>
   <dd> Enables the script to support the possibility, for the user, to select a required object before running the script.
 See </dd>
</dl>
<a href="#" onClick="openLink('','SelectElement2');return false">SelectElement2</a> .  
    <dt><tt> iTooltip</tt>
   <dd> Displays a tooltip as soon as an object is located under the mouse without being selected. 
 </dd>
    <dt><tt> iTriggeringOnMouseMove</tt>
   <dd> Triggers as soon as a mouse move event is detected. This option beeing set, oOutputState may be valued to
 "MouseMove".
 </dd>
    <dt><tt> oObjectSelected</tt>
   <dd>  Flag précising if the user choosed the selection or the indication. 
 </dd>
    <dt><tt> oWindowLocation2D</tt>
   <dd> X, Y - coordinates array of the location the user specified into the document window.
 This parameter is valuated only if oObjectSelected equals to false.
 </dd>
    <dt><tt> oWindowLocation3D</tt>
   <dd> X, Y, Z - coordinates array of the location the user specified in the document window.
 This parameter is valuated only if oObjectSelected equals to false.
 </dd>
    <dt><tt> oOutputState</tt>
   <dd> The state of the interactive command once IndicateOrSelectElement3D  returns. The possible values are the same than
 the values described regarding the oOutputState parameter of the </dd>
<a href="#" onClick="openLink('','SelectElement2');return false">SelectElement2</a> method, except that the "MouseMove" value can also be returned.
 
  <dt> <b>Example:</b> 
  <dd>  The following example suppose a part is currently edited, containing a plane. It creates a point 
 (see 
<a href="#" onClick="openLink('HybridShapePointOnPlane','');return false">HybridShapePointOnPlane</a> ), asks the end user to select a location into the part window, onto the Plane.1 plane, or to select a point.</br>
 As the mouse moves without clicking the left button, the location into the drawing window is determined, and the
 script creates a temporary point as a feedback.</br>
 A click into the document window or the selection of a point creates definitively the point
 (see 
<a href="#" onClick="openLink('HybridShapePointOnPlane','');return false">HybridShapePointOnPlane</a> ) located at the specified location (whether the location is a location into the part window or whether it is the existing point location).
 <pre>
 Dim Document,Part,HybridShapeFactory,Selection,Body,HybridShapePlane,PlaneReference,HardCodedPoint,Point
 Dim InputObjectType(0),WindowLocation2D(1),WindowLocation3D(2),TempPointHasBeenCreatedAtLeastOnce,Status
 Dim ObjectSelected,ExistingPoint
 Set Document = CATIA.ActiveDocument : Set Part = Document.Part
 Set HybridShapeFactory = Part.HybridShapeFactory : Set Selection = Document.Selection 
 Set Body = Part.Bodies.Item("PartBody") : Set HybridShapePlane = Body.HybridShapes.Item("Plane.1")
 Set PlaneReference = Part.CreateReferenceFromObject(HybridShapePlane)
'We create a point
 Set HardCodedPoint = HybridShapeFactory.AddNewPointOnPlane(PlaneReference,30.,30.)
 Body.InsertHybridShape HardCodedPoint : Part.InWorkObject = HardCodedPoint : Part.Update 
'We propose to the user that he specify a location into the part window or a point
 InputObjectType(0)="HybridShapePointOnPlane"
 Status = "MouseMove" : TempPointHasBeenCreatedAtLeastOnce = 0 : Selection.Clear
 Status=Selection.<font color="red">IndicateOrSelectElement3D</font>(HybridShapePlane,"select a point or click to locate the point", _ 
                                            InputObjectType,false,false,true, _ 
                                            ObjectSelected,WindowLocation2D,WindowLocation3D)
' We loop onto mouse moves without click
 do while (Status = "MouseMove")
     if (TempPointHasBeenCreatedAtLeastOnce) then 
         Selection.Add Point : Selection.Delete
     end if
     Set Point = HybridShapeFactory.AddNewPointOnPlane(PlaneReference,WindowLocation2D(0),WindowLocation2D(1))
     Body.InsertHybridShape Point : Part.InWorkObject = Point : Part.Update 
     TempPointHasBeenCreatedAtLeastOnce = 1
     Status=Selection.<font color="red">IndicateOrSelectElement3D</font>(HybridShapePlane,"select a point or click to locate the point", _ 
                                            InputObjectType,false,false,true, _ 
                                            ObjectSelected,WindowLocation2D,WindowLocation3D)
 loop
'We go out if necessary
 if (Status = "Cancel" Or Status = "Undo" Or Status = "Redo") then 
     if (TempPointHasBeenCreatedAtLeastOnce) then 
         Selection.Add Point : Selection.Add HardCodedPoint : Selection.Delete : Part.Update
     end if
     Exit Sub
 end if
'We determine the possible selected point coordinates
 if (ObjectSelected) then
     Set ExistingPoint = Selection.Item2(1).Value
     WindowLocation2D(0) = ExistingPoint.XOffset.Value : WindowLocation2D(1) = ExistingPoint.YOffset.Value
     Selection.Clear
 end if
'We clean-up the temporary point
 if (TempPointHasBeenCreatedAtLeastOnce) then 
     Selection.Add Point : Selection.Delete
 end if
'We create the point
 Set Point = HybridShapeFactory.AddNewPointOnPlane(PlaneReference,WindowLocation2D(0),WindowLocation2D(1))
 Body.InsertHybridShape Point : Part.InWorkObject = Point : Part.Update 
 </pre>
</dl>
</dl>
<a name="Item"><dt>

<table><tr><td>o Func <b>Item</b>(<td><script type="text/javascript"> activateLink('long','long')</script> <td><tt>iIndex</tt>) As <script type="text/javascript"> activateLink('SelectedElement','SelectedElement')</script> </table></dt>
<dl>
  <dd>
 
<dl>
  <dt> <b>Deprecated:</b> 
  <dd>  V5R16 #Item2 . The Count and Item Methods have been replaced by the Count2 and Item2 methods because
 they did not process correctly features which are not exposed to automation (such as a ResourcesList feature of a
 .CATProcess document).
</dl>
</dl>
<a name="Item2"><dt>

<table><tr><td>o Func <b>Item2</b>(<td><script type="text/javascript"> activateLink('long','long')</script> <td><tt>iIndex</tt>) As <script type="text/javascript"> activateLink('SelectedElement','SelectedElement')</script> </table></dt>
<dl>
  <dd>
 Returns the iIndex-th SelectedElement object contained by the current selection. 
 <br><b>Role</b>: Returns the iIndex-th 
<a href="#" onClick="openLink('SelectedElement','');return false">SelectedElement</a> object contained by the current Selection. The Value property of the 
<a href="#" onClick="openLink('SelectedElement','');return false">SelectedElement</a> object is an automation object associated to a selected feature. 
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iIndex</tt>
   <dd> The index of the </dd>
</dl>
<a href="#" onClick="openLink('SelectedElement','');return false">SelectedElement</a> object to return, 1&le;iIndex&le;Selection.Count2 . 
    <dt><tt> oSelectedElement</tt>
   <dd> The </dd>
<a href="#" onClick="openLink('SelectedElement','');return false">SelectedElement</a> object 
  <dt> <b>Example:</b> 
  <dd>  See the 
<a href="#" onClick="openLink('','SelectElement3');return false">SelectElement3</a> method first example.
</dl>
</dl>
<a name="Paste"><dt>

<table><tr><td>o Sub <b>Paste</b>(<td>)</table></dt>
<dl>
  <dd>
 Puts the contents of the clipboard in the document at the indicated location.
 <br><b>Role</b>: After the execution of the Paste method, there may be, among the pasted features, some which are
 not exposed to automation. If the selected feature after which the clipboard must be pasted is not exposed to
 automation, the Paste will be done all the way.<br>
 <b>Note</b>: The method (and the script execution) fails if one of the following errors occurs:
 <ul>
 <li>The CSO is empty. The Paste operation could not be performed.</li>
 <li>No CSO element remains after the filtering through the UI active object. The Paste operation could not be performed.</li>
 </ul>
 <! @sample>
 <dl>
 <dt><b>Example:</b>
 <dd>
 This example pastes, in a cut, or copy, and paste operation. A selected DMU Navigator URL will be put into the
 clipboard and removed from the document, although it is not exposed to automation.
 <pre>
 CATIA.ActiveDocument.Selection.<font color="red">Paste</font>()
 </pre>
 </dl>
</dl>
<a name="PasteSpecial"><dt>

<table><tr><td>o Sub <b>PasteSpecial</b>(<td><script type="text/javascript"> activateLink('CATBSTR','CATBSTR')</script> <td><tt>iFormat</tt>)</table></dt>
<dl>
  <dd>
 Puts the contents of the clipboard in the document at the indicated location, according to the specified format. 
 <br><b>Role</b>: After the execution of the Paste method, there may be, among the pasted features, some which are
 not exposed to automation. If the selected feature after which the clipboard must be pasted is not exposed to
 automation, the Paste will be done all the way.<br>
 <b>Note</b>: The method (and the script execution) fails if one of the following errors occurs:
 <ul>
 <li>The CSO is empty. The PasteSpecial operation could not be performed.</li>
 <li>No CSO element remains after the filtering through the UI active object. The PasteSpecial operation could not be performed.</li>
 </ul>
 <br>
 Formats are: 
 <br><ul>
 <b>In all the containers</b>
 <li><tt>"CATIA_LINK_FORMAT"</tt> to paste "Catia Link Source",</li>
 <li><tt>"OLE_LINK_FORMAT"</tt>   to paste "Ole Link Source",</li>
 <li><tt>"OLE_EMBED_FORMAT"</tt>  to paste "Ole Embed Source".</li>
 </ul> 
 <br><ul>
 <b>In a Part container</b>
 <li><tt>"CATPrtCont"</tt>              to paste "As Specified In Part Document",</li>
 <li><tt>"CATPrtResultWithOutLink"</tt> to paste "AsResult",</li>
 <li><tt>"CATPrtResult"</tt>            to paste "AsResultWithLink",</li>
 <li><tt>"CATMaterialCont"</tt>         to paste "As material",</li>
 <li><tt>"AsMaterialLink"</tt>          to paste "As material link",</li>
 <li><tt>"CATMechProdCont"</tt>         to paste "As specified in Assembly",</li>
 <li><tt>"CATProdCont"</tt>             to paste "As specified in Product Structure",</li>
 <li><tt>"CATIA_SPEC"</tt>              to paste "CATIA_SPEC",</li>
 <li><tt>"CATIA_RESULT"</tt>            to paste "CATIA_RESULT".</li>
 </ul> 
 <br><ul>
 <b>In a Product container</b>
 <li><tt>"CATProdCont"</tt>      to paste "As specified in Product Structure",</li>
 <li><tt>"CATSpecBreakLink"</tt> to paste "Break Link".</li>
 </ul> 
 <br><ul>
 <b>In a Process container</b>
 <li><tt>"SPPProcessCont"</tt> to paste "Simple paste",</li>
 <li><tt>"SPP_I"</tt>          to paste "Paste with Items",</li>
 <li><tt>"SPP_R"</tt>          to paste "Paste with Resources",</li>
 <li><tt>"SPP_IR"</tt>         to paste "Paste with Items and Resources",</li>
 <li><tt>"SPPI_I"</tt>         to paste "Paste with Items and entire hierarchy",</li>
 <li><tt>"SPPI_R"</tt>         to paste "Paste with Resources and entire hierarchy",</li>
 <li><tt>"SPPI_IR"</tt>        to paste "Paste with Items and Resources and entire hierarchy".</li>
 </ul> 
 <br><ul>
 <b>In a Material container</b>
 <li><tt>"CATMaterialCont"</tt> to paste "As material",</li>
 <li><tt>"AsMaterialLink"</tt>  to paste "As material link".</li>
 </ul> 
 <br><ul>
 <b>In a Catalog container</b>
 <li><tt>"CATDescriptionFormat"</tt> to paste "As defined in catalog instanciation",</li>
 <li><tt>"CATCtlgChapterFormat"</tt> to paste "As defined in catalog document".</li>
 </ul> 
 <br><ul>
 <b>In a Rendering Scene container</b>
 <li><tt>"CATRscLightContainer"</tt>       to paste "As light",</li>
 <li><tt>"CATRscEnvironmentContainer"</tt> to paste "As environment",</li>
 <li><tt>"CATRscShootingContainer"</tt>    to paste "As shooting",</li>
 <li><tt>"CATRscTurntableContainer"</tt>   to paste "As turntable".</li>
 </ul> 
 <br><ul>
 <b>In a Deneb Resource Program container</b>
 <li><tt>"DNBProgCont" to paste "Resource Program".</li>
 </ul> 
 <br><ul>
 <b>In a Behavior container</b>
 <li><tt>"Behaviors" to paste "Behaviors".</li>
 </ul> 
 <br><ul>
 <b>In a CATCamera container</b>
 <li><tt>"CATCameraContainer" to paste "Camera".</li>
 </ul> 
 <br>
 To know more about those formats, refer to the interactive command.
 <br><br>
 <! @sample>
 <dl>
 <dt><b>Example:</b>
 <dd>
 This example pastes, in a cut, or copy, and paste special operation. A selected DMU Navigator URL will be pasted
 from the clipboard at the specified location, although it is not exposed to automation.
 <pre>
 CATIA.ActiveDocument.Selection.<font color="red">PasteSpecial</font> "CATPrtResultWithOutLink"
 </pre>
 </dl>
</dl>
<a name="Remove"><dt>

<table><tr><td>o Sub <b>Remove</b>(<td><script type="text/javascript"> activateLink('long','long')</script> <td><tt>iIndex</tt>)</table></dt>
<dl>
  <dd>
 
<dl>
  <dt> <b>Deprecated:</b> 
  <dd>  V5R16 #Remove2 . This method does the same as the Remove2 method, but it does know how to manage features
 which are not exposed to automation (such as a ResourcesList feature of a .CATProcess document).
</dl>
</dl>
<a name="Remove2"><dt>

<table><tr><td>o Sub <b>Remove2</b>(<td><script type="text/javascript"> activateLink('long','long')</script> <td><tt>iIndex</tt>)</table></dt>
<dl>
  <dd>
 Removes the iIndex-th SelectedElement object contained by the current selection. 
 <br><b>Role</b>: Removes the iIndex-th 
<a href="#" onClick="openLink('SelectedElement','');return false">SelectedElement</a> object contained by the current selection. 
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iIndex</tt>
   <dd> The index of the </dd>
</dl>
<a href="#" onClick="openLink('SelectedElement','');return false">SelectedElement</a> object to remove, 1&le;iIndex&le;Selection.Count2 . <! @sample>
 <dl>
 <dt><b>Example:</b>
 <dd>
 This example removes the second 
<a href="#" onClick="openLink('SelectedElement','');return false">SelectedElement</a> object contained by the current selection. <pre>
 CATIA.ActiveDocument.Selection.<font color="red">Remove2</font>(2)
 </pre>
 </dl>
</dl>
</dl>
<a name="Search"><dt>

<table><tr><td>o Sub <b>Search</b>(<td><script type="text/javascript"> activateLink('CATBSTR','CATBSTR')</script> <td><tt>iStringBSTR</tt>)</table></dt>
<dl>
  <dd>
 Finds an object in the document using the Edit/Search grammar.
 <br><b>Role</b>: Finds an object in the document using the Edit/Search grammar, and fills the selection with
 the found objects. A criterium is created, based on the Search grammar, which defines in addition the depth of
 the investigation field.<br>
 <b>Note:</b> After the execution of the Search method, there may be, among the selected features, some which
 are not exposed to automation. 
 <! @sample>
 <dl>
 <dt><b>Example:</b>
 <dd>
 The following example searches the objects matching the following criterium in all the document:
 <tt>Part.Sketcher.Color='White'</tt> . A selected DMU Navigator URL put into the selection although it is not
 exposed to automation.
 <pre>
 CATIA.ActiveDocument.Selection.<font color="red">Search</font>("Part.Sketcher.Color='White',all")
 </pre>
 </dl>
</dl>
<a name="SelectElement2"><dt>

<table><tr><td>o Func <b>SelectElement2</b>(<td><script type="text/javascript"> activateLink('CATSafeArrayVariant','CATSafeArrayVariant')</script> <td><tt>iFilterType</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('CATBSTR','CATBSTR')</script> <td><tt>iMessage</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('boolean','boolean')</script> <td><tt>iObjectSelectionBeforeCommandUsePossibility</tt>) As <script type="text/javascript"> activateLink('CATBSTR','CATBSTR')</script> </table></dt>
<dl>
  <dd>
 Runs an interactive selection command.
 <br><b>Role</b>: <tt>SelectElement2</tt> asks the end user to select a feature (in the geometry or in the
 specification tree) in a 
<a href="#" onClick="openLink('Window','');return false">Window</a> of the active 
<a href="#" onClick="openLink('Document','');return false">Document</a> . During the selection, when the end user will move the mouse above a feature which maps the given filter, the mouse pointer will be the "hand" cursor, and
 when end user will move the mouse above a feature which does not map the given filter, the mouse pointer will be
 the "no entry" cursor.<br>
 <ul>
 <li>If iObjectSelectionBeforeCommandUsePossibility is equal to False: 
 <br>The end user is asked to interactively select an appropriate element. When this is done, the Selection 
 object is cleared, and filled with the selected element.</li>
 <br><li> If iObjectSelectionBeforeCommandUsePossibility is equal to True: 
 <br><tt>SelectElement2</tt> determines whether the automation objects specified in 
<a href="#" onClick="openLink('SelectedElement','Value');return false">SelectedElement.Value</a>, for the 
<a href="#" onClick="openLink('SelectedElement','');return false">SelectedElement</a> objects contained in the current selection, or one of the parents of the automation objects (see 
<a href="#" onClick="openLink('AnyObject','Parent');return false">AnyObject.Parent</a> ) is an appropriate element: <ul>
 <li>If it is the case, no interaction is asked to the end user, the Selection object is cleared, 
 and filled with the appropriate element.</li>
 <li>Otherwise, the Selection object is cleared, and the end user is asked to interactively select an 
 appropriate element. When this is done, the selection is filled with the selected element.</li>
 </ul>
 <b>Note</b>: The 
<a href="#" onClick="openLink('Selection','');return false">Selection</a> object on which the 
<a href="#" onClick="openLink('Selection','SelectElement2');return false">Selection.SelectElement2</a> method must be called must be the 
<a href="#" onClick="openLink('Selection','');return false">Selection</a> object obtained the following way: <ul>
 <li>determine the active document, for example, in the following case:
 <pre>
    Product3 
       !
       +- Product2 (Product2.1)
       !     !
       !     ! +---------------------+
       !     +-!Product1 (Product1.1)!
       !       +----------+----------+
       !                  !
       !                  +- Part1 (Part1.1)       
       !                       !
       !                       +- Part1
       !                            !
       !                            +- PartBody
       !                                  !                      +------------------+
       !                                  +- Pad.1               ! Selected feature !
       !                                       !                 +------------------+
       !                                       +- Sketch.1 
       +- Part2 (Part2.1)
 </pre>
 it will be Product3</li>
 <li>call the 
<a href="#" onClick="openLink('Document','Selection');return false">Document.Selection</a> property onto this document</li> </ul>
 Otherwise, results are unpredictable.
 <b>Note:</b> During the selection scan to find an automation object, a "Product" string constant specified in
 iFilterType will imply that SelectElement2 will also look at the possible automation object specified
 in 
<a href="#" onClick="openLink('SelectedElement','LeafProduct');return false">SelectedElement.LeafProduct</a> .</ul> After a call to <tt>SelectElement2</tt>, if the return value equals to "Normal", a call to the 
 
<a href="#" onClick="openLink('','Count2');return false">Count2</a> method will return one, and a call to Item2(1) will return the selected element.<p> <b>Note: </b>If the scripting language is Visual Basic for Applications or Visual Basic 6 Development Studio, then,
 you have to know that the use of an interactive selection method such as this one from a form (dialog box) method
 requires some constraints regarding the content of an average form method.<br>
 If your macro possess a form method which calls the 
<a href="#" onClick="openLink('','SelectElement2');return false">SelectElement2</a> method, then, the content of an average form method of your macro must begin by a test, which checks that no form method is currently being executed and,
 otherwise, go out of the method. This constraint enable to prevent that, during the execution of the
 
<a href="#" onClick="openLink('','SelectElement2');return false">SelectElement2</a> method from a form method, when CATIA asks the end user to select a feature: <ul>
 <li>the users select a dialog object of a form (CATIA going on asking the end user to select a feature)</li>
 <li>this selection trigger the corresponding form method</li>
 <li>this run CATIA automation objects methods, CATIA going on asking the end user to select a feature</li>
 </ul>
 which would lead to unpredictable results.<br>
 The code will be the following way:<pre>
  - macro module main variables:
    Dim AFormMethodIsBeingExecuted As Boolean
  - form method calling SelectElement2:
    Private Sub FormPossessingOneMethodCallingSelectElement2_Click()
        Dim InputObjectType(0), Status
        AFormMethodIsBeingExecuted = True
        InputObjectType(0)="TriDimFeatEdge" 
        Status=Selection.SelectElement2(InputObjectType,"Select an edge",false)
        AFormMethodIsBeingExecuted = False
    End Sub
  - average form method:
    Private Sub AverageForm_Click()
        If (AFormMethodIsBeingExecuted) Then Exit Sub
           . . .
     '     content of the form method itself
           . . .   
    End Sub</pre>
 
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iFilterType</tt>
   <dd> An array of strings constants defining the automation object types with which the selection will be filtered.
 During the selection, when the end user will move the mouse (above the geometry or the specification tree), if
 the feature under the mouse does not map iFilterType, the cursor will be the "no entry" cursor.<br>
 The resulting filter is a logical OR of the supplied strings constants. For instance if the array contains two
 elements <tt>"Point"</tt> and <tt>"Line"</tt>, when the end user will move the mouse above the geometry, if
 there is a feature under a mouse, which is a </dd>
</dl>
<a href="#" onClick="openLink('HybridShapePointCoord','');return false">HybridShapePointCoord</a> object (you have to know that the 
<a href="#" onClick="openLink('Point','');return false">Point</a> object is a parent object of the 
<a href="#" onClick="openLink('HybridShapePointCoord','');return false">HybridShapePointCoord</a> object ), then, the cursor will be a "hand" cursor. At the opposite, if there is a feature under a mouse, which is neither a
 
<a href="#" onClick="openLink('Point','');return false">Point</a> nor a 
<a href="#" onClick="openLink('Line','');return false">Line</a>, the cursor will be a "no entry" cursor.<p> Beside the automation object names, the 
<a href="#" onClick="openLink('CATSelectionFilter','');return false">CATSelectionFilter</a> value names are supported. 
    <dt><tt> iMessage</tt>
   <dd> A string which instructs the user what to select. This string is displayed in the message 
 area located at the left of the power input area.
 </dd>
    <dt><tt> iObjectSelectionBeforeCommandUsePossibility</tt>
   <dd> Enables the script to support the possibility, for the user, to select a required object before running the script. 
 <p>If the scripter:
 <ul>
 <li>writes a script calling SelectElement2, giving as iFilterType parameter an array containing one string: "Pad"</li>
 <li>for the first call to SelectElement2 made by the script, the iObjectSelectionBeforeCommandUsePossibility is
 set to True</li>
 <li>the scripter associates the script to an Icon. He will proceed as following:
 <ul>
 <li>in the Tools menu, select the Customize item. A window appears.</li>
 <li>select the Commands Tab. The window contains two lists.</li>
 <li>in the list on the left, select the Macros value</li>
 <li>select the "Show Properties" push button</li>
 <li>select the button on the right of the Icon label. A window containing a list of icons appears</li>
 <li>select an Icon</li>
 <li>select the Close button. The window containing the icon list disappears</li>
 <li>in the list on the right, push the key 1 of the mouse, the cursor beeing on the macro to associate to an Icon.
 Then drag to a desired Toolbar. The Icon has been added to the Toolbar.</li>
 </ul>
 </ul>
 <br>
 Then the user will be able to implement the following scenario:
 <ul>
 <li>select a Pad</li>
 <li>select the Icon mentioned above. This runs the script.</li>
 </ul>
 <br>
 During the execution of the script, the script will detect that the selected Pad is required as input, 
 and the first call to SelectElement2 will not ask to the user to interactively select a Pad: the Pad 
 selected before the script execution will be taken.<br>
 <b>Note:</b>Regarding the features selected by the user (a Pad in the example above), all the automation objects
 specified in </dd>
<a href="#" onClick="openLink('SelectedElement','Value');return false">SelectedElement.Value</a> for the current selection 
<a href="#" onClick="openLink('SelectedElement','');return false">SelectedElement</a> objects must be used: if an automation object specified in 
<a href="#" onClick="openLink('SelectedElement','Value');return false">SelectedElement.Value</a> is not asked by the input filter, the SelectElement2 method will ask the user to interactively select an appropriate element.<p>
 A False value for the iObjectSelectionBeforeCommandUsePossibility parameter may be used although the selection
 is not empty before entering the method. This enables that, during the selection, the selected elements remain
 highlighted. 
 <br><b>Caution: </b>After a call to 
<a href="#" onClick="openLink('','SelectElement2');return false">SelectElement2</a> , the iObjectSelectionBeforeCommandUsePossibility parameter being set to False, the elements which were selected before the call to 
<a href="#" onClick="openLink('','SelectElement2');return false">SelectElement2</a> are not any more in the selection (unless the user selected one of them!). Consequently, such a use of the False value for the
 iObjectSelectionBeforeCommandUsePossibility parameter requires the following code:
 <ul>
 <li>save the selection content in save variables</li>
 <li>call the 
<a href="#" onClick="openLink('','SelectElement2');return false">SelectElement2</a> method, the iObjectSelectionBeforeCommandUsePossibility parameter being set to False</li>
 <li>copy the selected element to a dedicated variable</li>
 <li>merge the selected element with the save variables, and put the result in the selection. This mean:
 <ul>
 <li>if the selected element does not belong to the save variables, add the save variables to the selection</li>
 <li>otherwise, remove the selected element from the save variables, clear the selection and then, add the save
 variables to the selection</li>
 </ul></li>
 </ul>
 
    <dt><tt> oOutputState</tt>
   <dd> The state of the selection command once SelectElement2 returns. It can be either "Normal" 
 (the selection has succeeded), "Cancel" (the user wants to cancel the VB command, which must 
 exit immediately), "Undo" or "Redo".<br>
 <b>Note:</b>The "Cancel" value is returned if one of the following cases occured:
 <ul>
 <li>an external command has been selected</li>
 <li>the ESCAPE key has been selected</li>
 <li>another window has been selected, the window document beeing another document than the current document</li>
 </ul>
 <b>Caution:</b>All scripts should exit (after the necessary cleanings) when the "Cancel" value is returned.</br>
 If the script does not exit (beside the cleanings) when the "Cancel" value is returned, but calls another
 interactive method such as </dd>
<a href="#" onClick="openLink('','SelectElement2');return false">SelectElement2</a> , and, during execution, the user select an external command (which triggers the return of the "Cancel" value), then, the execution of the other interactive method will display
 an error message.
 
  <dt> <b>Example:</b> 
  <dd>  The following example asks the end user to select a sketch (see 
<a href="#" onClick="openLink('Sketch','');return false">Sketch</a> ) in the current  window, and creates a Pad (see 
<a href="#" onClick="openLink('ShapeFactory','AddNewPad');return false">ShapeFactory.AddNewPad</a> ). If, before the script execution, a sketch was already selected, it will be taken into account and the end user will ne be asked to select a sketch.<br>
 Then, it asks the end user to select an edge of the pad, and creates an edge fillet. Then, is asks the end user to
 select a 1-D entity whose geometry is rectilinear (see 
<a href="#" onClick="openLink('CATSelectionFilter','');return false">CATSelectionFilter</a> ), such as an edge of the Pad.<br> Then, it asks the end user to select a pad face perpendicular to the 1-D entity previously selected. Then, it
 creates a hole at the face selected point, the hole direction being the direction of the 1-D selected entity.<br>
 During the face selection, the 1-D entity previously selected is highlighted.
 <pre>
 Dim Document,Part,Selection,ShapeFactory,SketchHasBeenAcquiredAtLeastOnce,EdgeHasBeenAcquiredAtLeastOnce
 Dim FaceHasBeenAcquiredAtLeastOnce,MonoDimEntityHasBeenAcquiredAtLeastOnce,FirstExtrudeNotFinished,FilletEdge
 Dim PadNotFinished,Status,SketchForPad,Pad,FilletNotFinished,Fillet,MonoDimEntityDeterminationNotFinished
 Dim SelectedElement,MonoDimEntity,HoleNotFinished,PadFace,Hole,InputObjectType(0),HoleLocation(2),MonoDimEntitySave
 Dim SketchForPadPartBody
 Set Document = CATIA.ActiveDocument : Set Part = Document.Part : Set Selection = Document.Selection
 Set ShapeFactory = Part.ShapeFactory  
 SketchHasBeenAcquiredAtLeastOnce = False : EdgeHasBeenAcquiredAtLeastOnce = False
 FaceHasBeenAcquiredAtLeastOnce = False : MonoDimEntityHasBeenAcquiredAtLeastOnce = False 
 FirstExtrudeNotFinished = True : PadNotFinished = True : ReDim SelectionAtBeginning(1)
'We save the current selection content
 ReDim SelectionAtBeginning(Selection.Count2)
 for SelectionObjectIndex = 0 to Selection.Count2-1
     Set SelectionAtBeginning(SelectionObjectIndex) = Selection.Item2(1).Value
 next
 SelectionAtBeginningLength = Selection.Count2
'Feature creation
 do while PadNotFinished
'  We propose to the user that he select a sketch
     InputObjectType(0)="Sketch" 
     Status=Selection.<font color="red">SelectElement2</font>(InputObjectType,"Select a sketch",true)
     if ((Status = "Cancel") Or (Status = "Undo")) then 
'      We restore the selection to its initial content
         Selection.Clear
         for SelectionObjectIndex = 0 to SelectionAtBeginningLength-1
             Selection.Add SelectionAtBeginning(SelectionObjectIndex)
         next
         Exit Sub
     elseif (Status = "Redo" And Not SketchHasBeenAcquiredAtLeastOnce ) then
'      We do nothing: Redo has no meaning in this context
     else
         if (Status &lt;&gt; "Redo") then Set SketchForPad = Selection.Item2(1).Value
         SketchHasBeenAcquiredAtLeastOnce = True
'      We determine the PartBody corresponding to the Sketch
         Set SketchForPadPartBody = SketchForPad.Parent.Parent
'      We create the Pad
         Set Pad = ShapeFactory.AddNewPad(SketchForPad,20.0)
         Pad.SecondLimit.Dimension.Value = 0.0 : Part.Update
         PadNotFinished = False
         Selection.Clear
'      We create the fillet and the hole
         FilletNotFinished = True
         do while (FilletNotFinished And Not PadNotFinished)
'          We propose to the user that he select an edge
             InputObjectType(0)="TriDimFeatEdge" 
             Status=Selection.<font color="red">SelectElement2</font>(InputObjectType,"Select an edge of the Pad",false)        
             if (Status = "Cancel") then 
'              We remove the pad, restore the selection to its initial content and go out
                 Selection.Clear : Selection.Add(Pad) : Selection.Delete
                 Part.Update
                 Selection.Clear
                 for SelectionObjectIndex = 0 to SelectionAtBeginningLength-1
                     Selection.Add SelectionAtBeginning(SelectionObjectIndex)
                 next
                 Exit Sub
             elseif (Status = "Redo" And Not EdgeHasBeenAcquiredAtLeastOnce ) then
'              We do nothing: Redo has no meaning in this context
             elseif (Status = "Undo") then
'              We copy the sketch to the clipboard
                 Selection.Clear : Selection.Add(SketchForPad)
'              We remove the pad
                 Selection.Clear : Selection.Add(Pad) : Selection.Delete : Part.Update
'              We re-create the sketch
                 Selection.Clear : Selection.Add(SketchForPadPartBody) : Selection.Paste()
'              We store the fact that the Pad is not finished
                 PadNotFinished = True
             else
                 if (Status &lt;&gt; "Redo") then Set FilletEdge = Selection.Item2(1).Value
                 EdgeHasBeenAcquiredAtLeastOnce = True
'              Create the Fillet
                 Set Fillet = ShapeFactory.AddNewSolidEdgeFilletWithConstantRadius(FilletEdge, catTangencyFilletEdgePropagation,5.0)
                 Part.Update
                 FilletNotFinished = False
                 Selection.Clear
'              Determine the 1-D entity
                 MonoDimEntityDeterminationNotFinished = True
                 do while (MonoDimEntityDeterminationNotFinished And Not FilletNotFinished)
'                  We propose to the user that he select 1-D entity whose geometry is rectilinear
                     InputObjectType(0)="RectilinearMonoDim" 
                     Status=Selection.<font color="red">SelectElement2</font>(InputObjectType, _ 
                                                     "Select a 1-D entity whose geometry is rectilinear",false)   
                     if (Status = "Cancel") then
'                      We remove the fillet, the pad, restore the selection to its initial content and go out
                         Selection.Clear : Selection.Add(Fillet) : Selection.Delete
                         Selection.Clear : Selection.Add(Pad) : Selection.Delete
                         Part.Update
                         Selection.Clear
                         for SelectionObjectIndex = 0 to SelectionAtBeginningLength-1
                             Selection.Add SelectionAtBeginning(SelectionObjectIndex)
                         next
                         Exit Sub
                     elseif (Status = "Redo" And Not MonoDimEntityHasBeenAcquiredAtLeastOnce ) then
'                      We do nothing: Redo has no meaning in this context
                     elseif (Status = "Undo") then 
'                      We remove the fillet
                         Selection.Clear : Selection.Add(Fillet) : Selection.Delete
                         Part.Update
                         FilletNotFinished = True
                     else
                         if (Status = "Redo") then 
                           Selection.Clear : Selection.Add(MonoDimEntity)
                         else
                           Set SelectedElement = Selection.Item2(1)
                           Set MonoDimEntity = SelectedElement.Value
                         end if
                         MonoDimEntityHasBeenAcquiredAtLeastOnce = True
                         MonoDimEntityDeterminationNotFinished = False  
'                      Create the Hole
                         HoleNotFinished = True
                         do while (HoleNotFinished And Not MonoDimEntityDeterminationNotFinished)
'                          We save the selection content in save variables.
'                          This corresponds to the fact that:
'                            - we want that, during the following call to SelectElement2, the 1-D entity previously
'                              selected remain highlighted
'                            - this is done using the False value for the iObjectSelectionBeforeCommandUsePossibility
'                              parameter, the selection containing the 1-D entity. It requires that the selection
'                              content be saved
                           Set MonoDimEntitySave = Selection.Item2(1).Value
'                          We propose to the user that he select a face
                             InputObjectType(0)="Face" 
                             Status=Selection.<font color="red">SelectElement2</font>(InputObjectType, _ 
                                                           "Select a face perpendicular to the 1-D entity",false)   
                             if (Status = "Cancel") then 
'                              We remove the fillet, the pad, restore the selection to its initial content and go out
                                 Selection.Clear : Selection.Add(Fillet) : Selection.Delete
                                 Selection.Clear : Selection.Add(Pad) : Selection.Delete
                                 Selection.Clear
                                 for SelectionObjectIndex = 0 to SelectionAtBeginningLength-1
                                     Selection.Add SelectionAtBeginning(SelectionObjectIndex)
                                 next
                                 Part.Update
                                 Exit Sub
                             elseif (Status = "Redo" And Not FaceHasBeenAcquiredAtLeastOnce ) then
'                              We do nothing: Redo has no meaning in this context
                             elseif (Status = "Undo") then
                               Selection.Clear
'                              The 1-D entity must be re-selected
                                 MonoDimEntityDeterminationNotFinished = True
                             else
                                 if (Status &lt;&gt; "Redo") then 
                                     Set SelectedElement = Selection.Item2(1)
                                     Set PadFace = SelectedElement.Value
                                     SelectedElement.GetCoordinates HoleLocation
'                                  We merge the selected element with the save variables, and put the result in the selection
                                     Selection.Add MonoDimEntitySave
                                 end if
                                 FaceHasBeenAcquiredAtLeastOnce = True
'                              We create the Hole
                                 Set Hole = Part.ShapeFactory.AddNewHoleFromPoint(HoleLocation(0),HoleLocation(1),HoleLocation(2),PadFace,10.0)
                                 Hole.ThreadingMode = 1 : Hole.ThreadSide = 0 : Hole.Diameter.Value = 5.0
                                 Hole.SetDirection FilletEdge
                                 Part.Update 
                                 HoleNotFinished = False
'                              We clear the selection
                                 Selection.Clear
                             end if
                         loop
                     end if
                 loop
             end if
         loop
     end if
 loop
 </pre>
</dl>
</dl>
<a name="SelectElement3"><dt>

<table><tr><td>o Func <b>SelectElement3</b>(<td><script type="text/javascript"> activateLink('CATSafeArrayVariant','CATSafeArrayVariant')</script> <td><tt>iFilterType</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('CATBSTR','CATBSTR')</script> <td><tt>iMessage</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('boolean','boolean')</script> <td><tt>iObjectSelectionBeforeCommandUsePossibility</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('CATMultiSelectionMode','CATMultiSelectionMode')</script> <td><tt>iMultiSelectionMode</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('boolean','boolean')</script> <td><tt>iTooltip</tt>) As <script type="text/javascript"> activateLink('CATBSTR','CATBSTR')</script> </table></dt>
<dl>
  <dd>
 Runs an interactive selection command, exhaustive version.
 <br><b>Role</b>: <tt>SelectElement3</tt> asks the end user to select a feature (in the geometry or in the
 specification tree). It is identical to the 
<a href="#" onClick="openLink('','SelectElement2');return false">SelectElement2</a> method except that it manages complex uses through the specification of 2 more parameters.<br>
 
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iFilterType</tt>
   <dd> An array of strings constants defining the automation object types with which the selection will be filtered.
 </dd>
    <dt><tt> iMessage</tt>
   <dd> A string which instructs the user what to select. This string is displayed in the message 
 area located at the left of the power input area.
 </dd>
    <dt><tt> iObjectSelectionBeforeCommandUsePossibility</tt>
   <dd> Enables the script to support the possibility, for the user, to select required object(s) before running the script.
 See </dd>
</dl>
<a href="#" onClick="openLink('','SelectElement2');return false">SelectElement2</a> . 
    <dt><tt> iMultiSelectionMode</tt>
   <dd> The type of multi-selection which will be offered to the user.
 </dd>
    <dt><tt> iTooltip</tt>
   <dd> Displays a tooltip as soon as an object is located under the mouse without being selected.
 </dd>
    <dt><tt> oOutputState</tt>
   <dd> The state of the selection command once SelectElement3 returns. It can be either "Normal", "Cancel", "Undo"
 or "Redo". See </dd>
<a href="#" onClick="openLink('','SelectElement2');return false">SelectElement2</a> . 
  <dt> <b>Example:</b> 
  <dd>  This first example asks the end user to select several points (see 
<a href="#" onClick="openLink('Point','');return false">Point</a> ) into the current Part window, drawing a trap, and performs a symmetry with respect to the XZ plane on the selected points 
 (see 
<a href="#" onClick="openLink('HybridShapeSymmetry','');return false">HybridShapeSymmetry</a> ). The points can be selected before the script be run. <pre>
 Dim Document,Part,Selection,HybridShapeFactory,HybridBodies,HybridBody,OriginElements,Plane,PlaneReference,Status
 Dim InputObjectType(0),PointIndex,PointReference,HybridShapeSymmetry
 Set Document = CATIA.ActiveDocument : Set Part = Document.Part : Set Selection = Document.Selection
 Set HybridShapeFactory = Part.HybridShapeFactory  
 Set Bodies = Part.Bodies
 Set Body = Bodies.Item("PartBody")
 Set OriginElements = Part.OriginElements
 Set Plane = OriginElements.PlaneZX
 Set PlaneReference = Part.CreateReferenceFromObject(Plane)
'We propose to the user that he select several points, drawing a trap
 InputObjectType(0)="Point" 
 Status=Selection.<font color="red">SelectElement3</font>(InputObjectType,"Select points", _
                                 true,CATMultiSelTriggWhenSelPerf,false)
 if (Status = "Cancel") then Exit Sub
 For PointIndex = 1 to Selection.Count2
     Set PointReference = Part.CreateReferenceFromObject(Selection.Item2(PointIndex).Value)
     Set HybridShapeSymmetry = HybridShapeFactory.AddNewSymmetry(PointReference,PlaneReference)
     HybridShapeSymmetry.VolumeResult = False
     Body.InsertHybridShape HybridShapeSymmetry
     Part.InWorkObject = HybridShapeSymmetry
     Part.Update 
 next
 Selection.Clear
 </pre>
 
  <dt> <b>Example:</b> 
  <dd>  This second example illustrates the use of the CATMultiSelTriggWhenUserValidatesSelection value for the 
 iMultiSelectionMode parameter. This example is a training tool enabling the user to learn how to use the "Symmetry"
 command of the "Geometry Modification" toolbar of the Drafting workbench.<br>
 It creates a drawing containing a line and three points, and guides the user in:
 <ul>
 <li>the selection of points</li>
 <li>the selection of the symmetry axis</li>
 </ul>
 the selected points being moved by symmetry according to the selected axis.
 <pre>
'We create a drawing
 Set Documents = CATIA.Documents : Set Document = Documents.Add("Drawing") : Document.Standard = catISO
 Set DrawingSheets = Document.Sheets : Set DrawingSheet = DrawingSheets.Item("Sheet.1")
 DrawingSheet.PaperSize = catPaperA0 : DrawingSheet.Scale = 1.000000 : DrawingSheet.Orientation = catPaperLandscape
 Set DrawingViews = DrawingSheet.Views : Set DrawingView = DrawingViews.ActiveView
 Set Factory2D = DrawingView.Factory2D : Set Selection = Document.Selection : Dim Coordinates(2)
 ReDim InputObjectType(0) : Dim SelectedPoint(3) : SelectedPointCount = 0
'We create a horizontal line with a zero ordinate
 Set LineLeftExtremity = Factory2D.CreatePoint(-100.0, 0.0) : LineLeftExtremity.ReportName = 3
 Set LineRightExtremity = Factory2D.CreatePoint(100.0, 0.0) : LineRightExtremity.ReportName = 4
 Set Line2D = Factory2D.CreateLine(-100.0, 0.0, 100.0, 0.0) : Line2D.ReportName = 5
 Line2D.StartPoint = LineLeftExtremity : Line2D.EndPoint = LineRightExtremity
'We create three points
 Set Point2D1 = Factory2D.CreatePoint(-50.0, 50.0) : Point2D1.ReportName = 6 : Point2D1.Construction = False
 Set Point2D2 = Factory2D.CreatePoint(0.0, 70.0) : Point2D2.ReportName = 7 : Point2D1.Construction = False
 Set Point2D3 = Factory2D.CreatePoint(50.0, 50.0) : Point2D3.ReportName = 8 : Point2D3.Construction = False
'We mention to the user that he will select the set of elements to be symmetrized
 msgbox "This tool will enable you to learn how to use the Symmetry command." & Chr(13) & Chr(13) & _ 
        "Suppose you selected the Symmetry command." & Chr(13) & _ 
        "You will first select several points to be symmetrized"
'We propose to the user that he select several points
 InputObjectType(0)="Point2D" 
 Status=Selection.<font color="red">SelectElement3</font>(InputObjectType,"Select the set of elements to be symmetrized", _
                                 true,CATMultiSelTriggWhenUserValidatesSelection,false)
 if (Status = "Cancel") then Exit Sub
'We add the selected points to SelectedPoint
 for PointIndex = 0 to Selection.Count2-1
     Set SelectedPoint(PointIndex) = Selection.Item2(PointIndex+1).Value : SelectedPointCount = SelectedPointCount+1
 next   
'We mention to the user that he will select the axis from which the elements will remain equidistant
 msgbox "You will then select the line from which the elements will remain equidistant"
'We propose to the user that he select the line
 InputObjectType(0)="Line2D" 
 Status=Selection.SelectElement2(InputObjectType, _ 
                                 "Select the line or axis from which the elements will remain equidistant", false)
 if (Status = "Cancel") then Exit Sub
'We move the selected points by symmetry according to the selected line
 for PointIndex = 0 to SelectedPointCount-1
     Set CurrentPoint2D = SelectedPoint(PointIndex)
     CurrentPoint2D.GetCoordinates Coordinates
     CurrentPoint2D.SetData Coordinates(0), -Coordinates(1)
 next   
 Selection.Clear
'We mention to the user that the points have successfully been moved
 msgbox "The points have successfully been moved."
 </pre>
</dl>
</dl>
<a name="SelectElement4"><dt>

<table><tr><td>o Func <b>SelectElement4</b>(<td><script type="text/javascript"> activateLink('CATSafeArrayVariant','CATSafeArrayVariant')</script> <td><tt>iFilterType</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('CATBSTR','CATBSTR')</script> <td><tt>iActiveDocumentMessage</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('CATBSTR','CATBSTR')</script> <td><tt>iNonActiveDocumentMessage</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('boolean','boolean')</script> <td><tt>iTooltip</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('Document','Document')</script> <td><tt>oDocument</tt>) As <script type="text/javascript"> activateLink('CATBSTR','CATBSTR')</script> </table></dt>
<dl>
  <dd>
 Runs an interactive selection command, enabling the selection in a non active document.
 <br><b>Role</b>: <tt>SelectElement4</tt> asks the end user to select a feature (in the geometry or in the
 specification tree) of a non active document. During the selection, when end user will move the mouse above
 a window corresponding to a non active document, when he will move the mouse above a feature which maps the given
 filter, the mouse pointer will be the "hand" cursor. When he will move the mouse above a feature which does not map
 the given filter, the mouse pointer will be the "no entry" cursor.<br> 
 This method may be used, for example, to write a script which does the following: 
 <ul>
 <li>a drawing is currently edited</li>
 <li>request that the user select a reference plane in the 3D geometry (a part)</li>
 <li>creation of a front view in the drawing, projecting the 3D geometry onto the selected reference plane</li>
 </ul><br>
 Compared to the 
<a href="#" onClick="openLink('','SelectElement2');return false">SelectElement2</a> , the result of the selection will not be accessed through the 
<a href="#" onClick="openLink('','Count2');return false">Count2</a> and 
<a href="#" onClick="openLink('','Item2');return false">Item2</a> methods of the current selection object, but through the 
<a href="#" onClick="openLink('','Count2');return false">Count2</a> and 
<a href="#" onClick="openLink('','Item2');return false">Item2</a> methods of the Selection object aggregated by the 
<a href="#" onClick="openLink('Document','');return false">Document</a> object returned through the oDocument parameter.</br> <b>Note:</b>The Selection object aggregated by the 
<a href="#" onClick="openLink('Document','');return false">Document</a> object returned through the oDocument parameter is emptied by before the effective interactive selection.
 
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iFilterType</tt>
   <dd> An array of strings constants defining the automation object types with which the selection will be filtered. 
 </dd>
    <dt><tt> iActiveDocumentMessage</tt>
   <dd> A string which instructs the user what to select, which will be displayed into the active document. This string is
 displayed in the message area located at the left of the power input area.
 </dd>
    <dt><tt> iNonActiveDocumentMessage</tt>
   <dd> A string which instructs the user what to select, which will be displayed into the non active document.
 </dd>
    <dt><tt> iTooltip</tt>
   <dd> Displays a tooltip as soon as an object is located under the mouse without being selected.
 </dd>
    <dt><tt> oOutputState</tt>
   <dd> The state of the selection command once SelectElement3 returns. It can be either "Normal", "Cancel", "Undo".
 </dd>
</dl>
  <dt> <b>Example:</b> 
  <dd>  The following example supposes a part, containing a pad, and drawing are currently edited, the drawing
 window beeing the current window. It asks the end user to select a 2-D topological entity, such as a 
 
<a href="#" onClick="openLink('Plane','');return false">Plane</a> , in a part. Then it creates a front view in the drawing, projecting the 3D geometry onto the selected 2-D topological entity.
 <pre>
 Dim DrawingSelection,DrawingSheets,DrawingSheet,DrawingViews,DrawingFrontView : ReDim DrawingSelectionAtBeginning(1)
 Dim Status,InputObjectType(0),Plane,Drawing,DrawingViewGenerativeBehavior,V1(2),V2(2),PartDocument
 Set Drawing = CATIA.ActiveDocument : Set DrawingSelection = Drawing.Selection : Set DrawingSheets  = Drawing.Sheets 
 Set DrawingSheet = DrawingSheets.ActiveSheet
'We save the current selection content
 ReDim DrawingSelectionAtBeginning(DrawingSelection.Count2)
 for SelectionObjectIndex = 0 to DrawingSelection.Count2-1
     Set DrawingSelectionAtBeginning(SelectionObjectIndex) = DrawingSelection.Item2(1).Value
 next
 SelectionAtBeginningLength = DrawingSelection.Count2
'Feature creation
 InputObjectType(0)="BiDimInfinite" 
 Status=DrawingSelection.<font color="red">SelectElement4</font>(InputObjectType,"Select a 2-D topological entity in a 3-D geometry", _
                                        "Select a 2-D topological entity",false,PartDocument)
 if ((Status = "Cancel") Or (Status = "Undo") Or (Status = "Redo")) then 
'  We restore the selection to its initial content
     PartDocument.Selection.Clear
     for SelectionObjectIndex = 0 to SelectionAtBeginningLength-1
         DrawingSelection.Add DrawingSelectionAtBeginning(SelectionObjectIndex)
     next
     Exit Sub
 else
     Set BiDimFeature = PartDocument.Selection.Item2(1).Value
     BiDimFeatureType = TypeName(BiDimFeature)
     if ((BiDimFeatureType="Plane") Or (BiDimFeatureType="PlanarFace")) then
       BiDimFeature.GetFirstAxis V1
       BiDimFeature.GetSecondAxis V2
     else
       Exit Sub
     end if
'  We create a view called "Front View" in the current sheet, using Plane as projection plane, and whose origin
'  coordinates are 300,150
     Set DrawingFrontView = DrawingSheet.Views.Add("Front View")
     Set DrawingViewGenerativeBehavior = DrawingFrontView.GenerativeBehavior
     DrawingViewGenerativeBehavior.Document = PartDocument
     DrawingViewGenerativeBehavior.DefineFrontView V1(0), V1(1), V1(2), V2(0), V2(1), V2(2)
     DrawingFrontView.x = 300
     DrawingFrontView.y = 150
     DrawingViewGenerativeBehavior.Update 
'  We clear the PartDocument Selection object
     PartDocument.Selection.Clear
 end if
 </pre>
</dl>
</dl>

</body>
<hr><p><i>
Copyright &#169; 1999-2011, Dassault Syst&#232;mes. All rights reserved.</i></p>
</html>
