<html>

<head>
<meta http-equiv="Content-Language" content="en-us">
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<meta name="GENERATOR" content="Microsoft FrontPage 5.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
<title>Changing the Pattern Parameters</title>
<link rel="stylesheet" type="text/css" href="../CAAScrBase/caav5.css">
<script language="JavaScript" src="../CAAScrJavaScript/submit.js">
</script>
</head>

<body>

<table border="0" width="100%">
  <tr>
    <td>
    <h2>Part Design</h2>
    </td>
    <td align="right" valign="top">
    <h2><a name="Top"></a>Changing the Pattern Parameters</h2>
    </td>
  </tr>
</table>
<hr>
<!null ---------------------------------comment--->
<table border="0" width="100%" cellspacing="0" cellpadding="5" style="border-collapse: collapse" bordercolor="#111111">
  <tr>
    <td valign="top">
    <img border="0" src="../CAAScrBase/images/atarget.gif" width="32" height="32"></td>
    <td><a name="Learn"></a>This macro shows you how to change the description 
    of a pattern to the unequal spacing angular mode.<br>
    This macro allows you to define:<ul>
      <li>A new instances number.</li>
      <li>The unequal spacing angular mode.</li>
      <li>The angular values between instances.</li>
    </ul>
    <p>It modifies the <i>
    <a href="#" onclick="javascript:CAAlink('IDL', 'PartInterfaces', 'CircPattern');return false;">
    CircPattern</a></i> object from its methods and properties, and update the 
    part.</td>
  </tr>
  <tr>
    <td valign="top">
    <img border="0" src="../CAAScrBase/images/ainfo.gif" width="32" height="32"></td>
    <td>
    <ul>
      <li><a name="How"></a>Open the
      <a href="samples/CAAPriChangePattern.CATPart">CAAPriChangePattern.CATPart</a> 
      document.</li>
      <li>Reference in the application the catscript file:&nbsp;
      <a href="CAAPriChangePatternSource.htm">CAAPriChangePattern.htm</a>.</li>
      <li>Run the macro.</li>
      <li>Select CircPattern.1 in the specification tree or in the the geometry.</li>
    </ul>
    </td>
  </tr>
  <tr>
    <td valign="top">
    <img border="0" src="../CAAScrBase/images/ascenari.gif" width="32" height="32"></td>
    <td><a name="Step"></a>CAAPriPatternDescription includes the following 
    steps:<ol>
      <li><a href="#Step1">Prolog</a></li>
      <li><a href="#Step2">Looking for the Circular Pattern Object in the 
      Selection</a></li>
      <li><a href="#Step3">Applying the Circular Pattern Description</a></li>
    </ol>
    <h4>Prolog<a name="Step1"></a></h4>
    <p>Load the CAAPriPatternDescription.CATPart that contains two circular 
    patterns.</p>
    <p><img border="1" src="images/CAAPriChangePattern01.gif" hspace="40" width="450" height="300"></p>
    <p><img border="1" src="images/CAAPriChangePattern03.gif" hspace="40" width="111" height="194"></p>
    <p>Run the macro.</p>
    <table class="code" style="border-collapse: collapse" bordercolor="#111111" cellpadding="0" cellspacing="0">
      <tr>
        <td>
        <pre>  ...
<font color="#008000">' ------------</font>
<font color="#008000">' Get the part document</font>
<font color="#008000">' ------------</font>
<font color="#0000FF">Set </font>oPartDocument = CATIA.ActiveDocument
<font color="#008000">' ------------</font>
<font color="#008000">' Get the part</font>
<font color="#008000">' ------------</font>
<font color="#0000FF">Set </font>oPart = oPartDocument.Part
   ...</pre>
        </td>
      </tr>
    </table>
    <p>Once the macro has been started, the <code>oPartDocument </code>and <code>
    oPart </code>variables are declared to receive the instance of the part 
    document and the part.</p>
    <h4>Looking for the Circular Pattern Object in the Selection<a name="Step2"></a></h4>
    <table class="code">
      <tr>
        <td>
        <pre>...
<font color="#008000">' ------------</font>
<font color="#008000">' Get the selection</font>
<font color="#008000">' ------------</font>
<font color="#0000FF">Set </font>oSelection = oPartDocument.Selection
<font color="#008000">' ------------</font>
<font color="#008000">' Set the selection type</font>
<font color="#008000">' ------------</font>
InputObjectType(0) = &quot;CircPattern&quot;
<font color="#008000">' ------------</font>
<font color="#008000">' Get the status</font>
<font color="#008000">' ------------</font>
oStatus = oSelection.SelectElement2 ( InputObjectType, &quot;Select a circular pattern&quot;, True )
<font color="#008000">' ------------</font>
<font color="#008000">' Get the object in the selection</font>
<font color="#008000">' ------------</font>
<font color="#0000FF">Set </font>oCircularPattern = oSelection.Item(1).Value...</pre>
        </td>
      </tr>
    </table>
    <p><code>oSelection </code>variable is declared to receive the instance of 
    the part document selection, the string containing selection type name is 
    defined in an array <code>InputObjectType</code>, the <code>SelectElement2</code> 
    method is used to retrieve the selection:</p>
    <ul>
      <li>If the document selection is empty or contains an object other than a 
      circular pattern, a message is displayed in the left bottom corner of the 
      application, <code>Select a circular pattern</code>.</li>
      <li>If the selection contains a circular pattern, no message is displayed.</li>
    </ul>
    <p>Take care, this allows you to select one object only in both cases!</p>
    <p><code>oCircularPattern </code>variable is declared to receive the 
    instance of the circular pattern from the selection collection.</p>
    <h4>Applying the Circular Pattern Description<a name="Step3"></a></h4>
    <table class="code">
      <tr>
        <td>
        <pre>...
<font color="#008000">' ------------</font>
<font color="#008000">' Set the circular pattern instance number</font>
<font color="#008000">' ------------</font>
oCircularPattern.AngularRepartition.InstancesCount.Value = 6
...</pre>
        </td>
      </tr>
    </table>
    <p>The circular pattern number of instances is set to 6.</p>
    <table class="code">
      <tr>
        <td>
        <pre>...
<font color="#008000">' ------------</font>
<font color="#008000">' Set the circular pattern instance as Unequal Angular Spacing mode</font>
<font color="#008000">' ------------</font>
oCircularPattern.CircularPatternParameters = catUnequalAngularSpacing
oCircularPattern.SetUnequalStep 6
...</pre>
        </td>
      </tr>
    </table>
    <p>The circular pattern parameter is set to Unequal Angular Spacing.</p>
    <table class="code">
      <tr>
        <td>
        <pre>...
<font color="#008000">' ------------</font>
<font color="#008000">' Set the circular pattern Unequal Angular Spacing</font>
<font color="#008000">' ------------</font>
oCircularPattern.SetInstanceAngularSpacing 2, 30.000000
oCircularPattern.SetInstanceAngularSpacing 3, 75.000000
oCircularPattern.SetInstanceAngularSpacing 4, 75.000000
oCircularPattern.SetInstanceAngularSpacing 5, 30.000000
oCircularPattern.SetInstanceAngularSpacing 6, 75.000000
...</pre>
        </td>
      </tr>
    </table>
    <p>For each circular pattern instances the angular spacing is modified.</p>
    <table class="code">
      <tr>
        <td>
        <pre>...
<font color="#008000">' ------------</font>
<font color="#008000">' Update the part</font>
<font color="#008000">' ------------</font>
oPart.Update 
...</pre>
        </td>
      </tr>
    </table>
    <p>The part document is updated, the circular pattern is modified.</p>
    <p><img border="1" src="images/CAAPriChangePattern02.gif" hspace="40" width="450" height="300"></td>
  </tr>
</table>
<p align="center">
<img border="0" src="../CAAScrBase/images/aendtask.gif" width="64" height="32"></p>
<p align="right">[<a href="#Top">Top</a>]</p>
<hr>
<!null ---------------------------------comment--->
<h4><a name="InShort"></a>In Short</h4>
<p>This use case has shown how to modify specifications of an existing circular 
pattern.</p>
<p align="right">[<a href="#Top">Top</a>]</p>
<hr>
<!null ---------------------------------comment--->
<h4><a name="References"></a>References</h4>
<table border="0" width="100%">
  <tr>
    <td valign="top" width="40">[1]</td>
    <td><a href="../CAAScdInfUseCases/CAAInfLauchMacro.htm">Replaying 
    a macro</a></td>
  </tr>
  <tr>
    <td valign="top" width="40"></td>
    <td></td>
  </tr>
  <tr>
    <td colspan="2" align="right" width="100%">[<a href="#Top">Top</a>]</td>
  </tr>
</table>
<hr>
<!null ---------------------------------comment--->
<p><i>Copyright © 2004, Dassault Systèmes. All rights reserved.</i></p>

</body>

</html>
