<html><head><meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"><title>CAAPriCreateEdgeFillet.CATScript</title><link rel="stylesheet" type="text/css" href="../CAAScrBase/caav5.css"></head><body><pre>
<font color="#0000FF">Option Explicit</font>
<font color="#008000">' COPYRIGHT DASSAULT SYSTEMES 2000</font>
<font color="#0000FF">Dim </font>Language<font color="#0000FF"> As </font>String
Language=&quot;VBSCRIPT&quot;

<font color="#008000">' ****************************************************************************</font>
<font color="#008000">'   Purpose     :  Create two EdgeFillet on the vertical edges of a pad</font>
<font color="#008000">'                  and on the top and bottom faces</font>
<font color="#008000">'</font>
<font color="#008000">'   Author      :</font>
<font color="#008000">'   Languages   :  VBScript</font>
<font color="#008000">'   Locales     :  English</font>
<font color="#008000">'   CATIA Level :  V5R6</font>
<font color="#008000">'*****************************************************************************</font>

<font color="#0000FF">Sub </font>CATMain()

<font color="#0000FF">    Dim </font>oPartDocument<font color="#0000FF"> As </font>PartDocument
<font color="#0000FF">    Set </font>oPartDocument = CATIA.Documents.Open(<font FACE="Courier New" SIZE="2">sDocPath &amp; &quot;\online\CAAScdPriUseCases\samples\Pad.CATPart&quot;)</font>

<font color="#0000FF">    Dim </font>oPart<font color="#0000FF"> As </font>Part
<font color="#0000FF">    Set </font>oPart =  CATIA.ActiveDocument.Part

    <font color="#008000">' Retrieve the part body of the document containing the pad to be used</font>
<font color="#0000FF">    Dim </font>oBody<font color="#0000FF"> As </font>Body
<font color="#0000FF">    Set </font>oBody = oPart.Bodies.Item  ( &quot;MechanicalTool.1&quot; ) 

    <font color="#008000">' Retrieve the pad of the body</font>
<font color="#0000FF">    Dim </font>oPad<font color="#0000FF"> As </font>Pad
<font color="#0000FF">    Set </font>oPad = oBody.Shapes.Item  ( &quot;Pad.1&quot; )

    <font color="#008000">' Retrieve the vertical edges of the pad to be filleted</font>
<font color="#0000FF">    Dim </font>oEdge1<font color="#0000FF"> As </font>Reference
<font color="#0000FF">    Set </font>oEdge1 = oPart.CreateReferenceFromBRepName  ( &quot;REdge:(Edge:(Face:(Brp:(Pad.1;0:(Brp:(Sketch.1;1)));None:());Face:(Brp:(Pad.1;0:(Brp:(Sketch.1;2)));None:());None:(Limits1:();Limits2:()));WithTemporaryBody;WithoutBuildError;WithSelectingFeatureSupport)&quot;, oPad ) 

<font color="#0000FF">    Dim </font>oEdge2<font color="#0000FF"> As </font>Reference
<font color="#0000FF">    Set </font>oEdge2 = oPart.CreateReferenceFromBRepName  ( &quot;REdge:(Edge:(Face:(Brp:(Pad.1;0:(Brp:(Sketch.1;2)));None:());Face:(Brp:(Pad.1;0:(Brp:(Sketch.1;3)));None:());None:(Limits1:();Limits2:()));WithTemporaryBody;WithoutBuildError;WithSelectingFeatureSupport)&quot;, oPad ) 

<font color="#0000FF">    Dim </font>oEdge3<font color="#0000FF"> As </font>Reference
<font color="#0000FF">    Set </font>oEdge3 = oPart.CreateReferenceFromBRepName  ( &quot;REdge:(Edge:(Face:(Brp:(Pad.1;0:(Brp:(Sketch.1;3)));None:());Face:(Brp:(Pad.1;0:(Brp:(Sketch.1;4)));None:());None:(Limits1:();Limits2:()));WithTemporaryBody;WithoutBuildError;WithSelectingFeatureSupport)&quot;, oPad ) 

<font color="#0000FF">    Dim </font>oEdge4<font color="#0000FF"> As </font>Reference
<font color="#0000FF">    Set </font>oEdge4 = oPart.CreateReferenceFromBRepName  ( &quot;REdge:(Edge:(Face:(Brp:(Pad.1;0:(Brp:(Sketch.1;4)));None:());Face:(Brp:(Pad.1;0:(Brp:(Sketch.1;1)));None:());None:(Limits1:();Limits2:()));WithTemporaryBody;WithoutBuildError;WithSelectingFeatureSupport)&quot;, oPad ) 

    <font color="#008000">' Define the fillet to be created with the first edge</font>
<font color="#0000FF">    Dim </font>oEdgeFillet1<font color="#0000FF"> As </font>ConstRadEdgeFillet
<font color="#0000FF">    Set </font>oEdgeFillet1 = oPart.ShapeFactory.AddNewEdgeFilletWithConstantRadius  ( oEdge1, 1, 5.000000 ) 

    <font color="#008000">' Add the others edges to be filleted </font>
    oEdgeFillet1.AddObjectToFillet oEdge2
    oEdgeFillet1.AddObjectToFillet oEdge3
    oEdgeFillet1.AddObjectToFillet oEdge4

    <font color="#008000">' Define the fillet radius to 5 mm</font>
    oEdgeFillet1.Radius.Value = 5.000000

    <font color="#008000">' Define the fillet to be propagated to all the tangent contiguous edges</font>
    oEdgeFillet1.EdgePropagation = 1

    <font color="#008000">' Update the document</font>
    oPart.Update

    <font color="#008000">' Retrieve the top face of the pad to be filleted</font>
<font color="#0000FF">    Dim </font>oTopFace<font color="#0000FF"> As </font>Reference
<font color="#0000FF">    Set </font>oTopFace = oPart.CreateReferenceFromBRepName  ( &quot;RSur:(Face:(Brp:(Pad.1;2);None:());WithTemporaryBody;WithoutBuildError;WithSelectingFeatureSupport)&quot;, oEdgeFillet1 ) 

    <font color="#008000">' Retrieve the bottom face of the pad to be filleted </font>
<font color="#0000FF">    Dim </font>oBottomFace<font color="#0000FF"> As </font>Reference
<font color="#0000FF">    Set </font>oBottomFace = oPart.CreateReferenceFromBRepName  ( &quot;RSur:(Face:(Brp:(Pad.1;1);None:());WithTemporaryBody;WithoutBuildError;WithSelectingFeatureSupport)&quot;, oEdgeFillet1 ) 

    <font color="#008000">' Define the fillet to be created with the first face</font>
<font color="#0000FF">    Dim </font>oEdgeFillet2<font color="#0000FF"> As </font>ConstRadEdgeFillet
<font color="#0000FF">    Set </font>oEdgeFillet2 = oPart.ShapeFactory.AddNewEdgeFilletWithConstantRadius  ( oTopFace, 1, 15.000000 )

    <font color="#008000">' Define the fillet radius to 5 mm</font>
    oEdgeFillet2.Radius.Value = 5.000000

    <font color="#008000">' Add the other face</font>
    oEdgeFillet2.AddObjectToFillet oBottomFace

    <font color="#008000">' Update the document</font>
    oPart.Update

<font color="#0000FF">End Sub</font>
</pre></body></html>


