<html>

<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<meta name="GENERATOR" content="Microsoft FrontPage 4.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
<title>Managing a Machining Axis System Activity</title>
<link rel="stylesheet" type="text/css" href="../CAAScrBase/caav5.css">
<script language="JavaScript" src="../CAAScrJavaScript/submit.js"></script>
</head>

<body>

<table border="0" width="100%">
  <tr>
    <td>
      <h2>Machining</h2>
    </td>
    <td align="right" valign="top">
      <h2><a name="Top"></a>Managing a Machining Axis System Activity</h2>
    </td>
  </tr>
</table>
<hr>
<! ---------------------------------comment------------------------------------->
<table border="0" width="100%">
  <tr>
    <td width="7%" valign="top"><img border="0" src="../CAAScrBase/images/atarget.gif" width="32" height="32"></td>
    <td width="93%">
      <p><a name="Learn"></a>This macro CAAMaiManageMachiningAxisSystem shows
      you how to create and manage a Machining Axis System.</p>
      <! ---------------------------------comment------------------------------------->
      <p>&nbsp;</p>
    </td>
  </tr>
  <tr>
    <td width="7%" valign="top"><img border="0" src="../CAAScrBase/images/ainfo.gif" width="32" height="32"></td>
    <td width="93%">
      <p><a name="How"></a>CAAMaiManageMachiningAxisSystem is launched in CATIA.
      Open the file 'Sample_Part.CATPart' located in the CAAScdMaiUseCases
      module, go to the Prismatic Manufacturing Programmer workbench and run the
      macro.</p>
      <p>CAAMaiManageMachiningAxisSystem.<a href="CAAMaiManageMachiningAxisSystemSource.htm" target="Source">CATScript</a>
      is located in the CAAScdMaiUseCases module.&nbsp;</p>
      <p>&nbsp;</p>
    </td>
  </tr>
  <tr>
    <td width="7%" valign="top"><img border="0" src="../CAAScrBase/images/ascenari.gif" width="32" height="32"></td>
    <td width="93%">
      <p><a name="Step"></a>CAAMaiManageMachiningAxisSystem includes 7 steps:</p>
      <ol>
        <li><a href="#Step1">Retrieve the active CATProcess document</a></li>
        <li><a href="#Step2">Retrieve the&nbsp; current setup</a></li>
        <li><a href="#Step3">Retrieve the Manufacturing View</a></li>
        <li><a href="#Step4">Retrieve the Manufacturing Program</a></li>
        <li><a href="#Step5">Insert a Coordinate System activity and assign its
          feature</a></li>
        <li><a href="#Step6">Manage activity as an Origin and sets Origin Group
          and Number</a></li>
        <li><a href="#Step7">Manage activity as a Machining Axis and Assign Part
          Axis System</a></li>
        <li><a href="#Step8">Manage activity as a Machining Axis and Assign
          Point and Direction</a></li>
      </ol>
      <h4><a name="Step1"></a>Retrieve the active CATProcess document</h4>
      <table class="code">
        <tr>
          <td>
            <pre style="word-spacing: 0; margin: 0">...</pre>
            <pre style="word-spacing: 0; margin: 0">&nbsp;</pre>
            <pre style="word-spacing: 0; margin: 0"><font color="#0000ff"><font color="#008000">'---------------------------------------------------------------</font> </font></pre>
            <pre style="word-spacing: 0; margin: 0"><font color="#008000"><font color="#0000ff">' </font>Retrieve the active CATProcess document  </font></pre>
            <pre style="word-spacing: 0; margin: 0"><font color="#008000">'---------------------------------------------------------------</font></pre>
            <pre style="word-spacing: 0; margin: 0"><font color="#0000ff">Dim </font>MfgDoc1<font color="#0000ff"> As </font>Document </pre>
            <pre style="word-spacing: 0; margin: 0"><font color="#0000ff">Set </font>MfgDoc1 = CATIA.ActiveDocument </pre>
            <pre style="word-spacing: 0; margin: 0">&nbsp;</pre>
            <pre style="word-spacing: 0; margin: 0">...</pre>
          </td>
        </tr>
      </table>
      <p>Retrieves the active document and sets it in the variable MfgDoc1.</p>
      <h4><a name="Step2"></a><a name="Step2">Retrieve the current setup</a></h4>
      <table class="code">
        <tr>
          <td>
            <pre style="word-spacing: 0; margin-top: 0; margin-bottom: 0">...</pre>
            <pre style="word-spacing: 0; margin-top: 0; margin-bottom: 0">&nbsp;</pre>
            <pre style="word-spacing: 0; margin: 0"><font color="#0000ff"><font color="#008000">'---------------------------------------------------------------</font> </font></pre>
            <pre style="word-spacing: 0; margin: 0"><font color="#008000"><font color="#0000ff">' </font>Retrieve the current setup  </font></pre>
            <pre style="word-spacing: 0; margin: 0"><font color="#008000">'---------------------------------------------------------------</font></pre>
            <pre style="word-spacing: 0; margin: 0">&nbsp;</pre>
            <pre style="word-spacing: 0; margin: 0"><font color="#008000">'*** Retrieve current Process Root</font></pre>
            <pre style="word-spacing: 0; margin: 0">&nbsp;</pre>
            <pre style="word-spacing: 0; margin: 0"><font color="#0000FF">Dim </font><font color="#000000">ActivityRef</font><font color="#0000FF"> As </font><font color="#000000">AnyObject</font></pre>
            <pre style="word-spacing: 0; margin: 0"><font color="#0000FF">Set </font><font color="#000000">ActivityRef</font><font color="#0000FF"> </font><font color="#000000">= MfgDoc1.GetItem(&quot;Process&quot;)</font></pre>
            <pre style="word-spacing: 0; margin: 0">&nbsp;</pre>
            <pre style="word-spacing: 0; margin: 0"><font color="#0000FF">Dim </font><font color="#000000">Setup1</font><font color="#0000FF"> As </font><font color="#000000">ManufacturingSetup</font></pre>
            <pre style="word-spacing: 0; margin: 0"><font color="#0000FF">Dim </font><font color="#000000">childs</font><font color="#0000FF"> As </font><font color="#000000">Activities</font></pre>
            <pre style="word-spacing: 0; margin: 0"><font color="#0000FF">Dim </font><font color="#000000">child</font><font color="#0000FF"> As </font><font color="#000000">Activity</font></pre>
            <pre style="word-spacing: 0; margin: 0">&nbsp;</pre>
            <pre style="word-spacing: 0; margin: 0"><font color="#0000FF">If </font><font color="#000000">(ActivityRef.IsSubTypeOf(&quot;PhysicalActivity&quot;))</font><font color="#0000FF"> Then</font></pre>
            <pre style="word-spacing: 0; margin: 0">&nbsp;</pre>
            <pre style="word-spacing: 0; margin: 0"><font color="#0000FF">  Set </font><font color="#000000">childs = ActivityRef.ChildrenActivities</font></pre>
            <pre style="word-spacing: 0; margin: 0"><font color="#0000FF">  </font><font color="#000000">quantity = childs.Count</font></pre>
            <pre style="word-spacing: 0; margin: 0">&nbsp;</pre>
            <pre style="word-spacing: 0; margin: 0"><font color="#0000FF">  If </font><font color="#000000">quantity &lt;= 0 </font><font color="#0000FF">Then</font></pre>
            <pre style="word-spacing: 0; margin: 0"><font color="#0000FF">    Exit Sub</font></pre>
            <pre style="word-spacing: 0; margin: 0"><font color="#0000FF">  End If</font></pre>
            <pre style="word-spacing: 0; margin: 0">&nbsp;</pre>
            <pre style="word-spacing: 0; margin: 0"><font color="#0000FF"> </font><font color="#000000"> NumberOfSetup = 0</font></pre>
            <pre style="word-spacing: 0; margin: 0">&nbsp;</pre>
            <pre style="word-spacing: 0; margin: 0"><font color="#0000FF">  For </font><font color="#000000">I=1</font><font color="#0000FF"> To </font><font color="#000000">quantity</font></pre>
            <pre style="word-spacing: 0; margin: 0"><font color="#0000FF">          Set </font><font color="#000000">child = childs.Item(I)</font></pre>
            <pre style="word-spacing: 0; margin: 0"><font color="#0000FF">          If </font><font color="#000000">(child.IsSubTypeOf(&quot;ManufacturingSetup&quot;)) </font><font color="#0000FF">Then</font></pre>
            <pre style="word-spacing: 0; margin: 0"><font color="#0000FF">                Set </font><font color="#000000">Setup1 = child</font></pre>
            <pre style="word-spacing: 0; margin: 0"><font color="#0000FF">                </font><font color="#000000">NumberOfSetup = NumberOfSetup +1</font></pre>
            <pre style="word-spacing: 0; margin: 0"><font color="#0000FF">                Exit For</font></pre>
            <pre style="word-spacing: 0; margin: 0"><font color="#0000FF">          End If </font></pre>
            <pre style="word-spacing: 0; margin: 0"><font color="#0000FF">  Next</font></pre>
            <pre style="word-spacing: 0; margin: 0">&nbsp;</pre>
            <pre style="word-spacing: 0; margin: 0"><font color="#0000FF">End If</font></pre>
            <pre style="word-spacing: 0; margin: 0">&nbsp;</pre>
            <pre style="word-spacing: 0; margin: 0"><font color="#0000FF">If </font><font color="#000000">NumberOfSetup &lt;= 0</font><font color="#0000FF"> Then</font></pre>
            <pre style="word-spacing: 0; margin: 0"><font color="#0000FF">     Exit Sub</font></pre>
            <pre style="word-spacing: 0; margin: 0"><font color="#0000FF">End If</font></pre>
            <pre style="word-spacing: 0; margin: 0">&nbsp;</pre>
            <pre style="word-spacing: 0; margin: 0"><font color="#008000">'*** Retrieve current Product linked to the current setup</font></pre>
            <pre style="word-spacing: 0; margin: 0">&nbsp;</pre>
            <pre style="word-spacing: 0; margin: 0"><font color="#0000FF">Dim </font><font color="#000000">Prod</font><font color="#0000FF"> As </font><font color="#000000">Product</font></pre>
            <pre style="word-spacing: 0; margin: 0"><font color="#0000FF">Set </font><font color="#000000">Prod = SetUp1.<font size="2">GetProductInstance</font></font></pre>
            <pre style="word-spacing: 0; margin: 0">&nbsp;</pre>
            <pre style="word-spacing: 0; margin: 0"><font color="#0000FF">...</font></pre>
          </td>
        </tr>
      </table>
      <p>.Retrieves the current process and, from this process, the current
      setup. Retrieves also the product linked to the setup .</p>
      <p><a name="Step3"></a><b>Retrieve the Manufacturing View</b></p>
      <table class="code">
        <tr>
          <td>
            <pre style="word-spacing: 0; margin: 0">...</pre>
            <pre style="word-spacing: 0; margin: 0">&nbsp;</pre>
            <pre style="word-spacing: 0; margin: 0"><font color="#0000ff"><font color="#008000">'---------------------------------------------------------------</font> </font></pre>
            <pre style="word-spacing: 0; margin: 0"><font color="#008000"><font color="#0000ff">' </font>Retrieve the Manufacturing View  </font></pre>
            <pre style="word-spacing: 0; margin: 0"><font color="#008000">'---------------------------------------------------------------</font></pre>
            <pre style="word-spacing: 0; margin: 0"><font color="#0000ff">Dim </font>MfgView<font color="#0000ff"> As </font>ManufacturingView </pre>
            <pre style="word-spacing: 0; margin: 0"><font color="#0000ff">Set </font>MfgView = Setup1.GetManufacturingView </pre>
            <pre style="word-spacing: 0; margin: 0">&nbsp;</pre>
            <pre style="word-spacing: 0; margin: 0">...</pre>
          </td>
        </tr>
      </table>
      <p>&nbsp;Retrieves the Manufacturing View and sets it in the variable
      MfgView</p>
      <h4><a name="Step4"></a>Retrieve the Manufacturing Program</h4>
      <table class="code">
        <tr>
          <td>
            <pre style="word-spacing: 0; margin-top: 0; margin-bottom: 0">...</pre>
            <pre style="word-spacing: 0; margin: 0">&nbsp;</pre>
            <pre style="word-spacing: 0; margin: 0"><font color="#0000ff"><font color="#008000">'---------------------------------------------------------------</font> </font></pre>
            <pre style="word-spacing: 0; margin: 0"><font color="#008000"><font color="#0000ff">' </font>Retrieve the Manufacturing Program</font></pre>
            <pre style="word-spacing: 0; margin: 0"><font color="#008000">'---------------------------------------------------------------</font></pre>
            <pre style="word-spacing: 0; margin-top: 0; margin-bottom: 0">Set ProgramList = Setup1.Programs
NumberOfProgram = ProgramList.Count

Set Program1 = ProgramList.GetElement(1)&nbsp;</pre>
            <pre style="word-spacing: 0; margin-top: 0; margin-bottom: 0"> ...</pre>
          </td>
        </tr>
      </table>
      <p>.Retrieves the Manufacturing Program and sets it in the variable
      Program1</p>
      <h4><a name="Step5"></a>Insert a Coordinate System activity and assign its
      feature</h4>
      <table class="code">
        <tr>
          <td>
            <pre style="word-spacing: 0; margin: 0">...</pre>
            <pre style="word-spacing: 0; margin: 0">&nbsp;</pre>
            <pre style="word-spacing: 0; margin: 0"><font color="#0000ff"><font color="#008000">'---------------------------------------------------------------</font> </font></pre>
            <pre style="word-spacing: 0; margin: 0"><font color="#008000"><font color="#0000ff">' </font>Insert a Coordinate System activity and assign its feature</font></pre>
            <pre style="word-spacing: 0; margin: 0"><font color="#008000">'---------------------------------------------------------------</font></pre>
            <pre style="word-spacing: 0; margin: 0">&nbsp;</pre>
            <pre style="word-spacing: 0; margin: 0"><font color="#008000">'*** Retrieve design pattern</font></pre>
            <pre style="word-spacing: 0; margin: 0">&nbsp;</pre>
            <pre style="word-spacing: 0; margin: 0">Set MyFeature = MfgView.ManufacturingFeatures.Add(&quot;MfgMachiningAxisSystem&quot;)

Set MachAxis = Program1.AppendOperation (&quot;CoordinateSystem&quot;,1)

MachAxis.SetFeature(MyFeature)
</pre>
            <pre style="word-spacing: 0; margin: 0">...</pre>
          </td>
        </tr>
      </table>
      <p>Insert a Coordinate System in the Program and assign corresponding
      feature.</p>
      <h4><a name="Step6"></a>Manage activity as an Origin and sets Origin Group
      and Number</h4>
      <table class="code">
        <tr>
          <td>
            <pre style="word-spacing: 0; margin: 0">...</pre>
            <pre style="word-spacing: 0; margin: 0">&nbsp;</pre>
            <pre style="word-spacing: 0; margin: 0"><font color="#0000ff"><font color="#008000">'---------------------------------------------------------------</font> </font></pre>
            <pre style="word-spacing: 0; margin: 0"><font color="#008000"><font color="#0000ff">' </font>Manage activity as an Origin and sets Origin Group and Number</font></pre>
            <pre style="word-spacing: 0; margin: 0"><font color="#008000">'---------------------------------------------------------------</font></pre>
            <pre style="word-spacing: 0; margin: 0">&nbsp;</pre>
            <pre style="word-spacing: 0; margin: 0">MyFeature.Origin = 1

MyFeature.OriginNumber = 2

MyFeature.OriginGroup = 3</pre>
            <pre style="word-spacing: 0; margin: 0"> </pre>
            <pre style="word-spacing: 0; margin: 0">...</pre>
          </td>
        </tr>
      </table>
      <p>Assigns origin number and origin group to feature used as an Origin</p>
      <h4><a name="Step7"></a>Manage activity as a Machining Axis and Assign
      Part Axis System</h4>
      <table class="code">
        <tr>
          <td>
            <pre style="word-spacing: 0; margin: 0">...</pre>
            <pre style="word-spacing: 0; margin: 0">&nbsp;</pre>
            <pre style="word-spacing: 0; margin: 0"><font color="#0000ff"><font color="#008000">'---------------------------------------------------------------</font> </font></pre>
            <pre style="word-spacing: 0; margin: 0"><font color="#0000ff">' </font><font color="#008000">Manage activity as a Machining Axis and Assign Part Axis System </font></pre>
            <pre style="word-spacing: 0; margin: 0"><font color="#008000">'---------------------------------------------------------------</font></pre>
            <pre style="word-spacing: 0; margin: 0">&nbsp;</pre>
            <pre style="word-spacing: 0; margin: 0">MyFeature.Origin = 0

set part1 = PartDoc1.Part
Set axisSystems = part1.AxisSystems

</pre>
            <pre>Language=&quot;VBSCRIPT&quot;

<font color="#008000">'*******************************************************************************************</font>
<font color="#008000">'*</font>
<font color="#008000">'* Main Entry  Point</font>
<font color="#008000">'*</font>
<font color="#008000">'*******************************************************************************************</font>

<font color="#0000FF">Sub </font>CATMain()
	
<font color="#008000">'*******************************************************************************************</font>
<font color="#008000">'Declarations</font>
<font color="#008000">'*******************************************************************************************</font>

<font color="#0000FF">	Dim </font>Count1<font color="#0000FF"> As </font>VARIANT
<font color="#0000FF">	Dim </font>MyHole<font color="#0000FF"> As </font>Hole
<font color="#0000FF">	Dim </font>Rel<font color="#0000FF"> As </font>Relations
<font color="#0000FF">	Dim </font>Setup1<font color="#0000FF"> As </font>ManufacturingSetup
<font color="#0000FF">	Dim </font>Program1<font color="#0000FF"> As </font>ManufacturingProgram
<font color="#0000FF">	Dim </font>MachAxis<font color="#0000FF"> As </font>ManufacturingOperation
<font color="#0000FF">	Dim </font>MfgDoc1<font color="#0000FF"> As </font>Document
<font color="#0000FF">	Dim </font>ActivityRef<font color="#0000FF"> As </font>AnyObject
<font color="#0000FF">	Dim </font>Feature<font color="#0000FF"> As </font>CATIABase
<font color="#0000FF">	Dim </font>MfgView<font color="#0000FF"> As </font>ManufacturingView
<font color="#0000FF">	Dim </font>MfgFeatures<font color="#0000FF"> As </font>ManufacturingFeatures

<font color="#0000FF">	Set </font>MfgDoc1 = CATIA.ActiveDocument
<font color="#0000FF">	Set </font>PartDoc1 = CATIA.Documents.Item(&quot;Sample_Part.CATPart&quot;)
	<font color="#008000">'MsgBox PartDoc1.Name</font>
<font color="#0000FF">	Set </font>ActivityRef = MfgDoc1.GetItem(&quot;Process&quot;)
<font color="#0000FF">	If </font>(ActivityRef.IsSubTypeOf(&quot;PhysicalActivity&quot;)) Then

<font color="#0000FF">		Set </font>childs = ActivityRef.ChildrenActivities
		quantity = childs.Count

<font color="#0000FF">		if </font>quantity &lt;= 0<font color="#0000FF"> then</font>
<font color="#0000FF">			Exit Sub</font>
<font color="#0000FF">		End if</font>

		NumberOfPO = 0

<font color="#0000FF">		For </font>I=1<font color="#0000FF"> To </font>quantity
<font color="#0000FF">			Set </font>child = childs.Item(I)
<font color="#0000FF">			If </font>(child.IsSubTypeOf(&quot;ManufacturingSetup&quot;)) Then
<font color="#0000FF">				Set </font>Setup1 = child
				NumberOfPO = NumberOfPO +1
<font color="#0000FF">				Exit For</font>
<font color="#0000FF">			End If</font>
<font color="#0000FF">		Next   </font>
<font color="#0000FF">	End If</font>

<font color="#0000FF">	if </font>NumberOfPO &lt;= 0<font color="#0000FF"> then</font>
<font color="#0000FF">	  Exit Sub</font>
<font color="#0000FF">	End if</font>

<font color="#008000">'*** Retrieve current Program</font>
<font color="#008000">'***</font>

<font color="#0000FF">	Set </font>ProgramList = Setup1.Programs
	NumberOfProgram = ProgramList.Count

<font color="#0000FF">	Set </font>Product = Setup1.<font size="2">GetProductInstance</font>

<font color="#0000FF">	Set </font>MfgView = Setup1.GetManufacturingView

<font color="#0000FF">	Set </font>MyFeature = MfgView.ManufacturingFeatures.Add(&quot;MfgMachiningAxisSystem&quot;)

<font color="#0000FF">	Set </font>Program1 = ProgramList.GetElement(1)	
<font color="#0000FF">	Set </font>MachAxis = Program1.AppendOperation (&quot;CoordinateSystem&quot;,1)

	MachAxis.SetFeature(MyFeature)

	<font color="#008000">'MsgBox MyFeature.Name</font>

	MyFeature.Origin = 1
	<font color="#008000">'MsgBox MyFeature.Origin</font>

	MyFeature.OriginNumber = 2
	<font color="#008000">'MsgBox MyFeature.OriginNumber</font>

	MyFeature.OriginGroup = 3
	<font color="#008000">'MsgBox MyFeature.OriginGroup</font>
	
	MyFeature.Origin = 0
	<font color="#008000">'MsgBox MyFeature.Origin</font>

<font color="#0000FF">	set </font>part1 = PartDoc1.Part
<font color="#0000FF">	Set </font>axisSystems = part1.AxisSystems

<font color="#0000FF">	Set </font>axisSystem = axisSystems.Item(1)

<font color="#0000FF">	Call </font>MyFeature.SetPartAxisSystem (axisSystem,Setup1.<font size="2">GetProductInstance</font>)

<font color="#0000FF">	Set </font>hybridBodies1 = part1.HybridBodies

<font color="#0000FF">	Set </font>hybridBody1 = hybridBodies1.Item(&quot;Open_body.1&quot;)

<font color="#0000FF">	Set </font>hybridShapes1 = hybridBody1.HybridShapes

<font color="#0000FF">	Set </font>hybridShapePointCoord2 = hybridShapes1.Item(&quot;Point.1&quot;)

<font color="#0000FF">	Call </font>MyFeature.SetOriginPoint( hybridShapePointCoord2,Setup1.<font size="2">GetProductInstance</font>)

<font color="#0000FF">	Call </font>MyFeature.SetOriginXDirection (0.0,0.0,-1.0)
<font color="#0000FF">	Call </font>MyFeature.SetOriginZDirection (-1.0,0.0,0.0)

<font color="#0000FF">End Sub</font>
</pre>
            <pre style="word-spacing: 0; margin: 0">Set axisSystem = axisSystems.Item(1)

Call MyFeature.SetPartAxisSystem (axisSystem,Setup1.<font size="2">GetProductInstance</font>)</pre>
            <pre style="word-spacing: 0; margin: 0">&nbsp;</pre>
            <pre style="word-spacing: 0; margin: 0">...</pre>
          </td>
        </tr>
      </table>
      <p>Assigns Part Axis System to Machining Axis System</p>
      <h4><a name="Step8"></a>Manage activity as a Machining Axis and Assign
      Point and Direction</h4>
      <table class="code">
        <tr>
          <td>
            <pre style="word-spacing: 0; margin: 0">...</pre>
            <pre style="word-spacing: 0; margin: 0">&nbsp;</pre>
            <pre style="word-spacing: 0; margin: 0"><font color="#0000ff"><font color="#008000">'---------------------------------------------------------------</font> </font></pre>
            <pre style="word-spacing: 0; margin: 0"><font color="#0000ff">' </font><font color="#008000">Manage activity as a Machining Axis and Assign Point and Direction</font></pre>
            <pre style="word-spacing: 0; margin: 0"><font color="#008000">'---------------------------------------------------------------</font></pre>
            <pre style="word-spacing: 0; margin: 0">&nbsp;</pre>
            <pre style="word-spacing: 0; margin: 0">Set hybridBodies1 = part1.HybridBodies

Set hybridBody1 = hybridBodies1.Item(&quot;Open_body.1&quot;)

Set hybridShapes1 = hybridBody1.HybridShapes

Set hybridShapePointCoord2 = hybridShapes1.Item(&quot;Point.1&quot;)

Call MyFeature.SetOriginPoint( hybridShapePointCoord2,Setup1.<font size="2">GetProductInstance</font>)

Call MyFeature.SetOriginXDirection (0.0,0.0,-1.0)
Call MyFeature.SetOriginZDirection (-1.0,0.0,0.0)</pre>
            <pre style="word-spacing: 0; margin: 0">&nbsp;</pre>
            <pre style="word-spacing: 0; margin: 0">...</pre>
          </td>
        </tr>
      </table>
      <p>Assigns point and coordinate of axis to Machining Axis System</p>
      <p>&nbsp;</p>
      <p>&nbsp;</p>
    </td>
  </tr>
</table>
<p align="center"><img border="0" src="../CAAScrBase/images/aendtask.gif" width="64" height="32"></p>
<p align="right">[<a href="#Top">Top</a>]</p>
<hr>
<! ---------------------------------comment------------------------------------->
<h4><a name="InShort"></a>In Short</h4>
<p>This use case has shown how to create a Machining Pattern and to assign
design features to it.</p>
<p align="right">[<a href="#Top">Top</a>]</p>
<hr>
<! ---------------------------------comment------------------------------------->
<h4><a name="References"></a>References</h4>
<table border="0" width="100%">
  <tr>
    <td valign="top" width="40">[1]</td>
    <td width="735"><a href="../CAAScdInfUseCases/CAAInfLauchMacro.htm">Replaying
      a macro</a></td>
  </tr>
  <tr>
    <td valign="top" width="40">[2]</td>
    <td width="735"><a href="../CAAScdMaiTechArticles/CAAMaiTocManufacturingActivity.htm"><i>Machining</i></a><i><a href="../CAAScdMaiTechArticles/CAAMaiTocManufacturingActivity.htm">
      automation objects</a></i>&nbsp;</td>
  </tr>
  <tr>
    <td colspan="2" align="right">[<a href="#Top">Top</a>]</td>
</table>
<hr>
<! ---------------------------------comment------------------------------------->
<p><i>Copyright © 2001, Dassault Systèmes. All rights reserved.</i></p>

</body>
