<html>

<head>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<meta name="GENERATOR" content="Microsoft FrontPage 4.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
<title>Loading the Machining Workbench and Initializing the Setup Activity</title>
<link rel="stylesheet" type="text/css" href="../CAAScrBase/caav5.css">
<script language="JavaScript" src="../CAAScrJavaScript/submit.js"></script>
</head>

<body>

<table border="0" width="100%">
  <tr>
    <td>
      <h2>Machining</h2>
    </td>
    <td align="right" valign="top">
      <h2><a name="Top"></a>Loading the Machining Workbench and Initializing the
      Setup Activity</h2>
    </td>
  </tr>
</table>
<hr>
<!----------------------------------comment------------------------------------->
<table border="0" width="100%">
  <tr>
    <td width="7%" valign="top"><img border="0" src="../CAAScrBase/images/atarget.gif" width="32" height="32"></td>
    <td width="93%">
      <p><a name="Learn"></a>This macro CAAMaiInitializeSetUp shows you how to
      launch NC Workbench and make an association between the Setup and the
      Part.</p>
    </td>
  </tr>
  <tr>
    <td width="7%" valign="top"><img border="0" src="../CAAScrBase/images/ainfo.gif" width="32" height="32"></td>
    <td width="93%">
      <p><a name="How"></a>CAAMaiInitializeSetUp is launched in CATIA. Open the
      file 'Sample.CATPart' located in the CAAScdMaiUseCases module, and run the
      macro.</p>
      <p><a href="CAAMaiInitializeSetUpSource.htm" target="Source">CAAMaiInitializeSetUp.CATScript</a>
      is located in the CAAScdMaiUseCases module.</p>
    </td>
  </tr>
  <tr>
    <td width="7%" valign="top"><img border="0" src="../CAAScrBase/images/ascenari.gif" width="32" height="32"></td>
    <td width="93%" valign="top">
      <p><a name="Step"></a>CAAMaiInitializeSetUp includes five steps:</p>
      <ol>
        <li><a href="#Step1">Retrieving the Active Part Document and the
          Associated Product</a></li>
        <li><a href="#Step2">Creating a New Process Document</a></li>
        <li><a href="#Step3">Starting the Prismatic Machining Workbench&nbsp;</a></li>
        <li><a href="#Step4">Retrieving the current Setup of the Existing
          Process</a></li>
        <li><a href="#Step5">Associating the Product with the Setup Activity</a></li>
      </ol>
      <h4><a name="Step1"></a>Retrieving the Active Part Document and the
      Associated Product</h4>
      <table class="code">
        <tr>
          <td>
            <pre>...
<font color="#0000FF">Dim</font> thePartDoc <font color="#0000FF">As</font> Document
<font color="#0000FF">Set</font> thePartDoc = CATIA.ActiveDocument

<font color="#0000FF">Dim</font> theProduct <font color="#0000FF">As</font> Product
<font color="#0000FF">Set</font> theProduct = thePartDoc.Product
...</pre>
          </td>
        </tr>
      </table>
      <p>Retrieves the active Part document and sets it in the variable
      thePartDoc, then retrieves the associated Product and sets it in the
      variable theProduct.</p>
      <h4><a name="Step2"></a>Creating a New Process Document</h4>
      <table class="code">
        <tr>
          <td>
            <pre>...
CATIA.Documents.Add &quot;Process&quot;
<font color="#0000FF">Dim</font> thePPRDoc <font color="#0000FF">As</font> Document
<font color="#0000FF">Set</font> thePPRDoc = CATIA.ActiveDocument
...</pre>
          </td>
        </tr>
      </table>
      <p>Creates a new Process document and sets it in the variable thePPRDoc.</p>
      <h4><a name="Step3"></a>Starting the Prismatic Machining Workbench</h4>
      <table class="code">
        <tr>
          <td>
            <pre>...
<font color="#0000FF">Dim</font> theApplication <font color="#0000FF">As</font> Application
<font color="#0000FF">Set</font> theApplication = thePPRDoc.Application
theApplication.StartWorkbench(&quot;ManufacturingProgramWorkbench&quot;)
...</pre>
          </td>
        </tr>
      </table>
      <p>Starts the Prismatic Machining Workbench.</p>
      <h4><a name="Step4"></a>Retrieving the Current Setup of the Existing
      Process</h4>
      <table class="code">
        <tr>
          <td>
            <pre>...
<font color="#0000FF">Dim</font> theSetup <font color="#0000FF">As</font> ManufacturingSetup
<font color="#0000FF">If</font> (theProcess.IsSubTypeOf(&quot;PhysicalActivity&quot;)) <font color="#0000FF">Then</font>
  <font color="#0000FF">Set</font> childs = theProcess.ChildrenActivities
  quantity = childs.Count
  <font color="#0000FF">If</font> quantity &lt;= 0 <font color="#0000FF">Then
    Exit Sub
  End If</font>

  NumberOfPO = 0
  <font color="#0000FF">For</font> I=1 <font color="#0000FF">To</font> quantity
    <font color="#0000FF">Set</font> child = childs.Item(I)
    <font color="#0000FF">If</font> (child.IsSubTypeOf(&quot;ManufacturingSetup&quot;)) <font color="#0000FF">Then
      Set</font> theSetup = child
      NumberOfPO = NumberOfPO + 1
      <font color="#0000FF">Exit For
    End If
  Next
End If
If</font> NumberOfPO &lt;= 0 <font color="#0000FF">Then
  Exit Sub
End If</font>
...</pre>
          </td>
        </tr>
      </table>
      <p>Scans the Process activities, searches for the existing Setup and sets
      it in the variable theSetup.</p>
      <h4><a name="Step5"></a>Associating the Product with the Setup Activity</h4>
      <table class="code">
        <tr>
          <td>
            <pre>...
theSetup.Product = theProduct
...</pre>
          </td>
        </tr>
      </table>
      <p>Associates the Product with the Setup activity.</p>
    </td>
  </tr>
</table>
<p align="center"><img border="0" src="../CAAScrBase/images/aendtask.gif" width="64" height="32"></p>
<p align="right">[<a href="#Top">Top</a>]</p>
<hr>
<!----------------------------------comment------------------------------------->
<h4><a name="InShort"></a>In Short</h4>
<p>This use case has shown how to launch an NC Workbench and make an association
between the Setup and the Part.</p>
<p align="right">[<a href="#Top">Top</a>]</p>
<hr>
<!----------------------------------comment------------------------------------->
<h4><a name="References"></a>References</h4>
<table border="0" width="100%">
  <tr>
    <td valign="top" width="40">[1]</td>
    <td width="735"><a href="../CAAScdInfUseCases/CAAInfLauchMacro.htm">Replaying
      a Macro</a></td>
  </tr>
  <tr>
    <td valign="top" width="40">[2]</td>
    <td width="735"><a href="../CAAScdMaiTechArticles/CAAMaiTocManufacturingActivity.htm">Machining
      automation objects</a></td>
  </tr>
  <tr>
    <td colspan="2" align="right">[<a href="#Top">Top</a>]</td>
</table>
<hr>
<!----------------------------------comment------------------------------------->
<p><i>Copyright © 2002, Dassault Systèmes. All rights reserved.</i></p>

</body>
