<html><head><meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"><title>CAAInfCreateDocument.CATScript</title><link rel="stylesheet" type="text/css" href="../CAAScrBase/caav5.css"></head><body><pre>
<font color="#0000FF">Option Explicit</font>
<font color="#008000">' COPYRIGHT DASSAULT SYSTEMES 2001</font>

<font color="#008000">' *****************************************************************************</font>
<font color="#008000">'   Purpose:       Create a New Document.</font>
<font color="#008000">'   Assumtions:   None</font>
<font color="#008000">'   Author: </font>
<font color="#008000">'   Languages:   VBScript</font>
<font color="#008000">'   Locales:        English </font>
<font color="#008000">'   CATIA Level:  V5R7 </font>
<font color="#008000">' *****************************************************************************</font>


<font color="#0000FF">Sub </font>CATMain()

    <font color="#008000">'Create a new part document.</font>
    <font color="#008000">'Add the new document to the end of the collection of documents.</font>
    <font color="#008000">'Create and display a new window for the new document.</font>
    <font color="#008000">'Activate the new document and the window.</font>
<font color="#0000FF">    Dim </font>oNewPartDoc<font color="#0000FF"> As </font>Document
<font color="#0000FF">    Set </font>oNewPartDoc = CATIA.Documents.Add("Part")
   
<font color="#0000FF">End Sub</font>

</pre></body></html>
