<html>
<head>
 <meta name="Generator" content="mihGene v1.1">
 <meta http-equiv="Expires" content="Tue, 04 Dec 1993 21:29:02 GMT">
 <title>MecModInterfaces Vertex (Object)</title>
<link rel="Stylesheet" type="text/css" href="../../../caav5.css">
<script language="Javascript" src="../_index/jslink.js"></script> 
<script language="Javascript" src="jsFwLink.js"></script> 
<script language="Javascript" type="text/javascript" src="../_index/jsTree.js"></script>  
</head>
<body>
<pre><a href="../_index/main.htm">All Frameworks</a>  <a href="../_index/tree.htm">Object Hierarchy</a>  <a href="../MecModInterfaces.htm">This Framework</a>  <a href="../_index/CAAHomeIdx.htm">Indexes</a>  <script type="text/javascript"> 
 var test=locateObject('Vertex','interface','0'); 
 if(test==1){ 
     document.write("<a href=\"#\" onclick=\"openLinkNP('Vertex','interface','0');return false\">Previous</a> "); 
 } 
 test=locateObject('Vertex','interface','1'); 
 if(test==1){ 
     document.write("<a href=\"#\" onclick=\"openLinkNP('Vertex','interface','1');return false\">Next</a> "); 
 } 
 </script> 
</pre>
<hr>
<h1>Vertex<font size=-1> (Object)</font></h1>
<script type="text/javascript" > 
 generatedFatherClass('interface_Vertex_17746','Vertex','0');</script>
<b><i> 0-D boundary.</i></b><br>

 <b>Role</b>: 
 This <a href="#" onClick="openLink('Boundary','');return false">Boundary</a> object may be, for example, the corner of a Pad resulting from the extrusion of a  square.</br>
 You will create an Vertex object using the 
<a href="#" onClick="openLink('Shapes','GetBoundary');return false">Shapes.GetBoundary</a> , 
<a href="#" onClick="openLink('HybridShapes','GetBoundary');return false">HybridShapes.GetBoundary</a> ,  
<a href="#" onClick="openLink('Sketches','GetBoundary');return false">Sketches.GetBoundary</a> or 
<a href="#" onClick="openLink('Selection','SelectElement2');return false">Selection.SelectElement2</a> method. Then, you pass it to the operator (such as 
<a href="#" onClick="openLink('HybridShapeFactory','AddNewLinePtPt');return false">HybridShapeFactory.AddNewLinePtPt</a> ).</br>  The lifetime of a Vertex object is limited, see 
<a href="#" onClick="openLink('Boundary','');return false">Boundary</a>.</br>  <b>See also:</b><br>
 
<a href="#" onClick="openLink('TriDimFeatVertexOrBiDimFeatVertex','');return false">TriDimFeatVertexOrBiDimFeatVertex</a> , 
<a href="#" onClick="openLink('NotWireBoundaryMonoDimFeatVertex','');return false">NotWireBoundaryMonoDimFeatVertex</a> , 
<a href="#" onClick="openLink('ZeroDimFeatVertexOrWireBoundaryMonoDimFeatVertex','');return false">ZeroDimFeatVertexOrWireBoundaryMonoDimFeatVertex</a> . <! @sample>
 <dl>
 <dt><b>Example:</b>
 <dd>
 This example asks the end user to select successively two vertices. Then, it creates a line between these
 two vertices.
 <pre>
 Dim InputObjectType(0)
 Set Document = CATIA.ActiveDocument
 Set Selection = Document.Selection
 Set HybridBodies = Document.Part.HybridBodies
 Set HybridBody = HybridBodies.Item("Geometrical Set.1")
 'We propose to the user that he select the first vertex
 InputObjectType(0)="Vertex"
 Status=Selection.SelectElement2(InputObjectType,"Select the first vertex",true)
 if (Status = "cancel") then Exit Sub
 Set FirstVertex = Selection.Item(1).Value
 Selection.Clear
 'We propose to the user that he select the second vertex
 InputObjectType(0)="Vertex"
 Status=Selection.SelectElement2(InputObjectType,"Select the second vertex",true)
 if (Status = "cancel") then Exit Sub
 Set SecondVertex = Selection.Item(1).Value
 Set hybridShapeLinePtPt = HybridShapeFactory.AddNewLinePtPt(FirstVertex,SecondVertex)
 HybridBody.AppendHybridShape hybridShapeLinePtPt
 Document.Part.InWorkObject = hybridShapeLinePtPt
 Document.Part.Update 
 </pre>
 </dl>
<hr>
<dl>
</dl>
<dl>
</dl>

</body>
<hr><p><i>
Copyright &#169; 1999-2011, Dassault Syst&#232;mes. All rights reserved.</i></p>
</html>
