<html>
<head>
 <meta name="Generator" content="mihGene v1.1">
 <meta http-equiv="Expires" content="Tue, 04 Dec 1993 21:29:02 GMT">
 <title>MecModInterfaces PlanarFace (Object)</title>
<link rel="Stylesheet" type="text/css" href="../../../caav5.css">
<script language="Javascript" src="../_index/jslink.js"></script> 
<script language="Javascript" src="jsFwLink.js"></script> 
<script language="Javascript" type="text/javascript" src="../_index/jsTree.js"></script>  
</head>
<body>
<pre><a href="../_index/main.htm">All Frameworks</a>  <a href="../_index/tree.htm">Object Hierarchy</a>  <a href="../MecModInterfaces.htm">This Framework</a>  <a href="../_index/CAAHomeIdx.htm">Indexes</a>  <script type="text/javascript"> 
 var test=locateObject('PlanarFace','interface','0'); 
 if(test==1){ 
     document.write("<a href=\"#\" onclick=\"openLinkNP('PlanarFace','interface','0');return false\">Previous</a> "); 
 } 
 test=locateObject('PlanarFace','interface','1'); 
 if(test==1){ 
     document.write("<a href=\"#\" onclick=\"openLinkNP('PlanarFace','interface','1');return false\">Next</a> "); 
 } 
 </script> 
</pre>
<hr>
<h1>PlanarFace<font size=-1> (Object)</font></h1>
<script type="text/javascript" > 
 generatedFatherClass('interface_PlanarFace_20455','PlanarFace','0');</script>
<b><i> 2-D boundary with a planar geometry.</i></b><br>

 <b>Role</b>: 
 This <a href="#" onClick="openLink('Boundary','');return false">Boundary</a> object may be, for example, the face of a cube.</br> You will create a PlanarFace object using the 
<a href="#" onClick="openLink('Shapes','GetBoundary');return false">Shapes.GetBoundary</a> , 
<a href="#" onClick="openLink('HybridShapes','GetBoundary');return false">HybridShapes.GetBoundary</a> ,  
<a href="#" onClick="openLink('Sketches','GetBoundary');return false">Sketches.GetBoundary</a> or 
<a href="#" onClick="openLink('Selection','SelectElement2');return false">Selection.SelectElement2</a> method. Then, you pass it to the operator (such as 
<a href="#" onClick="openLink('ShapeFactory','AddNewDraft');return false">ShapeFactory.AddNewDraft</a> ).</br>  The lifetime of a PlanarFace object is limited, see 
<a href="#" onClick="openLink('Boundary','');return false">Boundary</a>.</br>  <! @sample>
 <dl>
 <dt><b>Example:</b>
 <dd>
 This example asks the end user to select a face and two planar faces, and creates a draft on these faces:
 <pre>
 Dim InputObjectType(0)
 Set Document = CATIA.ActiveDocument
 Set Selection = Document.Selection
 'We propose to the user that he select the face to draft
 InputObjectType(0)="Face"
 Status=Selection.SelectElement2(InputObjectType,"Select the face to draft",true)
 if (Status = "cancel") then Exit Sub
 Set FaceToDraft = Selection.Item(1).Value
 Selection.Clear
 'We propose to the user that he select the neutral face
 InputObjectType(0)="PlanarFace"
 Status=Selection.SelectElement2(InputObjectType,"Select the neutral face",true)
 if (Status = "cancel") then Exit Sub
 Set NeutralFace = Selection.Item(1).Value
 Selection.Clear
 'We propose to the user that he select the parting element
 InputObjectType(0)="PlanarFace"
 Status=Selection.SelectElement2(InputObjectType,"Select the parting element",true)
 if (Status = "cancel") then Exit Sub
 Set PartingElement = Selection.Item(1).Value
 Set Draft = ShapeFactory.AddNewDraft(FaceToDraft,NeutralFace,0,PartingElement,0.0,0.0,1.0,0,5.0,0)
 Set DraftDomains = Draft.DraftDomains
 Set DraftDomain = DraftDomains.Item(1)
 DraftDomain.SetPullingDirection 0.0, 0.0,1.0
 Document.Part.Update  
 </pre>
 </dl>
<hr>
<dl>
</dl>
<dl>
 <h2><a name="MethodIndex"></a>Method Index</h2>
 <dt>
    <a href="#GetFirstAxis"><b>GetFirstAxis</b></a>
<dd>   Returns the planar face first axis
   
 <dt>
    <a href="#GetOrigin"><b>GetOrigin</b></a>
<dd>  Returns the origin of the planar face.
 <dt>
    <a href="#GetSecondAxis"><b>GetSecondAxis</b></a>
<dd>   Returns the planar face second axis.
</dl>
 <h2><a name="Methods"></a>Methods</h2> <br>
<a name="GetFirstAxis"><dt>

<table><tr><td>o Sub <b>GetFirstAxis</b>(<td><script type="text/javascript"> activateLink('CATSafeArrayVariant','CATSafeArrayVariant')</script> <td><tt>oFirstAxis</tt>)</table></dt>
<dl>
  <dd>
  Returns the planar face first axis
   
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> oFirstAxis[0]</tt>
   <dd>   The X Coordinate of the planar face first axis
   </dd>
    <dt><tt> oFirstAxis[1]</tt>
   <dd>   The Y Coordinate of the planar face first axis
   </dd>
    <dt><tt> oFirstAxis[2]</tt>
   <dd>   The Z Coordinate of the planar face first axis</dd>
</dl>
</dl>
</dl>
<a name="GetOrigin"><dt>

<table><tr><td>o Sub <b>GetOrigin</b>(<td><script type="text/javascript"> activateLink('CATSafeArrayVariant','CATSafeArrayVariant')</script> <td><tt>oOrigin</tt>)</table></dt>
<dl>
  <dd>
 Returns the origin of the planar face. 	
   
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> oOrigin[0]</tt>
   <dd>   The X Coordinate of the planar face origin
   </dd>
    <dt><tt> oOrigin[1]</tt>
   <dd>   The Y Coordinate of the planar face origin
   </dd>
    <dt><tt> oOrigin[2]</tt>
   <dd>   The Z Coordinate of the planar face origin</dd>
</dl>
</dl>
</dl>
<a name="GetSecondAxis"><dt>

<table><tr><td>o Sub <b>GetSecondAxis</b>(<td><script type="text/javascript"> activateLink('CATSafeArrayVariant','CATSafeArrayVariant')</script> <td><tt>oSecondAxis</tt>)</table></dt>
<dl>
  <dd>
  Returns the planar face second axis.
   
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> oSecondAxis[0]</tt>
   <dd>    The X Coordinate of the planar face second axis
   </dd>
    <dt><tt> oSecondAxis[1]</tt>
   <dd>   The Y Coordinate of the planar face second axis
   </dd>
    <dt><tt> oSecondAxis[2]</tt>
   <dd>   The Z Coordinate of the planar face second axis</dd>
</dl>
</dl>
</dl>

</body>
<hr><p><i>
Copyright &#169; 1999-2011, Dassault Syst&#232;mes. All rights reserved.</i></p>
</html>
