<html>
<head>
 <meta name="Generator" content="mihGene v1.1">
 <meta http-equiv="Expires" content="Tue, 04 Dec 1993 21:29:02 GMT">
 <title>CATSchPlatformInterfaces SchematicRoot (Object)</title>
<link rel="Stylesheet" type="text/css" href="../../../caav5.css">
<script language="Javascript" src="../_index/jslink.js"></script> 
<script language="Javascript" src="jsFwLink.js"></script> 
<script language="Javascript" type="text/javascript" src="../_index/jsTree.js"></script>  
</head>
<body>
<pre><a href="../_index/main.htm">All Frameworks</a>  <a href="../_index/tree.htm">Object Hierarchy</a>  <a href="../CATSchPlatformInterfaces.htm">This Framework</a>  <a href="../_index/CAAHomeIdx.htm">Indexes</a>  <script type="text/javascript"> 
 var test=locateObject('SchematicRoot','interface','0'); 
 if(test==1){ 
     document.write("<a href=\"#\" onclick=\"openLinkNP('SchematicRoot','interface','0');return false\">Previous</a> "); 
 } 
 test=locateObject('SchematicRoot','interface','1'); 
 if(test==1){ 
     document.write("<a href=\"#\" onclick=\"openLinkNP('SchematicRoot','interface','1');return false\">Next</a> "); 
 } 
 </script> 
</pre>
<hr>
<h1>SchematicRoot<font size=-1> (Object)</font></h1>
<script type="text/javascript" > 
 generatedFatherClass('interface_SchematicRoot_40510','SchematicRoot','0');</script>
<b><i> Represents the top node of the schematic object tree.</i></b><br>

 From this node all the queries for lists of schematic objects can be made. Furthermore, 
 all the factories handles can be obtained through this interface.<hr>
<dl>
</dl>
<dl>
 <h2><a name="MethodIndex"></a>Method Index</h2>
 <dt>
    <a href="#GetApplObjFactFromVirtualType"><b>GetApplObjFactFromVirtualType</b></a>
<dd>  Returns the object factory for specific schematic application.
 <dt>
    <a href="#GetApplicationObjectFactory"><b>GetApplicationObjectFactory</b></a>
<dd>  Returns the object factory for specific schematic application.
 <dt>
    <a href="#GetCompGroupFromCatalog"><b>GetCompGroupFromCatalog</b></a>
<dd>  Returns specific component group entry in a schematic component catalog document.
 <dt>
    <a href="#GetCompSymbolFromCatalog"><b>GetCompSymbolFromCatalog</b></a>
<dd>  Returns specific entry in a schematic component catalog document.
 <dt>
    <a href="#GetComponents"><b>GetComponents</b></a>
<dd>  Returns a list of schematic component instances under the root.
 <dt>
    <a href="#GetDrawing"><b>GetDrawing</b></a>
<dd>  Retrieves the drawing root in the schematic document.
 <dt>
    <a href="#GetDrawingStandard"><b>GetDrawingStandard</b></a>
<dd>  Get the drawing standard.
 <dt>
    <a href="#GetInterface"><b>GetInterface</b></a>
<dd>  Returns specific interface handle on a given object.
 <dt>
    <a href="#GetRefComponents"><b>GetRefComponents</b></a>
<dd>  Returns a list of schematic component references under the root.
 <dt>
    <a href="#GetRoutes"><b>GetRoutes</b></a>
<dd>  Returns a list of schematic routes under the root.
 <dt>
    <a href="#GetSchBaseFactory"><b>GetSchBaseFactory</b></a>
<dd>  Returns schematic base object factory.
 <dt>
    <a href="#GetSchematicSession"><b>GetSchematicSession</b></a>
<dd>  Returns the schematic session the document containing the root is associated with.
 <dt>
    <a href="#GetTemporaryListFactory"><b>GetTemporaryListFactory</b></a>
<dd>  Returns the factory to create lists of various types.
 <dt>
    <a href="#GetUnassociatedSymbols"><b>GetUnassociatedSymbols</b></a>
<dd>  Returns a list of unassociated symbol.
 <dt>
    <a href="#SetDrawingStandard"><b>SetDrawingStandard</b></a>
<dd>  Set the drawing standard.
</dl>
 <h2><a name="Methods"></a>Methods</h2> <br>
<a name="GetApplObjFactFromVirtualType"><dt>

<table><tr><td>o Func <b>GetApplObjFactFromVirtualType</b>(<td><script type="text/javascript"> activateLink('CATBSTR','CATBSTR')</script> <td><tt>iApplicationID</tt>) As <script type="text/javascript"> activateLink('SchAppObjectFactory','SchAppObjectFactory')</script> </table></dt>
<dl>
  <dd>
 Returns the object factory for specific schematic application.  
 
<dl>
  <dt> <b>Example:</b> 
  <dd>  This example illustrates how to get the object factory of user defined virtual type. 
 User provides implementation to this type.
 <pre>
 Dim objSchPlatformRoot As SchematicRoot
 Dim objSchObjFact As SchAppObjectFactory
 Dim objProductRoot As Product
 Set objProductRoot = CATIA.ActiveDocument.Product
 Set objSchPlatformRoot = objProductRoot.GetTechnologicalObject ("SchematicRoot")
 Set objSchObjFact = objSchPlatformRoot.<font color="red">GetApplObjFactFromVirtualType("UserDefined")(</font>
 </pre>
</dl>
</dl>
<a name="GetApplicationObjectFactory"><dt>

<table><tr><td>o Func <b>GetApplicationObjectFactory</b>(<td><script type="text/javascript"> activateLink('CatSchIDLApplicationID','CatSchIDLApplicationID')</script> <td><tt>iApplicationID</tt>) As <script type="text/javascript"> activateLink('SchAppObjectFactory','SchAppObjectFactory')</script> </table></dt>
<dl>
  <dd>
 Returns the object factory for specific schematic application.  
 
<dl>
  <dt> <b>Example:</b> 
  <dd>  This example illustrates how to get the object factory of Piping 
 and Instrumentation Diagram application.
 <pre>
 Dim objSchPlatformRoot As SchematicRoot
 Dim objSchObjFact As SchAppObjectFactory
 Dim objProductRoot As Product
 Set objProductRoot = CATIA.ActiveDocument.Product
 Set objSchPlatformRoot = objProductRoot.GetTechnologicalObject ("SchematicRoot")
 Set objSchObjFact = objSchPlatformRoot.<font color="red">GetApplicationObjectFactory("CatSchIDLCATPID")(</font>
 </pre>
</dl>
</dl>
<a name="GetCompGroupFromCatalog"><dt>

<table><tr><td>o Func <b>GetCompGroupFromCatalog</b>(<td><script type="text/javascript"> activateLink('CATBSTR','CATBSTR')</script> <td><tt>iCatalogEntryName</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('Document','Document')</script> <td><tt>iCtlgDoc</tt>) As <script type="text/javascript"> activateLink('SchComponent','SchComponent')</script> </table></dt>
<dl>
  <dd>
 Returns specific component group entry in a schematic component catalog document.  
 
<dl>
  <dt> <b>Example:</b> 
  <dd>  This example illustrates how to get a specific component group entry in a schematic component catalog document.
 <pre>
 Dim objSchPlatformRoot As SchematicRoot
 Dim objSchComponent As SchComponent
 Dim objProductRoot As Product
 Set objProductRoot = CATIA.ActiveDocument.Product
 Set objSchPlatformRoot = objProductRoot.GetTechnologicalObject ("SchematicRoot")
 Dim objCtlgDoc As Document
 Set objCtlgDoc = CATIA.Documents.Open ("Electrical_ANSI_PartFunctions.catalog")
 Set objSchComponent = objSchPlatformRoot.<font color="red">GetCompGroupFromCatalog ("JuncBox-TermBoard",objCtlgDoc)
 </pre>
</dl>
</dl>
<a name="GetCompSymbolFromCatalog"><dt>

<table><tr><td>o Func <b>GetCompSymbolFromCatalog</b>(<td><script type="text/javascript"> activateLink('CATBSTR','CATBSTR')</script> <td><tt>iCatalogEntryName</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('Document','Document')</script> <td><tt>iCtlgDoc</tt>) As <script type="text/javascript"> activateLink('SchGRR','SchGRR')</script> </table></dt>
<dl>
  <dd>
 Returns specific entry in a schematic component catalog document.  
 
<dl>
  <dt> <b>Example:</b> 
  <dd>  This example illustrates how to get a specific entry in a schematic component catalog document.
 <pre>
 Dim objSchPlatformRoot As SchematicRoot
 Dim objSchGRRComp As SchGRRComp
 Dim objProductRoot As Product
 Set objProductRoot = CATIA.ActiveDocument.Product
 Set objSchPlatformRoot = objProductRoot.GetTechnologicalObject ("SchematicRoot")
 Dim objCtlgDoc As Document
 Set objCtlgDoc = CATIA.Documents.Open ("PID_ANSI_Equipment.catalog")
 Set objSchGRRComp = objSchPlatformRoot.<font color="red">GetCompSymbolFromCatalog ("Blower",objCtlgDoc)
 </pre>
</dl>
</dl>
<a name="GetComponents"><dt>

<table><tr><td>o Func <b>GetComponents</b>(<td>) As <script type="text/javascript"> activateLink('SchListOfObjects','SchListOfObjects')</script> </table></dt>
<dl>
  <dd>
 Returns a list of schematic component instances under the root. 
 
<dl>
  <dt> <b>Example:</b> 
  <dd>  This example illustrates how to get the list of component instances from a schematic product document.
 <pre>
 Dim objSchPlatformRoot As SchematicRoot
 Dim objSchListComps As SchListOfObjects
 Set objoSchListComps = objSchPlatformRoot.<font color="red">GetComponents</font>
 </pre>
</dl>
</dl>
<a name="GetDrawing"><dt>

<table><tr><td>o Func <b>GetDrawing</b>(<td>) As <script type="text/javascript"> activateLink('DrawingRoot','DrawingRoot')</script> </table></dt>
<dl>
  <dd>
 Retrieves the drawing root in the schematic document.
 
<dl>
  <dt> <b>Example:</b> 
  <dd>  This example illustrates how to get the drawing of a schematic document.
 <pre>
 Dim objSchPlatformRoot As SchematicRoot
 Dim objProductRoot As Product
 Set objProductRoot = CATIA.ActiveDocument.Product
 Set objSchPlatformRoot = objProductRoot.GetTechnologicalObject ("SchematicRoot")
 Dim objDrawRoot As DrawingRoot
 Set objDrawRoot = objSchPlatformRoot.<font color="red">GetDrawing
 </pre>
</dl>
</dl>
<a name="GetDrawingStandard"><dt>

<table><tr><td>o Func <b>GetDrawingStandard</b>(<td>) As <script type="text/javascript"> activateLink('CatDrawingStandard','CatDrawingStandard')</script> </table></dt>
<dl>
  <dd>
 Get the drawing standard.
 
<dl>
  <dt> <b>Example:</b> 
  <dd>  This example illustrates how to get the drafting standard of a schematic document.
 <pre>
 Dim objSchPlatformRoot As SchematicRoot
 Dim objSchLSymbols As SchListOfObjects
 Dim objProductRoot As Product
 Set objProductRoot = CATIA.ActiveDocument.Product
 Set objSchPlatformRoot = objProductRoot.GetTechnologicalObject ("SchematicRoot")
 oDrwStd = objSchPlatformRoot.<font color="red">GetDrawingStandard
 </pre>
</dl>
</dl>
<a name="GetInterface"><dt>

<table><tr><td>o Func <b>GetInterface</b>(<td><script type="text/javascript"> activateLink('CATBSTR','CATBSTR')</script> <td><tt>iInterfaceName</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('AnyObject','AnyObject')</script> <td><tt>iObject</tt>) As <script type="text/javascript"> activateLink('AnyObject','AnyObject')</script> </table></dt>
<dl>
  <dd>
 Returns specific interface handle on a given object.  
 
<dl>
  <dt> <b>Example:</b> 
  <dd>  This example illustrates how to get a specific interface handle from a given object. 
 <pre>
 Dim objSchPlatformRoot As SchematicRoot
 Dim objSchObjFact As SchAppObjectFactory
 Dim objProductRoot As Product
 Set objProductRoot = CATIA.ActiveDocument.Product
 Set objSchPlatformRoot = objProductRoot.GetTechnologicalObject ("SchematicRoot")
 Set objSchObjFact = SchPlatformRoot.GetApplicationObjectFactory("CatSchIDLCATPID")
 Set objSchObjFact2 = objSchPlatformRoot.<font color="red">GetInterface ("CATIASchAppObjectFactory2",SchObjFact)
 </pre>
</dl>
</dl>
<a name="GetRefComponents"><dt>

<table><tr><td>o Func <b>GetRefComponents</b>(<td>) As <script type="text/javascript"> activateLink('SchListOfObjects','SchListOfObjects')</script> </table></dt>
<dl>
  <dd>
 Returns a list of schematic component references under the root.
 
<dl>
  <dt> <b>Example:</b> 
  <dd>  This example illustrates how to get the list of component references from a schematic product document.
 <pre>
 Dim objSchPlatformRoot As SchematicRoot
 Dim objSchListComps As SchListOfObjects
 Set objSchListComps = objSchPlatformRoot.<font color="red">GetRefComponents</font>
 </pre>
</dl>
</dl>
<a name="GetRoutes"><dt>

<table><tr><td>o Func <b>GetRoutes</b>(<td>) As <script type="text/javascript"> activateLink('SchListOfObjects','SchListOfObjects')</script> </table></dt>
<dl>
  <dd>
 Returns a list of schematic routes under the root.
 
<dl>
  <dt> <b>Example:</b> 
  <dd>  This example illustrates how to get the list of routes from a schematic product document.
 <pre>
 Dim objSchPlatformRoot As SchematicRoot
 Dim objSchListRoutes As SchListOfObjects
 Set objSchListRoutes = objSchPlatformRoot.<font color="red">GetRoutes</font>
 </pre>
</dl>
</dl>
<a name="GetSchBaseFactory"><dt>

<table><tr><td>o Func <b>GetSchBaseFactory</b>(<td>) As <script type="text/javascript"> activateLink('SchBaseFactory','SchBaseFactory')</script> </table></dt>
<dl>
  <dd>
 Returns schematic base object factory.  
 
<dl>
  <dt> <b>Example:</b> 
  <dd>  This example illustrates how to get the schematic base factory.
 <pre>
 Dim objSchPlatformRoot As SchematicRoot
 Dim objSchBaseFact As SchBaseFactory
 Dim objProductRoot As Product
 Set objProductRoot = CATIA.ActiveDocument.Product
 Set objSchPlatformRoot = objProductRoot.GetTechnologicalObject ("SchematicRoot")
 Set objSchBaseFact = objSchPlatformRoot.<font color="red">GetBaseFactory
 </pre>
</dl>
</dl>
<a name="GetSchematicSession"><dt>

<table><tr><td>o Func <b>GetSchematicSession</b>(<td>) As <script type="text/javascript"> activateLink('SchSession','SchSession')</script> </table></dt>
<dl>
  <dd>
 Returns the schematic session the document containing the root is associated with.  
 
<dl>
  <dt> <b>Example:</b> 
  <dd>  This example illustrates how to get the schematic session.
 <pre>
 Dim objSchPlatformRoot As SchematicRoot
 Dim objSchSession As SchSession
 Dim objProductRoot As Product
 Set objProductRoot = CATIA.ActiveDocument.Product
 Set objSchPlatformRoot = objProductRoot.GetTechnologicalObject ("SchematicRoot")
 Set objSchSession = objSchPlatformRoot.<font color="red">GetSession
 </pre>
</dl>
</dl>
<a name="GetTemporaryListFactory"><dt>

<table><tr><td>o Func <b>GetTemporaryListFactory</b>(<td>) As <script type="text/javascript"> activateLink('SchTempListFactory','SchTempListFactory')</script> </table></dt>
<dl>
  <dd>
 Returns the factory to create lists of various types. These lists will not 
 be saved with the model.
 
<dl>
  <dt> <b>Example:</b> 
  <dd>  This example illustrates how to get the list factory from a schematic product document.
 <pre>
 Dim objSchPlatformRoot As SchematicRoot
 Dim objSchList As SchTempListFactory
 Dim objProductRoot As Product
 Set objProductRoot = CATIA.ActiveDocument.Product
 Set objSchPlatformRoot = objProductRoot.GetTechnologicalObject ("SchematicRoot")
 Set objSchList = objSchPlatformRoot.<font color="red">GetTemporaryListFactory</font>
 </pre>
</dl>
</dl>
<a name="GetUnassociatedSymbols"><dt>

<table><tr><td>o Func <b>GetUnassociatedSymbols</b>(<td>) As <script type="text/javascript"> activateLink('SchListOfObjects','SchListOfObjects')</script> </table></dt>
<dl>
  <dd>
 Returns a list of unassociated symbol.  
 
<dl>
  <dt> <b>Example:</b> 
  <dd>  This example illustrates how to get a list of unassociated symbol.
 <pre>
 Dim objSchPlatformRoot As SchematicRoot
 Dim objSchLSymbols As SchListOfObjects
 Dim objProductRoot As Product
 Set objProductRoot = CATIA.ActiveDocument.Product
 Set objSchPlatformRoot = objProductRoot.GetTechnologicalObject ("SchematicRoot")
 Set objSchLSymbols = objSchPlatformRoot.<font color="red">GetUnassociatedSymbols
 </pre>
</dl>
</dl>
<a name="SetDrawingStandard"><dt>

<table><tr><td>o Sub <b>SetDrawingStandard</b>(<td><script type="text/javascript"> activateLink('CatDrawingStandard','CatDrawingStandard')</script> <td><tt>iDrwStd</tt>)</table></dt>
<dl>
  <dd>
 Set the drawing standard.  
 
<dl>
  <dt> <b>Example:</b> 
  <dd>  This example illustrates how to set the drafting standard of a schematic document.
 <pre>
 Dim objSchPlatformRoot As SchematicRoot
 Dim objSchLSymbols As SchListOfObjects
 Dim objProductRoot As Product
 Set objProductRoot = CATIA.ActiveDocument.Product
 Set objSchPlatformRoot = objProductRoot.GetTechnologicalObject ("SchematicRoot")
 objSchPlatformRoot.<font color="red">SetDrawingStandard catISO
 </pre>
</dl>
</dl>

</body>
<hr><p><i>
Copyright &#169; 1999-2011, Dassault Syst&#232;mes. All rights reserved.</i></p>
</html>
