<html>
<head>
 <meta name="Generator" content="mihGene v1.1">
 <meta http-equiv="Expires" content="Tue, 04 Dec 1993 21:29:02 GMT">
 <title>SpaceAnalysisInterfaces Measurable (Object)</title>
<link rel="Stylesheet" type="text/css" href="../../../caav5.css">
<script language="Javascript" src="../_index/jslink.js"></script> 
<script language="Javascript" src="jsFwLink.js"></script> 
<script language="Javascript" type="text/javascript" src="../_index/jsTree.js"></script>  
</head>
<body>
<pre><a href="../_index/main.htm">All Frameworks</a>  <a href="../_index/tree.htm">Object Hierarchy</a>  <a href="../SpaceAnalysisInterfaces.htm">This Framework</a>  <a href="../_index/CAAHomeIdx.htm">Indexes</a>  <script type="text/javascript"> 
 var test=locateObject('Measurable','interface','0'); 
 if(test==1){ 
     document.write("<a href=\"#\" onclick=\"openLinkNP('Measurable','interface','0');return false\">Previous</a> "); 
 } 
 test=locateObject('Measurable','interface','1'); 
 if(test==1){ 
     document.write("<a href=\"#\" onclick=\"openLinkNP('Measurable','interface','1');return false\">Next</a> "); 
 } 
 </script> 
</pre>
<hr>
<h1>Measurable<font size=-1> (Object)</font></h1>
<script type="text/javascript" > 
 generatedFatherClass('interface_Measurable_34815','Measurable','0');</script>
<b><i>   The interface to access a CATIAMeasurable  
 Get measurements on the object.</i></b><br>

 <p>
 Two types of measurement can be done:
 <ul>
 <li> itself : gives dimensions related to the object itself (ex the radius of a circle).
 <li> between : gives dimensions related to another object (ex the distance between two products). 
 A restriction occurs for distance between: bodies (CATBody) cannot be measured.
 </ul>
 
 Methods on VOLUME   : GetVolume
                       GetArea
                       GetCOG
 
 Methods on SURFACE  : GetArea
                       GetCOG
                       GetPerimeter
 
 Methods on PLANE    : GetArea
                       GetCOG
                       GetPlane
 
 Methods on CYLINDER : GetArea
                       GetCOG
                       GetAxis
                       GetPointsOnAxis
                       GetRadius
 
 Methods on CONE     : GetArea
                       GetCOG
                       GetAxis
                       GetPointsOnAxis
                       GetAngle

 Methods on SPHERE   : GetArea
                       GetCOG
                       GetRadius
                       GetCenter
 
 Methods on CURVE    : GetLength
                       GetCOG
                       GetPointsOnCurve
 
 Methods on LINE     : GetLength
                       GetCOG
                       GetPointsOnCurve
                       GetDirection 

 Methods on CIRCLE   : GetLength
                       GetCOG
                       GetPointsOnCurve
                       GetRadius
                       GetCenter
                       GetAngle
                       GetAxis
 
 Methods on POINT     : GetPoint
 
 Methods on AXIS SYST : GetAxisSystem
<hr>
<dl>
 <h2><a name="PropertyIndex"></a>Property Index</h2>
 <dt>
    <a href="#Angle"><b>Angle</b></a>
<dd>  Returns the Angle of a circle or cone.
 <dt>
    <a href="#Area"><b>Area</b></a>
<dd>  Returns the area of the surface or wet area from volume.
 <dt>
    <a href="#GeometryName"><b>GeometryName</b></a>
<dd>  Returns the name of the geometry of the measured object.
 <dt>
    <a href="#Length"><b>Length</b></a>
<dd>  Returns the Length of a curve.
 <dt>
    <a href="#Perimeter"><b>Perimeter</b></a>
<dd>  Returns the perimeter of a surface.
 <dt>
    <a href="#Radius"><b>Radius</b></a>
<dd>  Returns the radius of an arc, cylinder or sphere.
 <dt>
    <a href="#Volume"><b>Volume</b></a>
<dd>  Returns the volume.
</dl>
<dl>
 <h2><a name="MethodIndex"></a>Method Index</h2>
 <dt>
    <a href="#GetAngleBetween"><b>GetAngleBetween</b></a>
<dd>  Compute the angle between the CATIAMeasurable and another.
 <dt>
    <a href="#GetAxis"><b>GetAxis</b></a>
<dd>  Retrieves the axis vector of the cylinder or a cone.
 <dt>
    <a href="#GetAxisSystem"><b>GetAxisSystem</b></a>
<dd>  Retrieves the information of the axis system.
 <dt>
    <a href="#GetCOG"><b>GetCOG</b></a>
<dd>  Retrieves the position of the center of gravity of a surface and volume .
 <dt>
    <a href="#GetCenter"><b>GetCenter</b></a>
<dd>  Retrieves the position of the center of a circle or sphere.
 <dt>
    <a href="#GetDirection"><b>GetDirection</b></a>
<dd>  Retrieves the direction of the line.
 <dt>
    <a href="#GetMinimumDistance"><b>GetMinimumDistance</b></a>
<dd>  Compute the minimum distance between the CATIAMeasurable and another.
 <dt>
    <a href="#GetMinimumDistancePoints"><b>GetMinimumDistancePoints</b></a>
<dd>  Compute the points corresponding to the minimum distance between the two references.
 <dt>
    <a href="#GetPlane"><b>GetPlane</b></a>
<dd>  Retrieves informations of the plane.
 <dt>
    <a href="#GetPoint"><b>GetPoint</b></a>
<dd>  Retrieves the position of the point.
 <dt>
    <a href="#GetPointsOnAxis"><b>GetPointsOnAxis</b></a>
<dd>  Retrieves the the characteristic points of the axis with respect of the size of the revolution object.
 <dt>
    <a href="#GetPointsOnCurve"><b>GetPointsOnCurve</b></a>
<dd>  Retrieves the the characteristic points of the curve : the start point, the middle point and the end point.
</dl>
 <h2><a name="Properties"></a>Properties</h2> <br>
<a name="Angle"><dt>

<table><tr><td>o Property <b>Angle</b>(<td>) As <script type="text/javascript"> activateLink('double','double')</script>  (Read Only)</table></dt>
<dl>
  <dd>
 Returns the Angle of a circle or cone.
 
<dl>
  <dt> <b>Example:</b> 
  <dd>     This example retrieves the Angle of <tt>NewMeasurable</tt> measure.
    <pre>
    Dim AAngle As double
    AAngle = NewMeasurable.<font color="red">Angle</font>
    </pre>
</dl>
</dl>
<a name="Area"><dt>

<table><tr><td>o Property <b>Area</b>(<td>) As <script type="text/javascript"> activateLink('double','double')</script>  (Read Only)</table></dt>
<dl>
  <dd>
 Returns the area of the surface or wet area from volume.
 
<dl>
  <dt> <b>Example:</b> 
  <dd>     This example retrieves the area of <tt>NewMeasurable</tt> measure.
    The area unit given by oArea is m²
    <pre>
    Dim AArea As double
    AArea = NewMeasurable.<font color="red">Area</font>
    </pre>
</dl>
</dl>
<a name="GeometryName"><dt>

<table><tr><td>o Property <b>GeometryName</b>(<td>) As <script type="text/javascript"> activateLink('CatMeasurableName','CatMeasurableName')</script>  (Read Only)</table></dt>
<dl>
  <dd>
 Returns the name of the geometry of the measured object.
 
<dl>
  <dt> <b>Example:</b> 
  <dd>     This example retrieves the name of the geometry of the <tt>NewMeasurable</tt> measure.
    <pre>
    Dim AGeometryName As CatMeasurableName
    AGeometryName = NewMeasurable.<font color="red">GeometryName</font>
    </pre>
</dl>
</dl>
<a name="Length"><dt>

<table><tr><td>o Property <b>Length</b>(<td>) As <script type="text/javascript"> activateLink('double','double')</script>  (Read Only)</table></dt>
<dl>
  <dd>
 Returns the Length of a curve.
 
<dl>
  <dt> <b>Example:</b> 
  <dd>     This example retrieves the Length of <tt>NewMeasurable</tt> measure.
    <pre>
    Dim ALength As double
    ALength = NewMeasurable.<font color="red">Length</font>
    </pre>
</dl>
</dl>
<a name="Perimeter"><dt>

<table><tr><td>o Property <b>Perimeter</b>(<td>) As <script type="text/javascript"> activateLink('double','double')</script>  (Read Only)</table></dt>
<dl>
  <dd>
 Returns the perimeter of a surface.
 
<dl>
  <dt> <b>Example:</b> 
  <dd>     This example retrieves the perimeter of <tt>NewMeasurable</tt> measure.
    <pre>
    Dim APerimeter As double
    APerimeter = NewMeasurable.<font color="red">Perimeter</font>
    </pre>
</dl>
</dl>
<a name="Radius"><dt>

<table><tr><td>o Property <b>Radius</b>(<td>) As <script type="text/javascript"> activateLink('double','double')</script>  (Read Only)</table></dt>
<dl>
  <dd>
 Returns the radius of an arc, cylinder or sphere.
 
<dl>
  <dt> <b>Example:</b> 
  <dd>     This example retrieves the Radius of <tt>NewMeasurable</tt> measure.
    <pre>
    Dim ARadius As double
    ARadius = NewMeasurable.<font color="red">Radius</font>
    </pre>
</dl>
</dl>
<a name="Volume"><dt>

<table><tr><td>o Property <b>Volume</b>(<td>) As <script type="text/javascript"> activateLink('double','double')</script>  (Read Only)</table></dt>
<dl>
  <dd>
 Returns the volume.
 
<dl>
  <dt> <b>Example:</b> 
  <dd>     This example retrieves the volume of <tt>NewMeasurable</tt> measure.
    The volume unit given by oVolume is m^3
    <pre>
    Dim AVolume As double
    AVolume = NewMeasurable.<font color="red">Volume</font>
    </pre>
</dl>
</dl>
 <h2><a name="Methods"></a>Methods</h2> <br>
<a name="GetAngleBetween"><dt>

<table><tr><td>o Func <b>GetAngleBetween</b>(<td><script type="text/javascript"> activateLink('Reference','Reference')</script> <td><tt>iMeasuredItem</tt>) As <script type="text/javascript"> activateLink('double','double')</script> </table></dt>
<dl>
  <dd>
 Compute the angle between the CATIAMeasurable and another.
 
<dl>
  <dt> <b>Example:</b> 
  <dd>     This example retrieves the angle between the reference1 and reference2.
    Dim reference1 As Reference
    Set reference1 = part1.CreateReferenceFromObject(object1)
    Dim reference2 As Reference
    Set reference2 = part1.CreateReferenceFromObject(object1)
    Dim TheSPAWorkbench As Workbench
    Set TheSPAWorkbench = CATIA.ActiveDocument.GetWorkbench ( "SPAWorkbench" )
    Dim TheMeasurable As Measurable
    Set TheMeasurable = TheSPAWorkbench.<font color="red">GetMeasurable(reference1)</font>
    Dim MinimumDistance As double
    MinimumDistance = TheMeasurable.<font color="red">GetAngleBetween(reference2)</font>
    </pre>
</dl>
</dl>
<a name="GetAxis"><dt>

<table><tr><td>o Sub <b>GetAxis</b>(<td><script type="text/javascript"> activateLink('CATSafeArrayVariant','CATSafeArrayVariant')</script> <td><tt>oAxisVector</tt>)</table></dt>
<dl>
  <dd>
 Retrieves the axis vector of the cylinder or a cone.
 
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> oVector</tt>
   <dd>    The axis vector of the cylinder or a cone with respect to the product coordinate system:
    <ul>
    <li>oAxisVector(0) is the X direction
    <li>oAxisVector(1) is the Y direction
    <li>oAxisVector(2) is the Z direction
    </ul>
 </dd>
</dl>
  <dt> <b>Example:</b> 
  <dd>     This example retrieves the axis vector of the cylinder or a cone of <tt>NewMeasurable</tt> measure.
    <pre>
    Dim AxisVector (2)
    NewMeasurable.<font color="red">GetAxis</font> AxisVector
    </pre>
</dl>
</dl>
<a name="GetAxisSystem"><dt>

<table><tr><td>o Sub <b>GetAxisSystem</b>(<td><script type="text/javascript"> activateLink('CATSafeArrayVariant','CATSafeArrayVariant')</script> <td><tt>oComponents</tt>)</table></dt>
<dl>
  <dd>
 Retrieves the information of the axis system.
 
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> oCoordinates</tt>
   <dd>    The information of the axis system with respect to the product coordinate system:
    <ul>
    <li>oComponents(0) is the X coordinate of the origin of the axis system
    <li>oComponents(1) is the Y coordinate of the origin of the axis system
    <li>oComponents(2) is the Z coordinate of the origin of the axis system
    <li>oComponents(3) is the X coordinate of the first direction of the axis system
    <li>oComponents(4) is the Y coordinate of the first direction of the axis system
    <li>oComponents(5) is the Z coordinate of the first direction of the axis system
    <li>oComponents(6) is the X coordinate of the second direction of the axis system
    <li>oComponents(7) is the Y coordinate of the second direction of the axis system
    <li>oComponents(8) is the Z coordinate of the second direction of the axis system
    <li>oComponents(9) is the X coordinate of the third direction of the axis system
    <li>oComponents(10) is the Y coordinate of the third direction of the axis system
    <li>oComponents(11) is the Z coordinate of the third direction of the axis system
    </ul>
 </dd>
</dl>
  <dt> <b>Example:</b> 
  <dd>     This example retrieves information of the axis system of <tt>NewMeasurable</tt> measure.
    <pre>
    Dim Components (11)
    NewMeasurable.<font color="red">GetAxisSystem</font> Components
    </pre>
</dl>
</dl>
<a name="GetCOG"><dt>

<table><tr><td>o Sub <b>GetCOG</b>(<td><script type="text/javascript"> activateLink('CATSafeArrayVariant','CATSafeArrayVariant')</script> <td><tt>oCoordinates</tt>)</table></dt>
<dl>
  <dd>
 Retrieves the position of the center of gravity of a surface and volume .
 
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> oCoordinates</tt>
   <dd>    The position of the center of gravity with respect to the product coordinate system:
    <ul>
    <li>oCoordinates(0) is the X coordinate
    <li>oCoordinates(1) is the Y coordinate
    <li>oCoordinates(2) is the Z coordinate
    </ul>
 </dd>
</dl>
  <dt> <b>Example:</b> 
  <dd>     This example retrieves the position of the center of gravity of <tt>NewMeasurable</tt> measure.
    <pre>
    Dim Coordinates (2)
    NewMeasurable.<font color="red">GetCOG</font> Coordinates
    </pre>
</dl>
</dl>
<a name="GetCenter"><dt>

<table><tr><td>o Sub <b>GetCenter</b>(<td><script type="text/javascript"> activateLink('CATSafeArrayVariant','CATSafeArrayVariant')</script> <td><tt>oCoordinates</tt>)</table></dt>
<dl>
  <dd>
 Retrieves the position of the center of a circle or sphere.
 
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> oCoordinates</tt>
   <dd>    The position of the center  with respect to the product coordinate system:
    <ul>
    <li>oCoordinates(0) is the X coordinate
    <li>oCoordinates(1) is the Y coordinate
    <li>oCoordinates(2) is the Z coordinate
    </ul>
 </dd>
</dl>
  <dt> <b>Example:</b> 
  <dd>     This example retrieves the position of the center of <tt>NewMeasurable</tt> measure.
    <pre>
    Dim Coordinates (2)
    NewMeasurable.<font color="red">GetCOGPosition</font> Coordinates
    </pre>
</dl>
</dl>
<a name="GetDirection"><dt>

<table><tr><td>o Sub <b>GetDirection</b>(<td><script type="text/javascript"> activateLink('CATSafeArrayVariant','CATSafeArrayVariant')</script> <td><tt>oDirection</tt>)</table></dt>
<dl>
  <dd>
 Retrieves the direction of the line.
 
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> oDirection</tt>
   <dd>    The direction of the line with respect to the product coordinate system:
    <ul>
    <li>oDirection(0) is the X direction
    <li>oDirection(1) is the Y direction
    <li>oDirection(2) is the Z direction
    </ul>
 </dd>
</dl>
  <dt> <b>Example:</b> 
  <dd>     This example retrieves the direction of the line of <tt>NewMeasurable</tt> measure.
    <pre>
    Dim Direction (2)
    NewMeasurable.<font color="red">GetDirection</font> Direction
    </pre>
</dl>
</dl>
<a name="GetMinimumDistance"><dt>

<table><tr><td>o Func <b>GetMinimumDistance</b>(<td><script type="text/javascript"> activateLink('Reference','Reference')</script> <td><tt>iMeasuredItem</tt>) As <script type="text/javascript"> activateLink('double','double')</script> </table></dt>
<dl>
  <dd>
 Compute the minimum distance between the CATIAMeasurable and another. Bodies (openbody, hybridbody..) cannot be measured between.
 
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> oCoordinates</tt>
   <dd>    The information of the axis system with respect to the product coordinate system:
    <ul>
    <li>oComponents(0) is the X coordinate of the origin of the axis system
    <li>oComponents(1) is the Y coordinate of the origin of the axis system
    <li>oComponents(2) is the Z coordinate of the origin of the axis system
    <li>oComponents(3) is the X coordinate of the first direction of the axis system
    <li>oComponents(4) is the Y coordinate of the first direction of the axis system
    <li>oComponents(5) is the Z coordinate of the first direction of the axis system
    </ul>
 </dd>
</dl>
  <dt> <b>Example:</b> 
  <dd>     This example retrieves the distance between the reference1 and reference2.
    Dim reference1 As Reference
    Set reference1 = part1.CreateReferenceFromObject(object1)
    Dim reference2 As Reference
    Set reference2 = part1.CreateReferenceFromObject(object1)
    Dim TheSPAWorkbench As Workbench
    Set TheSPAWorkbench = CATIA.ActiveDocument.GetWorkbench ( "SPAWorkbench" )
    Dim TheMeasurable As Measurable
    Set TheMeasurable = TheSPAWorkbench.<font color="red">GetMeasurable(reference1)</font>
    Dim MinimumDistance As double
    MinimumDistance = TheMeasurable.<font color="red">GetMinimumDistance(reference2)</font>
    </pre>
</dl>
</dl>
<a name="GetMinimumDistancePoints"><dt>

<table><tr><td>o Sub <b>GetMinimumDistancePoints</b>(<td><script type="text/javascript"> activateLink('Reference','Reference')</script> <td><tt>iMeasuredItem</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('CATSafeArrayVariant','CATSafeArrayVariant')</script> <td><tt>oCoordinates</tt>)</table></dt>
<dl>
  <dd>
 Compute the points corresponding to the minimum distance between the two references.
 
<dl>
  <dt> <b>Example:</b> 
  <dd>     This example retrieves the points corresponding to the distance between the reference1 and reference2.
    Dim reference1 As Reference
    Set reference1 = part1.CreateReferenceFromObject(object1)
    Dim reference2 As Reference
    Set reference2 = part1.CreateReferenceFromObject(object1)
    Dim TheSPAWorkbench As Workbench
    Set TheSPAWorkbench = CATIA.ActiveDocument.GetWorkbench ( "SPAWorkbench" )
    Dim TheMeasurable As Measurable
    Set TheMeasurable = TheSPAWorkbench.<font color="red">GetMeasurable(reference1)</font>
    Dim Coordinates (8)
    TheMeasurable.<font color="red">GetMinimumDistancePoints reference2, Coordinates</font>
    </pre>
</dl>
</dl>
<a name="GetPlane"><dt>

<table><tr><td>o Sub <b>GetPlane</b>(<td><script type="text/javascript"> activateLink('CATSafeArrayVariant','CATSafeArrayVariant')</script> <td><tt>oComponents</tt>)</table></dt>
<dl>
  <dd>
 Retrieves informations of the plane.
 
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> oComponents</tt>
   <dd>    The informations of the plane with respect to the product coordinate system:
    <ul>
    <li>oComponents(0) is the X coordinate of the origin
    <li>oComponents(1) is the Y coordinate of the origin
    <li>oComponents(2) is the Z coordinate of the origin
    <li>oComponents(3) is the X coordinate of the first direction of the plane
    <li>oComponents(4) is the Y coordinate of the first direction of the plane
    <li>oComponents(5) is the Z coordinate of the first direction of the plane
    <li>oComponents(6) is the X coordinate of the second direction of the plane
    <li>oComponents(7) is the Y coordinate of the second direction of the plane
    <li>oComponents(8) is the Z coordinate of the second direction of the plane
    </ul>
 </dd>
</dl>
  <dt> <b>Example:</b> 
  <dd>     This example retrieves informations of the plane of <tt>NewMeasurable</tt> measure.
    <pre>
    Dim Components (2)
    NewMeasurable.<font color="red">GetPlane</font> Components
    </pre>
</dl>
</dl>
<a name="GetPoint"><dt>

<table><tr><td>o Sub <b>GetPoint</b>(<td><script type="text/javascript"> activateLink('CATSafeArrayVariant','CATSafeArrayVariant')</script> <td><tt>oCoordinates</tt>)</table></dt>
<dl>
  <dd>
 Retrieves the position of the point.
 
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> oCoordinates</tt>
   <dd>    The coordinate of the point with respect to the product coordinate system:
    <ul>
    <li>oCoordinates(0) is the X coordinate
    <li>oCoordinates(1) is the Y coordinate
    <li>oCoordinates(2) is the Z coordinate
    </ul>
 </dd>
</dl>
  <dt> <b>Example:</b> 
  <dd>     This example retrieves the coordinate of the point of <tt>NewMeasurable</tt> measure.
    <pre>
    Dim Coordinates (2)
    NewMeasurable.<font color="red">GetPoint</font> Coordinates
    </pre>
</dl>
</dl>
<a name="GetPointsOnAxis"><dt>

<table><tr><td>o Sub <b>GetPointsOnAxis</b>(<td><script type="text/javascript"> activateLink('CATSafeArrayVariant','CATSafeArrayVariant')</script> <td><tt>oCoordinates</tt>)</table></dt>
<dl>
  <dd>
 Retrieves the the characteristic points of the axis with respect of the size of the revolution object.
 
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> oCoordinates</tt>
   <dd>    The information of the characteristic points with respect to the product coordinate system:
    <ul>
    <li>oCoordinates(0) is the X coordinate of the centerpoint of the axis
    <li>oCoordinates(1) is the Y coordinate of the centerpoint of the axis
    <li>oCoordinates(2) is the Z coordinate of the centerpoint of the axis
    <li>oCoordinates(3) is the X coordinate of the startpoint of the axis
    <li>oCoordinates(4) is the Y coordinate of the startpoint of the axis
    <li>oCoordinates(5) is the Z coordinate of the startpoint of the axis
    <li>oCoordinates(6) is the X coordinate of the endpoint of the axis
    <li>oCoordinates(7) is the Y coordinate of the endpoint of the axis
    <li>oCoordinates(8) is the Z coordinate of the endpoint of the axis
    </ul>
 </dd>
</dl>
  <dt> <b>Example:</b> 
  <dd>     This example retrieves the characteristic points of the axis of <tt>NewMeasurable</tt> measure.
    <pre>
    Dim Coordinates (8)
    NewMeasurable.<font color="red">GetPointsOnAxis</font> Coordinates
    </pre>
</dl>
</dl>
<a name="GetPointsOnCurve"><dt>

<table><tr><td>o Sub <b>GetPointsOnCurve</b>(<td><script type="text/javascript"> activateLink('CATSafeArrayVariant','CATSafeArrayVariant')</script> <td><tt>oCoordinates</tt>)</table></dt>
<dl>
  <dd>
 Retrieves the the characteristic points of the curve : the start point, the middle point and the end point.
 
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> oCoordinates</tt>
   <dd>    The information of the characteristic points of the curve with respect to the product coordinate system:
    <ul>
    <li>oCoordinates(0) is the X coordinate of the startpoint of the curve
    <li>oCoordinates(1) is the Y coordinate of the startpoint of the curve
    <li>oCoordinates(2) is the Z coordinate of the startpoint of the curve
    <li>oCoordinates(3) is the X coordinate of the midpoint of the curve
    <li>oCoordinates(4) is the Y coordinate of the midpoint of the curve
    <li>oCoordinates(5) is the Z coordinate of the midpoint of the curve
    <li>oCoordinates(6) is the X coordinate of the endpoint of the curve
    <li>oCoordinates(7) is the Y coordinate of the endpoint of the curve
    <li>oCoordinates(8) is the Z coordinate of the endpoint of the curve
    </ul>
 </dd>
</dl>
  <dt> <b>Example:</b> 
  <dd>     This example retrieves the characteristic points of the curve of <tt>NewMeasurable</tt> measure.
    <pre>
    Dim Coordinates (8)
    NewMeasurable.<font color="red">GetPointsOnCurve</font> Coordinates
    </pre>
</dl>
</dl>

</body>
<hr><p><i>
Copyright &#169; 1999-2011, Dassault Syst&#232;mes. All rights reserved.</i></p>
</html>
