<html><head><meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"><title>CAASchPlaceComponent.CATScript</title><link rel="stylesheet" type="text/css" href="../CAAScrBase/caav5.css"></head><body><pre>
<font color="#0000FF">Option Explicit</font>
<font color="#008000">' COPYRIGHT DASSAULT SYSTEMES 2004</font>

<font color="#008000">' *****************************************************************************</font>
<font color="#008000">'   Purpose:      Schematic component placement in free space and connected to</font>
<font color="#008000">'                 existing component.</font>
<font color="#008000">'   Languages:    VBScript</font>
<font color="#008000">'   Locales:      English </font>
<font color="#008000">'   CATIA Level:  V5R15 </font>
<font color="#008000">' *****************************************************************************</font>

<font color="#0000FF">Sub </font>CATMain()

    <font color="#008000">' ------------------------------------------------------------------------- </font>
    <font color="#008000">' Optional: allows to find the sample wherever it's installed</font>
<font color="#0000FF">    dim </font>sDocPath<font color="#0000FF"> As </font>String 
    sDocPath=CATIA.SystemService.Environ("CATDocView")

<font color="#0000FF">    If </font>(Not CATIA.FileSystem.FolderExists(sDocPath))<font color="#0000FF"> Then</font>
      Err.Raise 9999,sDocPath,"No Doc Path Defined"
<font color="#0000FF">    End If</font>

    <font color="#008000">' ------------------------------------------------------------------------- </font>
    <font color="#008000">' Open the schematic document </font>
<font color="#0000FF">    Dim </font>sCtlgFilePath
    sCtlgFilePath = CATIA.FileSystem.ConcatenatePaths(sDocPath, _
            "online\CAAScdSchUseCases\samples\CAASCH_Sample.catalog")

<font color="#0000FF">    Dim </font>objSchCtlgDoc<font color="#0000FF"> As </font>Document
<font color="#0000FF">    Set </font>objSchCtlgDoc = CATIA.Documents.Open(sCtlgFilePath)

    <font color="#008000">' Open main schematic P&ID design document (for new component instances created here)</font>
<font color="#0000FF">    Dim </font>sFilePath
    sFilePath = CATIA.FileSystem.ConcatenatePaths(sDocPath, _
            "online\CAAScdSchUseCases\samples\CAASCH_RouteForPlacement2.CATProduct")

<font color="#0000FF">    Dim </font>objSchDoc<font color="#0000FF"> As </font>Document
<font color="#0000FF">    Set </font>objSchDoc = CATIA.Documents.Open(sFilePath)

<font color="#0000FF">    Dim </font>strMessage<font color="#0000FF"> As </font>String

    strMessage = _
      "--------------------------------------------------------------------" & vbCr
    strMessage = strMessage & _
      "Output traces from CAASchPlaceComponent.CATScript" & vbCrLf

    <font color="#008000">'</font>
    <font color="#008000">' Find the top node of the schematic object tree - schematic root.</font>
<font color="#0000FF">    Dim </font>objPrdRoot<font color="#0000FF"> As </font>Product
<font color="#0000FF">    Dim </font>objSchRoot<font color="#0000FF"> As </font>SchematicRoot
<font color="#0000FF">    If </font>( Not ( objSchDoc Is Nothing ) )<font color="#0000FF"> Then</font>
<font color="#0000FF">      Set </font>objPrdRoot = objSchDoc.Product 
<font color="#0000FF">      If </font>( Not ( objPrdRoot Is Nothing ) )<font color="#0000FF"> Then</font>
<font color="#0000FF">        Set </font>objSchRoot = objPrdRoot.GetTechnologicalObject("SchematicRoot")
<font color="#0000FF">      End If</font>
<font color="#0000FF">    End If</font>

<font color="#0000FF">    Dim </font>objSchGRRCtlg<font color="#0000FF"> As </font>SchGRR
<font color="#0000FF">    Dim </font>objSchCntblRef<font color="#0000FF"> As </font>SchAppConnectable
<font color="#0000FF">    Dim </font>objSchComp2Ref<font color="#0000FF"> As </font>SchComponent2
<font color="#0000FF">    Dim </font>objSchCompInstA<font color="#0000FF"> As </font>SchComponent
<font color="#0000FF">    Dim </font>objSchGRRCompInstA<font color="#0000FF"> As </font>SchGRRComp
<font color="#0000FF">    Dim </font>objSchCompGraphInstA<font color="#0000FF"> As </font>SchCompGraphic
<font color="#0000FF">    Dim </font>objSchCompatInstA<font color="#0000FF"> As </font>SchCompatible
<font color="#0000FF">    Dim </font>objSchCompInstB<font color="#0000FF"> As </font>SchComponent

    <font color="#008000">'--------------------------------------------------------------------------</font>
    <font color="#008000">' Component instance (to be created below) orientation matrix.</font>
    <font color="#008000">' x-axis = (1.0,0.0)</font>
    <font color="#008000">' y-axis = (0.0,1.0)</font>
    <font color="#008000">' origin = (100.0,300.0)</font>
    <font color="#008000">'--------------------------------------------------------------------------</font>
<font color="#0000FF">    Dim </font>db6Array(6)<font color="#0000FF"> As </font>CATSafeArrayVariant
    db6Array(0)=1.0
    db6Array(1)=0.0
    db6Array(2)=0.0
    db6Array(3)=1.0
    db6Array(4)=145.0
    db6Array(5)=130.0

<font color="#0000FF">    If </font>( Not ( objSchRoot Is Nothing ) )<font color="#0000FF"> Then</font>

       <font color="#008000">'-----------------------------------------------------------------------</font>
       <font color="#008000">' Get the first symbol from component catalog.</font>
       <font color="#008000">'-----------------------------------------------------------------------</font>
<font color="#0000FF">       Set </font>objSchGRRCtlg = objSchRoot.GetCompSymbolFromCatalog ("Blocking Valve",objSchCtlgDoc)
<font color="#0000FF">       If </font>( Not ( objSchGRRCtlg Is Nothing ) )<font color="#0000FF"> Then</font>
         strMessage = strMessage &  "Got the first catalog symbol" & vbCr

         <font color="#008000">'---------------------------------------------------------------------</font>
         <font color="#008000">' Get the owner of the first symbol. That is a reference component</font>
         <font color="#008000">' in the catalog.</font>
         <font color="#008000">'---------------------------------------------------------------------</font>
<font color="#0000FF">         Set </font>objSchCntblRef = objSchGRRCtlg.GetSchObjOwner
<font color="#0000FF">         If </font>( Not ( objSchCntblRef Is Nothing ) )<font color="#0000FF"> Then</font>
           strMessage = strMessage &  "Got catalog connectable of the first symbol" & vbCr

           <font color="#008000">'-------------------------------------------------------------------</font>
           <font color="#008000">' Place an instance of the catalog reference in an empty space in </font>
           <font color="#008000">' the design document</font>
           <font color="#008000">' Note that the target document is an input to PlaceInSpace</font>
           <font color="#008000">'-------------------------------------------------------------------</font>
<font color="#0000FF">           Set </font>objSchComp2Ref = objSchRoot.GetInterface ("CATIASchComponent2",objSchCntblRef)
<font color="#0000FF">           If </font>( Not ( objSchComp2Ref Is Nothing ) )<font color="#0000FF"> Then</font>
              strMessage = strMessage &  "Got catalog component reference of the symbol" & vbCr
              objSchComp2Ref.PlaceInSpace objSchGRRCtlg,db6Array,objSchDoc,objSchCompInstA
<font color="#0000FF">              If </font>( Not ( objSchCompInstA Is Nothing ) )<font color="#0000FF"> Then</font>
                 strMessage = strMessage &  "Place component instance in space is successful" & vbCr
<font color="#0000FF">              End If </font>
<font color="#0000FF">           End If </font>
<font color="#0000FF">         End If</font>
<font color="#0000FF">       End If</font>

       <font color="#008000">'-----------------------------------------------------------------------</font>
       <font color="#008000">' Get another symbol from component catalog.</font>
       <font color="#008000">'-----------------------------------------------------------------------</font>
<font color="#0000FF">       Dim </font>objSchGRRCVCtlg<font color="#0000FF"> As </font>SchGRR 
<font color="#0000FF">       Dim </font>objSchCntblCVRef<font color="#0000FF"> As </font>SchAppConnectable
<font color="#0000FF">       Dim </font>objSchCompCVRef<font color="#0000FF"> As </font>SchComponent

<font color="#0000FF">       Set </font>objSchGRRCVCtlg = objSchRoot.GetCompSymbolFromCatalog ("Control Valve",objSchCtlgDoc)
<font color="#0000FF">       If </font>( Not ( objSchGRRCVCtlg Is Nothing ) )<font color="#0000FF"> Then</font>
         strMessage = strMessage &  "Got the second catalog symbol" & vbCr

         <font color="#008000">'---------------------------------------------------------------------</font>
         <font color="#008000">' Get the owner of the second symbol. That is a reference component</font>
         <font color="#008000">' in the catalog.</font>
         <font color="#008000">'---------------------------------------------------------------------</font>
<font color="#0000FF">         Set </font>objSchCntblCVRef = objSchGRRCVCtlg.GetSchObjOwner
<font color="#0000FF">         If </font>( Not ( objSchCntblCVRef Is Nothing ) )<font color="#0000FF"> Then</font>
           strMessage = strMessage &  "Got catalog connectable of the second symbol" & vbCr

           <font color="#008000">'-------------------------------------------------------------------</font>
           <font color="#008000">' Place an instance of the second reference connecting it to the</font>
           <font color="#008000">' first one. That is to "place" a new instance B connecting to </font>
           <font color="#008000">' the existing instance A.</font>
           <font color="#008000">'-------------------------------------------------------------------</font>
<font color="#0000FF">           Dim </font>objCompRefPlaceInfo<font color="#0000FF"> As </font>AnyObject  
<font color="#0000FF">           Dim </font>objCompatInfo<font color="#0000FF"> As </font>AnyObject  
<font color="#0000FF">           Dim </font>objFinalPlaceInfo<font color="#0000FF"> As </font>AnyObject
<font color="#0000FF">           Dim </font>bYesCompat<font color="#0000FF"> As </font>Boolean   
<font color="#0000FF">           Dim </font>bFindAllSolutions<font color="#0000FF"> As </font>Boolean    

<font color="#0000FF">           Set </font>objSchCompCVRef = objSchRoot.GetInterface ("CATIASchComponent",objSchCntblCVRef)
<font color="#0000FF">           If </font>( Not ( objSchCompCVRef Is Nothing ) )<font color="#0000FF"> Then</font>
              strMessage = strMessage &  "Got catalog component reference of the second symbol" & vbCr
<font color="#0000FF">           End If </font>

           <font color="#008000">'-------------------------------------------------------------------</font>
           <font color="#008000">'  Preparing to place B on A. </font>
           <font color="#008000">'  1- need to retreive a CATIASchCompatibility interface handle</font>
           <font color="#008000">'     from the existing instance (objSchCompInstA), the one we have</font>
           <font color="#008000">'     just placed in empty space.</font>
           <font color="#008000">'  2- need to retreive the graphical image (symbol instance) of</font>
           <font color="#008000">'     objSchCompInstA. This is needed for the compatibility </font>
           <font color="#008000">'     checking. </font>
           <font color="#008000">'     For this we need another interface handle: CATIASchCompGraphic</font>
           <font color="#008000">'-------------------------------------------------------------------</font>

<font color="#0000FF">           If </font>( Not ( objSchCompInstA Is Nothing ) )<font color="#0000FF"> Then</font>
<font color="#0000FF">              Set </font>objSchCompatInstA = objSchRoot.GetInterface ("CATIASchCompatible", _
                objSchCompInstA)
<font color="#0000FF">              Set </font>objSchCompGraphInstA = objSchRoot.GetInterface ("CATIASchCompGraphic", _
                objSchCompInstA)
<font color="#0000FF">              Set </font>objSchGRRCompInstA = GetComponentImage (objSchCompGraphInstA)
<font color="#0000FF">           End If</font>

<font color="#0000FF">           If </font>( Not ( objSchCompatInstA Is Nothing ) And _ 
                Not ( objSchGRRCompInstA Is Nothing ) And _
                Not ( objSchCompCVRef Is Nothing ) )<font color="#0000FF"> Then</font>

              <font color="#008000">'----------------------------------------------------------------</font>
              <font color="#008000">'  1- QueryConnectAbility.</font>
              <font color="#008000">'     Ask the reference of the new instance B for information</font>
              <font color="#008000">'     to use in compatibility checking. The objCompRefPlaceInfo</font>
              <font color="#008000">'     is an output and should be used as a "black box". </font>
              <font color="#008000">'     It is the input to the next call.</font>
              <font color="#008000">'</font>
              <font color="#008000">'  2- IsTargetOKForPlace</font>
              <font color="#008000">'     Check whether A is compatible to B in making a connection.</font>
              <font color="#008000">'     A is the first instance, it is the "target". </font>
              <font color="#008000">'     objCompatInfo is an output and should be used as </font>
              <font color="#008000">'     a "black box". It is an input to the next call.</font>
              <font color="#008000">'</font>
              <font color="#008000">'  3- GetBestFitPlaceInfo</font>
              <font color="#008000">'     Input the placement location, close to the x-y location of</font>
              <font color="#008000">'     the connector of objSchCompInstA (A) that you want to connect</font>
              <font color="#008000">'     B to. </font>
              <font color="#008000">'     objFinalPlaceInfo is an output and should be used as</font>
              <font color="#008000">'     a "black box". It is an input to the next call.</font>
              <font color="#008000">'</font>
              <font color="#008000">'  4- PlaceOnComponentWithInfo</font>
              <font color="#008000">'     Place a new instance with the black box info. </font>
              <font color="#008000">' </font>
              <font color="#008000">'----------------------------------------------------------------</font>

              <font color="#008000">' -- step 1 </font>
<font color="#0000FF">              Set </font>objCompRefPlaceInfo = objSchCompCVRef.QueryConnectAbility _
                (objSchGRRCVCtlg) 

              <font color="#008000">' -- step 2 </font>
              objSchCompatInstA.IsTargetOKForPlace objSchGRRCompInstA, _
                objCompRefPlaceInfo, objCompatInfo, bYesCompat

<font color="#0000FF">              Dim </font>db2Pt(2)<font color="#0000FF"> As </font>CATSafeArrayVariant

              <font color="#008000">'-- 6.50 is the relative x coordinate of the right connector</font>
              <font color="#008000">'-- from the symbol origin</font>
              db2Pt(0) = 145.0 + 5.00
              db2Pt(1) = 130.0

<font color="#0000FF">              If </font>( bYesCompat )<font color="#0000FF"> Then</font>
                 strMessage = strMessage &  "Target is compatible" & vbCr
                 bFindAllSolutions = false

                 <font color="#008000">' -- step 3 </font>
                 objSchCompatInstA.GetBestFitPlaceInfo db2Pt, objCompatInfo, _
                   objFinalPlaceInfo, bFindAllSolutions

<font color="#0000FF">                 If </font>( Not ( objFinalPlaceInfo is Nothing ) )<font color="#0000FF"> Then</font>

                    <font color="#008000">' -- step 4 </font>
<font color="#0000FF">                    Set </font>objSchCompInstB = objSchCompCVRef.PlaceOnComponentWithInfo _
                      (objFinalPlaceInfo)

<font color="#0000FF">                    If </font>( Not ( objSchCompInstB is Nothing ) )<font color="#0000FF"> Then</font>
                       strMessage = strMessage &  _
                         "Place a new component instance on another existing object is successful" & vbCr
<font color="#0000FF">                    End If</font>

<font color="#0000FF">                 End If </font>

              Else 
                 strMessage = strMessage &  "Target is NOT compatible" & vbCr
<font color="#0000FF">              End If</font>

<font color="#0000FF">           End If </font><font color="#008000">'----If ( Not ( objSchCompatInstA Is Nothing )...</font>

<font color="#0000FF">         End If </font><font color="#008000">'---- If ( Not ( objSchCntblCVRef Is Nothing )...</font>
<font color="#0000FF">       End If </font><font color="#008000">'---- If ( Not ( objSchGRRCVCtlg Is Nothing )...</font>
<font color="#0000FF">    End If  </font><font color="#008000">'----If ( Not ( objSchRoot Is Nothing )...</font>

    strMessage = strMessage & _
      "--------------------------------------------------------------------" & vbCr
    MsgBox strMessage

<font color="#0000FF">End Sub</font>

<font color="#008000">' -----------------------------------------------------------------------------</font>
<font color="#008000">' | Find the first symbol used for the input schematic component.</font>
<font color="#008000">' | Input: objSchCompGraphArg:  the schematic component </font>
<font color="#008000">' |        (a CATIASchCompGraphic interface handle).</font>
<font color="#008000">' | Returns: the component image (the symbol instance)</font>
<font color="#008000">' -----------------------------------------------------------------------------</font>
Private Function GetComponentImage (objSchCompGraphArg<font color="#0000FF"> As </font>SchCompGraphic)<font color="#0000FF"> As </font>SchGRRComp
<font color="#0000FF">   Dim </font>objSchLSymbols<font color="#0000FF"> As </font>SchListOfObjects
<font color="#0000FF">   If </font>( Not ( objSchCompGraphArg Is Nothing ) )<font color="#0000FF"> Then</font>
<font color="#0000FF">      Set </font>objSchLSymbols = objSchCompGraphArg.ListGraphicalImages
<font color="#0000FF">      If </font>( Not ( objSchLSymbols Is Nothing ) )<font color="#0000FF"> Then</font>
<font color="#0000FF">         Set </font>GetComponentImage = objSchLSymbols.Item (1,"CATIASchGRRComp")
<font color="#0000FF">      End If</font>
<font color="#0000FF">   End If</font>
<font color="#0000FF">End Function</font>





</pre></body></html>
