<html><head><meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"><title>CAASchCompRefGraphic.CATScript</title><link rel="stylesheet" type="text/css" href="../CAAScrBase/caav5.css"></head><body><pre>
<font color="#0000FF">Option Explicit</font>
<font color="#008000">' COPYRIGHT DASSAULT SYSTEMES 2004</font>

<font color="#008000">' *****************************************************************************</font>
<font color="#008000">'   Purpose:      Add/List graphical representations to a reference component. </font>
<font color="#008000">'   Languages:    VBScript</font>
<font color="#008000">'   Locales:      English </font>
<font color="#008000">'   CATIA Level:  V5R15 </font>
<font color="#008000">' *****************************************************************************</font>

<font color="#0000FF">Sub </font>CATMain()

    <font color="#008000">' ------------------------------------------------------------------------- </font>
    <font color="#008000">' Optional: allows to find the sample wherever it's installed</font>
<font color="#0000FF">    dim </font>sDocPath<font color="#0000FF"> As </font>String 
    sDocPath=CATIA.SystemService.Environ("CATDocView")

<font color="#0000FF">    If </font>(Not CATIA.FileSystem.FolderExists(sDocPath))<font color="#0000FF"> Then</font>
      Err.Raise 9999,sDocPath,"No Doc Path Defined"
<font color="#0000FF">    End If</font>
    <font color="#008000">' ------------------------------------------------------------------------- </font>
    <font color="#008000">' Open the schematic document </font>
<font color="#0000FF">    Dim </font>sFilePath
    sFilePath = CATIA.FileSystem.ConcatenatePaths(sDocPath, _
            "online\CAAScdSchUseCases\samples\CAASCH_Detail03.CATProduct")

<font color="#0000FF">    Dim </font>objSchDoc<font color="#0000FF"> As </font>Document
<font color="#0000FF">    Set </font>objSchDoc = CATIA.Documents.Open(sFilePath)

<font color="#0000FF">    Dim </font>strMessage<font color="#0000FF"> As </font>String

    strMessage = _
      "--------------------------------------------------------------------" & vbCr
    strMessage = strMessage & _
      "Output traces from CAASchCompRefGraphic.CATScript" & vbCrLf

    <font color="#008000">' Find the top node of the schematic object tree - schematic root.</font>
<font color="#0000FF">    Dim </font>objPrdRoot<font color="#0000FF"> As </font>Product
<font color="#0000FF">    Dim </font>objSchRoot<font color="#0000FF"> As </font>SchematicRoot
<font color="#0000FF">    If </font>( Not ( objSchDoc Is Nothing ) )<font color="#0000FF"> Then</font>
<font color="#0000FF">      Set </font>objPrdRoot = objSchDoc.Product 
<font color="#0000FF">      If </font>( Not ( objPrdRoot Is Nothing ) )<font color="#0000FF"> Then</font>
<font color="#0000FF">        Set </font>objSchRoot = objPrdRoot.GetTechnologicalObject("SchematicRoot")
<font color="#0000FF">      End If</font>
<font color="#0000FF">    End If</font>

<font color="#0000FF">    Dim </font>objLCompRefs<font color="#0000FF"> As </font>SchListOfObjects
<font color="#0000FF">    Dim </font>objCompRefGraphic<font color="#0000FF"> As </font>SchCompGraphic

<font color="#0000FF">    If </font>( Not ( objSchRoot Is Nothing ) )<font color="#0000FF"> Then</font>

       <font color="#008000">'-----------------------------------------------------------------------</font>
       <font color="#008000">' Find a list of reference component in the model</font>
       <font color="#008000">'-----------------------------------------------------------------------</font>
<font color="#0000FF">       Set </font>objLCompRefs = objSchRoot.GetRefComponents

<font color="#0000FF">       If </font>( Not ( objLCompRefs Is Nothing ) )<font color="#0000FF"> Then</font>

          <font color="#008000">'--------------------------------------------------------------------</font>
          <font color="#008000">' Get a SchCompGraphic interface handle from a reference</font>
          <font color="#008000">' component</font>
          <font color="#008000">'--------------------------------------------------------------------</font>
<font color="#0000FF">          Set </font>objCompRefGraphic = objLCompRefs.Item (1,"CATIASchCompGraphic")

<font color="#0000FF">          If </font>( Not ( objCompRefGraphic Is Nothing ) )<font color="#0000FF"> Then</font>

<font color="#0000FF">              Dim </font>objUnassocSymbol<font color="#0000FF"> As </font>AnyObject

              <font color="#008000">'----------------------------------------------------------------</font>
              <font color="#008000">' Find a symbol that is not associated with any reference in</font>
              <font color="#008000">' the model</font>
              <font color="#008000">'----------------------------------------------------------------</font>
<font color="#0000FF">              Set </font>objUnassocSymbol = GetComponentSymbol (objSchRoot)

<font color="#0000FF">              If </font>( Not ( objUnassocSymbol Is Nothing ) )<font color="#0000FF"> Then</font>

                <font color="#008000">'--------------------------------------------------------------</font>
                <font color="#008000">'  Add the second graphical representation to the reference</font>
                <font color="#008000">'  component using the symbol just found</font>
                <font color="#008000">'--------------------------------------------------------------</font>
                objCompRefGraphic.AddGraphicalRepresentation objUnassocSymbol

                strMessage = strMessage & "Successfully add the second graphical representation" & vbCr

<font color="#0000FF">              End If</font>

              <font color="#008000">'----------------------------------------------------------------</font>
              <font color="#008000">' Find another symbol that is not associated with </font>
              <font color="#008000">' any reference in the model</font>
              <font color="#008000">'----------------------------------------------------------------</font>
<font color="#0000FF">              Set </font>objUnassocSymbol = GetComponentSymbol (objSchRoot)
<font color="#0000FF">              If </font>( Not ( objUnassocSymbol Is Nothing ) )<font color="#0000FF"> Then</font>

                <font color="#008000">'--------------------------------------------------------------</font>
                <font color="#008000">'  Add the third graphical representation to the reference</font>
                <font color="#008000">'  component using the symbol just found</font>
                <font color="#008000">'--------------------------------------------------------------</font>
                objCompRefGraphic.AddGraphicalRepresentation objUnassocSymbol

                strMessage = strMessage & "Successfully add the third graphical representation" & vbCr

<font color="#0000FF">              End If</font>

<font color="#0000FF">              Dim </font>intNbGraphic<font color="#0000FF"> As </font>Integer
<font color="#0000FF">              Dim </font>objGRR<font color="#0000FF"> As </font>SchGRR
<font color="#0000FF">              Dim </font>objLGraphic<font color="#0000FF"> As </font>SchListOfObjects
<font color="#0000FF">              Set </font>objLGraphic = objCompRefGraphic.ListGraphicalRepresentations
             
<font color="#0000FF">              If </font>( Not ( objLGraphic Is Nothing ) )<font color="#0000FF"> Then</font>
                 intNbGraphic = objLGraphic.Count
                 strMessage = strMessage & "Number of graphical representations"
                 strMessage = strMessage & "= " & intNbGraphic & vbCr

<font color="#0000FF">                 Set </font>objGRR = Nothing
<font color="#0000FF">                 If </font>(intNbGraphic &gt; 1)<font color="#0000FF"> Then</font>
<font color="#0000FF">                    Set </font>objGRR = objLGraphic.Item(intNbGraphic,"CATIASchGRR")
<font color="#0000FF">                    If </font>( Not (objGRR Is Nothing ) )<font color="#0000FF"> Then</font>
                       objCompRefGraphic.RemoveGraphicalRepresentation objGRR
<font color="#0000FF">                       Set </font>objLGraphic = objCompRefGraphic.ListGraphicalRepresentations
<font color="#0000FF">                       If </font>( Not ( objLGraphic Is Nothing ) )<font color="#0000FF"> Then</font>
                          intNbGraphic = objLGraphic.Count
                          strMessage = strMessage & "Number of graphical representations"
                          strMessage = strMessage & "after calling "
                          strMessage = strMessage & " RemoveGraphicalRepresentation = " & intNbGraphic & vbCr
<font color="#0000FF">                       End If </font>
<font color="#0000FF">                    End If</font>
<font color="#0000FF">                 End If </font><font color="#008000">' --- If (intNbGraphic &gt; 1)</font>
<font color="#0000FF">              End If </font><font color="#008000">'--- If ( Not ( objLGraphic Is Nothing ) ) Then</font>

<font color="#0000FF">          End If </font><font color="#008000">'--- If ( Not ( objCompRefGraphic Is Nothing )...</font>

<font color="#0000FF">       End If </font><font color="#008000">'--- If ( Not ( objLCompRefs Is Nothing ) ...</font>

<font color="#0000FF">    End If </font><font color="#008000">'--- If ( Not ( objSchRoot Is Nothing )...</font>

    strMessage = strMessage & _
      "--------------------------------------------------------------------" & vbCr
    MsgBox strMessage


<font color="#0000FF">End Sub</font>

<font color="#008000">' -----------------------------------------------------------------------------</font>
<font color="#008000">' | Find a component symbol that has not been associated with a schematic</font>
<font color="#008000">' | component from a document root.</font>
<font color="#008000">' | Input: objSchRootArg:  the root of the document.</font>
<font color="#008000">' | Returns: component symbol object.</font>
<font color="#008000">' -----------------------------------------------------------------------------</font>
Private Function GetComponentSymbol (objSchRootArg<font color="#0000FF"> As </font>SchematicRoot)<font color="#0000FF"> As </font>AnyObject
<font color="#0000FF">   Dim </font>objSchLSymbols<font color="#0000FF"> As </font>SchListOfObjects
<font color="#0000FF">   If </font>( Not ( objSchRootArg Is Nothing ) )<font color="#0000FF"> Then</font>
<font color="#0000FF">      Set </font>objSchLSymbols = objSchRootArg.GetUnassociatedSymbols
<font color="#0000FF">      If </font>( Not ( objSchLSymbols Is Nothing ) )<font color="#0000FF"> Then</font>
<font color="#0000FF">         Set </font>GetComponentSymbol = objSchLSymbols.Item (1,"CATIASchGRR")
<font color="#0000FF">      End If</font>
<font color="#0000FF">   End If</font>
<font color="#0000FF">End Function</font>
</pre></body></html>
