<html>

 <head>
 <meta http-equiv="Content-Language" content="fr">
 <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
 <meta name="GENERATOR" content="Microsoft FrontPage 5.0">
 <meta name="ProgId" content="FrontPage.Editor.Document">
 <title>Creating a Schematic Document from an Existing Document</title>
 <link rel="stylesheet" type="text/css" href="../CAAScrBase/caav5.css">
 <script language="JavaScript" src="../CAAScrJavaScript/submit.js">
 </script>
 </head>

 <body>

 <table border="0" width="100%">
   <tr>
     <td>
     <h2>Schematics Platform Modeler</h2>
     </td>
     <td align="right" valign="top">
     <h2><a name="Top"></a>Creating a Schematic Document from an Existing 
     Document</h2>
     </td>
   </tr>
 </table>
 <hr>
 <!---------------------------------comment----------------------------------->
 <table border="0">
   <tr>
     <td width="7%" valign="top">
     <img border="0" src="../CAAScrBase/images/atarget.gif" width="32" height="32"></td>
     <td width="93%"><a name="Learn"></a>This macro shows you how to create a 
     new schematic document from an opened document.<p>This macro opens the 
     document CAASchSCH_Detail01.CATProduct. From the root object of this 
     document, the macro obtains a handle on the current CNEXT session. The 
     macro creates a new schematic document and add it to this session.</td>
   </tr>
   <tr>
     <td width="7%" valign="top">
     <img border="0" src="../CAAScrBase/images/ainfo.gif" width="32" height="32"></td>
     <td width="93%"><a name="How"></a>CAASchCreateSchDocument is launched in 
     CATIA [<a href="#References">1</a>]. No open document is needed.<p>
     <a href="CAASchCreateSchDocumentSource.htm">
     CAASchCreateSchDocument.CATScript </a>is located in the CAAScdSchUseCases 
     module. <a href="macros/CAASchCreateSchDocument.CATScript">Execute macro</a> 
     (Windows only).</td>
   </tr>
   <tr>
     <td width="7%" valign="top">
     <img border="0" src="../CAAScrBase/images/ascenari.gif" width="32" height="32"></td>
     <td width="93%"><a name="Step"></a>CAASchCreateSchDocument includes the 
     following steps:<ol>
       <li><a href="#Prolog">Prolog</a></li>
       <li><a href="#Get CNEXT session">Get a the current CNEXT session</a></li>
       <li><a href="#Create Schematic document">Create a new schematic document</a></li>
       <li><a href="#Set the drawing standard">Set the drawing standard</a></li>
     </ol>
     <h4><a name="Prolog"></a>Prolog</h4>
     <p>The macro first loads CAASCH_Detail01.CATProduct.</p>
     <table class="code">
       <tr>
         <td width="100%">&nbsp;&nbsp;&nbsp;    <font color="#008000">...</font><br>
<font color="#008000">&nbsp;&nbsp;&nbsp; ' Open the schematic document </font>
         <br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;    Dim </font>sFilePath<br>
&nbsp;&nbsp;&nbsp; sFilePath = CATIA.FileSystem.ConcatenatePaths(sDocPath, _<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "online\CAAScdSchUseCases\samples\CAASCH_Detail01.CATProduct")<br>
         <br>

<font color="#0000FF">&nbsp;&nbsp;&nbsp;    Dim </font>objSchDoc<font color="#0000FF"> As </font>Document<br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;    Set </font>objSchDoc = CATIA.Documents.Open(sFilePath)<br>
&nbsp;&nbsp;&nbsp;
    <font color="#008000">...</font></td>
       </tr>
     </table>
     <p>Next, the macro acquires the schematic root object from the document. 
     The schematic root is the top node of the object instance tree in a 
     schematic document.</p>
     <table class="code">
       <tr>
         <td width="100%">&nbsp;&nbsp;&nbsp;    <font color="#008000">...</font><br>
&nbsp;&nbsp;&nbsp;
    <font color="#008000">' Find the top node of the schematic object tree - schematic root.</font><br>
<font color="#0000ff">&nbsp;&nbsp;&nbsp;    Dim </font>objPrdRoot<font color="#0000ff"> As </font>Product<br>
<font color="#0000ff">&nbsp;&nbsp;&nbsp;    Dim </font>objSchRoot<font color="#0000ff"> As </font>SchematicRoot<br>
<font color="#0000ff">&nbsp;&nbsp;&nbsp;    If </font>( Not ( objSchDoc Is Nothing ) )<font color="#0000ff"> Then</font><br>
<font color="#0000ff">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;      Set </font>objPrdRoot = objSchDoc.Product
         <br>
<font color="#0000ff">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;      If </font>( Not ( objPrdRoot Is Nothing ) )<font color="#0000ff"> Then</font><br>
<font color="#0000ff">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;        Set </font>objSchRoot = objPrdRoot.GetTechnologicalObject(&quot;SchematicRoot&quot;)<br>
<font color="#0000ff">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; End If</font><br>
<font color="#0000ff">&nbsp;&nbsp;&nbsp; End If</font><br>
&nbsp;&nbsp;&nbsp;
    <font color="#008000">...</font></td>
       </tr>
     </table>
     <h4><a name="Get CNEXT session"></a>Get a the current CNEXT session</h4>
     <p>Using the GeSchematicSession method, a handle on the SchSession 
     interface can be obtained. This interface provides a method to create a new 
     schematic document.</p>
     <table class="code">
       <tr>
         <td width="100%">&nbsp;&nbsp;&nbsp;    <font color="#008000">...</font><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
       <font color="#008000">'-----------------------------------------------------------------------</font><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
       <font color="#008000">' Get the schematic session.</font><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
       <font color="#008000">'-----------------------------------------------------------------------</font><br>
         <br>

<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;       Set </font>objSchSession = objSchRoot.GetSchematicSession<br>
&nbsp;&nbsp;&nbsp;
    <font color="#008000">...</font></td>
       </tr>
     </table>
     <h4><a name="Create Schematic document"></a>Create a new schematic document</h4>
     <table class="code">
       <tr>
         <td width="100%">&nbsp;&nbsp;&nbsp;    <font color="#008000">...</font><br>
<font color="#0000FF">&nbsp;</font>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;         <font color="#008000">'---------------------------------------------------------------------</font><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
         <font color="#008000">' Create another schematic document.</font><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
         <font color="#008000">'---------------------------------------------------------------------</font><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
         <font color="#008000">'bInteractive = true</font><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; bInteractive = false<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; objSchSession.CreateDocument &quot;CATProduct&quot;,bInteractive,objSchDocNew<br>
&nbsp;&nbsp;&nbsp;
    <font color="#008000">...</font></td>
       </tr>
     </table>
     <h4><a name="Set the drawing standard"></a>Set the drawing standard of the 
     drafting viewer in the schematic document</h4>
     <p>A schematic document has a drafting viewer embedded in it. The drawing 
     standard of that drafting viewer can be set by calling the 
     SetDrawingStandard method. This macro also illustrates how to use the 
     GetDrawingStandard method to retrieve the drawing standard of a schematic 
     document.</p>
     <table class="code">
       <tr>
         <td width="100%">&nbsp;&nbsp;&nbsp;    <font color="#008000">...</font><br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;         If </font>( Not ( objSchDocNew Is Nothing ) )<font color="#0000FF"> Then</font><br>
         <br>

<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;            Set </font>objPrdRoot = Nothing<br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;            Set </font>objSchRoot = Nothing<br>
         <br>

<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;            Set </font>objPrdRoot = objSchDocNew.Product
         <br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;            If </font>( Not ( objPrdRoot Is Nothing ) )<font color="#0000FF"> Then</font><br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;               Set </font>objSchRoot = objPrdRoot.GetTechnologicalObject(&quot;SchematicRoot&quot;)<br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; End If</font><br>
         <br>

<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;            If </font>( Not ( objSchRoot Is Nothing ) )<font color="#0000FF"> Then</font><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; objSchRoot.SetDrawingStandard catISO<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; strMessage = strMessage &amp; &quot;drawing standard set to catISO&quot; &amp; vbCr<br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;               Dim </font>std<font color="#0000FF"> As </font>CatDrawingStandard<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; std = objSchRoot.GetDrawingStandard<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; strMessage = strMessage &amp; &quot;drawing standard = &quot; &amp; std &amp; vbCr<br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; End If</font><br>
&nbsp;&nbsp;&nbsp;
    <font color="#008000">...</font></td>
       </tr>
     </table>
     </td>
   </tr>
 </table>
 <p align="right">[<a href="#Top">Top</a>]</p><hr>
 <!---------------------------------comment----------------------------------->
 <h4><a name="InShort"></a>In Short</h4>
 <p>This use case shows how to create a schematic document from the root of an 
 existing document. A message logging the status of the critical steps is 
 displayed at the end of the use case. </p>
 <p>
 <img border="0" src="images/CAASchCreateSchDocument.jpg" width="638" height="225"></p>
 <p align="right">[<a href="#Top">Top</a>]</p><hr>
 <!---------------------------------comment----------------------------------->
 <h4><a name="References"></a>References</h4>
 <table border="0" width="100%">
   <tr>
     <td valign="top">[1]</td>
     <td><a href="../CAAScdInfUseCases/CAAInfLauchMacro.htm">
     Replaying a Macro</a></td>
   </tr>
   <tr>
     <td valign="top"></td>
     <td></td>
   </tr>
   <tr>
     <td colspan="2" align="right">[<a href="#Top">Top</a>]</td>
   </tr>
 </table>
 <hr>
 <!---------------------------------comment----------------------------->
 <p><i>Copyright © 2001, Dassault Systèmes. All rights reserved.</i></p>

 </body>

</html>
