<html>

 <head>
 <meta http-equiv="Content-Language" content="fr">
 <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
 <meta name="GENERATOR" content="Microsoft FrontPage 6.0">
 <meta name="ProgId" content="FrontPage.Editor.Document">
 <title>Creating a Schematic Network Object</title>
 <link rel="stylesheet" type="text/css" href="../CAAScrBase/caav5.css">
 <script language="JavaScript" src="../CAAScrJavaScript/submit.js">
 </script>
 </head>

 <body>

 <table border="0" width="100%">
   <tr>
     <td>
     <h2>Schematics Platform Modeler</h2>
     </td>
     <td align="right" valign="top">
     <h2><a name="Top"></a>Creating a Schematic Network Object</h2>
     </td>
   </tr>
 </table>
 <hr>
 <!---------------------------------comment----------------------------------->
 <table border="0" width="100%">
   <tr>
     <td width="7%" valign="top">
     <img border="0" src="../CAAScrBase/images/atarget.gif" width="32" height="32"></td>
     <td width="93%"><a name="Learn"></a>This macro shows you how to create a 
     schematic network object.<p>Given a list of independent objects, this 
     macros shows how to create a Schematic network for each member in the list. 
     The network will include the member itself and all the objects that are 
     connected to it.</p>
     <p>This macro opens the CAASCH_Network01.CATProduct document.</p>
     <p>
     <img border="0" src="images/CAASchNetwork_01.jpg" width="730" height="453"></p>
     <p>Through special naming convention (i.e. the word &quot;network&quot; embedded in 
     the instance name), the macro knows to include the following Schematic 
     component instances in the input list.</p>
     <ol>
       <li>V-082_network_scale_instance.</li>
       <li>V_084_network instance (the control valve in the screen shot).</li>
     </ol>
     </td>
   </tr>
   <tr>
     <td width="7%" valign="top">
     <img border="0" src="../CAAScrBase/images/ainfo.gif" width="32" height="32"></td>
     <td width="93%"><a name="How"></a>CAASchNetwork is launched in CATIA [<a href="#References">1</a>]. 
     No open document is needed.<p>Special 
		environment must be available to successfully run this macro:</p>
		<ul>
			<li>Prerequisites:</li>
		</ul>
		<blockquote>
			<ol>
				<li>RADE must be installed.</li>
				<li>CAASchPlatformModeler.edu must exist in CAADoc folder.</li>
			</ol>
		</blockquote>
		<ul>
			<li>Setup:</li>
		</ul>
		<blockquote>
			<ol>
				<li>Build CAASchAppBase.m and CAASchAppUtilities.m, located in 
				CAASchPlatformModeler.edu (RADE is required). </li>
				<li>Copy generated DLLs, CAASchAppBase.dll and 
				CAASchAppUtilities.m, respectively, to the run-time environment 
				folder &quot;intel_a\code\bin.&quot;</li>
				<li>Copy CAASCHEDUApp.CATfct, located CAASchPlatformModeler.edu\CNext\resources\graphic, 
				to the run-time environment folder &quot;intel_a\resources\graphic.&quot;</li>
				<li>Copy CAASchPlatformModeler.edu\CNext\code\dictionary\CAASchPlatformModeler.edu.dico 
				to the run-time environment folder &quot;intel_a\code\dictionary.&quot;</li>
			</ol>
		</blockquote>
		<p><a href="CAASchNetworkSource.htm">
     CAASchNetwork.CATScript </a>is located in the CAAScdSchUseCases module.
     <a href="macros/CAASchNetwork.CATScript">Execute macro</a> (Windows only).</td>
   </tr>
   <tr>
     <td width="7%" valign="top">
     <img border="0" src="../CAAScrBase/images/ascenari.gif" width="32" height="32"></td>
     <td width="93%"><a name="Step"></a>CAASchNetwork includes the following 
     steps:<ol>
       <li><a href="#Prolog">Prolog</a></li>
       <li><a href="#Create a list of network">Create a list of network objects 
       using the SchBaseFactory interface</a></li>
       <li><a href="#Query member">Query the member of the list of network 
       objects</a></li>
     </ol>
     <h4><a name="Prolog"></a>Prolog</h4>
     <p>The macro first loads CAASCH_Network01.CATProduct.</p>
     <table class="code">
       <tr>
         <td width="100%">&nbsp;&nbsp;&nbsp;    <font color="#008000">...</font><br>
&nbsp;&nbsp;&nbsp;
    <font color="#008000">' ------------------------------------------------------------------------- </font>
         <br>
&nbsp;&nbsp;&nbsp;
    <font color="#008000">' Open the schematic document </font><br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;    Dim </font>sFilePath<br>
&nbsp;&nbsp;&nbsp; sFilePath = CATIA.FileSystem.ConcatenatePaths(sDocPath, _<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "online\CAAScdSchUseCases\samples\CAASCH_Network01.CATProduct")<br>
         <br>

<font color="#0000FF">&nbsp;&nbsp;&nbsp;    Dim </font>objSchDoc<font color="#0000FF"> As </font>Document<br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;    Set </font>objSchDoc = CATIA.Documents.Open(sFilePath)<br>
&nbsp;&nbsp;&nbsp;
    <font color="#008000">...</font></td>
       </tr>
     </table>
     <p>Next, the macro acquires the schematic root object from the document. 
     The schematic root is the top node of the object instance tree in a 
     schematic document.</p>
     <table class="code">
       <tr>
         <td width="100%">&nbsp;&nbsp;&nbsp;    <font color="#008000">...</font><br>
&nbsp;&nbsp;&nbsp;
    <font color="#008000">' Find the top node of the schematic object tree - schematic root.</font><br>
<font color="#0000ff">&nbsp;&nbsp;&nbsp;    Dim </font>objPrdRoot<font color="#0000ff"> As </font>Product<br>
<font color="#0000ff">&nbsp;&nbsp;&nbsp;    Dim </font>objSchRoot<font color="#0000ff"> As </font>SchematicRoot<br>
<font color="#0000ff">&nbsp;&nbsp;&nbsp;    If </font>( Not ( objSchDoc Is Nothing ) )<font color="#0000ff"> Then</font><br>
<font color="#0000ff">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;      Set </font>objPrdRoot = objSchDoc.Product
         <br>
<font color="#0000ff">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;      If </font>( Not ( objPrdRoot Is Nothing ) )<font color="#0000ff"> Then</font><br>
<font color="#0000ff">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;        Set </font>objSchRoot = objPrdRoot.GetTechnologicalObject(&quot;SchematicRoot&quot;)<br>
<font color="#0000ff">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; End If</font><br>
<font color="#0000ff">&nbsp;&nbsp;&nbsp; End If</font><br>
&nbsp;&nbsp;&nbsp;
    <font color="#008000">...</font></td>
       </tr>
     </table>
     <h4><a name="Create a list of network"></a>Create a list of network objects 
     using the SchBaseFactory interface</h4>
     <p>The macro calls the GetSchBaseFactory method to get a handle of the 
     SchBaseFactory interface.</p>
     <p>This macro provides a private Find2ComponentInst function which searches 
     for 2 component instances in the model based on a specific naming 
     convention. Those instances which have the word &quot;network&quot; as parts of their 
     instance names will be included. For each instance returned by 
     Find2ComponentInst, the graphical image of the instance is also returned. 
     Notice that two global variables: objLCntbl_<b>g</b> and objLGRR_<b>g </b>
     are used to stored these results in Find2ComponentInst. They are available 
     to the main subroutine to be used in calling the CreateNetwork method.</p>
     <table class="code">
       <tr>
         <td width="100%">&nbsp;&nbsp;&nbsp;    <font color="#008000">...</font><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
       <font color="#008000">'-----------------------------------------------------------------------</font><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
       <font color="#008000">' Get all the necessary factories.</font><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
       <font color="#008000">'-----------------------------------------------------------------------</font><br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;       Set </font>objSchBaseFact = objSchRoot.GetSchBaseFactory
         <br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;       Set </font>objSchTempListFact = objSchRoot.GetTemporaryListFactory<br>
         <br>

<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;       If </font>( Not ( objSchBaseFact Is Nothing )&nbsp; And _<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Not ( objSchTempListFact Is Nothing ) )<font color="#0000FF"> Then</font><br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;          Set </font>objLCntbl_g = objSchTempListFact.CreateListOfObjects<br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;          Set </font>objLGRR_g = objSchTempListFact.CreateListOfObjects<br>
         <br>

<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;          If </font>( Not ( objLCntbl_g Is Nothing )&nbsp; And _<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Not ( objLGRR_g Is Nothing ) )<font color="#0000FF"> Then</font><br>
         <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

             <font color="#008000">'-----------------------------------------------------------------</font><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
             <font color="#008000">' The following &quot;Sub&quot; will populate objLCntbl_g and objLGRR_g</font><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
             <font color="#008000">'-----------------------------------------------------------------</font><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Find2ComponentInst objSchRoot<br>
         <br>

<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;             Set </font>objLNetWork = objSchBaseFact.CreateNetwork (objLCntbl_g, _<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; objLGRR_g)<br>
<font color="#008000">&nbsp;&nbsp;&nbsp;    ...</font></td>
       </tr>
     </table>
     <h4><a name="Query member"></a>Query the member of the list of network 
     objects</h4>
     <p>Each network object in the list contains the following information.</p>
     <ol>
       <li>The input object itself.</li>
       <li>A list of Schematic component instances that are directly or 
       indirectly connected to the input object. This list of connected 
       component instances can be retrieved using the ListNetworkObjects method.</li>
       <li>The listing procedure is recursive, and it will stop when the 
       connected object is a Schematic route. This Schematic route (known as the 
       &quot;extremity&quot;) will be stored in a separate list. This list of &quot;extremity&quot; 
       objects can be retrieved using the ListExtremityObjects method.</li>
     </ol>
     <p>The macro first find out the number of network objects in the output 
     list. Then, for each member in the output list it does the following.</p>
     <ol>
       <li>Call the ListNetworkObjects method to get a list of connected 
       Schematic component.</li>
       <li>Call the ListExtremityObjects method to get a list of extremity 
       objects (the Schematic route objects).</li>
       <li>For each member in those lists, the macro obtain a Product interface 
       handle to report their instance names.</li>
     </ol>
     <table class="code">
       <tr>
         <td width="100%">&nbsp;&nbsp;&nbsp;    <font color="#008000">...</font><br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;    If </font>(&nbsp; Not ( objLNetWork Is Nothing ) )<font color="#0000FF"> Then</font><br>
         <br>

<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;       Dim </font>intNbNet<font color="#0000FF"> As </font>Integer<br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;       Dim </font>intNetIndex<font color="#0000FF"> As </font>Integer<br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;       Dim </font>intNbMember<font color="#0000FF"> As </font>Integer<br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;       Dim </font>intMemIndex<font color="#0000FF"> As </font>Integer<br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;       Dim </font>objSchNet<font color="#0000FF"> As </font>SchNetworkAnalysis<br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;       Dim </font>objLNetMember<font color="#0000FF"> As </font>SchListOfObjects<br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;       Dim </font>objMemPrd<font color="#0000FF"> As </font>Product<br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;       Dim </font>strName<font color="#0000FF"> As </font>String<br>
         <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

      <font color="#0000FF">&nbsp;int</font>NbNet = objLNetWork.Count<br>
&nbsp;&nbsp;&nbsp;
    <font color="#008000">...</font><br>
         <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

       <font color="#008000">'-----------------------------------------------------------------------</font><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
       <font color="#008000">' Query the network members</font><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
       <font color="#008000">'-----------------------------------------------------------------------</font><br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;       For </font>intNetIndex = 1 To<font color="#0000FF"> int</font>NbNet
         <br>
         <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 

        <font color="#0000FF">&nbsp;int</font>NbMember = 0<br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;         Set </font>objLNetMember = Nothing<br>
         <br>

<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;         Set </font>objSchNet = objLNetWork.Item (intNetIndex,&quot;CATIASchNetworkAnalysis&quot;)<br>
         <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

         <font color="#008000">'---------------------------------------------------------------------</font><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
         <font color="#008000">'&nbsp; Get the members of the list of connectables.</font><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
         <font color="#008000">'---------------------------------------------------------------------</font><br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;         If </font>( Not ( objSchNet Is Nothing ) )<font color="#0000FF"> Then</font><br>
         <br>

<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;            Set </font>objLNetMember = objSchNet.ListNetworkObjects<br>
         <br>

<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; End If </font>
         <br>
         <br>

<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;         If </font>( Not ( objLNetMember Is Nothing ) )<font color="#0000FF"> Then</font><br>
         <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

           <font color="#0000FF">&nbsp;int</font>NbMember = objLNetMember.Count<br>
         <br>
&nbsp;&nbsp;&nbsp;

    <font color="#008000">...</font><br>
         <br>

<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;            For </font>intMemIndex = 1 To<font color="#0000FF"> int</font>NbMember<br>
         <br>

<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;              Set </font>objMemPrd = objLNetMember.Item (intMemIndex,&quot;CATIAProduct&quot;)<br>
&nbsp;&nbsp;&nbsp;
    <font color="#008000">...</font><br>
         <br>

<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;            Next </font><font color="#008000">'--- For intMemIndex</font><br>
         <br>

<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; End If </font><font color="#008000">'--- If ( Not ( objLNetMember Is Nothing ) ...</font><br>
         <br>
         <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;


         <font color="#008000">'---------------------------------------------------------------------</font><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
         <font color="#008000">'&nbsp; Get the members of the list of extremities (routes).</font><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
         <font color="#008000">'---------------------------------------------------------------------</font><br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;         If </font>( Not ( objSchNet Is Nothing ) )<font color="#0000FF"> Then</font><br>
         <br>

<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;            Set </font>objLNetMember = objSchNet.ListExtremityObjects<br>
         <br>

<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; End If </font>
         <br>
         <br>

<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;         If </font>( Not ( objLNetMember Is Nothing ) )<font color="#0000FF"> Then</font><br>
         <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

           <font color="#0000FF">&nbsp;int</font>NbMember = objLNetMember.Count<br>
&nbsp;&nbsp;&nbsp;
    <font color="#008000">...</font><br>
         <br>

<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;            For </font>intMemIndex = 1 To<font color="#0000FF"> int</font>NbMember<br>
         <br>

<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;              Set </font>objMemPrd = objLNetMember.Item (intMemIndex,&quot;CATIAProduct&quot;)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; strName = &quot;&quot;<br>
&nbsp;&nbsp;&nbsp;
    <font color="#008000">...</font><br>
         <br>

<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;            Next </font><font color="#008000">'--- For intMemIndex</font><br>
         <br>

<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; End If </font><font color="#008000">'--- If ( Not ( objLNetMember Is Nothing ) ...</font><br>
         <br>

<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;       Next </font><font color="#008000">'--- For intNetIndex</font><br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp; End If </font><font color="#008000">'--- If ( Not ( objLNetWork Is Nothing ) ...</font></td>
       </tr>
     </table>
     </td>
   </tr>
 </table>
 <p align="right">[<a href="#Top">Top</a>]</p><hr>
 <!---------------------------------comment----------------------------------->
 <h4><a name="InShort"></a>In Short</h4>
 <p>This use case shows how to create a Schematic network object. Furthermore, 
 it illustrates how to get information from the network object. A message 
 logging the status of the critical steps is displayed at the end of the use 
 case. </p>
 <p><img border="0" src="images/CAASchNetwork_02.jpg" width="788" height="516"></p>
 <p align="right">[<a href="#Top">Top</a>]</p><hr>
 <!---------------------------------comment----------------------------------->
 <h4><a name="References"></a>References</h4>
 <table border="0" width="100%">
   <tr>
     <td valign="top">[1]</td>
     <td><a href="../CAAScdInfUseCases/CAAInfLauchMacro.htm">
     Replaying a Macro</a></td>
   </tr>
   <tr>
     <td valign="top"></td>
     <td></td>
   </tr>
   <tr>
     <td colspan="2" align="right">[<a href="#Top">Top</a>]</td>
   </tr>
 </table>
 <hr>
 <!---------------------------------comment----------------------------------->
 <p><i>Copyright © 2001, Dassault Systèmes. All rights reserved.</i></p>

 </body>

</html>
