<html><head><meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"><title>CAASchQueryConnectivity.CATScript</title><link rel="stylesheet" type="text/css" href="../CAAScrBase/caav5.css"></head><body><pre>
<font color="#0000FF">Option Explicit</font>
<font color="#008000">' COPYRIGHT DASSAULT SYSTEMES 2004</font>

<font color="#008000">' *****************************************************************************</font>
<font color="#008000">'   Purpose:      Query the connectivity of components and routes in a network.</font>
<font color="#008000">'   Languages:    VBScript</font>
<font color="#008000">'   Locales:      English </font>
<font color="#008000">'   CATIA Level:  V5R15 </font>
<font color="#008000">' *****************************************************************************</font>

<font color="#008000">'--- strMessage_g is a global variable visible to all private Sub/Function</font>
<font color="#0000FF">Dim </font>strMessage_g<font color="#0000FF"> As </font>String

<font color="#0000FF">Sub </font>CATMain()

    <font color="#008000">' ------------------------------------------------------------------------- </font>
    <font color="#008000">' Optional: allows to find the sample wherever it's installed</font>
<font color="#0000FF">    dim </font>sDocPath<font color="#0000FF"> As </font>String 
    sDocPath=CATIA.SystemService.Environ("CATDocView")

<font color="#0000FF">    If </font>(Not CATIA.FileSystem.FolderExists(sDocPath))<font color="#0000FF"> Then</font>
      Err.Raise 9999,sDocPath,"No Doc Path Defined"
<font color="#0000FF">    End If</font>
    <font color="#008000">' ------------------------------------------------------------------------- </font>
    <font color="#008000">' Open the schematic document </font>
<font color="#0000FF">    Dim </font>sFilePath
    sFilePath = CATIA.FileSystem.ConcatenatePaths(sDocPath, _
            "online\CAAScdSchUseCases\samples\CAASCH_CompRoute01.CATProduct")

<font color="#0000FF">    Dim </font>objSchDoc<font color="#0000FF"> As </font>Document
<font color="#0000FF">    Set </font>objSchDoc = CATIA.Documents.Open(sFilePath)

    strMessage_g = _
      "--------------------------------------------------------------------" & vbCr
    strMessage_g = strMessage_g & _
      "Output traces from CAASchQueryConnectivity.CATScript" & vbCrLf

    <font color="#008000">' Find the top node of the schematic object tree - schematic root.</font>
<font color="#0000FF">    Dim </font>objPrdRoot<font color="#0000FF"> As </font>Product
<font color="#0000FF">    Dim </font>objSchRoot<font color="#0000FF"> As </font>SchematicRoot
<font color="#0000FF">    If </font>( Not ( objSchDoc Is Nothing ) )<font color="#0000FF"> Then</font>
<font color="#0000FF">      Set </font>objPrdRoot = objSchDoc.Product 
<font color="#0000FF">      If </font>( Not ( objPrdRoot Is Nothing ) )<font color="#0000FF"> Then</font>
<font color="#0000FF">        Set </font>objSchRoot = objPrdRoot.GetTechnologicalObject("SchematicRoot")
<font color="#0000FF">      End If</font>
<font color="#0000FF">    End If</font>

<font color="#0000FF">    Dim </font>objSchLComps<font color="#0000FF"> As </font>SchListOfObjects
<font color="#0000FF">    Dim </font>objSchLRoutes<font color="#0000FF"> As </font>SchListOfObjects


    <font color="#008000">' ------------------------------------------------------------------------- </font>
    <font color="#008000">' |  Get a list of all component instances and</font>
    <font color="#008000">' |  a list of all route instances in the model.</font>
    <font color="#008000">' ------------------------------------------------------------------------- </font>
<font color="#0000FF">    If </font>( Not ( objSchRoot Is Nothing ) )<font color="#0000FF"> Then</font>
<font color="#0000FF">       Set </font>objSchLComps = objSchRoot.GetComponents
<font color="#0000FF">       Set </font>objSchLRoutes = objSchRoot.GetRoutes
<font color="#0000FF">    End If</font>

<font color="#0000FF">    Dim </font>intNb<font color="#0000FF"> As </font>Integer
<font color="#0000FF">    Dim </font>intNbRoute<font color="#0000FF"> As </font>Integer
<font color="#0000FF">    Dim </font>intIndex<font color="#0000FF"> As </font>Integer
<font color="#0000FF">    Dim </font>objPrd<font color="#0000FF"> As </font>Product
<font color="#0000FF">    Dim </font>strName<font color="#0000FF"> As </font>String
<font color="#0000FF">    Dim </font>objAppCntbl<font color="#0000FF"> As </font>SchAppConnectable
<font color="#0000FF">    Dim </font>objLCntblOther<font color="#0000FF"> As </font>SchListOfObjects
<font color="#0000FF">    Dim </font>objLCntrThis<font color="#0000FF"> As </font>SchListOfObjects
<font color="#0000FF">    Dim </font>objLCntrOther<font color="#0000FF"> As </font>SchListOfObjects
<font color="#0000FF">    Dim </font>objSchTempListFact<font color="#0000FF"> As </font>SchTempListFactory
<font color="#0000FF">    Dim </font>objLFilter<font color="#0000FF"> As </font>SchListOfBSTRs

    <font color="#008000">' ------------------------------------------------------------------------- </font>
    <font color="#008000">' |  For each component instance in the list, find connected objects</font>
    <font color="#008000">' ------------------------------------------------------------------------- </font>
<font color="#0000FF">    If </font>( Not ( objSchLComps Is Nothing ) And _
         Not ( objSchRoot Is Nothing ) )<font color="#0000FF"> Then</font>

      <font color="#0000FF"> int</font>Nb = objSchLComps.Count
       strMessage_g = strMessage_g &  "Number of schematic component instances = " & intNb & vbCrLf
<font color="#0000FF">       If </font>(intNb &gt; 0)<font color="#0000FF"> Then</font>
          strMessage_g = strMessage_g &  "-----------Component Connectivity report ------------------- " _
            & vbCrLf

<font color="#0000FF">          For </font>intIndex = 1 To<font color="#0000FF"> int</font>Nb
<font color="#0000FF">            Set </font>objPrd = Nothing
            strName = ""
<font color="#0000FF">            Set </font>objPrd = objSchLComps.Item (intIndex,"CATIAProduct")
<font color="#0000FF">            If </font>( Not ( objPrd Is Nothing ) )<font color="#0000FF"> Then</font>
               strName = objPrd.Name
               strMessage_g = strMessage_g &  " member " & intIndex & _
                 "= " & strName & vbCr
<font color="#0000FF">            End If  </font>
            
<font color="#0000FF">            Set </font>objAppCntbl = objSchRoot.Ge<font color="#0000FF">tInt</font>erface ("CATIASchAppConnectable",objPrd)

<font color="#0000FF">            If </font>( Not ( objAppCntbl Is Nothing ) )<font color="#0000FF"> Then</font>

 
               <font color="#008000">'---------------------------------------------------------------</font>
               <font color="#008000">'  AppListConnectables output 3 lists of objects.</font>
               <font color="#008000">'</font>
               <font color="#008000">'  If a component A is connected to another component B on </font>
               <font color="#008000">'  one side and to a route C on the other side, then the</font>
               <font color="#008000">'  output lists of objects will contain the following members.</font>
               <font color="#008000">'</font>
               <font color="#008000">'         objLCntblOther    objLCntrThis    objLCntrOther</font>
               <font color="#008000">'         --------------    --------------  ----------------</font>
               <font color="#008000">'           B               connector on A   connector on B</font>
               <font color="#008000">'           C               connector on A   connector on C</font>
               <font color="#008000">'---------------------------------------------------------------</font>

<font color="#0000FF">               Set </font>objLFilter = Nothing

               objAppCntbl.AppListConnectables objLFilter, objLCntblOther, _
                 objLCntrThis, objLCntrOther

               GenerateALine objSchRoot, objLCntblOther, objLCntrOther

<font color="#0000FF">               Set </font>objLCntblOther = Nothing
<font color="#0000FF">               Set </font>objLCntrThis = Nothing
<font color="#0000FF">               Set </font>objLCntrOther = Nothing

<font color="#0000FF">            End If</font>
                      
<font color="#0000FF">         Next </font><font color="#008000">'--- For intIndex = 1 To intNb</font>

<font color="#0000FF">       End If </font><font color="#008000">' --- If (intNb &gt; 0) Then</font>

<font color="#0000FF">    End If </font><font color="#008000">'--- If ( Not ( objSchLComps Is Nothing ) And ...</font>


    <font color="#008000">' ------------------------------------------------------------------------- </font>
    <font color="#008000">' |  For each route instance in the list, find connected objects</font>
    <font color="#008000">' ------------------------------------------------------------------------- </font>
<font color="#0000FF">    If </font>( Not ( objSchLRoutes Is Nothing ) And _
         Not ( objSchRoot Is Nothing ) )<font color="#0000FF"> Then</font>

      <font color="#0000FF"> int</font>Nb = objSchLRoutes.Count
       strMessage_g = strMessage_g &  "Number of schematic route instances = " & intNb & vbCrLf
<font color="#0000FF">       If </font>(intNb &gt; 0)<font color="#0000FF"> Then</font>
          strMessage_g = strMessage_g &  "---------------- Route Connectivity report ------------------- " _
            & vbCrLf

<font color="#0000FF">          For </font>intIndex = 1 To<font color="#0000FF"> int</font>Nb
<font color="#0000FF">            Set </font>objPrd = Nothing
            strName = ""
<font color="#0000FF">            Set </font>objPrd = objSchLRoutes.Item (intIndex,"CATIAProduct")
<font color="#0000FF">            If </font>( Not ( objPrd Is Nothing ) )<font color="#0000FF"> Then</font>
               strName = objPrd.Name
               strMessage_g = strMessage_g &  " member " & intIndex & _
                 "= " & strName & vbCr
<font color="#0000FF">            End If  </font>
            
<font color="#0000FF">            Set </font>objAppCntbl = objSchRoot.Ge<font color="#0000FF">tInt</font>erface ("CATIASchAppConnectable",objPrd)

<font color="#0000FF">            If </font>( Not ( objAppCntbl Is Nothing ) )<font color="#0000FF"> Then</font>

<font color="#0000FF">               Set </font>objLFilter = Nothing

               objAppCntbl.AppListConnectables objLFilter, objLCntblOther, _
                 objLCntrThis, objLCntrOther

               GenerateALine objSchRoot, objLCntblOther, objLCntrOther

<font color="#0000FF">               Set </font>objLCntblOther = Nothing
<font color="#0000FF">               Set </font>objLCntrThis = Nothing
<font color="#0000FF">               Set </font>objLCntrOther = Nothing

<font color="#0000FF">            End If</font>
                      
<font color="#0000FF">         Next </font><font color="#008000">'--- For intIndex = 1 To intNb</font>

<font color="#0000FF">       End If </font><font color="#008000">' --- If (intNb &gt; 0) Then</font>

<font color="#0000FF">    End If </font><font color="#008000">'--- If ( Not ( objSchLComps Is Nothing ) And ...</font>




    strMessage_g = strMessage_g & _
      "--------------------------------------------------------------------" & vbCr
    MsgBox strMessage_g

<font color="#0000FF">End Sub</font>

Private Sub GenerateALine (objSchRootArg<font color="#0000FF"> As </font>SchematicRoot, _
  objLCntblArg<font color="#0000FF"> As </font>SchListOfObjects, objLCntrArg<font color="#0000FF"> As </font>SchListOfObjects)

<font color="#0000FF">  Dim </font>intNbCntbl<font color="#0000FF"> As </font>Integer
<font color="#0000FF">  Dim </font>intNbCntr<font color="#0000FF"> As </font>Integer
<font color="#0000FF">  Dim </font>intIndex<font color="#0000FF"> As </font>Integer
<font color="#0000FF">  Dim </font>intNbCoord<font color="#0000FF"> As </font>Integer
<font color="#0000FF">  Dim </font>dbX<font color="#0000FF"> As </font>Double
<font color="#0000FF">  Dim </font>dbY<font color="#0000FF"> As </font>Double
<font color="#0000FF">  Dim </font>objPrd<font color="#0000FF"> As </font>Product
<font color="#0000FF">  Dim </font>objCntr<font color="#0000FF"> As </font>SchCntrLocation
<font color="#0000FF">  Dim </font>objCntbl<font color="#0000FF"> As </font>SchAppConnectable
<font color="#0000FF">  Dim </font>objGRR<font color="#0000FF"> As </font>SchGRR
<font color="#0000FF">  Dim </font>objLDb<font color="#0000FF"> As </font>SchListOfDoubles
<font color="#0000FF">  Dim </font>strName<font color="#0000FF"> As </font>String

<font color="#0000FF">  If </font>( Not ( objLCntblArg Is Nothing ) And _
       Not ( objLCntrArg Is Nothing ) )<font color="#0000FF"> Then</font>

    <font color="#0000FF"> int</font>NbCntbl = objLCntblArg.Count
    <font color="#0000FF"> int</font>NbCntr = objLCntrArg.Count

<font color="#0000FF">     If </font>(<font color="#0000FF"> int</font>NbCntbl =<font color="#0000FF"> int</font>NbCntr )<font color="#0000FF"> Then</font>

<font color="#0000FF">        For </font>intIndex = 1 To<font color="#0000FF"> int</font>NbCntbl
<font color="#0000FF">          Set </font>objPrd = Nothing
          strName = ""

<font color="#0000FF">          Set </font>objPrd = objLCntblArg.Item (intIndex,"CATIAProduct")
    
<font color="#0000FF">          Set </font>objCntbl = objSchRootArg.Ge<font color="#0000FF">tInt</font>erface ("CATIASchAppConnectable",objPrd)

          <font color="#008000">'--------------------------------------------------------------------</font>
          <font color="#008000">'  Report the name of the object connected </font>
          <font color="#008000">'--------------------------------------------------------------------</font>
<font color="#0000FF">          If </font>( Not ( objPrd Is Nothing ) )<font color="#0000FF"> Then</font>
             strName = objPrd.Name
             strMessage_g = strMessage_g &  "    connected to  " & intIndex  _
                & strName 
<font color="#0000FF">          End If  </font>

          <font color="#008000">'--------------------------------------------------------------------</font>
          <font color="#008000">'  Report the location of the connection through the connector </font>
          <font color="#008000">'  position</font>
          <font color="#008000">'--------------------------------------------------------------------</font>
<font color="#0000FF">          Set </font>objGRR = Nothing
<font color="#0000FF">          Set </font>objGRR = GetImage (objSchRootArg, objCntbl)

<font color="#0000FF">          If </font>( Not ( objGRR Is Nothing ) )<font color="#0000FF"> Then</font>
             
<font color="#0000FF">             Set </font>objCntr = objLCntrArg.Item (intIndex,"CATIASchCntrLocation")

<font color="#0000FF">             If </font>( Not ( objCntr Is Nothing ) )<font color="#0000FF"> Then</font>

<font color="#0000FF">                Set </font>objLDb = Nothing
                objCntr.GetPosition objGRR, objLDb

<font color="#0000FF">                If </font>( Not ( objLDb Is Nothing ) )<font color="#0000FF"> Then</font>
                  <font color="#0000FF"> int</font>NbCoord = objLDb.Count
<font color="#0000FF">                   If </font>(<font color="#0000FF"> int</font>NbCoord &gt; 1 )<font color="#0000FF"> Then</font>
                      dbX = objLDb.Item(1)
                      dbY = objLDb.Item(2)
                      strMessage_g = strMessage_g &  " at " & dbX & "," & dbY & vbCr
<font color="#0000FF">                   End If</font>
<font color="#0000FF">                End If </font>

<font color="#0000FF">             End If</font>

<font color="#0000FF">          End If </font><font color="#008000">'--- If ( Not ( objGRR Is Nothing ) ) Then ...</font>

 
<font color="#0000FF">        Next </font><font color="#008000">'--- For intIndex = 1 To intNb</font>

<font color="#0000FF">     End If </font><font color="#008000">'--- If ( intNbCntbl = intNbCntr ) Then ...</font>

<font color="#0000FF">  End If </font><font color="#008000">'--- If ( Not ( objLCntblArg Is Nothing ) And ...</font>

<font color="#0000FF">End Sub</font>

<font color="#008000">' -----------------------------------------------------------------------------</font>
<font color="#008000">' | Find the first symbol used for the input schematic component.</font>
<font color="#008000">' | Input: objSchCompGraph:  the schematic component </font>
<font color="#008000">' |        (a CATIASchCompGraphic interface handle).</font>
<font color="#008000">' | Returns: the component image (the symbol instance)</font>
<font color="#008000">' -----------------------------------------------------------------------------</font>
Private Function GetImage (objSchRootArg<font color="#0000FF"> As </font>SchematicRoot, _
  objSchCntblArg<font color="#0000FF"> As </font>SchAppConnectable)<font color="#0000FF"> As </font>SchGRR

<font color="#0000FF">  Dim </font>objSchLImages<font color="#0000FF"> As </font>SchListOfObjects
<font color="#0000FF">  Dim </font>objSchCompGraph<font color="#0000FF"> As </font>SchCompGraphic
<font color="#0000FF">  Dim </font>objSchRouteGraph<font color="#0000FF"> As </font>SchRouteGraphic
<font color="#0000FF">  Dim </font>ErrorCode<font color="#0000FF"> As </font>Integer

<font color="#0000FF">  Set </font>objSchCompGraph = Nothing
<font color="#0000FF">  Set </font>objSchRouteGraph = Nothing

<font color="#0000FF">  If </font>( Not ( objSchRootArg Is Nothing ) And _
       Not ( objSchCntblArg Is Nothing ) )<font color="#0000FF"> Then</font>


     <font color="#008000">'-------------------------------------------------------------------------</font>
     <font color="#008000">' Input objSchCntblArg could be a route or a component.  If </font>
     <font color="#008000">' objSchCntblArg is a component, we expect </font>
     <font color="#008000">' Set objSchRouteGraph = objSchRootArg.GetInterface ( _</font>
     <font color="#008000">'  "CATIASchRouteGraphic",objSchCntblArg) to fail</font>
     <font color="#008000">' Error handling is to call GetInterface again with "CATIASchCompGraphic"</font>
     <font color="#008000">' as input argument.</font>
     <font color="#008000">'-------------------------------------------------------------------------</font>
     On Error Resume Next

<font color="#0000FF">     Set </font>objSchRouteGraph = objSchRootArg.Ge<font color="#0000FF">tInt</font>erface ( _
       "CATIASchRouteGraphic",objSchCntblArg)

     ErrorCode = Err.Number
<font color="#0000FF">     If </font>(ErrorCode &lt;&gt; 0)<font color="#0000FF"> Then</font>
        On Error Goto 0
<font color="#0000FF">        If </font>( objSchRouteGraph Is Nothing )<font color="#0000FF"> Then</font>

<font color="#0000FF">           Set </font>objSchCompGraph = objSchRootArg.Ge<font color="#0000FF">tInt</font>erface ( _
             "CATIASchCompGraphic",objSchCntblArg)

<font color="#0000FF">        End If</font>
<font color="#0000FF">     End If</font>
     On Error Goto 0

<font color="#0000FF">  End If</font>

<font color="#0000FF">  If </font>( Not ( objSchCompGraph Is Nothing ) )<font color="#0000FF"> Then</font>
<font color="#0000FF">      Set </font>objSchLImages = objSchCompGraph.ListGraphicalImages
  Else 
<font color="#0000FF">     If </font>( Not ( objSchRouteGraph Is Nothing ) )<font color="#0000FF"> Then</font>
<font color="#0000FF">       Set </font>objSchLImages = objSchRouteGraph.ListGraphicalPrimitives
<font color="#0000FF">     End If </font>
<font color="#0000FF">  End If</font>

<font color="#0000FF">  If </font>( Not ( objSchLImages Is Nothing ) )<font color="#0000FF"> Then</font>
<font color="#0000FF">     Set </font>GetImage = objSchLImages.Item (1,"CATIASchGRR")
<font color="#0000FF">  End If</font>

<font color="#0000FF">End Function</font>


</pre></body></html>
