<html><head><meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"><title>CAASchSyncCompInst.CATScript</title><link rel="stylesheet" type="text/css" href="../CAAScrBase/caav5.css"></head><body><pre>
<font color="#0000FF">Option Explicit</font>
<font color="#008000">' COPYRIGHT DASSAULT SYSTEMES 2007</font>

<font color="#008000">' *****************************************************************************</font>
<font color="#008000">'   Purpose:      Update component instances when the catalog ref was modiifed.</font>
<font color="#008000">'   Languages:    VBScript</font>
<font color="#008000">'   Locales:      English </font>
<font color="#008000">'   CATIA Level:  V5R18 </font>
<font color="#008000">' *****************************************************************************</font>
<font color="#0000FF">
Sub </font>CATMain()

    <font color="#008000">' ------------------------------------------------------------------------- </font>
    <font color="#008000">' Optional: allows to find the sample wherever it's installed</font>
<font color="#0000FF">    dim </font>sDocPath<font color="#0000FF"> As </font>String 
    sDocPath=CATIA.SystemService.Environ("CATDocView")

<font color="#0000FF">    If </font>(Not CATIA.FileSystem.FolderExists(sDocPath))<font color="#0000FF"> Then</font>
      Err.Raise 9999,sDocPath,"No Doc Path Defined"
<font color="#0000FF">    End If</font>

    <font color="#008000">' ------------------------------------------------------------------------- </font>
    <font color="#008000">' Open the schematic document </font>
<font color="#0000FF">    Dim </font>sFilePath
    sFilePath = CATIA.FileSystem.ConcatenatePaths(sDocPath, _
            "online\CAAScdSchUseCases\samples\CAASCH_SyncCompInst.CATProduct")

<font color="#0000FF">    Dim </font>objSchDoc<font color="#0000FF"> As </font>Document
<font color="#0000FF">    Set </font>objSchDoc = CATIA.Documents.Open(sFilePath)

    <span style="color: #0000ff">Dim </span>strMessage<font color="#0000FF">As </font>String

    strMessage = _
      "--------------------------------------------------------------------" &amp; vbCr
    strMessage = strMessage & _
      "Output traces from CAASchSyncCompInst.CATScript" & vbCrLf

    <font color="#008000">' Find the top node of the schematic object tree - schematic root.</font>
<font color="#0000FF">    Dim </font>objPrdRoot<font color="#0000FF"> As </font>Product
<font color="#0000FF">    Dim </font>objSchRoot<font color="#0000FF"> As </font>SchematicRoot
<font color="#0000FF">    If </font>( Not ( objSchDoc Is Nothing ) )<font color="#0000FF"> Then</font>
<font color="#0000FF">      Set </font>objPrdRoot = objSchDoc.Product 
<font color="#0000FF">      If </font>( Not ( objPrdRoot Is Nothing ) )<font color="#0000FF"> Then</font>
<font color="#0000FF">        Set </font>objSchRoot = objPrdRoot.GetTechnologicalObject("SchematicRoot")
<font color="#0000FF">      End If</font>
<font color="#0000FF">    End If</font>

    <font color="#008000">' Get SchUpdateInstances interface on the schematic root. 
    </font><span
        style="color: #0000ff">Dim </span>objUpdateInstances<font color="#0000FF">As </font>SchUpdateInstances
<font color="#0000FF"></font>
<font color="#0000FF">    If </font>( Not ( objSchRoot Is Nothing ) )<font color="#0000FF"> Then</font>
<font color="#0000FF">       Set </font>objUpdateInstances = objSchRoot.GetInterface ("CATIASchUpdateInstances",objSchRoot) 
<font color="#0000FF">    End If </font>
<span style="color: #008000">   
    ' Find a list of reference component in the model</span>
<span style="color: #0000ff">    Dim </span>objLCompRefs<font color="#0000FF">As </font>SchListOfObjects
<span style="color: #0000ff">    Dim </span>objCompRef<font color="#0000FF">As </font>SchComponent
<span style="color: #0000ff">    If </span>( Not ( objSchRoot Is Nothing ) )<font color="#0000FF"> Then</font>
<font color="#0000FF">       Set </font>objLCompRefs = objSchRoot.GetRefComponents

<span style="color: #008000">       ' Get the first reference component </span><span style="color: #0000ff">
</span><span style="color: #0000ff">       If </span>( Not ( objLCompRefs Is Nothing ) )<font color="#0000FF">Then</font>
<font color="#0000FF">          Set </font>objCompRef = objLCompRefs.Item (1,"CATIASchComponent")
<span style="color: #0000ff">       End If</span>
<font color="#0000FF">    End If </font>
<span style="color: #008000">   
    ' Synchronize component instances of the first reference component 
    </span><span style="color: #0000ff">If </span>( Not ( objCompRef Is Nothing ) And _
         Not ( objUpdateInstances Is Nothing ) )<font color="#0000FF">Then
</font>
       strMessage = strMessage &amp; _ 
         "Synchronizing instances for the first reference component" &amp; vbCr 

       objUpdateInstances.UpdateAllInstancesFromReference objCompRef

<span style="color: #008000"></span><font color="#0000FF">    End If <span style="color: #008000">'--- If ( Not ( objCompRef Is Nothing )...</span></font>

    strMessage = strMessage & _
      "--------------------------------------------------------------------" & vbCr
    MsgBox strMessage

<font color="#0000FF">End Sub</font>
</pre></body></html>
