<html>

 <head>
 <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
 <meta name="GENERATOR" content="Microsoft FrontPage 6.0">
 <meta name="ProgId" content="FrontPage.Editor.Document">
 <title>Managing Internal Flow in a Schematic Reference Component</title>
 <link rel="stylesheet" type="text/css" href="../CAAScrBase/caav5.css">
 <script language="JavaScript" src="../CAAScrJavaScript/submit.js">
 </script>
 </head>

 <body>

 <table border="0" width="100%">
   <tr>
     <td>
     <h2>Schematics Platform Modeler</h2>
     </td>
     <td align="right" valign="top">
     <h2><a name="Top"></a>Managing Internal Flow in a Schematic Reference 
     Component</h2>
     </td>
   </tr>
 </table>
 <hr>
 <!---------------------------------comment----------------------------------->
 <table border="0" width="100%">
   <tr>
     <td width="7%" valign="top">
     <img border="0" src="../CAAScrBase/images/atarget.gif" width="32" height="32"></td>
     <td width="93%"><a name="Learn"></a>This macro shows you how to manage 
     internal flow objects aggregated under a Schematic reference component. 
     This includes the following.<ol>
       <li>Adding an internal flow object to the reference component.</li>
       <li>Querying for a list of existing internal flow objects.</li>
       <li>Removing an internal flow object from the reference component.</li>
     </ol>
     <p>In order for the instance of a Schematic reference component to be 
     capable of being inserted into a route, the reference component must have 
     at least one compatible internal flow object. An internal flow object 
     references two connectors of the reference component. Through their 
     connector positions, the orientation of the instance in the route is 
     defined.</p>
     <p>This macro opens the CAASCH_Detail02.CATProduct document.</p>
     <p>The following screen shot shows an internal flow of a Schematic 
     reference component. Notice the two connectors (in this case - Connector.1 
     and Connector.2) that must be defined.</p>
     <p>
     <img border="0" src="images/CAASchInternalFlow_01.jpg" width="694" height="374"></td>
   </tr>
   <tr>
     <td width="7%" valign="top">
     <img border="0" src="../CAAScrBase/images/ainfo.gif" width="32" height="32"></td>
     <td width="93%"><a name="How"></a>CAASchInternalFlow is launched in CATIA [<a href="#References">1</a>]. 
     No open document is needed.<p>Special 
		environment must be available to successfully run this macro:</p>
		<ul>
			<li>Prerequisites:</li>
		</ul>
		<blockquote>
			<ol>
				<li>RADE must be installed.</li>
				<li>CAASchPlatformModeler.edu must exist in CAADoc folder.</li>
			</ol>
		</blockquote>
		<ul>
			<li>Setup:</li>
		</ul>
		<blockquote>
			<ol>
				<li>Build CAASchAppBase.m and CAASchAppUtilities.m, located in 
				CAASchPlatformModeler.edu (RADE is required). </li>
				<li>Copy generated DLLs, CAASchAppBase.dll and CAASchAppUtilities.m, respectively, to the run-time environment 
				folder &quot;intel_a\code\bin.&quot;</li>
				<li>Copy CAASCHEDUApp.CATfct, located CAASchPlatformModeler.edu\CNext\resources\graphic, 
				to the run-time environment folder &quot;intel_a\resources\graphic.&quot;</li>
				<li>Copy CAASchPlatformModeler.edu\CNext\code\dictionary\CAASchPlatformModeler.edu.dico 
				to the run-time environment folder &quot;intel_a\code\dictionary.&quot;</li>
			</ol>
		</blockquote>
		<p><a href="CAASchInternalFlowSource.htm">
     CAASchInternalFlow.CATScript </a>is located in the CAAScdSchUseCases 
     module. <a href="macros/CAASchInternalFlow.CATScript">Execute macro</a> 
     (Windows only).</td>
   </tr>
   <tr>
     <td width="7%" valign="top">
     <img border="0" src="../CAAScrBase/images/ascenari.gif" width="32" height="32"></td>
     <td width="93%"><a name="Step"></a>CAASchInternalFlow includes the 
     following steps:<ol>
       <li><a href="#Prolog">Prolog</a></li>
       <li><a href="#Create internal flow">Add an internal flow object to the 
       Schematic reference component</a></li>
       <li><a href="#Query internal flow">Query for a list of existing internal 
       flow objects of a Schematic reference component</a></li>
       <li><a href="#Delete internal flow">Remove an internal flow objects from 
       the Schematic reference component</a></li>
     </ol>
     <h4><a name="Prolog"></a>Prolog</h4>
     <p>The macro first loads CAASCH_Detail02.CATProduct.</p>
     <table class="code">
       <tr>
         <td width="100%">&nbsp;&nbsp;&nbsp;    <font color="#008000">...</font><br>
&nbsp;&nbsp;&nbsp;
    <font color="#008000">' Open main schematic P&amp;ID design document (for new component instances created here)</font><br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;    Dim </font>sFilePath<br>
&nbsp;&nbsp;&nbsp; sFilePath = CATIA.FileSystem.ConcatenatePaths(sDocPath, _<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "online\CAAScdSchUseCases\samples\CAASCH_Detail02.CATProduct")<br>
         <br>

<font color="#0000FF">&nbsp;&nbsp;&nbsp;    Dim </font>objSchDoc<font color="#0000FF"> As </font>Document<br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;    Set </font>objSchDoc = CATIA.Documents.Open(sFilePath)<br>
&nbsp;&nbsp;&nbsp;
    <font color="#008000">...</font></td>
       </tr>
     </table>
     <p>Next, the macro acquires the schematic root object from the document. 
     The schematic root is the top node of the object instance tree in a 
     schematic document.</p>
     <table class="code">
       <tr>
         <td width="100%">&nbsp;&nbsp;&nbsp;    <font color="#008000">...</font><br>
&nbsp;&nbsp;&nbsp;
    <font color="#008000">' Find the top node of the schematic object tree - schematic root.</font><br>
<font color="#0000ff">&nbsp;&nbsp;&nbsp;    Dim </font>objPrdRoot<font color="#0000ff"> As </font>Product<br>
<font color="#0000ff">&nbsp;&nbsp;&nbsp;    Dim </font>objSchRoot<font color="#0000ff"> As </font>SchematicRoot<br>
<font color="#0000ff">&nbsp;&nbsp;&nbsp;    If </font>( Not ( objSchDoc Is Nothing ) )<font color="#0000ff"> Then</font><br>
<font color="#0000ff">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;      Set </font>objPrdRoot = objSchDoc.Product
         <br>
<font color="#0000ff">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;      If </font>( Not ( objPrdRoot Is Nothing ) )<font color="#0000ff"> Then</font><br>
<font color="#0000ff">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;        Set </font>objSchRoot = objPrdRoot.GetTechnologicalObject(&quot;SchematicRoot&quot;)<br>
<font color="#0000ff">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; End If</font><br>
<font color="#0000ff">&nbsp;&nbsp;&nbsp; End If</font><br>
&nbsp;&nbsp;&nbsp;
    <font color="#008000">...</font></td>
       </tr>
     </table>
     <p>The SchematicRoot interface provides the GetRefComponents method to find 
     a list of all the Schematic reference component in the model. The macro 
     takes the first one in the list and specifically requests for the 
     SchComponent interface on the first member.</p>
     <table class="code">
       <tr>
         <td width="100%">&nbsp;&nbsp;&nbsp;    <font color="#008000">...</font><br>
<font color="#0000FF">&nbsp;</font>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;      <font color="#008000">'-----------------------------------------------------------------------</font><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
       <font color="#008000">' Find a list of reference component in the model</font><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
       <font color="#008000">'-----------------------------------------------------------------------</font><br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;       Set </font>objLCompRefs = objSchRoot.GetRefComponents<br>
         <br>

<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;       If </font>( Not ( objLCompRefs Is Nothing ) )<font color="#0000FF"> Then</font><br>
         <br>

<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;          Set </font>objCompRef = objLCompRefs.Item (1,&quot;CATIASchComponent&quot;)<br>
&nbsp;&nbsp;&nbsp;
    <font color="#008000">...</font></td>
       </tr>
     </table>
     <h4><a name="Create internal flow"></a>Add an internal flow object to the 
     Schematic reference component</h4>
     <p>The macro calls the GetInterface method to get a handle on the reference 
     component for the SchCompFlow interface.</p>
     <table class="code">
       <tr>
         <td width="100%"><font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;              Set </font>objCompFlow = objSchRoot.Ge<font color="#0000FF">tInt</font>erface ( _<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &quot;CATIASchCompFlow&quot;,objCompRef)</td>
       </tr>
     </table>
     <p>Next, the macro get a list of all connectors of the Schematic Component.</p>
     <table class="code">
       <tr>
         <td width="100%">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;             <font color="#008000">'-----------------------------------------------------------------</font><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
             <font color="#008000">' Find all the connectors associated with the reference </font>
         <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
             <font color="#008000">' component</font><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
             <font color="#008000">'----------------------------------------------------------------- </font>
         <br>
&nbsp;&nbsp;&nbsp;
    <font color="#008000">...</font><br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;             Set </font>objLCntr = objCntbl.AppListConnectors (objLFilter)<br>
&nbsp;&nbsp;&nbsp;
    <font color="#008000">...</font></td>
       </tr>
     </table>
     <p>Method CreateListOfObject is called to create a list of connectors 
     containing the first and the second connectors. This list is used as input 
     to the AddInternalFlow method to add an internal flow object to the 
     reference component..</p>
     <table class="code">
       <tr>
         <td width="100%">&nbsp;&nbsp;&nbsp;    <font color="#008000">...</font><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
             <font color="#008000">'-----------------------------------------------------------------</font><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
             <font color="#008000">' Add internal flow to the reference component.</font><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
             <font color="#008000">' 2 pairs:</font><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
             <font color="#008000">' Flow 1: connector 1 to connector 2</font><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
             <font color="#008000">' Flow 2: connector 1 to connector 3</font><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
             <font color="#008000">'-----------------------------------------------------------------</font><br>
&nbsp;&nbsp;
   <font color="#008000">...</font><br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;             Dim </font>objFlow1<font color="#0000FF"> As </font>SchInternalFlow<br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;             Dim </font>objFlow2<font color="#0000FF"> As </font>SchInternalFlow<br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;             Dim </font>objCntr1<font color="#0000FF"> As </font>SchAppConnector<br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;             Dim </font>objCntr2<font color="#0000FF"> As </font>SchAppConnector<br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;             Dim </font>objCntr3<font color="#0000FF"> As </font>SchAppConnector<br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;             Dim </font>objLCntr1<font color="#0000FF"> As </font>SchListOfObjects<br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;             Dim </font>objLCntr2<font color="#0000FF"> As </font>SchListOfObjects<br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;             Dim </font>objLFlow<font color="#0000FF"> As </font>SchListOfObjects<br>
         <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;

            <font color="#0000FF">&nbsp;int</font>NbCntr = objLCntr.Count<br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;             Set </font>objLCntr1 = objSchTempListFact.CreateListOfObjects<br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;             Set </font>objLCntr2 = objSchTempListFact.CreateListOfObjects<br>
         <br>

<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;             Set </font>objCntr1 = Nothing<br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;             Set </font>objCntr2 = Nothing<br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;             Set </font>objCntr3 = Nothing<br>
         <br>

<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;             If </font>(<font color="#0000FF"> int</font>NbCntr &gt; 0 ) Then Set objCntr1 = objLCntr.Item(1,&quot;CATIASchAppConnector&quot;)<br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;             If </font>(<font color="#0000FF"> int</font>NbCntr &gt; 1 ) Then Set objCntr2 = objLCntr.Item(2,&quot;CATIASchAppConnector&quot;)<br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;             If </font>(<font color="#0000FF"> int</font>NbCntr &gt; 2 ) Then Set objCntr3 = objLCntr.Item(3,&quot;CATIASchAppConnector&quot;)<br>
         <br>

<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;             Set </font>objFlow1 = Nothing<br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;             If </font>( Not objLCntr1 Is Nothing )<font color="#0000FF"> Then</font><br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;                If </font>( Not ( objCntr1 Is Nothing ) And _<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Not ( objCntr2 Is Nothing ) )<font color="#0000FF"> Then</font><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; objLCntr1.Append (objCntr1)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; objLCntr1.Append (objCntr2)<br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;                   Set </font>objFlow1 = objCompFlow.AddInternalFlow (objLCntr1)<br>
&nbsp;&nbsp;&nbsp;
    <font color="#008000">...</font></td>
       </tr>
     </table>
     <p>Similarly, the macro creates a second list of connectors containing the 
     first and the third connectors. This list is used as input to the 
     AddInternalFlow method to add the second internal flow object to the 
     reference component.</p>
     <table class="code">
       <tr>
         <td width="100%">&nbsp;&nbsp;&nbsp;    <font color="#008000">...</font><br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;             Set </font>objFlow2 = Nothing<br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;             If </font>( Not objLCntr2 Is Nothing )<font color="#0000FF"> Then</font><br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;                If </font>( Not ( objCntr1 Is Nothing ) And _<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Not ( objCntr3 Is Nothing ) )<font color="#0000FF"> Then</font><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; objLCntr2.Append (objCntr1)<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; objLCntr2.Append (objCntr3)<br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;                   Set </font>objFlow2 = objCompFlow.AddInternalFlow (objLCntr2)<br>
&nbsp;&nbsp;&nbsp;
    <font color="#008000">...</font></td>
       </tr>
     </table>
     <h4><a name="Query internal flow"></a>Query for a list of existing internal 
     flow objects of a Schematic reference component</h4>
     <table class="code">
       <tr>
         <td width="100%">&nbsp;&nbsp;&nbsp;    <font color="#008000">...</font><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <font color="#008000">'-----------------------------------------------------------------</font><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <font color="#008000">' Return a list of all the internal flows </font>
         <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <font color="#008000">' associated to the reference component. There should be 2.</font><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
            <font color="#008000">'-----------------------------------------------------------------</font><br>
&nbsp;&nbsp;&nbsp;&nbsp;
     <font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;             Set </font>objLFlow = objCompFlow.Lis<font color="#0000FF">tInt</font>ernalFlows<br>
&nbsp;&nbsp;&nbsp;
    <font color="#008000">...</font></td>
       </tr>
     </table>
     <h4><a name="Delete internal flow"></a>Remove an internal flow objects from 
     the Schematic reference component</h4>
     <table class="code">
       <tr>
         <td width="100%">&nbsp;&nbsp;&nbsp;    <font color="#008000">...</font><br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;                If </font>( Not ( objFlow2 Is Nothing ) )<font color="#0000FF"> Then</font><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                   <font color="#008000">'-----------------------------------------------------------------</font><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                   <font color="#008000">' Remove &quot;Flow 2&quot; from the reference component</font><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                   <font color="#008000">'-----------------------------------------------------------------</font><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; objCompFlow.RemoveInternalFlow objFlow2<br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; End If</font><br>
&nbsp;&nbsp;&nbsp;
    <font color="#008000">...</font></td>
       </tr>
     </table>
     </td>
   </tr>
 </table>
 <p align="right">[<a href="#Top">Top</a>]</p><hr>
 <!---------------------------------comment----------------------------------->
 <h4><a name="InShort"></a>In Short</h4>
 <p>This use case shows how to manage internal flow objects of a Schematic 
 reference component. A message logging the status of the critical steps is 
 displayed at the end of the use case.</p>
 <p>
 <img border="0" src="images/CAASchInternalFlow_02.jpg" width="410" height="360"></p>
 <p align="right">[<a href="#Top">Top</a>]</p><hr>
 <!---------------------------------comment----------------------------------->
 <h4><a name="References"></a>References</h4>
 <table border="0" width="100%">
   <tr>
     <td valign="top">[1]</td>
     <td><a href="../CAAScdInfUseCases/CAAInfLauchMacro.htm">
     Replaying a Macro</a></td>
   </tr>
   <tr>
     <td valign="top"></td>
     <td></td>
   </tr>
   <tr>
     <td colspan="2" align="right">[<a href="#Top">Top</a>]</td>
   </tr>
 </table>
 <hr>
 <!---------------------------------comment----------------------------------->
 <p><i>Copyright © 2001, Dassault Systèmes. All rights reserved.</i></p>

 </body>

</html>
