<html><head><meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"><title>CAASchCreateSchDocument2.CATScript</title><link rel="stylesheet" type="text/css" href="../CAAScrBase/caav5.css"></head><body><pre>
<font color="#0000FF">Option Explicit</font>
<font color="#008000">' COPYRIGHT DASSAULT SYSTEMES 2004</font>

<font color="#008000">' *****************************************************************************</font>
<font color="#008000">'   Purpose:      Create a schematic document (2).</font>
<font color="#008000">'   Assumtions:   Product level: Schematic Platform (SDI).</font>
<font color="#008000">'   Languages:    VBScript</font>
<font color="#008000">'   Locales:      English </font>
<font color="#008000">'   CATIA Level:  V5R15 </font>
<font color="#008000">' *****************************************************************************</font>

<font color="#0000FF">Sub </font>CATMain()

    <font color="#008000">' ------------------------------------------------------------------------- </font>
    <font color="#008000">' Optional: allows to find the sample wherever it's installed</font>
<font color="#0000FF">    dim </font>sSavePath<font color="#0000FF"> As </font>String 
    sSavePath=CATIA.SystemService.Environ("CATSavePath")

<font color="#0000FF">    If </font>(Not CATIA.FileSystem.FolderExists(sSavePath))<font color="#0000FF"> Then</font>
      Err.Raise 9999,sSavePath,"No Path for saving document"
<font color="#0000FF">    End If</font>
    <font color="#008000">' ------------------------------------------------------------------------- </font>

<font color="#0000FF">    Dim </font>strMessage<font color="#0000FF"> As </font>String

    strMessage = _
      "--------------------------------------------------------------------" & vbCr
    strMessage = strMessage & _
      "Output traces from CAASchCreateSchDocument2.CATScript" & vbCrLf

    <font color="#008000">'--------------------------------------------------------------------------</font>
    <font color="#008000">' Create a CATProduct document</font>
    <font color="#008000">'--------------------------------------------------------------------------</font>
<font color="#0000FF">    Dim </font>objSchDoc<font color="#0000FF"> As </font>Document
<font color="#0000FF">    Set </font>objSchDoc = CATIA.Documents.Add ("CATProduct")
    <font color="#008000">'</font>
    <font color="#008000">' Find the top node of the schematic object tree - schematic root.</font>
<font color="#0000FF">    Dim </font>objPrdRoot<font color="#0000FF"> As </font>Product
<font color="#0000FF">    Dim </font>objSchRoot<font color="#0000FF"> As </font>SchematicRoot

    <font color="#008000">'--------------------------------------------------------------------------</font>
    <font color="#008000">' Associate schematic behavior to the CATProduct document through</font>
    <font color="#008000">' the method GetTechnologicalObject.</font>
    <font color="#008000">'--------------------------------------------------------------------------</font>
<font color="#0000FF">    Dim </font>strRootName<font color="#0000FF"> As </font>String
<font color="#0000FF">    Dim </font>strDocName<font color="#0000FF"> As </font>String
    strRootName = "Sample_SchematicRoot"
    strDocName = CATIA.FileSystem.ConcatenatePaths(sSavePath, _
	             "SampleOutput_SchDoc02.CATProduct")

<font color="#0000FF">    If </font>( Not ( objSchDoc Is Nothing ) )<font color="#0000FF"> Then</font>
<font color="#0000FF">      Set </font>objPrdRoot = objSchDoc.Product 
<font color="#0000FF">      If </font>( Not ( objPrdRoot Is Nothing ) )<font color="#0000FF"> Then</font>
<font color="#0000FF">        Set </font>objSchRoot = objPrdRoot.GetTechnologicalObject("SchematicRoot")
        objPrdRoot.PartNumber = strRootName
<font color="#0000FF">      End If</font>

<font color="#0000FF">      If </font>( Not ( objSchRoot Is Nothing ) )<font color="#0000FF"> Then</font>

         <font color="#008000">'---------------------------------------------------------------------</font>
         <font color="#008000">' Regular CATProduct is a 3D document and is associated with a 3D</font>
         <font color="#008000">' editor and a 3D viewer. On the other hand a schematic document</font>
         <font color="#008000">' is a special CATProduct document that is associated with a special</font>
         <font color="#008000">' 2D viewer and 2D editor. Therefore, we need to trigger the</font>
         <font color="#008000">' documentation initialization (which has already been done in </font>
         <font color="#008000">' CATDocuments.Add) again after associating schematic </font>
         <font color="#008000">' behavior to the document, </font>
         <font color="#008000">' by saving the document and re-opening it again.</font>
         <font color="#008000">'---------------------------------------------------------------------</font>
         objSchDoc.SaveAs strDocName

         objSchDoc.Close

<font color="#0000FF">         Set </font>objSchDoc = CATIA.Documents.Open (strDocName)

<font color="#0000FF">         Set </font>objPrdRoot = Nothing
<font color="#0000FF">         Set </font>objSchRoot = Nothing
<font color="#0000FF">         If </font>( Not ( objSchDoc Is Nothing ) )<font color="#0000FF"> Then</font>
<font color="#0000FF">            Set </font>objPrdRoot = objSchDoc.Product 
<font color="#0000FF">            If </font>( Not ( objPrdRoot Is Nothing ) )<font color="#0000FF"> Then</font>
<font color="#0000FF">               Set </font>objSchRoot = objPrdRoot.GetTechnologicalObject("SchematicRoot")
<font color="#0000FF">            End If</font>
<font color="#0000FF">         End If</font>

         <font color="#008000">'---------------------------------------------------------------------</font>
         <font color="#008000">' Set the drawing standard if needed </font>
         <font color="#008000">'---------------------------------------------------------------------</font>
<font color="#0000FF">         If </font>( Not ( objSchRoot Is Nothing ) )<font color="#0000FF"> Then</font>
            objSchRoot.SetDrawingStandard catISO
            strMessage = strMessage & "drawing standard set to catISO" & vbCr
<font color="#0000FF">            Dim </font>std<font color="#0000FF"> As </font>CatDrawingStandard
            std = objSchRoot.GetDrawingStandard
            strMessage = strMessage & "drawing standard = " & std & vbCr
<font color="#0000FF">         End If</font>

         <font color="#008000">'objSchDoc.SaveAs strDocName</font>

<font color="#0000FF">       End If  </font><font color="#008000">'----If ( Not ( objSchRoot Is Nothing )...</font>


<font color="#0000FF">    End If</font>

 
    strMessage = strMessage & _
      "--------------------------------------------------------------------" & vbCr
    MsgBox strMessage

<font color="#0000FF">End Sub</font>







</pre></body></html>
