<html>

 <head>
 <meta http-equiv="Content-Language" content="fr">
 <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
 <meta name="GENERATOR" content="Microsoft FrontPage 6.0">
 <meta name="ProgId" content="FrontPage.Editor.Document">
 <title>Deleting Schematic Objects</title>
 <link rel="stylesheet" type="text/css" href="../CAAScrBase/caav5.css">
 <script language="JavaScript" src="../CAAScrJavaScript/submit.js">
 </script>
 </head>

 <body>

 <table border="0" width="100%">
   <tr>
     <td>
     <h2>Schematics Platform Modeler</h2>
     </td>
     <td align="right" valign="top">
     <h2><a name="Top"></a>Deleting Schematic Objects</h2>
     </td>
   </tr>
 </table>
 <hr>
 <!---------------------------------comment----------------------------------->
 <table border="0" width="100%">
   <tr>
     <td width="7%" valign="top">
     <img border="0" src="../CAAScrBase/images/atarget.gif" width="32" height="32"></td>
     <td width="93%"><a name="Learn"></a>This macro shows you how to delete 
     Schematic objects.<p>This macro opens the document 
     CAASCH_Delete01.CATProduct. It contains a schematic component that is 
     connected to a schematic route at both ends (the highlighted object in the 
     screen shot below). Notice that the instance name of this component has the 
     word &quot;delete&quot; embedded in it. This word identifies the object to be deleted 
     to the macro.</p>
     <p>
     <img border="0" src="images/CAASchDelete_01.jpg" width="801" height="349"></td>
   </tr>
   <tr>
     <td width="7%" valign="top">
     <img border="0" src="../CAAScrBase/images/ainfo.gif" width="32" height="32"></td>
     <td width="93%"><a name="How"></a>CAASchDelete is launched in CATIA [<a href="#References">1</a>]. 
     No open document is needed.<p>Special 
		environment must be available to successfully run this macro:</p>
		<ul>
			<li>Prerequisites:</li>
		</ul>
		<blockquote>
			<ol>
				<li>RADE must be installed.</li>
				<li>CAASchPlatformModeler.edu must exist in CAADoc folder.</li>
			</ol>
		</blockquote>
		<ul>
			<li>Setup:</li>
		</ul>
		<blockquote>
			<ol>
				<li>Build CAASchAppBase.m and CAASchAppUtilities.m, located in 
				CAASchPlatformModeler.edu (RADE is required). </li>
				<li>Copy generated DLLs, CAASchAppBase.dll and 
				CAASchAppUtilities.m, respectively, to the run-time environment 
				folder &quot;intel_a\code\bin.&quot;</li>
				<li>Copy CAASCHEDUApp.CATfct, located CAASchPlatformModeler.edu\CNext\resources\graphic, 
				to the run-time environment folder &quot;intel_a\resources\graphic.&quot;</li>
				<li>Copy CAASchPlatformModeler.edu\CNext\code\dictionary\CAASchPlatformModeler.edu.dico 
				to the run-time environment folder &quot;intel_a\code\dictionary.&quot;</li>
			</ol>
		</blockquote>
		<p><a href="CAASchDeleteSource.htm">
     CAASchDelete.CATScript i</a>s located in the CAAScdSchUseCases module.
     <a href="macros/CAASchDelete.CATScript">Execute macro</a> (Windows only).</td>
   </tr>
   <tr>
     <td width="7%" valign="top">
     <img border="0" src="../CAAScrBase/images/ascenari.gif" width="32" height="32"></td>
     <td width="93%"><a name="Step"></a>CAASchDelete includes the following 
     steps:<ol>
       <li><a href="#Prolog">Prolog</a></li>
       <li><a href="#Delete a Schematic component">Delete a Schematic component</a></li>
       <li><a href="#Delete a Schematic route">Delete a Schematic route</a></li>
     </ol>
     <h4><a name="Prolog"></a>Prolog</h4>
     <p>The macro first loads CAASCH_Delete01.CATProduct.</p>
     <table class="code">
       <tr>
         <td width="100%">&nbsp;&nbsp;&nbsp;    <font color="#008000">...</font><br>
&nbsp;&nbsp;&nbsp;
    <font color="#008000">' Open the schematic document </font><br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;    Dim </font>sFilePath<br>
&nbsp;&nbsp;&nbsp; sFilePath = CATIA.FileSystem.ConcatenatePaths(sDocPath, _<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; "online\CAAScdSchUseCases\samples\CAASCH_Delete01.CATProduct")<br>
         <br>

<font color="#0000FF">&nbsp;&nbsp;&nbsp;    Dim </font>objSchDoc<font color="#0000FF"> As </font>Document<br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;    Set </font>objSchDoc = CATIA.Documents.Open(sFilePath)<br>
&nbsp;&nbsp;&nbsp;
    <font color="#008000">...</font></td>
       </tr>
     </table>
     <p>Next, the macro acquires the schematic root object from the document. 
     The schematic root is the top node of the object instance tree in a 
     schematic document.</p>
     <table class="code">
       <tr>
         <td width="100%">&nbsp;&nbsp;&nbsp;    <font color="#008000">...</font><br>
&nbsp;&nbsp;&nbsp;
    <font color="#008000">' Find the top node of the schematic object tree - schematic root.</font><br>
<font color="#0000ff">&nbsp;&nbsp;&nbsp;    Dim </font>objPrdRoot<font color="#0000ff"> As </font>Product<br>
<font color="#0000ff">&nbsp;&nbsp;&nbsp;    Dim </font>objSchRoot<font color="#0000ff"> As </font>SchematicRoot<br>
<font color="#0000ff">&nbsp;&nbsp;&nbsp;    If </font>( Not ( objSchDoc Is Nothing ) )<font color="#0000ff"> Then</font><br>
<font color="#0000ff">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;      Set </font>objPrdRoot = objSchDoc.Product
         <br>
<font color="#0000ff">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;      If </font>( Not ( objPrdRoot Is Nothing ) )<font color="#0000ff"> Then</font><br>
<font color="#0000ff">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;        Set </font>objSchRoot = objPrdRoot.GetTechnologicalObject(&quot;SchematicRoot&quot;)<br>
<font color="#0000ff">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; End If</font><br>
<font color="#0000ff">&nbsp;&nbsp;&nbsp; End If</font><br>
&nbsp;&nbsp;&nbsp;
    <font color="#008000">...</font></td>
       </tr>
     </table>
     <p>Using the GetSchBaseFactory method, a SchBaseFact interface handle is 
     obtained. The DeleteObject method of this interface is used in the next 
     step.</p>
     <table class="code">
       <tr>
         <td width="100%">&nbsp;&nbsp;&nbsp;    <font color="#008000">...</font><br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;    Dim </font>objSchBaseFact<font color="#0000FF"> As </font>SchBaseFactory<br>
         <br>

<font color="#0000FF">&nbsp;&nbsp;&nbsp;    If </font>( Not ( objSchRoot Is Nothing ) )<font color="#0000FF"> Then</font><br>
         <br>

<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;       Set </font>objSchBaseFact = objSchRoot.GetSchBaseFactory<br>
&nbsp;&nbsp;&nbsp;
    <font color="#008000">...</font></td>
       </tr>
     </table>
     <h4><a name="Delete a Schematic component"></a>Delete a Schematic component</h4>
     <p>The macro finds the component to be deleted in the private 
     FindComponentInst function. This is based on a naming convention on the 
     Schematic component. FindComponentInst returns the first instance whose 
     name has the word &quot;delete&quot; embedded in it. The macro calls DeleteObject to 
     delete the component.</p>
     <table class="code">
       <tr>
         <td width="100%">&nbsp;&nbsp;&nbsp;    <font color="#008000">...</font><br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;       If </font>( Not ( objSchBaseFact Is Nothing ) )<font color="#0000FF"> Then</font><br>
         <br>

<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;          Set </font>objSchComp = FindComponentInst (objSchRoot)<br>
         <br>

<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;          If </font>( Not ( objSchComp Is Nothing ) )<font color="#0000FF"> Then</font><br>
         <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; objSchBaseFact.DeleteObject objSchComp<br>
         <br>
&nbsp;&nbsp;&nbsp;

    <font color="#008000">...</font></td>
       </tr>
     </table>
     <h4><a name="Delete a Schematic route"></a>Delete a Schematic route</h4>
     <p>The word &quot;inserted&quot; in the comment below is used to describe a situation 
     where a Schematic component is connected to two Schematic routes through 
     two of its connectors. These connectors must be internally connected to 
     each other by an &quot;internal flow&quot; object. The latter is aggregated by the 
     Schematic component. For example, the highlighted &quot;valve&quot; in the screen 
     shot of the current document above has been inserted into the route.</p>
     <table class="code">
       <tr>
         <td width="100%">&nbsp;&nbsp;&nbsp;    <font color="#008000">...</font><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
       <font color="#008000">'-----------------------------------------------------------------------</font><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
       <font color="#008000">'&nbsp; In this specific input model, we expects to find a component</font><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
       <font color="#008000">'&nbsp; instance that has been inserted into a route.</font><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
       <font color="#008000">'</font><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
       <font color="#008000">'&nbsp; After this component instance is deleted, the two routes on </font>
         <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
       <font color="#008000">'&nbsp; each side of the deleted component will be concatenated by the</font><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
       <font color="#008000">'&nbsp; system to become one. </font><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
       <font color="#008000">'</font><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
       <font color="#008000">'-----------------------------------------------------------------------</font><br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;       Set </font>objLRoutes = objSchRoot.GetRoutes<br>
&nbsp;&nbsp;
   <font color="#008000">...</font></td>
       </tr>
     </table>
     <p>This macro uses a private FindOpenConnector function to find the 2 
     unconnected ends of the 2 routes that are connected to each ends of the 
     component before it is deleted. With these 2 ends, the Concatenate method 
     of the SchRoute interface is then called to connect the 2 route into one. 
     Note that the input SchRoute interface handle (in this case, the objRoute2) 
     will be deleted implicitly by the Concatenate method. </p>
     <table class="code">
       <tr>
         <td width="100%"><font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
         Set </font>objLRoutes = objSchRoot.GetRoutes<br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; If </font>( Not ( 
         objLRoutes Is Nothing ) )<font color="#0000FF"> Then</font><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
         <font color="#0000FF">&nbsp;int</font>NbRouteAfter = objLRoutes.Count<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; strMessage = strMessage &amp; 
         &quot;Number of routes in the model &quot;<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; strMessage = strMessage &amp; 
         &quot;after deleting an inserted component &quot; <br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; strMessage = strMessage &amp; 
         &quot; = &quot; &amp; intNbRouteAfter &amp; vbCr<br>
         <br>

<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Dim </font>
         objRoute1<font color="#0000FF"> As </font>SchRoute<br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Dim </font>
         objRoute2<font color="#0000FF"> As </font>SchRoute<br>
         <br>

<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Dim </font>
         objRCntbl1<font color="#0000FF"> As </font>SchConnectable<br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Dim </font>
         objRCntbl2<font color="#0000FF"> As </font>SchConnectable<br>
         <br>

<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Dim </font>
         objAppRCntr1<font color="#0000FF"> As </font>SchAppConnector<br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; Dim </font>
         objAppRCntr2<font color="#0000FF"> As </font>SchAppConnector<br>
         <br>

<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; If </font>
         (<font color="#0000FF"> int</font>NbRouteAfter &gt; 0 )<font color="#0000FF"> 
         Then</font><br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
         Set </font>objRoute1 = objLRoutes.Item (1, &quot;CATIASchRoute&quot;)<br>
         <br>

<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
         If </font>( Not ( objRoute1 Is Nothing ) )<font color="#0000FF"> Then</font><br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
         Set </font>objRCntbl1 = objSchRoot.Ge<font color="#0000FF">tInt</font>erface 
         ( _<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
         &quot;CATIASchAppConnectable&quot;, objRoute1)<br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
         If </font>( Not ( objRCntbl1 Is Nothing ) )<font color="#0000FF"> Then</font><br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
         Set </font>objAppRCntr1 = FindOpenConnector (objSchRoot,objRCntbl1)<br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
         Set </font>objRoute2 = objLRoutes.Item (2, &quot;CATIASchRoute&quot;)<br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
         End If</font><br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
         End If</font><br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
         If </font>( Not ( objRoute2 Is Nothing ) )<font color="#0000FF"> Then</font><br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
         Set </font>objRCntbl2 = objSchRoot.Ge<font color="#0000FF">tInt</font>erface 
         ( _<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
         &quot;CATIASchAppConnectable&quot;, objRoute2)<br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
         If </font>( Not ( objRCntbl2 Is Nothing ) )<font color="#0000FF"> Then</font><br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
         Set </font>objAppRCntr2 = FindOpenConnector (objSchRoot,objRCntbl2)<br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
         End If</font><br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
         End If</font><br>
         <br>

<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
         If </font>( Not ( objRoute1 Is Nothing ) And _<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
         Not ( objAppRCntr1 Is Nothing ) And _<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
         Not ( objAppRCntr2 Is Nothing ) )<font color="#0000FF"> Then</font><br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
         Set </font>objRoute2 = objLRoutes.Item (2, &quot;CATIASchRoute&quot;)<br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
         If </font>( Not ( objRoute2 Is Nothing ) )<font color="#0000FF"> Then</font><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
         objRoute1.Concatenate objAppRCntr1, objRoute2, objAppRCntr2<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                    <font color="#008000">...</font><br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
         End If</font><br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; 
         End If </font><br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; End 
         If </font><br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; End If </font><font color="#008000">
         '--- If ( Not ( objLRoutes Is Nothing ) ...</font><br>
&nbsp;&nbsp;&nbsp;

    <font color="#008000">...</font></td>
       </tr>
     </table>
     </td>
   </tr>
 </table>
 <p align="right">[<a href="#Top">Top</a>]</p><hr>
 <!---------------------------------comment----------------------------------->
 <h4><a name="InShort"></a>In Short</h4>
 <p>This use case shows how to delete Schematic objects. A message logging the 
 status of the critical steps is displayed at the end of the use case. </p>
 <p><img border="0" src="images/CAASchDelete_02.jpg" width="804" height="314"></p>
 <p align="right">[<a href="#Top">Top</a>]</p><hr>
 <!---------------------------------comment----------------------------------->
 <h4><a name="References"></a>References</h4>
 <table border="0" width="100%">
   <tr>
     <td valign="top">[1]</td>
     <td><a href="../CAAScdInfUseCases/CAAInfLauchMacro.htm">
     Replaying a Macro</a></td>
   </tr>
   <tr>
     <td valign="top"></td>
     <td></td>
   </tr>
   <tr>
     <td colspan="2" align="right">[<a href="#Top">Top</a>]</td>
   </tr>
 </table>
 <hr>
 <!---------------------------------comment----------------------------------->
 <p><i>Copyright © 2001, Dassault Systèmes. All rights reserved.</i></p>

 </body>

</html>
