<html>

 <head>
 <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
 <meta name="GENERATOR" content="Microsoft FrontPage 6.0">
 <meta name="ProgId" content="FrontPage.Editor.Document">
 <title>Inserting a Schematic Component into a Schematic Route</title>
 <link rel="stylesheet" type="text/css" href="../CAAScrBase/caav5.css">
 <script language="JavaScript" src="../CAAScrJavaScript/submit.js">
 </script>
 </head>

 <body>

 <table border="0" width="100%">
   <tr>
     <td>
     <h2>Schematics Platform Modeler</h2>
     </td>
     <td align="right" valign="top">
     <h2><a name="Top"></a>Inserting a Schematic Component into a Schematic 
     Route</h2>
     </td>
   </tr>
 </table>
 <hr>
 <!null ---------------------------------comment----------------------------->
 <table border="0" width="100%">
   <tr>
     <td width="7%" valign="top">
     <img border="0" src="../CAAScrBase/images/atarget.gif" width="32" height="32"></td>
     <td width="93%"><a name="Learn"></a>This macro shows you how to insert a 
     Schematic component into a Schematic route.
     <p>The word &quot;insert&quot; refers to a process by which a Schematic route is 
     split at a specific location (creating a new route) and a Schematic 
     component is connected to the two routes, creating two connections. These 
     connections are created through two connectors of the schematic component. 
     These two connectors must be internally connected to each other by an 
     &quot;internal flow&quot; object, which is aggregated by the Schematic component.</p>
     <p>This macro opens two documents: CAASCH_Sample.catalog and 
     CAASCH_RouteForPlacement.CATProduct. </p>
     <p>Notice the x-y coordinates of a point (80,50), as indicated in the 
     screen shots. They will be used later in this use case.</p>
     <p>
     <img border="0" src="images/CAASchInsertComponent_01.jpg" width="798" height="315"></p>
     <p>In this use case, two Schematic components are inserted into route using 
     two different approaches.</td>
   </tr>
   <tr>
     <td width="7%" valign="top">
     <img border="0" src="../CAAScrBase/images/ainfo.gif" width="32" height="32"></td>
     <td width="93%"><a name="How"></a>CAASchInsertComponent is launched in 
     CATIA [<a href="#References">1</a>]. No open document is needed.<p>Special 
		environment must be available to successfully run this macro:</p>
		<ul>
			<li>Prerequisites:</li>
		</ul>
		<blockquote>
			<ol>
				<li>RADE must be installed.</li>
				<li>CAASchPlatformModeler.edu must exist in CAADoc folder.</li>
			</ol>
		</blockquote>
		<ul>
			<li>Setup:</li>
		</ul>
		<blockquote>
			<ol>
				<li>Build CAASchAppBase.m and CAASchAppUtilities.m, located in 
				CAASchPlatformModeler.edu (RADE is required). </li>
				<li>Copy generated DLLs, CAASchAppBase.dll and CAASchAppUtilities.m, respectively, to the run-time environment 
				folder &quot;intel_a\code\bin.&quot;</li>
				<li>Copy CAASCHEDUApp.CATfct, located CAASchPlatformModeler.edu\CNext\resources\graphic, 
				to the run-time environment folder &quot;intel_a\resources\graphic.&quot;</li>
				<li>Copy CAASchPlatformModeler.edu\CNext\code\dictionary\CAASchPlatformModeler.edu.dico 
				to the run-time environment folder &quot;intel_a\code\dictionary.&quot;</li>
			</ol>
		</blockquote>
		<p>
     <a href="CAASchInsertComponentSource.htm">CAASchInsertComponent.CATScript i</a>s 
     located in the CAAScdSchUseCases module.
     <a href="macros/CAASchInsertComponent.CATScript">Execute macro</a> (Windows 
     only).</td>
   </tr>
   <tr>
     <td width="7%" valign="top">
     <img border="0" src="../CAAScrBase/images/ascenari.gif" width="32" height="32"></td>
     <td width="93%"><a name="Step"></a>CAASchInsertComponent includes the 
     following steps:<ol>
       <li><a href="#Prolog">Prolog</a></li>
       <li><a href="#Get the Schematic reference component">Get the Schematic 
       reference component from the catalog</a></li>
       <li><a href="#Insert instance 01">Insert an instance of the Schematic 
       reference component - approach 1</a></li>
       <li><a href="#Insert instance 02">Insert an instance of the Schematic 
       reference component - approach 2</a></li>
     </ol>
     <h4><a name="Prolog"></a>Prolog</h4>
     <p>The macro first loads two documents. CAASCH_Sample.catalog and 
     CAASCH_RouteForPlacement.CATProduct.</p>
     <table class="code">
       <tr>
         <td width="100%">
     <pre>    <font color="#008000">...</font>
    <font color="#008000">' ------------------------------------------------------------------------- </font>
    <font color="#008000">' Open the catalog document </font>
<font color="#0000FF">    Dim </font>sCtlgFilePath
    sCtlgFilePath = CATIA.FileSystem.ConcatenatePaths(sDocPath, _
            "online\CAAScdSchUseCases\samples\CAASCH_Sample.catalog")

<font color="#0000FF">    Dim </font>objSchCtlgDoc<font color="#0000FF"> As </font>Document
<font color="#0000FF">    Set </font>objSchCtlgDoc = CATIA.Documents.Open(sCtlgFilePath)
     </pre>
     <pre>    <font color="#008000">' Open main schematic design document (for new component instances created here)</font>
<font color="#0000FF">    Dim </font>sFilePath
    sFilePath = CATIA.FileSystem.ConcatenatePaths(sDocPath, _
            "online\CAAScdSchUseCases\samples\CAASCH_RouteForPlacement.CATProduct")

<font color="#0000FF">    Dim </font>objSchDoc<font color="#0000FF"> As </font>Document
<font color="#0000FF">    Set </font>objSchDoc = CATIA.Documents.Open(sFilePath)
    <font color="#008000">...</font></pre>
         </td>
       </tr>
     </table>
     <p>Next, the macro acquires the schematic root object from the document. 
     The schematic root is the top node of the object instance tree in a 
     schematic document. </p>
     <table class="code">
       <tr>
         <td width="100%">
     <pre>    <font color="#008000">...</font>
    <font color="#008000">' Find the top node of the schematic object tree - schematic root.</font>
<font color="#0000ff">    Dim </font>objPrdRoot<font color="#0000ff"> As </font>Product
<font color="#0000ff">    Dim </font>objSchRoot<font color="#0000ff"> As </font>SchematicRoot
<font color="#0000ff">    If </font>( Not ( IsEmpty ( objSchDoc ) )<font color="#0000ff"> Then</font>
<font color="#0000ff">      Set </font>objPrdRoot = objSchDoc.Product 
<font color="#0000ff">      If </font>( Not ( IsEmpty ( objPrdRoot ) )<font color="#0000ff"> Then</font>
<font color="#0000ff">        Set </font>objSchRoot = objPrdRoot.GetTechnologicalObject(&quot;SchematicRoot&quot;)
<font color="#0000ff">      End If</font>
<font color="#0000ff">    End If</font></pre>
     <pre>    <font color="#008000">...</font></pre>
         </td>
       </tr>
     </table>
     <p>The SchematicRoot interface provides a method to retrieve the graphical 
     representation of a reference component from the catalog by name. This 
     graphical representation is associated to a reference component in the 
     catalog.</p>
     <table class="code">
       <tr>
         <td width="100%">
     <pre>    <font color="#008000">...</font>
<font color="#0000FF">    Dim </font>objSchGRRCVCtlg<font color="#0000FF"> As </font>SchGRR </pre>
     <pre>    <font color="#008000">...</font>

<font color="#0000FF">    If </font>( Not ( IsEmpty ( objSchRoot ) ) )<font color="#0000FF"> Then</font>

       <font color="#008000">'-----------------------------------------------------------------------</font>
       <font color="#008000">' Get the symbol of a component from the component catalog.</font>
       <font color="#008000">'-----------------------------------------------------------------------</font>
<font color="#0000FF">       Set </font>objSchGRRCVCtlg = objSchRoot.GetCompSymbolFromCatalog (&quot;Control Valve&quot;,objSchCtlgDoc)
    <font color="#008000">...</font></pre>
         </td>
       </tr>
     </table>
     <h4><a name="Get the Schematic reference component"></a>Get the Schematic 
     reference component from the catalog</h4>
     <p>Given the graphical representation (symbol) from the previous step, the 
     macro calls GetSchObjOwner to get the Schematic reference component that 
     the symbol is associated with.</p>
     <table class="code">
       <tr>
         <td width="100%">&nbsp;&nbsp;&nbsp;    <font color="#008000">...</font><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
         <font color="#008000">'---------------------------------------------------------------------</font><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
         <font color="#008000">' Get the owner of the symbol. That is, a reference component,</font><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
         <font color="#008000">' in the catalog.</font><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
         <font color="#008000">'---------------------------------------------------------------------</font><br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;         Set </font>objSchCntblCVRef = objSchGRRCVCtlg.GetSchObjOwner<br>
&nbsp;&nbsp;&nbsp;
    <font color="#008000">...</font></td>
       </tr>
     </table>
     <p>Through the GetInterface method, the macro obtains a handle on the 
     SchComponent interface, which is needed for creating an instance of the 
     Schematic reference component from the catalog.</p>
     <table class="code">
       <tr>
         <td width="100%">&nbsp;&nbsp;&nbsp;    <font color="#008000">...</font><br>
<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;         If </font>( Not ( IsEmpty ( objSchCntblCVRef ) ) )<font color="#0000FF"> Then</font><br>
         <br>

<font color="#0000FF">&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;           Set </font>objSchCompCVRef = objSchRoot.Ge<font color="#0000FF">tInt</font>erface (&quot;CATIASchComponent&quot;,objSchCntblCVRef)<br>
&nbsp;&nbsp;&nbsp;
    <font color="#008000">...</font></td>
       </tr>
     </table>
     <h4><a name="Insert instance 01"></a>Insert an instance of the Schematic 
     reference component - approach 1</h4>
     <p>The &quot;insert&quot; process includes the following.</p>
     <ul>
       <li>
     <pre>Create a new instance of the Schematic reference component.</li>
       <li>Spit the existing route into two pieces, creating a new route in the 
       process.</li>
       <li>Make all necessary connections between the new component instance and 
       the routes.</li>
     </ul>
     <p>Approach 1 is specially designed for client application that has 
     dedicated graphical user interface to manage the checking of the 
     compatibility between the route and the component. In particular, the QueryConnectAbility and the IsTargetOKForInsert methods can be used to 
     filter out incompatible component-route combinations (perhaps accompanied 
     with client specific visual user feedbacks). Furthermore, when the route is 
     being selected and the &quot;mouse&quot; is traveling along the route path and right 
     before the left-mouse button clicking to define the placement location, the GetBestFitInsertInfo method can be used to make sure that the compatible 
     component will &quot;fit&quot; into the route..</p>
     <table class="code"><tr><td width="100%">    <font color="#008000">...</font><br>              <font color="#008000">'----------------------------------------------------------------</font><br>              <font color="#008000">'  Insert a component into a route.</font><br>              <font color="#008000">'</font><br>              <font color="#008000">'  Approach 1 - with compatibility information.</font><br>              <font color="#008000">'  1- QueryConnectAbility.</font><br>              <font color="#008000">'     Ask the reference of the component for information</font><br>              <font color="#008000">'     to use in compatibility checking. The objCompRefPlaceInfo</font><br>              <font color="#008000">'     is an output and should be used as a &quot;black box&quot;. </font><br>              <font color="#008000">'     It is the input to the next call.</font><br>              <font color="#008000">'</font><br>              <font color="#008000">'  2- IsTargetOKForInsert</font><br>              <font color="#008000">'     Check whether the route is compatible to the component</font><br>              <font color="#008000">'     in making connections.</font><br>              <font color="#008000">'     The route instance is the &quot;target&quot;. </font><br>              <font color="#008000">'     objCompatInfo is an output and should be used as </font><br>              <font color="#008000">'     a &quot;black box&quot;. It is an input to the next call.</font><br>              <font color="#008000">'</font><br>              <font color="#008000">'  3- GetBestFitInsertInfo</font><br>              <font color="#008000">'     Input the placement location, close to middle of the route</font><br>              <font color="#008000">'     objFinalInsertInfo is an output and should be used as</font><br>              <font color="#008000">'     a &quot;black box&quot;. It is an input to the next call.</font><br>              <font color="#008000">'</font><br>              <font color="#0080
00">'  4- InsertIntoRouteWithInfo</font><br>              <font color="#008000">'     Place a new component instance with the black box info.</font><br>              <font color="#008000">'     The route will be broken up into 2 pieces (shorten the</font><br>              <font color="#008000">'     existing route and create a new route instance).</font><br>              <font color="#008000">'     The new component instance will be connected to the</font><br>              <font color="#008000">'     2 routes on each of the 2 sides (left and right).  </font><br>              <font color="#008000">'----------------------------------------------------------------</font><br><br>              <font color="#008000">' -- step 1 </font><br><font color="#0000FF">              Set </font>objCompRefPlaceInfo = objSchCompCVRef.QueryConnectAbility _<br>                (objSchGRRCVCtlg) <br><br>              <font color="#008000">' -- step 2 </font><br>              objSchCompatRoute.IsTargetOKForInsert objCompRefPlaceInfo, _<br>                objCompatInfo, bYesCompat<br><br><font color="#0000FF">              Dim </font>db2Pt(2)<font color="#0000FF"> As </font>CATSafeArrayVariant<br><br>              <font color="#008000">'-- a point at the middle of the route</font><br>              db2Pt(0) = 80.0<br>              db2Pt(1) = 50.0<br><br><br><font color="#0000FF">              If </font>( bYesCompat )<font color="#0000FF"> Then</font><br>    <font color="#008000">...</font><br>                 bFindAllSolutions = false<br><br>                 <font color="#008000">' -- step 3 </font><br>                 objSchCompatRoute.GetBestFitInsertInfo db2Pt, objCompatInfo, _<br>                   objFinalInsertInfo, bFindAllSolutions<br><br><font color="#0000FF">                 If </font>( Not ( IsEmpty ( objFinalInsertInfo ) ) )<font color="#0000FF"> Then</font><br><br>                    <font color="#008000">' -- step 4 </font><br>                    objSchCompCVRef.Inser<font color="#0000FF">tInt</font>oRouteWithInfo objFinalI
nsertInfo, _<br>                      objSchCompInst,objSchRouteInst<br>    <font color="#008000">...</font></td></tr></table><h4><a name="Insert instance 02"></a>Insert an instance of the Schematic 
     reference component - approach 2</h4>
     <p>An client application which doesn't want to deal with the details of the 
     compatibility checking should use approach 2. By calling the PlaceOnObject method, a Schematic component can be inserted into a route. All the 
     compatibility methods are implicitly called in the implementation of the PlaceOnObject method and are kept transparent to the application. There are 
     only two required input: the placement location and the object to be 
     connected to the new instance.</p>
     <table class="code"><tr><td width="100%">    <font color="#008000">...</font><br><font color="#0000FF">                 Dim </font>db6Matrix(6)<font color="#0000FF"> As </font>CATSafeArrayVariant<br>                 db6Matrix(0)=1.0<br>                 db6Matrix(1)=0.0<br>                 db6Matrix(2)=0.0<br>                 db6Matrix(3)=1.0<br>                 db6Matrix(4)=db2Pt(0)<br>                 db6Matrix(5)=db2Pt(1)<br><br>                 objSchCompCVRef.PlaceOnObject objSchGRRCVCtlg, db6Matrix, _<br>                   objSchCntblRouteInst, objSchCompInst2<br>    <font color="#008000">...</font></td></tr></table><p>To figure out the placement location of the component instance, the 
     macro calls the private FindPlacementPoint function. There, the x-y 
     coordinates of the route path defining points are retrieved using the GetPath method of the SchGRRRoute interface. Given these, the macro takes 
     the mid point of the first two points in the path and returns its x-y 
     coordinates to be the placement location.</p>
     <p><br>
     </td>
   </tr>
 </table>
 <p align="right">[<a href="#Top">Top</a>]</p><hr>
 <!---------------------------------comment----------------------------------->
 <h4><a name="InShort"></a>In Short</h4>
 <p>This use case shows two ways to insert a Schematic object into a Schematic 
 route. A message logging the status of the critical steps is displayed at the 
 end of the use case. </p>
 <p>
 <img border="0" src="images/CAASchInsertComponent_02.jpg" width="574" height="336"></p>
 <p align="right">[<a href="#Top">Top</a>]</p><hr>
 <!---------------------------------comment----------------------------------->
 <h4><a name="References"></a>References</h4>
 <table border="0" width="100%">
   <tr>
     <td valign="top">[1]</td>
     <td><a href="../CAAScdInfUseCases/CAAInfLauchMacro.htm">
     Replaying a Macro</a></td>
   </tr>
   <tr>
     <td valign="top"></td>
     <td></td>
   </tr>
   <tr>
     <td colspan="2" align="right">[<a href="#Top">Top</a>]</td>
   </tr>
 </table>
 <hr>
 <!---------------------------------comment----------------------------------->
 <p><i>Copyright © 2001, Dassault Systèmes. All rights reserved.</i></p>

 </body>

</html>
