<html><head><meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"><title>CAASchCreateSchDocument.CATScript</title><link rel="stylesheet" type="text/css" href="../CAAScrBase/caav5.css"></head><body><pre>
<font color="#0000FF">Option Explicit</font>
<font color="#008000">' COPYRIGHT DASSAULT SYSTEMES 2004</font>

<font color="#008000">' *****************************************************************************</font>
<font color="#008000">'   Purpose:      Create a schematic document.</font>
<font color="#008000">'   Languages:    VBScript</font>
<font color="#008000">'   Locales:      English </font>
<font color="#008000">'   CATIA Level:  V5R15 </font>
<font color="#008000">' *****************************************************************************</font>

<font color="#0000FF">Sub </font>CATMain()

    <font color="#008000">' ------------------------------------------------------------------------- </font>
    <font color="#008000">' Optional: allows to find the sample wherever it's installed</font>

<font color="#0000FF">    dim </font>sDocPath<font color="#0000FF"> As </font>String 
    sDocPath=CATIA.SystemService.Environ("CATDocView")

<font color="#0000FF">    If </font>(Not CATIA.FileSystem.FolderExists(sDocPath))<font color="#0000FF"> Then</font>
      Err.Raise 9999,sDocPath,"No Doc Path Defined"
<font color="#0000FF">    End If</font>

<font color="#0000FF">    dim </font>sSavePath<font color="#0000FF"> As </font>String 
    sSavePath=CATIA.SystemService.Environ("CATSavePath")

    CATIA.SystemService.Print "CATSavePath = " & sSavePath

<font color="#0000FF">    If </font>(Not CATIA.FileSystem.FolderExists(sSavePath))<font color="#0000FF"> Then</font>
      Err.Raise 9999,sSavePath,"No Path for saving document"
<font color="#0000FF">    End If</font>

    <font color="#008000">' Open main schematic P&ID design document </font>
<font color="#0000FF">    Dim </font>sFilePath
    sFilePath = CATIA.FileSystem.ConcatenatePaths(sDocPath, _
            "online\CAAScdSchUseCases\samples\CAASCH_Detail01.CATProduct")

<font color="#0000FF">    Dim </font>objSchDoc<font color="#0000FF"> As </font>Document
<font color="#0000FF">    Set </font>objSchDoc = CATIA.Documents.Open(sFilePath)

<font color="#0000FF">    Dim </font>strMessage<font color="#0000FF"> As </font>String

    strMessage = _
      "--------------------------------------------------------------------" & vbCr
    strMessage = strMessage & _
      "Output traces from CAASchCreateSchDocument.CATScript" & vbCrLf

    <font color="#008000">'</font>
    <font color="#008000">' Find the top node of the schematic object tree - schematic root.</font>
<font color="#0000FF">    Dim </font>objPrdRoot<font color="#0000FF"> As </font>Product
<font color="#0000FF">    Dim </font>objSchRoot<font color="#0000FF"> As </font>SchematicRoot
<font color="#0000FF">    If </font>( Not ( objSchDoc Is Nothing ) )<font color="#0000FF"> Then</font>
<font color="#0000FF">      Set </font>objPrdRoot = objSchDoc.Product 
<font color="#0000FF">      If </font>( Not ( objPrdRoot Is Nothing ) )<font color="#0000FF"> Then</font>
<font color="#0000FF">        Set </font>objSchRoot = objPrdRoot.GetTechnologicalObject("SchematicRoot")
<font color="#0000FF">      End If</font>
<font color="#0000FF">    End If</font>

<font color="#0000FF">    Dim </font>objSchSession<font color="#0000FF"> As </font>SchSession
<font color="#0000FF">    Dim </font>objSchDocNew<font color="#0000FF"> As </font>Document
<font color="#0000FF">    Dim </font>bInteractive<font color="#0000FF"> As </font>boolean

<font color="#0000FF">    If </font>( Not ( objSchRoot Is Nothing ) )<font color="#0000FF"> Then</font>

       <font color="#008000">'-----------------------------------------------------------------------</font>
       <font color="#008000">' Get the schematic session.</font>
       <font color="#008000">'-----------------------------------------------------------------------</font>

<font color="#0000FF">       Set </font>objSchSession = objSchRoot.GetSchematicSession
<font color="#0000FF">       If </font>( Not ( objSchSession Is Nothing ) )<font color="#0000FF"> Then</font>
         strMessage = strMessage &  "Got schematic session" & vbCr

         <font color="#008000">'---------------------------------------------------------------------</font>
         <font color="#008000">' Create another schematic document.</font>
         <font color="#008000">'---------------------------------------------------------------------</font>
         <font color="#008000">'bInteractive = true</font>
         bInteractive = false
         objSchSession.CreateDocument "CATProduct",bInteractive,objSchDocNew

<font color="#0000FF">         If </font>( Not ( objSchDocNew Is Nothing ) )<font color="#0000FF"> Then</font>

<font color="#0000FF">            Set </font>objPrdRoot = Nothing
<font color="#0000FF">            Set </font>objSchRoot = Nothing

<font color="#0000FF">            Set </font>objPrdRoot = objSchDocNew.Product 
<font color="#0000FF">            If </font>( Not ( objPrdRoot Is Nothing ) )<font color="#0000FF"> Then</font>
<font color="#0000FF">               Set </font>objSchRoot = objPrdRoot.GetTechnologicalObject("SchematicRoot")
<font color="#0000FF">            End If</font>

<font color="#0000FF">            If </font>( Not ( objSchRoot Is Nothing ) )<font color="#0000FF"> Then</font>
               objSchRoot.SetDrawingStandard catISO
               strMessage = strMessage & "drawing standard set to catISO" & vbCr
<font color="#0000FF">               Dim </font>std<font color="#0000FF"> As </font>CatDrawingStandard
               std = objSchRoot.GetDrawingStandard
               strMessage = strMessage & "drawing standard = " & std & vbCr
<font color="#0000FF">            End If</font>

<font color="#0000FF">            Dim </font>strDocName<font color="#0000FF"> As </font>String

            strDocName = objSchDocNew.FullName

            strMessage = strMessage & "document created" & vbCr
            strMessage = strMessage & "default name = " & strDocName & vbCr

            strDocName = CATIA.FileSystem.ConcatenatePaths(sSavePath, _
			              "SampleOutput_SchDoc01.CATProduct")

            objSchDocNew.SaveAs strDocName

            strMessage = strMessage &  "document created" & vbCr
            strMessage = strMessage &  "document saved as " & strDocName & vbCr
<font color="#0000FF">         End If</font>

<font color="#0000FF">       End If </font><font color="#008000">'--- If ( Not ( objSchDocNew ...</font>

<font color="#0000FF">    End If  </font><font color="#008000">'----If ( Not ( objSchRoot Is Nothing )...</font>

    strMessage = strMessage & _
      "--------------------------------------------------------------------" & vbCr
    MsgBox strMessage

<font color="#0000FF">End Sub</font>







</pre></body></html>
