<html>
<head>
 <meta name="Generator" content="mihGene v1.1">
 <meta http-equiv="Expires" content="Tue, 04 Dec 1993 21:29:02 GMT">
 <title>DraftingInterfaces DrawingComponents (Collection)</title>
<link rel="Stylesheet" type="text/css" href="../../../caav5.css">
<script language="Javascript" src="../_index/jslink.js"></script> 
<script language="Javascript" src="jsFwLink.js"></script> 
<script language="Javascript" type="text/javascript" src="../_index/jsTree.js"></script>  
</head>
<body>
<pre><a href="../_index/main.htm">All Frameworks</a>  <a href="../_index/tree.htm">Object Hierarchy</a>  <a href="../DraftingInterfaces.htm">This Framework</a>  <a href="../_index/CAAHomeIdx.htm">Indexes</a>  <script type="text/javascript"> 
 var test=locateObject('DrawingComponents','interface','0'); 
 if(test==1){ 
     document.write("<a href=\"#\" onclick=\"openLinkNP('DrawingComponents','interface','0');return false\">Previous</a> "); 
 } 
 test=locateObject('DrawingComponents','interface','1'); 
 if(test==1){ 
     document.write("<a href=\"#\" onclick=\"openLinkNP('DrawingComponents','interface','1');return false\">Next</a> "); 
 } 
 </script> 
</pre>
<hr>
<h1>DrawingComponents<font size=-1> (Collection)</font></h1>
<script type="text/javascript" > 
 generatedFatherClass('interface_DrawingComponents_34316','DrawingComponents','0');</script>
<b><i>   A collection of all the drawing components (ditto) currently managed by a
 drawing view of drawing sheet in a drawing document.</i></b><br>
<hr>
<dl>
</dl>
<dl>
 <h2><a name="MethodIndex"></a>Method Index</h2>
 <dt>
    <a href="#Add"><b>Add</b></a>
<dd>  Creates a drawing component instance and adds it to the DrawingComponents collection.
 <dt>
    <a href="#Item"><b>Item</b></a>
<dd>  Returns a drawing component instance using its index or its name from the DrawingComponents collection.
 <dt>
    <a href="#Remove"><b>Remove</b></a>
<dd>  Removes a drawing component from the DrawingComponents collection.
</dl>
 <h2><a name="Methods"></a>Methods</h2> <br>
<a name="Add"><dt>

<table><tr><td>o Func <b>Add</b>(<td><script type="text/javascript"> activateLink('DrawingView','DrawingView')</script> <td><tt>iDrawingComponentRef</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('double','double')</script> <td><tt>iPositionX</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('double','double')</script> <td><tt>iPositionY</tt>) As <script type="text/javascript"> activateLink('DrawingComponent','DrawingComponent')</script> </table></dt>
<dl>
  <dd>
 Creates a drawing component instance and adds it to the DrawingComponents collection.
 
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iDrawingComponentRef</tt>
   <dd>   The view (i.e. the detail) that is the component reference .
   This view also called a detail MUST belong to a sheet of component references (i.e. details)
 </dd>
    <dt><tt> iPositionX,iPositionY</tt>
   <dd>   The drawing component x and y coordinates, expressed in millimeters,
   with respect to the drawing view coordinate system
 </dd>
</dl>
  <dt> <b>Returns:</b> 
  <dd>  The created drawing component instance <!-- @sample -->
 </dl>
 <dt><b>Example:</b>
 <dd>
 The following example creates a drawing component instance with a given component reference <tt>MyComponentRef</tt>
 coming from a Sheet of component references (i.e. details) <tt>SheetComponentRef</tt> 
 and retrieved in <tt>MyComponentInst</tt> in the drawing view collection
 of the <tt>MyView</tt> drawing view.
 This view belongs to the drawing view collection of the drawing sheet
 <pre>
 Dim MyComponentRef As DrawingView
 Set MyComponentRef = SheetComponentRef.Views.<font color="red">Item</font>(1)
 Dim MyView As DrawingView
 Set MyView = MySheet.Views.<font color="red">ActiveView</font>
 Dim MyComponentInst As DrawingComponent
 Set MyComponentInst = MyView.Components.<font color="red">Add</font>(MyComponentRef, 100., 50.)
 </pre>
 </dl>
</dl>
</dl>
<a name="Item"><dt>

<table><tr><td>o Func <b>Item</b>(<td><script type="text/javascript"> activateLink('CATVariant','CATVariant')</script> <td><tt>iIndex</tt>) As <script type="text/javascript"> activateLink('DrawingComponent','DrawingComponent')</script> </table></dt>
<dl>
  <dd>
 Returns a drawing component instance using its index or its name from the DrawingComponents collection.
 
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iIndex</tt>
   <dd>   The index or the name of the drawing component instance to retrieve from
   the collection of drawing components.
   As a numerics, this index is the rank of the drawing component instance
   in the collection.
   The index of the first drawing component instance in the collection is 1, and
   the index of the last drawing component instance is Count.
   As a string, it is the name you assigned to the drawing component instance using
   the </dd>
</dl>
<a href="#" onClick="openLink('AnyObject','Name');return false">AnyObject.Name</a> property  
  <dt> <b>Returns:</b> 
  <dd>  The retrieved drawing component instance <!-- @sample -->
 </dl>
 <dt><b>Example:</b>
 <dd>
 This example retrieves in <tt>ThisDrawingComponent</tt> the second drawing component instance,
 <tt>MyView</tt> in the drawing view collection of the active sheet
 in the active document, supposed to be a drawing document.
 <pre>
 Dim MySheet As DrawingSheet
 Set MySheet = CATIA.ActiveDocument.Sheets.ActiveSheet
 Dim MyView  As DrawingView
 Set MyView  = MySheet.Views.ActiveView
 Dim ThisDrawingComponent As DrawingComponent
 Set ThisDrawingComponent = MyView.Components.<font color="red">Item</font>(2)
 </pre>
 </dl>
</dl>
</dl>
<a name="Remove"><dt>

<table><tr><td>o Sub <b>Remove</b>(<td><script type="text/javascript"> activateLink('CATVariant','CATVariant')</script> <td><tt>iIndex</tt>)</table></dt>
<dl>
  <dd>
 Removes a drawing component from the DrawingComponents collection.
 
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iIndex</tt>
   <dd>   The index of the drawing component to remove from
   the collection of drawing components.
   As a numerics, this index is the rank of the drawing component
   in the collection.
   The index of the first drawing component instance in the collection is 1, and
   the index of the last drawing component instance is Count.
   As a string, it is the name you assigned to the drawing component using
   the </dd>
</dl>
<a href="#" onClick="openLink('AnyObject','Name');return false">AnyObject.Name</a> property  <!-- @sample -->
 </dl>
 <dt><b>Example:</b>
 <dd>
 The following example removes the third drawing component instance 
 in the drawing component collection of the active view
 of the active document, supposed to be a drawing document.
 <pre>
 Dim MyView As DrawingView
 Set MyView  = MySheet.Views.ActiveView
 MyView.Components.<font color="red">Remove</font>(3)
 </pre>
 </dl>
</dl>
</dl>

</body>
<hr><p><i>
Copyright &#169; 1999-2011, Dassault Syst&#232;mes. All rights reserved.</i></p>
</html>
