<html>
<head>
 <meta name="Generator" content="mihGene v1.1">
 <meta http-equiv="Expires" content="Tue, 04 Dec 1993 21:29:02 GMT">
 <title>DraftingInterfaces DrawingComponent (Object)</title>
<link rel="Stylesheet" type="text/css" href="../../../caav5.css">
<script language="Javascript" src="../_index/jslink.js"></script> 
<script language="Javascript" src="jsFwLink.js"></script> 
<script language="Javascript" type="text/javascript" src="../_index/jsTree.js"></script>  
</head>
<body>
<pre><a href="../_index/main.htm">All Frameworks</a>  <a href="../_index/tree.htm">Object Hierarchy</a>  <a href="../DraftingInterfaces.htm">This Framework</a>  <a href="../_index/CAAHomeIdx.htm">Indexes</a>  <script type="text/javascript"> 
 var test=locateObject('DrawingComponent','interface','0'); 
 if(test==1){ 
     document.write("<a href=\"#\" onclick=\"openLinkNP('DrawingComponent','interface','0');return false\">Previous</a> "); 
 } 
 test=locateObject('DrawingComponent','interface','1'); 
 if(test==1){ 
     document.write("<a href=\"#\" onclick=\"openLinkNP('DrawingComponent','interface','1');return false\">Next</a> "); 
 } 
 </script> 
</pre>
<hr>
<h1>DrawingComponent<font size=-1> (Object)</font></h1>
<script type="text/javascript" > 
 generatedFatherClass('interface_DrawingComponent_32476','DrawingComponent','0');</script>
<b><i>   Represents a drawing component instance (ditto) in a drawing view.</i></b><br>
<hr>
<dl>
 <h2><a name="PropertyIndex"></a>Property Index</h2>
 <dt>
    <a href="#Angle"><b>Angle</b></a>
<dd>  Returns or sets the angle of the drawing component instance.
 <dt>
    <a href="#CompRef"><b>CompRef</b></a>
<dd>  Returns the component reference of this drawing component instance.
 <dt>
    <a href="#Scale2"><b>Scale2</b></a>
<dd>  Returns or sets the scale of the drawing component instance (Workaround for VBA keyword).
 <dt>
    <a href="#x"><b>x</b></a>
<dd>  Returns or sets the x coordinate of the drawing component instance position.
 <dt>
    <a href="#y"><b>y</b></a>
<dd>  Returns or sets the y coordinate of the drawing component instance position.
</dl>
<dl>
 <h2><a name="MethodIndex"></a>Method Index</h2>
 <dt>
    <a href="#Explode"><b>Explode</b></a>
<dd>  Explodes the drawing component instance (every sub elements of the drawing component
 are created).
 <dt>
    <a href="#ExplodeAndSelect"><b>ExplodeAndSelect</b></a>
<dd>  Explodes the drawing component instance (every sub elements of the drawing component
 are created) and put created sub elements in selection set.
 <dt>
    <a href="#ExposeCompRef"><b>ExposeCompRef</b></a>
<dd>  Exposes the component reference of this drawing component instance in a new detail sheet.
 <dt>
    <a href="#ExposeCompRefInSheet"><b>ExposeCompRefInSheet</b></a>
<dd>  Exposes the component reference of this drawing component instance in a specific detail sheet.
 <dt>
    <a href="#Flip"><b>Flip</b></a>
<dd>  Flips the drawing component instance around X axis
 To flip around Y axis you have to flip the component around X and to add
 a rotation of 180 degrees.
 <dt>
    <a href="#GetFlip"><b>GetFlip</b></a>
<dd>  Returns the flip state of a drawing component instance around X axis.
 <dt>
    <a href="#GetMatrix"><b>GetMatrix</b></a>
<dd>  Gets the matrix of the drawing component instance.
 <dt>
    <a href="#GetModifiableObject"><b>GetModifiableObject</b></a>
<dd>  Gets a modifiable object by index or name in this drawing component instance.
 <dt>
    <a href="#GetModifiableObjectsCount"><b>GetModifiableObjectsCount</b></a>
<dd>  Gets the number of modifiable objects in this drawing component instance.
 <dt>
    <a href="#SetMatrix"><b>SetMatrix</b></a>
<dd>  Sets the matrix of the drawing component instance.
</dl>
 <h2><a name="Properties"></a>Properties</h2> <br>
<a name="Angle"><dt>

<table><tr><td>o Property <b>Angle</b>(<td>) As <script type="text/javascript"> activateLink('double','double')</script> </table></dt>
<dl>
  <dd>
 Returns or sets the angle of the drawing component instance.
 The angle is given in the axis system of the drawing view
 The angle is measured in radians and is counted counterclockwise.
 <!-- @sample -->
 <dl>
 <dt><b>Example:</b>
 <dd>
 This example sets the angle of the <tt>MyComponent</tt> drawing component instance to 90
 degrees clockwise.
 You first need to compute the angle in radians and set the
 minus sign to indicate the rotation is clockwise.
 <pre>
 PI = 3.1415926535
 Angle90Clockwise = -PI/2
 MyComponent.<font color="red">Angle</font> = Angle90Clockwise
 </pre>
 </dl>
</dl>
<a name="CompRef"><dt>

<table><tr><td>o Property <b>CompRef</b>(<td>) As <script type="text/javascript"> activateLink('DrawingView','DrawingView')</script>  (Read Only)</table></dt>
<dl>
  <dd>
 Returns the component reference of this drawing component instance.
 this is a CATIADrawingView
 <!-- @sample -->
 <dl>
 <dt><b>Example:</b>
 <dd>
 This example gets the drawing component reference of the
 <tt>MyComponent</tt> drawing component instance.
 <pre>
 Dim ComponentRef As DrawingView
 Set ComponentRef = MyComponent.<font color="red">CompRef</font>
 </pre>
 </dl>
</dl>
<a name="Scale2"><dt>

<table><tr><td>o Property <b>Scale2</b>(<td>) As <script type="text/javascript"> activateLink('double','double')</script> </table></dt>
<dl>
  <dd>
 Returns or sets the scale of the drawing component instance (Workaround for VBA keyword).
 <!-- @sample -->
 <dl>
 <dt><b>Example:</b>
 <dd>
 This example sets the scale of the <tt>MyComponent</tt> drawing component instance to 0.5.
 <pre>
 MyComponent.<font color="red">Scale2</font> = 0.5
 </pre>
 </dl>
</dl>
<a name="x"><dt>

<table><tr><td>o Property <b>x</b>(<td>) As <script type="text/javascript"> activateLink('double','double')</script> </table></dt>
<dl>
  <dd>
 Returns or sets the x coordinate of the drawing component instance position.
 It is expressed with respect to the view coordinate system.
 This coordinate, like any length, is measured in millimeters.
 <!-- @sample -->
 <dl>
 <dt><b>Example:</b>
 <dd>
 This example sets the x coordinate of the position of the
 <tt>MyComponent</tt> drawing component instance to 5 inches.
 You need first to convert the 5 inches into millimeters.
 <pre>
 NewXCoordinate = 5*25.4
 MyComponent.<font color="red">x</font> =  NewXCoordinate
 </pre>
 </dl>
</dl>
<a name="y"><dt>

<table><tr><td>o Property <b>y</b>(<td>) As <script type="text/javascript"> activateLink('double','double')</script> </table></dt>
<dl>
  <dd>
 Returns or sets the y coordinate of the drawing component instance position.
 It is expressed with respect to the view coordinate system.
 This coordinate, like any length, is measured in millimeters.
 <!-- @sample -->
 <dl>
 <dt><b>Example:</b>
 <dd>
 This example sets the y coordinate of the position of the
 <tt>MyComponent</tt> drawing component instance to 5 inches.
 You need first to convert the 5 inches into millimeters.
 <pre>
 NewYCoordinate = 5*25.4
 MyComponent.<font color="red">y</font> =  NewYCoordinate
 </pre>
 </dl>
</dl>
 <h2><a name="Methods"></a>Methods</h2> <br>
<a name="Explode"><dt>

<table><tr><td>o Sub <b>Explode</b>(<td>)</table></dt>
<dl>
  <dd>
 Explodes the drawing component instance (every sub elements of the drawing component
 are created).
 Note: The drawing component is not removed by Explode method
 <!-- @sample -->
 <dl>
 <dt><b>Example:</b>
 <dd>
 This example Explodes the <tt>MyComponent</tt> drawing component instance and removes it.
 <pre>
 MyComponent.<font color="red">Explode</font>
 Set MySelection = CATIA.ActiveDocument.Selection
 MySelection.clear
 MySelection.add MyComponent
 MySelection.delete
 </pre>
 </dl>
</dl>
<a name="ExplodeAndSelect"><dt>

<table><tr><td>o Sub <b>ExplodeAndSelect</b>(<td>)</table></dt>
<dl>
  <dd>
 Explodes the drawing component instance (every sub elements of the drawing component
 are created) and put created sub elements in selection set.
 <!-- @sample -->
 <dl>
 <dt><b>Example:</b>
 <dd>
 This example Explodes the <tt>MyComponent</tt> drawing component instance.
 <pre>
 MyComponent.<font color="red">ExplodeAndSelect</font>
 </pre>
 </dl>
</dl>
<a name="ExposeCompRef"><dt>

<table><tr><td>o Sub <b>ExposeCompRef</b>(<td>)</table></dt>
<dl>
  <dd>
 Exposes the component reference of this drawing component instance in a new detail sheet.
 <!-- @sample -->
 <dl>
 <dt><b>Example:</b>
 <dd>
 This example exposes the component reference of the <tt>MyComponent</tt> drawing
 component instance in a new detail sheet.
 <pre>
 MyComponent.<font color="red">ExposeCompRef</font>
 </pre>
 </dl>
</dl>
<a name="ExposeCompRefInSheet"><dt>

<table><tr><td>o Sub <b>ExposeCompRefInSheet</b>(<td><script type="text/javascript"> activateLink('DrawingSheet','DrawingSheet')</script> <td><tt>iSheet</tt>)</table></dt>
<dl>
  <dd>
 Exposes the component reference of this drawing component instance in a specific detail sheet.
 
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iSheet</tt>
   <dd> The drawing sheet where the reference component has to be exposed.
 This sheet has to be a detail sheet, if not the component reference
 will be placed in a new detail sheet.
 <!-- @sample -->
 <dl>
 <dt><b>Example:</b>
 <dd>
 This example exposes the component reference of the <tt>MyComponent</tt> drawing
 component instance in the <tt>MyDetailSheet</tt> drawing sheet.
 <pre>
 MyComponent.<font color="red">ExposeCompRefInSheet</font> MyDetailSheet
 </pre>
 </dl></dd>
</dl>
</dl>
</dl>
<a name="Flip"><dt>

<table><tr><td>o Sub <b>Flip</b>(<td>)</table></dt>
<dl>
  <dd>
 Flips the drawing component instance around X axis
 To flip around Y axis you have to flip the component around X and to add
 a rotation of 180 degrees.
 <!-- @sample -->
 <dl>
 <dt><b>Example:</b>
 <dd>
 This example Flips the <tt>MyComponent</tt> drawing component instance.
 <pre>
 MyComponent.<font color="red">Flip</font>
 </pre>
 </dl>
</dl>
<a name="GetFlip"><dt>

<table><tr><td>o Func <b>GetFlip</b>(<td>) As <script type="text/javascript"> activateLink('boolean','boolean')</script> </table></dt>
<dl>
  <dd>
 Returns the flip state of a drawing component instance around X axis.
 <!-- @sample -->
 <dl>
 <dt><b>Example:</b>
 <dd>
 This example Get the flip info of the <tt>MyComponent</tt> drawing component instance.
 <pre>
 IsFlipped = MyComponent.<font color="red">GetFlip</font>
 </pre>
 </dl>
</dl>
<a name="GetMatrix"><dt>

<table><tr><td>o Sub <b>GetMatrix</b>(<td><script type="text/javascript"> activateLink('CATSafeArrayVariant','CATSafeArrayVariant')</script> <td><tt>ioMatrix</tt>)</table></dt>
<dl>
  <dd>
 Gets the matrix of the drawing component instance.
 This matrix enables you to define the position (index 4 and 5 of the matrix)
 and the scale, the angle and the flip (index 0,1,2 and 3)
 of the drawing component instance at the same time.
 
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> ioMatrix[0]</tt>
   <dd> The 1st coordinate of the first vector
 </dd>
    <dt><tt> ioMatrix[1]</tt>
   <dd> The 2nd coordinate of the first vector
 </dd>
    <dt><tt> ioMatrix[2]</tt>
   <dd> The 1st coordinate of the second vector
 </dd>
    <dt><tt> ioMatrix[3]</tt>
   <dd> The 2nd coordinate of the second vector
 </dd>
    <dt><tt> ioMatrix[4]</tt>
   <dd> The x value of the translation vector
 </dd>
    <dt><tt> ioMatrix[5]</tt>
   <dd> The y value of the translation vector</dd>
</dl>
</dl>
</dl>
<a name="GetModifiableObject"><dt>

<table><tr><td>o Func <b>GetModifiableObject</b>(<td><script type="text/javascript"> activateLink('CATVariant','CATVariant')</script> <td><tt>iIndex</tt>) As <script type="text/javascript"> activateLink('AnyObject','AnyObject')</script> </table></dt>
<dl>
  <dd>
 Gets a modifiable object by index or name in this drawing component instance.
 <!-- @sample -->
 <dl>
 <dt><b>Example:</b>
 <dd>
 This example Gets the first modifiable object in the <tt>MyComponent</tt> drawing 
 component instance.
 <pre>
 Object = MyComponent.<font color="red">GetModifiableObject</font>(1)
 </pre>
 </dl>
</dl>
<a name="GetModifiableObjectsCount"><dt>

<table><tr><td>o Func <b>GetModifiableObjectsCount</b>(<td>) As <script type="text/javascript"> activateLink('long','long')</script> </table></dt>
<dl>
  <dd>
 Gets the number of modifiable objects in this drawing component instance.
 <!-- @sample -->
 <dl>
 <dt><b>Example:</b>
 <dd>
 This example Gets the number of modifiable objects in <tt>MyComponent</tt> drawing 
 component instance.
 <pre>
 Count = MyComponent.<font color="red">GetModifiableObjectsCount</font>
 </pre>
 </dl>
</dl>
<a name="SetMatrix"><dt>

<table><tr><td>o Sub <b>SetMatrix</b>(<td><script type="text/javascript"> activateLink('CATSafeArrayVariant','CATSafeArrayVariant')</script> <td><tt>iMatrix</tt>)</table></dt>
<dl>
  <dd>
 Sets the matrix of the drawing component instance.
 This matrix enables you to define the position (index 4 and 5 of the matrix)
 and the scale, the angle and the flip (index 0,1,2 and 3)
 of the drawing component instance at the same time.
 
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> ioMatrix[0]</tt>
   <dd> The 1st coordinate of the first vector
 </dd>
    <dt><tt> ioMatrix[1]</tt>
   <dd> The 2nd coordinate of the first vector
 </dd>
    <dt><tt> ioMatrix[2]</tt>
   <dd> The 1st coordinate of the second vector
 </dd>
    <dt><tt> ioMatrix[3]</tt>
   <dd> The 2nd coordinate of the second vector
 </dd>
    <dt><tt> ioMatrix[4]</tt>
   <dd> The x value of the translation vector
 </dd>
    <dt><tt> ioMatrix[5]</tt>
   <dd> The y value of the translation vector</dd>
</dl>
</dl>
</dl>

</body>
<hr><p><i>
Copyright &#169; 1999-2011, Dassault Syst&#232;mes. All rights reserved.</i></p>
</html>
