<html>

<head>
<meta http-equiv="Content-Language" content="en-us">
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<meta name="GENERATOR" content="Microsoft FrontPage 4.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
<title>Instantiating a Ditto in a Drawing View from Another Drawing Document</title>
<link rel="stylesheet" type="text/css" href="../CAAScrBase/caav5.css">
<script language="JavaScript" src="../CAAScrJavaScript/submit.js">
 </script>
</head>

<body>

<table border="0" width="100%">
  <tr>
    <td>
      <h2>Interactive Drafting</h2>
    </td>
    <td align="right" valign="top">
      <h2><a name="Top"></a>Instantiating a Ditto in a Drawing View from Another
      Drawing Document</h2>
    </td>
  </tr>
</table>
<hr>
<table border="0" width="100%" style="border-collapse: collapse" bordercolor="#111111" cellpadding="5" cellspacing="0">
  <tr>
    <td width="4%" valign="top"><img border="0" src="../CAAScrBase/images/atarget.gif" width="32" height="32"></td>
    <td width="96%">This macro shows you how to instantiate a ditto into a view
      from an existing ditto in another drawing document, offers to user to
      define the ditto location and defines the ditto's modifiable text value.
      This macro open the drawing document source containing the ditto and the
      drawing document target an the detail view. To instantiate the ditto we
      use the copy/paste mechanism because it is not possible interactively or
      using automation to create a ditto from a detail view in another document.</td>
  </tr>
  <tr>
    <td width="4%" valign="top"><img border="0" src="../CAAScrBase/images/ainfo.gif" width="32" height="32"></td>
    <td width="96%"><a name="How"></a>&nbsp;CAADriInstantiateOuterDitto is
      launched in CATIA [<a href="#References">1</a>]. No open document is
      needed.<!--------------------------------------comment--------------------->
      <p><a href="CAADriInstantiateOuterDittoSource.htm">CAADriInstantiateOuterDitto</a>
      is located in the CAADriUseCases module.&nbsp; <a href="macros/CAADriInstantiateOuterDitto.CATScript">Execute
      macro</a> (Windows only).</td>
  </tr>
  <tr>
    <td width="4%" valign="top"><img border="0" src="../CAAScrBase/images/ascenari.gif" width="32" height="32"></td>
    <td width="96%"><a name="Step"></a>CAADriInstantiateOuterDitto includes nine
      steps:
      <ol>
        <li><a href="#Step1">Prolog</a></li>
        <li><a href="#Step2">Opening the Drawing Document Source</a></li>
        <li><a href="#Step3">Retrieving and Defining the Ditto</a></li>
        <li><a href="#Step4">Copying the Ditto</a></li>
        <li><a href="#Step5">Opening the Drawing Document Target</a></li>
        <li><a href="#Step6">Retrieving and Defining the View</a></li>
        <li><a href="#Step7">Defining the Ditto's Location</a></li>
        <li><a href="#Step8">Pasting the Ditto</a></li>
        <li><a href="#Step9">Retrieving the Instantiated Ditto and Defining its
          Location</a></li>
        <li><a href="#step10">Retrieving the Ditto's Modifiable Text</a></li>
      </ol>
      <h4><a name="Step1"></a>Prolog</h4>
      <table class="code">
        <tr>
          <td>
            <pre>  ...
    <font color="#008000">' Set the CATIA popup file alerts to False</font>
    <font color="#008000">' It prevents to stop the macro at each alert during its execution</font>
    CATIA.DisplayFileAlerts = False
  ...</pre>
          </td>
        </tr>
      </table>
      <p>The CATIA prompts are disabled thanks to the <code>DisplayFileAlerts</code>
      property of the <i>Application</i> object set to <code>False</code>.</p>
      <h4><a name="Step2"></a>Opening the Drawing Document Source</h4>
      <table class="code">
        <tr>
          <td>
            <pre>  ...
    <font color="#008000">' Open the drawing document containing the existing ditto</font>
<font color="#0000FF">    Dim </font>oDrawingSource<font color="#0000FF"> As </font>DrawingDocument
<font color="#0000FF">    Set </font>oDrawingSource = CATIA.Documents.Open(sDocPath &amp; _
             &quot;\online\CAAScdDriUseCases\samples\CAADriInstantiateDittoSource.CATDrawing&quot;)
  ...</pre>
          </td>
        </tr>
      </table>
      <p>A drawing document is opened.</p>
      <h4><a name="Step3"></a>Retrieving and Defining the Ditto</h4>
      <table class="code">
        <tr>
          <td>
            <pre>  ...
    <font color="#008000">' Retrieve the sheet containing the ditto to be copied</font>
<font color="#0000FF">    Dim </font>oSheetSource<font color="#0000FF"> As </font>DrawingSheet
<font color="#0000FF">    Set </font>oSheetSource = oDrawingSource.Sheets.Item(&quot;Sheet.3&quot;)
    
    <font color="#008000">' Retrieve the view containing the ditto to be copied</font>
<font color="#0000FF">    Dim </font>oViewSource<font color="#0000FF"> As </font>DrawingView
<font color="#0000FF">    Set </font>oViewSource = oSheetSource.Views.Item(&quot;View.1&quot;)
    
    <font color="#008000">' Retrieve the ditto</font>
<font color="#0000FF">    Dim </font>oDitto<font color="#0000FF"> As </font>DrawingComponent
<font color="#0000FF">    Set </font>oDi<font color="#0000FF">tto </font>= oViewSource.Components.Item(1)
  ...</pre>
          </td>
        </tr>
      </table>
      <p>The sheets collection is retrieved from the <code>oDrawingSource</code>
      object using the <code>Sheets</code> method.<br>
      The sheet object is retrieved from the collection using the <code>Item</code>
      method from its name.<br>
      The views collection is retrieved from the <code>oSheetSource</code>
      object using the <code>Views</code> method.<br>
      The view object is retrieved from the collection using the <code>Item</code>
      method from its name.<br>
      The components collection is retrieved from the <code>oViewSource</code>
      object using the <code>Components</code> method.<br>
      The component object is retrieved from the collection using the <code>Item</code>
      method from its index.</p>
      <h4><a name="Step4"></a>Copying the Ditto</h4>
      <table class="code">
        <tr>
          <td>
            <pre>  ...
    <font color="#008000">' Create an object of selection for the source document</font>
<font color="#0000FF">    Dim </font>oSelectionSource<font color="#0000FF"> As </font>Selection
<font color="#0000FF">    Set </font>oSelectionSource = oDrawingSource.Selection
    
    <font color="#008000">' Clear the selection</font>
    oSelectionSource.Clear
    <font color="#008000">' Add the ditto to be duplicated in the selection</font>
    oSelectionSource.Add oDitto
    <font color="#008000">' Copy the view</font>
    oSelectionSource.Copy
    <font color="#008000">' Clear the selection</font>
    oSelectionSource.Clear
  ...</pre>
          </td>
        </tr>
      </table>
      <p>The selection object is retrieved from the <code>oDrawingSource</code>
      object using the <code>Selection</code> method.<br>
      The selection object is cleared using the <code>Clear</code> method to
      remove pre-selecting objects if exist.<br>
      The component object is added to the selection object using the <code>Add</code>
      method.<br>
      The view object is copied to the clipboard from the selection object using
      the <code>Copy</code> method.<br>
      The selection object is cleared using the <code>Clear</code> method
      another time.</p>
      <h4><a name="Step5"></a>Opening the Drawing Document Target</h4>
      <table class="code">
        <tr>
          <td>
            <pre>  ...
    <font color="#008000">' Open the drawing document where the ditto will be instantiated</font>
<font color="#0000FF">    Dim </font>oDrawingTarget<font color="#0000FF"> As </font>DrawingDocument
<font color="#0000FF">    Set </font>oDrawingTarget<font color="#0000FF"> </font>= CATIA.Documents.Open(sDocPath &amp; _
             &quot;\online\CAADriScriptUseCases\samples\CAADriInstantiateDittoTarget.CATDrawing&quot;)
    CATIA.ActiveWindow.ActiveViewer.Reframe
  ...</pre>
          </td>
        </tr>
      </table>
      <p>A drawing document is opened, its window is reframed according to the
      size of the sheet.</p>
      <h4><a name="Step6"></a>Retrieving and Defining the View</h4>
      <table class="code">
        <tr>
          <td>
            <pre>  ...
    <font color="#008000">' Retrieve the sheet where the ditto will be instantiated</font>
<font color="#0000FF">    Dim </font>oSheetTarget<font color="#0000FF"> As </font>DrawingSheet
<font color="#0000FF">    Set </font>oSheetTarget = oDrawingTarget.Sheets.Item(&quot;Sheet.1&quot;)
    oSheetTarget.Activate

    <font color="#008000">' Retrieve the view where the ditto will be instantiated</font>
<font color="#0000FF">    Dim </font>oViewTarget<font color="#0000FF"> As </font>DrawingView
<font color="#0000FF">    Set </font>oViewTarget = oSheetTarget.Views.Item(&quot;View.3&quot;)
  ...</pre>
          </td>
        </tr>
      </table>
      <p>The sheets collection is retrieved from the <code>oDrawingTarget</code>
      object using the <code>Sheets</code> method.<br>
      The sheet object is retrieved from the collection using the <code>Item</code>
      method from its name.<br>
      The views collection is retrieved from the <code>oSheetTarget</code>
      object using the <code>Views</code> method.<br>
      The view object is retrieved from the collection using the <code>Item</code>
      method from its name.<br>
      The sheet is activated.</p>
      <h4><a name="Step7"></a>Defining the Ditto's Location</h4>
      <p>The ditto's location is retrieved using the <code>Indicate2D</code>
      method which allow user to retrieve the <code>x</code> and <code>y</code>
      coordinates when clicking the mouse. Coordinates are stored&nbsp; in an
      array <code>iDittoCoordinates</code>. An unspecified object <code>oDraw</code>
      is used to prevent a signature's method restriction usage.</p>
      <p><img border="1" src="images/img018.gif" hspace="40" width="524" height="383"></p>
      <h4><a name="Step8"></a>Pasting the Ditto</h4>
      <table class="code">
        <tr>
          <td>
            <pre>  ...
    <font color="#008000">' Create an object of selection for the target document</font>
<font color="#0000FF">    Dim </font>oSelectionTarget<font color="#0000FF"> As </font>Selection
<font color="#0000FF">    Set </font>oSelectionTarget = oDrawingTarget.Selection
    
    <font color="#008000">' Clear the selection</font>
    oSelectionTarget.Clear
    <font color="#008000">' Add the view in the selection, where the ditto will be instantiated</font>
    oSelectionTarget.Add oViewTarget
    <font color="#008000">' Paste the clipboard</font>
    oSelectionTarget.Paste
    <font color="#008000">' Clear the selection</font>
    oSelectionTarget.Clear
  ...</pre>
          </td>
        </tr>
      </table>
      <p>The selection object is retrieved from the <code>oDrawingTarget</code>
      object using the <code>Selection</code> method.<br>
      The selection object is cleared using the <code>Clear</code> method to
      remove pre-selecting objects if exist.<br>
      The sheet object is added to the selection object using the <code>Add</code>
      method.<br>
      The view is pasted from the clipboard into the sheet from the selection
      object using the <code>Paste</code> method.<br>
      The selection object is cleared using the <code>Clear</code> method
      another time.</p>
      <h4><a name="Step9"></a>Retrieving the Instantiated Ditto and Defining its
      Location</h4>
      <table class="code">
        <tr>
          <td>
            <pre>  ...
    <font color="#008000">' Retrieve the drawing components collection of the target drawing view</font>
<font color="#0000FF">    Dim </font>o2DComponents<font color="#0000FF"> As </font>DrawingComponents
<font color="#0000FF">    Set </font>o2DComponents = oViewTarget.Components
    
    <font color="#008000">' Retrieve the ditto and define its location</font>
<font color="#0000FF">    Dim </font>o2DComponent<font color="#0000FF"> As </font>DrawingComponent
<font color="#0000FF">    Set </font>o2DComponent = o2DComponents.Item(&quot;DrwDetail.1&quot;)
    o2DComponent.X = iDittoCoordinates(0)
    o2DComponent.Y = iDittoCoordinates(1)
  ...</pre>
          </td>
        </tr>
      </table>
      <p><img border="1" src="images/img019.gif" hspace="40" width="524" height="383"></p>
      <h4><a name="step10"></a>Retrieving the Ditto's Modifiable Text</h4>
      <table class="code">
        <tr>
          <td>
            <pre>  ...
    <font color="#008000">' Retrieve the modifiable text of the ditto</font>
<font color="#0000FF">    Dim </font>oText<font color="#0000FF"> As </font>DrawingText
<font color="#0000FF">    Set </font>oText = o2DComponent.GetModifiableObject(1)
    
    <font color="#008000">' Modify the modifiable text value</font>
<font color="#0000FF">    Dim </font>ReturnValue<font color="#0000FF"> As </font>String
    ReturnValue = InputBox(&quot;Enter a value&quot;, &quot;&quot;, &quot;New Value For Text&quot;)
    oText.Text = ReturnValue
  ...</pre>
          </td>
        </tr>
      </table>
      <p>The text object is retrieved from the <code>o2DComponent</code> object
      using the <code>GetModifiableObject</code> method.<br>
      The text of the text object is returned using the <code>InputBox</code>
      procedure. Enter 10 and click OK.</p>
      <p><img border="0" src="images/img016.gif" hspace="40" width="363" height="145"></p>
      <p><img border="1" src="images/img020.gif" hspace="40" width="524" height="383"></p>
    </td>
  </tr>
</table>
<p align="center"><img border="0" src="../CAAScrBase/images/aendtask.gif" width="64" height="32"></p>
<p align="right">[<a href="#Top">Top</a>]</p>
<hr>
<!--------------------------------------comment--------------------->
<h4><a name="InShort"></a>In Short</h4>
<p>This use case has shown how to instantiate a drawing detail view as a ditto
in a view using the <i>Add </i>method of the <i>Components</i> object.</p>
<p align="right">[<a href="#Top">Top</a>]</p>
<hr>
<!--------------------------------------comment--------------------->
<h4><a name="References"></a>References</h4>
<table border="0" width="100%">
  <tr>
    <td valign="top">[1]</td>
    <td><a href="../CAAScdInfUseCases/CAAInfLauchMacro.htm">Replaying
      a Macro</a></td>
  </tr>
  <tr>
    <td valign="top">[2]</td>
    <td><i><a href="../CAAScdDriTechArticles/CAADriObjDrawingDocument.htm">DrawingDocument</a></i>,
      <i><a href="../CAAScdDriTechArticles/CAADriObjDrawingSheet.htm">DrawingSheet</a>,</i>
      <a href="../CAAScdDriTechArticles/CAADriObjDrawingSheets.htm"><i>DrawingSheets</i></a><i>,
      </i><a href="../CAAScdDriTechArticles/CAADriObjDrawingView.htm"><i>DrawingView</i></a></td>
  </tr>
  <tr>
    <td colspan="2" align="right" width="100%">[<a href="#Top">Top</a>]</td>
  </tr>
</table>
<hr>
<!--------------------------------------comment--------------------->
<p><i>Copyright © 2003, Dassault Systèmes. All rights reserved.</i>

</body>

</html>
