<html><head><meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"><title>CAADriDetailSheet.CATScript</title><link rel="stylesheet" type="text/css" href="../CAAScrBase/caav5.css"></head><body><pre>
<font color="#0000FF">Option Explicit</font>
<font color="#008000">' COPYRIGHT DASSAULT SYSTEMES 2001</font>

<font color="#008000">' ***********************************************************************</font>
<font color="#008000">'   Purpose:      Creates constraints between assembly Parts using Publications</font>
<font color="#008000">'   Assumptions:   Looks for CAADriDetailSheet.CATDrawing in the DocView   </font>
<font color="#008000">'   Author: </font>
<font color="#008000">'   Languages:    VBScript</font>
<font color="#008000">'   Locales:      English </font>
<font color="#008000">'   CATIA Level:  V5R7 </font>
<font color="#008000">' ***********************************************************************</font>


<font color="#0000FF">Sub </font>CATMain()


    <font color="#008000">' ----------------------------------------------------------- </font>
    <font color="#008000">' Optional: allows to find the sample wherever it's installed</font>
<font color="#0000FF">    dim </font>sDocPath<font color="#0000FF"> As </font>String 
    sDocPath=CATIA.SystemService.Environ(&quot;CATDocView&quot;)
<font color="#0000FF">    If </font>(Not CATIA.FileSystem.FolderExists(sDocPath))<font color="#0000FF"> Then</font>
      Err.Raise 9999,,&quot;No Doc Path Defined&quot;
<font color="#0000FF">    End If</font>
    <font color="#008000">' ----------------------------------------------------------- </font>

    <font color="#008000">' Open the Drawing document </font>
<font color="#0000FF">    Dim </font>oDoc<font color="#0000FF"> As </font>Document
<font color="#0000FF">    set </font>oDoc = CATIA.Documents.Open(sDocPath &amp; _
                 &quot;\online\CAAScdDriUseCases\samples\CAADriDetailSheet.CATDrawing&quot;)


<font color="#008000">' ------------</font>
<font color="#008000">' Get the sheets collection of the drawing</font>
<font color="#008000">' ------------</font>
<font color="#0000FF">Dim </font>oDrawingSheets<font color="#0000FF"> As </font>DrawingSheets
<font color="#0000FF">Set </font>oDrawingSheets = oDoc.Sheets

<font color="#008000">' ------------</font>
<font color="#008000">' Add the detail sheet with a default name to the sheets collection of the drawing</font>
<font color="#008000">' ------------</font>
MsgBox &quot;Click OK to create the new sheet.&quot;
<font color="#0000FF">Dim </font>oDrawingSheet<font color="#0000FF"> As </font>DrawingSheet
<font color="#0000FF">Set </font>oDrawingSheet = oDrawingSheets.AddDetail(&quot;New Detail Sheet&quot;) 

<font color="#008000">' ------------</font>
<font color="#008000">' Activate the detail sheet</font>
<font color="#008000">' ------------</font>
MsgBox &quot;Click OK to activate the new detail sheet.&quot;
oDrawingSheet.Activate 

<font color="#0000FF">End Sub</font>
</pre></body></html>


