<html><head><meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"><title>CAADriCreateView.CATScript</title><link rel="stylesheet" type="text/css" href="../CAAScrBase/caav5.css"></head><body><pre>
<font color="#0000FF">Option Explicit</font>
<font color="#008000">' COPYRIGTH DASSAULT SYSTEMES 2000</font>

<font color="#008000">' ***********************************************************************</font>
<font color="#008000">'   Purpose:      Create A Drawing document with a front view and a projection view</font>
<font color="#008000">'   Assumtions:   Looks for MyPart.CATPart in the DocView   </font>
<font color="#008000">'   Author: </font>
<font color="#008000">'   Languages:    VBScript</font>
<font color="#008000">'   Locales:      English </font>
<font color="#008000">'   CATIA Level:  V5R6 </font>
<font color="#008000">' ***********************************************************************</font>


<font color="#0000FF">Sub </font>CATMain()


    <font color="#008000">' ----------------------------------------------------------- </font>
    <font color="#008000">' Optional: allows to find the sample wherever it's installed</font>
<font color="#0000FF">    dim </font>sDocPath<font color="#0000FF"> As </font>String 
    sDocPath=CATIA.SystemService.Environ("CATDocView")
<font color="#0000FF">    If </font>(Not CATIA.FileSystem.FolderExists(sDocPath))<font color="#0000FF"> Then</font>
      Err.Raise 9999,,"No Doc Path Defined"
<font color="#0000FF">    End If</font>
    <font color="#008000">' ----------------------------------------------------------- </font>

    <font color="#008000">' Open the Part document </font>
<font color="#0000FF">    Dim </font>oPartToDraw<font color="#0000FF"> As </font>PartDocument
<font color="#0000FF">    Set </font>oPartToDraw = CATIA.Documents.Open(sDocPath & _
             "\online\CAAScdDriUseCases\samples\Cube.CATPart")

    <font color="#008000">' Create a drawing document: it becomes the active document.</font>
<font color="#0000FF">    Dim </font>oDrawing<font color="#0000FF"> As </font>DrawingDocument
<font color="#0000FF">    Set </font>oDrawing = CATIA.Documents.Add("Drawing")

    <font color="#008000">' Retrieve the active sheet</font>
<font color="#0000FF">    Dim </font>oSheet<font color="#0000FF"> As </font>DrawingSheet
<font color="#0000FF">    Set </font>oSheet = oDrawing.Sheets.ActiveSheet

    <font color="#008000">' Create a view called "Front View" in this sheet</font>
<font color="#0000FF">    Dim </font>oFrontView<font color="#0000FF"> As </font>DrawingView
<font color="#0000FF">    Set </font>oFrontView = oSheet.Views.Add("Front View")

    <font color="#008000">' Retrieve it generative behavior</font>
<font color="#0000FF">    Dim </font>oFrontViewGB<font color="#0000FF"> As </font>DrawingViewGenerativeBehavior
<font color="#0000FF">    Set </font>oFrontViewGB = oFrontView.GenerativeBehavior

    <font color="#008000">' Declare the part to draw in this front view</font>
    oFrontViewGB.Document = oPartToDraw

    <font color="#008000">' Define this view as a front view, with the XY plane (in oPartToDraw) as projection plane </font>
    oFrontViewGB.DefineFrontView 1, 0, 0, 0, 1, 0

    <font color="#008000">' Position the View in the Sheet</font>
    oFrontView.x = 300
    oFrontView.y = 150

    <font color="#008000">' Update the view</font>
    oFrontViewGB.Update 

<font color="#0000FF">End Sub</font>

</pre></body></html>
