<html>

<head>
<meta http-equiv="Content-Language" content="en-us">
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
<meta name="GENERATOR" content="Microsoft FrontPage 4.0">
<meta name="ProgId" content="FrontPage.Editor.Document">
<title>Duplicating a Drawing View</title>
<link rel="stylesheet" type="text/css" href="../CAAScrBase/caav5.css">
 <script language="JavaScript" src="../CAAScrJavaScript/submit.js">
 </script>
</head>

<body>

<table border="0" width="100%">
  <tr>
    <td>
      <h2>Interactive Drafting</h2>
    </td>
    <td align="right" valign="top">
      <h2><a name="Top"></a>Duplicating a Drawing View</h2>
    </td>
  </tr>
</table>
<hr>
 <!--------------------------------------comment------------------------------->
<table border="0" width="100%">
  <tr>
    <td valign="top"><img border="0" src="../CAAScrBase/images/atarget.gif" width="32" height="32"></td>
    <td>This macro shows you how to copy a view in drawing document and paste it
      into another drawing document. The copied view has been generated from a
      part document but isolated, so the pasted view is also isolated. This
      macro open the drawing document containing the view to be copied and
      create a new drawing document containing the view to be pasted.
      <!--------------------------------------comment------------------------------->
    </td>
  </tr>
  <tr>
    <td valign="top"><img border="0" src="../CAAScrBase/images/ainfo.gif" width="32" height="32"></td>
    <td><a name="How"></a>CAADriDuplicateAView is launched in CATIA [<a href="#References">1</a>].
      No open document is needed.
      <p><a href="CAADriDuplicateAViewSource.htm">CAADriDuplicateAView</a> is
      located in the CAADriUseCases module.&nbsp; <a href="macros/CAADriDuplicateAView.CATScript">Execute
      macro</a> (Wndows only).</p>
      <p>&nbsp;</td>
  </tr>
  <tr>
    <td valign="top"><img border="0" src="../CAAScrBase/images/ascenari.gif" width="32" height="32"></td>
    <td><a name="Step"></a>CAADriDuplicateAView includes seven steps:
      <ol>
        <li><a href="#Step1">Prolog</a></li>
        <li><a href="#Step2">Opening and Reframing an Existing Drawing Document</a></li>
        <li><a href="#Step3">Retrieving and Defining the Sheet</a></li>
        <li><a href="#Step4">Retrieving and Defining the View</a></li>
        <li><a href="#Step5">Copying the View</a></li>
        <li><a href="#Step6">Creating the New Drawing Document</a></li>
        <li><a href="#Step7">Pasting the View</a></li>
      </ol>
      <h4><a name="Step1"></a>Prolog</h4>
      <table class="code">
        <tr>
          <td>
            <pre>  ...
    <font color="#008000">' Set the CATIA popup file alerts to False</font>
    <font color="#008000">' It prevents to stop the macro at each alert during its execution</font>
    CATIA.DisplayFileAlerts = False
  ...</pre>
          </td>
        </tr>
      </table>
      <p>The CATIA prompts are disabled thanks to the <code>DisplayFileAlerts</code>
      property of the <i>Application</i> object set to <code>False</code>.</p>
      <h4><a name="Step2"></a>Opening and Reframing an Existing Drawing Document</h4>
      <table class="code">
        <tr>
          <td>
            <pre>  ...
    <font color="#008000">' Open the Drawing document</font>
<font color="#0000FF">    Dim </font>oDrawingSource<font color="#0000FF"> As </font>DrawingDocument
<font color="#0000FF">    Set </font>oDrawingSource = CATIA.Documents.Open(sDocPath &amp; _
             &quot;\online\CAAScdDriUseCases\samples\CAADriDuplicateAView.CATDrawing&quot;)
    
    <font color="#008000">' Fit in window the opened document</font>
    CATIA.ActiveWindow.ActiveViewer.Reframe
  ...</pre>
          </td>
        </tr>
      </table>
      <p>A drawing document is opened, its window is reframed according to the
      size of the sheet.</p>
      <h4><a name="Step3"></a>Retrieving and Defining the Sheet</h4>
      <table class="code">
        <tr>
          <td>
            <pre>  ...
    <font color="#008000">' Retrieve the sheet containing the view to be duplicated</font>
<font color="#0000FF">    Dim </font>oSheetSource<font color="#0000FF"> As </font>DrawingSheet
<font color="#0000FF">    Set </font>oSheetSource = oDrawingSource.Sheets.Item(&quot;Sheet.1&quot;)
  ...</pre>
          </td>
        </tr>
      </table>
      <p>The sheets collection is retrieved from the <code>oDrawingSource</code>
      object using the <code>Sheets</code> method.<br>
      The sheet object is retrieved from the collection using the <code>Item</code>
      method from its name.</p>
      <h4><a name="Step4"></a>Retrieving and Defining the View</h4>
      <table class="code">
        <tr>
          <td>
            <pre>  ...
    <font color="#008000">' Retrieve the view to be duplicated</font>
<font color="#0000FF">    Dim </font>oViewSource<font color="#0000FF"> As </font>DrawingView
<font color="#0000FF">    Set </font>oViewSource = oSheetSource.Views.Item(&quot;Front view&quot;)
  ...</pre>
          </td>
        </tr>
      </table>
      <p>The views collection is retrieved from the <code>oSheetSource</code>
      object using the <code>Views</code> method.<br>
      The view object is retrieved from the collection using the <code>Item</code>
      method from its name.</p>
      <h4><a name="Step5"></a>Copying the View</h4>
      <table class="code">
        <tr>
          <td>
            <pre>  ...
    <font color="#008000">' Create an object of selection for the source document</font>
<font color="#0000FF">    Dim </font>oSelectionSource<font color="#0000FF"> As </font>Selection
<font color="#0000FF">    Set </font>oSelectionSource = oDrawingSource.Selection
    
    <font color="#008000">' Clear the selection</font>
    oSelectionSource.Clear
    <font color="#008000">' Add the view to be duplicated in the selection</font>
    oSelectionSource.Add oViewSource
    <font color="#008000">' Copy the view</font>
    oSelectionSource.Copy
    <font color="#008000">' Clear the selection</font>
    oSelectionSource.Clear
  ...</pre>
          </td>
        </tr>
      </table>
      <p>The selection object is retrieved from the <code>oDrawingSource</code>
      object using the <code>Selection</code> method.<br>
      The selection object is cleared using the <code>Clear</code> method to
      remove pre-selecting objects if exist.<br>
      The view object is added to the selection object using the <code>Add</code>
      method.<br>
      The view object is copied to the clipboard from the selection object using
      the <code>Copy</code> method.<br>
      The selection object is cleared using the <code>Clear</code> method
      another time.</p>
      <h4><a name="Step6"></a>Creating the New Drawing Document</h4>
      <table class="code">
        <tr>
          <td>
            <pre>  ...
    <font color="#008000">' Create the Drawing document where the view will be pasted</font>
<font color="#0000FF">    Dim </font>oDrawingTarget<font color="#0000FF"> As </font>DrawingDocument
<font color="#0000FF">    Set </font>oDrawingTarget = CATIA.Documents.Add(&quot;Drawing&quot;)
    
    <font color="#008000">' Retrieve the where the view will be pasted</font>
<font color="#0000FF">    Dim </font>oSheetTarget<font color="#0000FF"> As </font>DrawingSheet
<font color="#0000FF">    Set </font>oSheetTarget = oDrawingTarget.Sheets.Item(&quot;Sheet.1&quot;)
    
    <font color="#008000">' Set the sheet paper size</font>
    oSheetTarget.PaperSize = catPaperA0
  ...</pre>
          </td>
        </tr>
      </table>
      <p>A new drawing document is created and the sheet object is retrieved,
      the size of its sheet is set to A0.</p>
      <h4><a name="Step7"></a>Pasting the View</h4>
      <table class="code">
        <tr>
          <td>
            <pre>  ...
    <font color="#008000">' Create an object of selection for the source document</font>
<font color="#0000FF">    Dim </font>oSelectionTarget<font color="#0000FF"> As </font>Selection
<font color="#0000FF">    Set </font>oSelectionTarget = oDrawingTarget.Selection
    
    <font color="#008000">' Clear the selection</font>
    oSelectionTarget.Clear
    <font color="#008000">' Add the sheet where the view will be pasted in the selection</font>
    oSelectionTarget.Add oSheetTarget
    <font color="#008000">' Paste the clipboard</font>
    oSelectionTarget.Paste
    <font color="#008000">' Clear the selection</font>
    oSelectionTarget.Clear
  ...</pre>
          </td>
        </tr>
      </table>
      <p>The selection object is retrieved from the <code>oDrawingTarget</code>
      object using the <code>Selection</code> method.<br>
      The selection object is cleared using the <code>Clear</code> method to
      remove pre-selecting objects if exist.<br>
      The sheet object is added to the selection object using the <code>Add</code>
      method.<br>
      The view is pasted from the clipboard into the sheet from the selection
      object using the <code>Paste</code> method.<br>
      The selection object is cleared using the <code>Clear</code> method
      another time.</p>
    </td>
  </tr>
</table>
<p align="center"><img border="0" src="../CAAScrBase/images/aendtask.gif" width="64" height="32"></p>
<p align="right">[<a href="#Top">Top</a>]</p>
<hr>
<!--------------------------------------comment------------------------------->
<h4><a name="InShort"></a>In Short</h4>
<p>This use case has shown how to copy/paste a Drawing view using the <i>Copy </i>and<i>
Paste</i> methods of the <i>Selection</i> object.</p>
<p align="right">[<a href="#Top">Top</a>]</p>
<hr>
<!--------------------------------------comment------------------------------->
<h4><a name="References"></a>References</h4>
<table border="0" width="100%">
  <tr>
    <td valign="top">[1]</td>
    <td><a href="../CAAScdInfUseCases/CAAInfLauchMacro.htm">Replaying
      a Macro</a></td>
  </tr>
  <tr>
    <td valign="top">[2]</td>
    <td><i><a href="../CAAScdDriTechArticles/CAADriObjDrawingDocument.htm">DrawingDocument</a></i>,
      <i><a href="../CAAScdDriTechArticles/CAADriObjDrawingSheet.htm">DrawingSheet</a>,</i>
      <a href="../CAAScdDriTechArticles/CAADriObjDrawingSheets.htm"><i>DrawingSheets</i></a><i>,
      </i><a href="../CAAScdDriTechArticles/CAADriObjDrawingView.htm"><i>DrawingView</i></a></td>
  </tr>
  <tr>
    <td colspan="2" align="right" width="100%">[<a href="#Top">Top</a>]</td>
  </tr>
</table>
<hr>
<!--------------------------------------comment------------------------------->
<p><i>Copyright © 2003, Dassault Systèmes. All rights reserved.</i>

</body>

</html>
