<html>
<head>
 <meta name="Generator" content="mihGene v1.1">
 <meta http-equiv="Expires" content="Tue, 04 Dec 1993 21:29:02 GMT">
 <title>CATGSMIDLItf HybridShapeSpline (Object)</title>
<link rel="Stylesheet" type="text/css" href="../../../caav5.css">
<script language="Javascript" src="../_index/jslink.js"></script> 
<script language="Javascript" src="jsFwLink.js"></script> 
<script language="Javascript" type="text/javascript" src="../_index/jsTree.js"></script>  
</head>
<body>
<pre><a href="../_index/main.htm">All Frameworks</a>  <a href="../_index/tree.htm">Object Hierarchy</a>  <a href="../CATGSMIDLItf.htm">This Framework</a>  <a href="../_index/CAAHomeIdx.htm">Indexes</a>  <script type="text/javascript"> 
 var test=locateObject('HybridShapeSpline','interface','0'); 
 if(test==1){ 
     document.write("<a href=\"#\" onclick=\"openLinkNP('HybridShapeSpline','interface','0');return false\">Previous</a> "); 
 } 
 test=locateObject('HybridShapeSpline','interface','1'); 
 if(test==1){ 
     document.write("<a href=\"#\" onclick=\"openLinkNP('HybridShapeSpline','interface','1');return false\">Next</a> "); 
 } 
 </script> 
</pre>
<hr>
<h1>HybridShapeSpline<font size=-1> (Object)</font></h1>
<script type="text/javascript" > 
 generatedFatherClass('interface_HybridShapeSpline_23314','HybridShapeSpline','0');</script>
<b><i> Represents the hybrid shape spline feature object.</i></b><br>

 <b>Role</b>: To access the data of the hybrid shape spline feature object.
 This data includes:
 <ul>
 <li>The support surface</li>
 <li>The control points</li>
 <li>The tension at each control point</li>
 <li>The curvature radius at each control point</li>
 </ul>
 <p>Use the  CATIAHybridShapeFactory to create a HybridShapeAffinity object.
 <dl>
  <dt> <b>See also:</b> 
  <dd> <a href="#" onClick="openLink('HybridShapeFactory','');return false">HybridShapeFactory</a>
</dl>
<hr>
<dl>
</dl>
<dl>
 <h2><a name="MethodIndex"></a>Method Index</h2>
 <dt>
    <a href="#AddPoint"><b>AddPoint</b></a>
<dd>  Add a new point .
 <dt>
    <a href="#AddPointWithConstraintExplicit"><b>AddPointWithConstraintExplicit</b></a>
<dd>  Add a new point with explicit tangency and curvature.
 <dt>
    <a href="#AddPointWithConstraintFromCurve"><b>AddPointWithConstraintFromCurve</b></a>
<dd>  Add a new point with tangency/curvature from a curve.
 <dt>
    <a href="#GetClosure"><b>GetClosure</b></a>
<dd>  Gets whether the curve is closed.
 <dt>
    <a href="#GetConstraintType"><b>GetConstraintType</b></a>
<dd>  Returns the ControlPoint type  at the given position.
 <dt>
    <a href="#GetCurvatureRadius"><b>GetCurvatureRadius</b></a>
<dd>  Returns the curvature radius value for each point of the spline.
 <dt>
    <a href="#GetDirectionInversion"><b>GetDirectionInversion</b></a>
<dd>  Gets the orientation of the tangent direction .
 <dt>
    <a href="#GetNbControlPoint"><b>GetNbControlPoint</b></a>
<dd>  Returns the number of control points.
 <dt>
    <a href="#GetPoint"><b>GetPoint</b></a>
<dd>  Returns the Point   at the given position.
 <dt>
    <a href="#GetPointConstraintExplicit"><b>GetPointConstraintExplicit</b></a>
<dd>  Returns the Constraint of the point at iPos.
 <dt>
    <a href="#GetPointConstraintFromCurve"><b>GetPointConstraintFromCurve</b></a>
<dd>  Returns the Constraint of the point at iPos.
 <dt>
    <a href="#GetPointPosition"><b>GetPointPosition</b></a>
<dd>  Returns the position of a given point.
 <dt>
    <a href="#GetSplineType"><b>GetSplineType</b></a>
<dd>  Gets the spline type.
 <dt>
    <a href="#GetSupport"><b>GetSupport</b></a>
<dd>  Gets the support surface.
 <dt>
    <a href="#GetTangentNorm"><b>GetTangentNorm</b></a>
<dd>  Returns the tension for each point of the spline.
 <dt>
    <a href="#InvertDirection"><b>InvertDirection</b></a>
<dd>  Inverts the orientation of the tangent direction .
 <dt>
    <a href="#RemoveAll"><b>RemoveAll</b></a>
<dd>  Removes all elements in the list of points.
 <dt>
    <a href="#RemoveControlPoint"><b>RemoveControlPoint</b></a>
<dd>  Removes a point at the given position.
 <dt>
    <a href="#RemoveCurvatureRadiusDirection"><b>RemoveCurvatureRadiusDirection</b></a>
<dd>  Removes Curvature Radius  Direction for the given point of the spline.
 <dt>
    <a href="#RemoveCurvatureRadiusValue"><b>RemoveCurvatureRadiusValue</b></a>
<dd>  Removes Curvature Radius  Value for the given point of the spline.
 <dt>
    <a href="#RemoveSupport"><b>RemoveSupport</b></a>
<dd>  Removes the support surface.
 <dt>
    <a href="#RemoveTangentDirection"><b>RemoveTangentDirection</b></a>
<dd>  Removes tangent Direction for the given point of the spline.
 <dt>
    <a href="#RemoveTension"><b>RemoveTension</b></a>
<dd>  Removes  the Tension for the given point of the spline.
 <dt>
    <a href="#ReplacePointAtPosition"><b>ReplacePointAtPosition</b></a>
<dd>  Replaces a point in the list at the given position.
 <dt>
    <a href="#SetClosing"><b>SetClosing</b></a>
<dd>  Activates the closing option of the spline.
 <dt>
    <a href="#SetPointAfter"><b>SetPointAfter</b></a>
<dd>  Sets the Point After a given position.
 <dt>
    <a href="#SetPointBefore"><b>SetPointBefore</b></a>
<dd>  Sets the Point Before a given position.
 <dt>
    <a href="#SetPointConstraintExplicit"><b>SetPointConstraintExplicit</b></a>
<dd>  Sets the Constraint of the point at iPos.
 <dt>
    <a href="#SetPointConstraintFromCurve"><b>SetPointConstraintFromCurve</b></a>
<dd>  Sets the Constraint of the point at iPos.
 <dt>
    <a href="#SetSplineType"><b>SetSplineType</b></a>
<dd>  Sets the spline type.
 <dt>
    <a href="#SetSupport"><b>SetSupport</b></a>
<dd>  Sets the spline support surface.
</dl>
 <h2><a name="Methods"></a>Methods</h2> <br>
<a name="AddPoint"><dt>

<table><tr><td>o Sub <b>AddPoint</b>(<td><script type="text/javascript"> activateLink('Reference','Reference')</script> <td><tt>ipIAPoint</tt>)</table></dt>
<dl>
  <dd>
 Add a new point .
 
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iPoint</tt>
   <dd>    Point element.</dd>
</dl>
</dl>
</dl>
<a name="AddPointWithConstraintExplicit"><dt>

<table><tr><td>o Sub <b>AddPointWithConstraintExplicit</b>(<td><script type="text/javascript"> activateLink('Reference','Reference')</script> <td><tt>ipIAPoint</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('HybridShapeDirection','HybridShapeDirection')</script> <td><tt>ipIADirTangency</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('double','double')</script> <td><tt>iTangencyNorm</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('long','long')</script> <td><tt>iInverseTangency</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('HybridShapeDirection','HybridShapeDirection')</script> <td><tt>ipIADirCurvature</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('double','double')</script> <td><tt>iCurvatureRadius</tt>)</table></dt>
<dl>
  <dd>
 Add a new point with explicit tangency and curvature. 
 
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> ipIAPoint</tt>
   <dd>    Point element.
 </dd>
    <dt><tt> ipIADirTangency</tt>
   <dd>    Tangent direction.
 </dd>
    <dt><tt> iTangencyNorm</tt>
   <dd>    Tension.
 </dd>
    <dt><tt> iInverseTangency</tt>
   <dd>    Flag to reverse tangent direction (value can be 1 or -1).
 </dd>
    <dt><tt> ipIADirCurvature</tt>
   <dd>    Curvature direction.
 </dd>
    <dt><tt> iCurvatureRadius</tt>
   <dd>    Curvature radius value.</dd>
</dl>
</dl>
</dl>
<a name="AddPointWithConstraintFromCurve"><dt>

<table><tr><td>o Sub <b>AddPointWithConstraintFromCurve</b>(<td><script type="text/javascript"> activateLink('Reference','Reference')</script> <td><tt>ipIAPoint</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('Reference','Reference')</script> <td><tt>ipIACurveCst</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('double','double')</script> <td><tt>iTangencyNorm</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('long','long')</script> <td><tt>iInvertValue</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('long','long')</script> <td><tt>iCrvCstType</tt>)</table></dt>
<dl>
  <dd>
 Add a new point with tangency/curvature from a curve. 
 
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> ipIAPoint</tt>
   <dd>    Point element.
 </dd>
    <dt><tt> ipIACurveCst</tt>
   <dd>   Curvature direction.
 </dd>
    <dt><tt> iTangencyNorm</tt>
   <dd>     tension factor for tangency.
 </dd>
    <dt><tt> iInvertValue</tt>
   <dd>   Orientation for tangent 
 </dd>
    <dt><tt> iCrvCstType</tt>
   <dd>    Continuity type for Curve Constraint (1=Tangency , 2-= Curvature).</dd>
</dl>
</dl>
</dl>
<a name="GetClosure"><dt>

<table><tr><td>o Func <b>GetClosure</b>(<td>) As <script type="text/javascript"> activateLink('long','long')</script> </table></dt>
<dl>
  <dd>
 Gets whether the curve is closed.
   
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> oClosed</tt>
   <dd>       Closing flag
<dl><dt>1</dt><dd> for a closed curve</dd>
    <dt>0</dt><dd> for an open curve</dd>
</dl></dd>
</dl>
</dl>
</dl>
<a name="GetConstraintType"><dt>

<table><tr><td>o Func <b>GetConstraintType</b>(<td><script type="text/javascript"> activateLink('long','long')</script> <td><tt>iPos</tt>) As <script type="text/javascript"> activateLink('long','long')</script> </table></dt>
<dl>
  <dd>
 Returns the ControlPoint type  at the given position. 
 
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iPos</tt>
   <dd>    The poistion of the point to retrieve
 </dd>
    <dt><tt> oCstType</tt>
   <dd>   Type of Control point (CstType=0 : not defined / CstType=1 : Explicit / CstType=2 : FromCurve)</dd>
</dl>
</dl>
</dl>
<a name="GetCurvatureRadius"><dt>

<table><tr><td>o Func <b>GetCurvatureRadius</b>(<td><script type="text/javascript"> activateLink('long','long')</script> <td><tt>iPos</tt>) As <script type="text/javascript"> activateLink('Length','Length')</script> </table></dt>
<dl>
  <dd>
 Returns the curvature radius value for each point of the spline.
 
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iPos</tt>
   <dd>    The position of the point in the spline.
   <br><b>Legal values</b>: first position is 1.
    The position cannot be 0. 
 </dd>
    <dt><tt> oRadius</tt>
   <dd>   The curvature radius value at this point</dd>
</dl>
</dl>
</dl>
<a name="GetDirectionInversion"><dt>

<table><tr><td>o Func <b>GetDirectionInversion</b>(<td><script type="text/javascript"> activateLink('long','long')</script> <td><tt>iPos</tt>) As <script type="text/javascript"> activateLink('long','long')</script> </table></dt>
<dl>
  <dd>
 Gets the orientation of the tangent direction .
   
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> oInvertFlag</tt>
   <dd>      invert flag
    = 1  No Inversion
    = -1 Invert
   </dd>
    <dt><tt> iPos</tt>
   <dd>      Position of point in spline
                   First Position is 1
                   Position 0 return E_FAIL</dd>
</dl>
</dl>
</dl>
<a name="GetNbControlPoint"><dt>

<table><tr><td>o Func <b>GetNbControlPoint</b>(<td>) As <script type="text/javascript"> activateLink('long','long')</script> </table></dt>
<dl>
  <dd>
 Returns the number of control points.
 
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> oNbCtrPt</tt>
   <dd>   The number of control points.</dd>
</dl>
</dl>
</dl>
<a name="GetPoint"><dt>

<table><tr><td>o Func <b>GetPoint</b>(<td><script type="text/javascript"> activateLink('long','long')</script> <td><tt>iPos</tt>) As <script type="text/javascript"> activateLink('Reference','Reference')</script> </table></dt>
<dl>
  <dd>
 Returns the Point   at the given position. 
 
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iPos</tt>
   <dd>    The poistion of the point to retrieve
 </dd>
    <dt><tt> opIAPoint</tt>
   <dd>   Type of Control point (TypeCtrPoint =1 : Explicit / TypeCtrPoint =2 : FromCurve)</dd>
</dl>
</dl>
</dl>
<a name="GetPointConstraintExplicit"><dt>

<table><tr><td>o Sub <b>GetPointConstraintExplicit</b>(<td><script type="text/javascript"> activateLink('long','long')</script> <td><tt>iPos</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('HybridShapeDirection','HybridShapeDirection')</script> <td><tt>opIADirTangency</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('double','double')</script> <td><tt>oTangencyNorm</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('long','long')</script> <td><tt>oInverseTangency</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('HybridShapeDirection','HybridShapeDirection')</script> <td><tt>opIADirCurvature</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('double','double')</script> <td><tt>oCurvatureRadius</tt>)</table></dt>
<dl>
  <dd>
 Returns the Constraint of the point at iPos.
<br> Available for Explicit Point Constraint type (CstType =1 from GetContraintType)
 
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iPos</tt>
   <dd>    The position of the point to retrieve
 </dd>
    <dt><tt> opIADirTangency</tt>
   <dd>    Tangent direction.
 </dd>
    <dt><tt> oTangencyNorm</tt>
   <dd>    Tension.
 </dd>
    <dt><tt> oInverseTangency</tt>
   <dd>    Flag to reverse tangent direction (value can be 1 or -1).
 </dd>
    <dt><tt> opIADirCurvature</tt>
   <dd>    Curvature direction.
 </dd>
    <dt><tt> oCurvatureRadius</tt>
   <dd>    Curvature radius value.</dd>
</dl>
</dl>
</dl>
<a name="GetPointConstraintFromCurve"><dt>

<table><tr><td>o Sub <b>GetPointConstraintFromCurve</b>(<td><script type="text/javascript"> activateLink('long','long')</script> <td><tt>iPos</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('Reference','Reference')</script> <td><tt>opIACurveCst</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('double','double')</script> <td><tt>oTangencyNorm</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('long','long')</script> <td><tt>oInvertValue</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('long','long')</script> <td><tt>oCrvCstType</tt>)</table></dt>
<dl>
  <dd>
 Returns the Constraint of the point at iPos.
<br> Available for FromCurve Point Constraint type (CstType =2 from GetContraintType)
 
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iPos</tt>
   <dd>    The position of the point to retrieve
 </dd>
    <dt><tt> opIACurveCst</tt>
   <dd>   Curvature direction.
 </dd>
    <dt><tt> oTangencyNorm</tt>
   <dd>     tension factor for tangency.
 </dd>
    <dt><tt> oInvertValue</tt>
   <dd>   Orientation for tangent 
 </dd>
    <dt><tt> oCrvCstType</tt>
   <dd>    Continuity type for Curve Constraint (1=Tangency , 2-= Curvature).</dd>
</dl>
</dl>
</dl>
<a name="GetPointPosition"><dt>

<table><tr><td>o Func <b>GetPointPosition</b>(<td><script type="text/javascript"> activateLink('Reference','Reference')</script> <td><tt>ipIAPoint</tt>) As <script type="text/javascript"> activateLink('long','long')</script> </table></dt>
<dl>
  <dd>
 Returns the position of a given point. 
 
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> ipIAPoint</tt>
   <dd>   Point 
 </dd>
    <dt><tt> oPos</tt>
   <dd>    The position of the point (=0 Point Not in Spline)</dd>
</dl>
</dl>
</dl>
<a name="GetSplineType"><dt>

<table><tr><td>o Func <b>GetSplineType</b>(<td>) As <script type="text/javascript"> activateLink('long','long')</script> </table></dt>
<dl>
  <dd>
 Gets the spline type.
   
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> oType</tt>
   <dd> = 0 : Cubic Type Spline.                = 1 : WilsonFowler Type Spline.</dd>
</dl>
</dl>
</dl>
<a name="GetSupport"><dt>

<table><tr><td>o Func <b>GetSupport</b>(<td>) As <script type="text/javascript"> activateLink('Reference','Reference')</script> </table></dt>
<dl>
  <dd>
 Gets the support surface.
   
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> oSupport</tt>
   <dd>      Supporting surface for spline (if exist)</dd>
</dl>
</dl>
</dl>
<a name="GetTangentNorm"><dt>

<table><tr><td>o Func <b>GetTangentNorm</b>(<td><script type="text/javascript"> activateLink('long','long')</script> <td><tt>iPos</tt>) As <script type="text/javascript"> activateLink('RealParam','RealParam')</script> </table></dt>
<dl>
  <dd>
 Returns the tension for each point of the spline.
 <br>The tension is the tangent norm at the given point.
 
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iPos</tt>
   <dd>    The position of the point in the spline.
   <br><b>Legal values</b>: first position is 1.
    The position cannot be 0. 
 </dd>
    <dt><tt> oTension</tt>
   <dd>    The tension at this point</dd>
</dl>
</dl>
</dl>
<a name="InvertDirection"><dt>

<table><tr><td>o Sub <b>InvertDirection</b>(<td><script type="text/javascript"> activateLink('long','long')</script> <td><tt>iPos</tt>)</table></dt>
<dl>
  <dd>
 Inverts the orientation of the tangent direction .
   
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iPos</tt>
   <dd>      Position of point in spline
                   First Position is 1
                   Position 0 return E_FAIL</dd>
</dl>
</dl>
</dl>
<a name="RemoveAll"><dt>

<table><tr><td>o Sub <b>RemoveAll</b>(<td>)</table></dt>
<dl>
  <dd>
 Removes all elements in the list of points.
</dl>
<a name="RemoveControlPoint"><dt>

<table><tr><td>o Sub <b>RemoveControlPoint</b>(<td><script type="text/javascript"> activateLink('long','long')</script> <td><tt>iPos</tt>)</table></dt>
<dl>
  <dd>
 Removes a point at the given position.
 
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iPos</tt>
   <dd>    The position of the point to remove</dd>
</dl>
</dl>
</dl>
<a name="RemoveCurvatureRadiusDirection"><dt>

<table><tr><td>o Sub <b>RemoveCurvatureRadiusDirection</b>(<td><script type="text/javascript"> activateLink('long','long')</script> <td><tt>iPos</tt>)</table></dt>
<dl>
  <dd>
 Removes Curvature Radius  Direction for the given point of the spline.
   
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iPos</tt>
   <dd>      Position of point in spline
                   First Position is 1
                   Position 0 return E_FAIL</dd>
</dl>
</dl>
</dl>
<a name="RemoveCurvatureRadiusValue"><dt>

<table><tr><td>o Sub <b>RemoveCurvatureRadiusValue</b>(<td><script type="text/javascript"> activateLink('long','long')</script> <td><tt>iPos</tt>)</table></dt>
<dl>
  <dd>
 Removes Curvature Radius  Value for the given point of the spline.
   
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iPos</tt>
   <dd>      Position of point in spline
                   First Position is 1
                   Position 0 return E_FAIL</dd>
</dl>
</dl>
</dl>
<a name="RemoveSupport"><dt>

<table><tr><td>o Sub <b>RemoveSupport</b>(<td>)</table></dt>
<dl>
  <dd>
 Removes the support surface.
</dl>
<a name="RemoveTangentDirection"><dt>

<table><tr><td>o Sub <b>RemoveTangentDirection</b>(<td><script type="text/javascript"> activateLink('long','long')</script> <td><tt>iPos</tt>)</table></dt>
<dl>
  <dd>
 Removes tangent Direction for the given point of the spline.
   
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iPos</tt>
   <dd>      Position of point in spline
                   First Position is 1
                   Position 0 return E_FAIL</dd>
</dl>
</dl>
</dl>
<a name="RemoveTension"><dt>

<table><tr><td>o Sub <b>RemoveTension</b>(<td><script type="text/javascript"> activateLink('long','long')</script> <td><tt>iPos</tt>)</table></dt>
<dl>
  <dd>
 Removes  the Tension for the given point of the spline.
   
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iPos</tt>
   <dd>      Position of point in spline
                   First Position is 1
                   Position 0 return E_FAIL</dd>
</dl>
</dl>
</dl>
<a name="ReplacePointAtPosition"><dt>

<table><tr><td>o Sub <b>ReplacePointAtPosition</b>(<td><script type="text/javascript"> activateLink('long','long')</script> <td><tt>iPos</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('Reference','Reference')</script> <td><tt>iPoint</tt>)</table></dt>
<dl>
  <dd>
 Replaces a point in the list at the given position.
   
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> oPoint</tt>
   <dd>      Point
   </dd>
    <dt><tt> iPos</tt>
   <dd>      Replace position</dd>
</dl>
</dl>
</dl>
<a name="SetClosing"><dt>

<table><tr><td>o Sub <b>SetClosing</b>(<td><script type="text/javascript"> activateLink('long','long')</script> <td><tt>iClosingType</tt>)</table></dt>
<dl>
  <dd>
 Activates the closing option of the spline.
 
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iClosingType</tt>
   <dd>    The spline closing option</dd>
</dl>
</dl>
</dl>
<a name="SetPointAfter"><dt>

<table><tr><td>o Sub <b>SetPointAfter</b>(<td><script type="text/javascript"> activateLink('long','long')</script> <td><tt>iPos</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('Reference','Reference')</script> <td><tt>ipIAPoint</tt>)</table></dt>
<dl>
  <dd>
 Sets the Point After a given position. 
 
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iPos</tt>
   <dd>    The position reference (0 < position < Nbpt)
 </dd>
    <dt><tt> ipIAPoint</tt>
   <dd>   Point</dd>
</dl>
</dl>
</dl>
<a name="SetPointBefore"><dt>

<table><tr><td>o Sub <b>SetPointBefore</b>(<td><script type="text/javascript"> activateLink('long','long')</script> <td><tt>iPos</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('Reference','Reference')</script> <td><tt>ipIAPoint</tt>)</table></dt>
<dl>
  <dd>
 Sets the Point Before a given position. 
 
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iPos</tt>
   <dd>    The position reference (1 < position < Nbpt+1) 
 </dd>
    <dt><tt> ipIAPoint</tt>
   <dd>   Point</dd>
</dl>
</dl>
</dl>
<a name="SetPointConstraintExplicit"><dt>

<table><tr><td>o Sub <b>SetPointConstraintExplicit</b>(<td><script type="text/javascript"> activateLink('long','long')</script> <td><tt>iPos</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('HybridShapeDirection','HybridShapeDirection')</script> <td><tt>ipIADirTangency</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('double','double')</script> <td><tt>iTangencyNorm</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('long','long')</script> <td><tt>iInverseTangency</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('HybridShapeDirection','HybridShapeDirection')</script> <td><tt>ipIADirCurvature</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('double','double')</script> <td><tt>iCurvatureRadius</tt>)</table></dt>
<dl>
  <dd>
 Sets the Constraint of the point at iPos.
<br> Available for Explicit  Point Constraint type (CstType =1 from GetContraintType)
 
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iPos</tt>
   <dd>    The position of the point to retrieve
 </dd>
    <dt><tt> ipIADirTangency</tt>
   <dd>    Tangent direction.
 </dd>
    <dt><tt> iTangencyNorm</tt>
   <dd>    Tension.
 </dd>
    <dt><tt> iInverseTangency</tt>
   <dd>    Flag to reverse tangent direction (value can be 1 or -1).
 </dd>
    <dt><tt> ipIADirCurvature</tt>
   <dd>    Curvature direction.
 </dd>
    <dt><tt> iCurvatureRadius</tt>
   <dd>    Curvature radius value.</dd>
</dl>
</dl>
</dl>
<a name="SetPointConstraintFromCurve"><dt>

<table><tr><td>o Sub <b>SetPointConstraintFromCurve</b>(<td><script type="text/javascript"> activateLink('long','long')</script> <td><tt>iPos</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('Reference','Reference')</script> <td><tt>ipIACurveCst</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('double','double')</script> <td><tt>iTangencyNorm</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('long','long')</script> <td><tt>iInvertValue</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('long','long')</script> <td><tt>iCrvCstType</tt>)</table></dt>
<dl>
  <dd>
 Sets the Constraint of the point at iPos.
<br> Available for From Curve Point Constraint type (CstType =2 from GetContraintType)
 
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iPos</tt>
   <dd>    The position of the point to retrieve
 </dd>
    <dt><tt> ipIACurveCst</tt>
   <dd>   Curvature direction.
 </dd>
    <dt><tt> iTangencyNorm</tt>
   <dd>     tension factor for tangency.
 </dd>
    <dt><tt> iInvertValue</tt>
   <dd>   Orientation for tangent 
 </dd>
    <dt><tt> iCrvCstType</tt>
   <dd>    Continuity type for Curve Constraint (1=Tangency , 2-= Curvature).</dd>
</dl>
</dl>
</dl>
<a name="SetSplineType"><dt>

<table><tr><td>o Sub <b>SetSplineType</b>(<td><script type="text/javascript"> activateLink('long','long')</script> <td><tt>iSplineType</tt>)</table></dt>
<dl>
  <dd>
 Sets the spline type.
 
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iSplineType</tt>
   <dd>    The spline type
   <br><b>Legal values</b>: Cubic spline (0) or WilsonFowler (1)</dd>
</dl>
</dl>
</dl>
<a name="SetSupport"><dt>

<table><tr><td>o Sub <b>SetSupport</b>(<td><script type="text/javascript"> activateLink('Reference','Reference')</script> <td><tt>iSupport</tt>)</table></dt>
<dl>
  <dd>
 Sets the spline support surface.
 <br>Have your "tangent direction" tangent to this support is recommended.
 
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iSupport</tt>
   <dd>    The spline support surface.
 <br>Sub-element(s) supported (see </dd>
</dl>
<a href="#" onClick="openLink('Boundary','');return false">Boundary</a> object):  
<a href="#" onClick="openLink('Face','');return false">Face</a>.
</dl>
</dl>

</body>
<hr><p><i>
Copyright &#169; 1999-2011, Dassault Syst&#232;mes. All rights reserved.</i></p>
</html>
