<html>
<head>
 <meta name="Generator" content="mihGene v1.1">
 <meta http-equiv="Expires" content="Tue, 04 Dec 1993 21:29:02 GMT">
 <title>CATGSMIDLItf HybridShapeCombine (Object)</title>
<link rel="Stylesheet" type="text/css" href="../../../caav5.css">
<script language="Javascript" src="../_index/jslink.js"></script> 
<script language="Javascript" src="jsFwLink.js"></script> 
<script language="Javascript" type="text/javascript" src="../_index/jsTree.js"></script>  
</head>
<body>
<pre><a href="../_index/main.htm">All Frameworks</a>  <a href="../_index/tree.htm">Object Hierarchy</a>  <a href="../CATGSMIDLItf.htm">This Framework</a>  <a href="../_index/CAAHomeIdx.htm">Indexes</a>  <script type="text/javascript"> 
 var test=locateObject('HybridShapeCombine','interface','0'); 
 if(test==1){ 
     document.write("<a href=\"#\" onclick=\"openLinkNP('HybridShapeCombine','interface','0');return false\">Previous</a> "); 
 } 
 test=locateObject('HybridShapeCombine','interface','1'); 
 if(test==1){ 
     document.write("<a href=\"#\" onclick=\"openLinkNP('HybridShapeCombine','interface','1');return false\">Next</a> "); 
 } 
 </script> 
</pre>
<hr>
<h1>HybridShapeCombine<font size=-1> (Object)</font></h1>
<script type="text/javascript" > 
 generatedFatherClass('interface_HybridShapeCombine_24827','HybridShapeCombine','0');</script>
<b><i> Represents the hybrid shape combined curve object.</i></b><br>

 <b>Role</b>: To access the data of the hybrid shape combined curve object.
 This data includes:
 <ul>
 <li>The three curves to which the circle is tangent</li>
 <li>The surface that supports the circle</li>
 <li>The orientation of each curve.</li>
 </ul>
 <p>Use the <a href="#" onClick="openLink('HybridShapeFactory','');return false">HybridShapeFactory</a> object to create a HybridShapeCombine object.
<hr>
<dl>
 <h2><a name="PropertyIndex"></a>Property Index</h2>
 <dt>
    <a href="#Direction1"><b>Direction1</b></a>
<dd>  Returns or sets the first direction used to create the combined curve.
 <dt>
    <a href="#Direction2"><b>Direction2</b></a>
<dd>  Returns or sets the second direction used to create the combined curve.
 <dt>
    <a href="#Elem1"><b>Elem1</b></a>
<dd>  Returns or sets the first curve used to create the combined curve.
 <dt>
    <a href="#Elem2"><b>Elem2</b></a>
<dd>  Returns or sets the second curve used to create the combined curve.
 <dt>
    <a href="#NearestSolution"><b>NearestSolution</b></a>
<dd>  Returns or sets whether the combined curve is or should be created as the curve closest
 to the first curve.
 <dt>
    <a href="#SolutionTypeCombine"><b>SolutionTypeCombine</b></a>
<dd>  Returns or sets whether the curves that create the combined curve are or should be
 extruded along normals to the curve planes or along given directions.
</dl>
<dl>
</dl>
 <h2><a name="Properties"></a>Properties</h2> <br>
<a name="Direction1"><dt>

<table><tr><td>o Property <b>Direction1</b>(<td>) As <script type="text/javascript"> activateLink('HybridShapeDirection','HybridShapeDirection')</script> </table></dt>
<dl>
  <dd>
 Returns or sets the first direction used to create the combined curve.
 The first direction is the direction along which the first curve is extruded.
 
<dl>
  <dt> <b>Example:</b> 
  <dd>  This example sets <code>firstDir</code> as the first direction to create the combined curve
 <code>hybCombCurve</code>.
 <pre>
 hybCombCurve.<font color="red">Direction1</font> = firstDir
 </pre>
</dl>
</dl>
<a name="Direction2"><dt>

<table><tr><td>o Property <b>Direction2</b>(<td>) As <script type="text/javascript"> activateLink('HybridShapeDirection','HybridShapeDirection')</script> </table></dt>
<dl>
  <dd>
 Returns or sets the second direction used to create the combined curve. 
 
<dl>
  <dt> <b>Example:</b> 
  <dd>  This example retrieves in <code>secondDir</code> the second direction used
 to create the combined curve <code>hybCombCurve</code>.
 <pre>
 Dim secondDir As CATIAHybridShapeDirection
 Set secondDir = hybCombCurve.<font color="red">Direction2</font>
 </pre>
</dl>
</dl>
<a name="Elem1"><dt>

<table><tr><td>o Property <b>Elem1</b>(<td>) As <script type="text/javascript"> activateLink('Reference','Reference')</script> </table></dt>
<dl>
  <dd>
 Returns or sets the first curve used to create the combined curve.
 <br>Sub-element(s) supported (see 
<a href="#" onClick="openLink('Boundary','');return false">Boundary</a> object):  
<a href="#" onClick="openLink('TriDimFeatEdge','');return false">TriDimFeatEdge</a> or 
<a href="#" onClick="openLink('BiDimFeatEdge','');return false">BiDimFeatEdge</a>. 
<dl>
  <dt> <b>Example:</b> 
  <dd>  This example sets <code>firstCurve</code> as the first curve to create the combined curve
 <code>hybCombCurve</code>.
 <pre>
 hybCombCurve.<font color="red">Elem1</font> = firstCurve
 </pre>
</dl>
</dl>
<a name="Elem2"><dt>

<table><tr><td>o Property <b>Elem2</b>(<td>) As <script type="text/javascript"> activateLink('Reference','Reference')</script> </table></dt>
<dl>
  <dd>
 Returns or sets the second curve used to create the combined curve.
 <br>Sub-element(s) supported (see 
<a href="#" onClick="openLink('Boundary','');return false">Boundary</a> object):  
<a href="#" onClick="openLink('TriDimFeatEdge','');return false">TriDimFeatEdge</a> or 
<a href="#" onClick="openLink('BiDimFeatEdge','');return false">BiDimFeatEdge</a>. 
<dl>
  <dt> <b>Example:</b> 
  <dd>  This example retrieves in <code>secondCurve</code> the second curve used to create
 the combined curve <code>hybCombCurve</code>.
 <pre>
 Dim secondCurve As CATIAReference
 Set secondCurve = hybCombCurve.<font color="red">Elem2</font>
 </pre>
</dl>
</dl>
<a name="NearestSolution"><dt>

<table><tr><td>o Property <b>NearestSolution</b>(<td>) As <script type="text/javascript"> activateLink('long','long')</script> </table></dt>
<dl>
  <dd>
 Returns or sets whether the combined curve is or should be created as the curve closest
 to the first curve.
 <br><b>Role</b>: The nearest solution indicates whether the created combined curve
 is the one closest to the first curve if there are several possible combined curves,
 or if all these possible combined curves are created..
 <br><b>Legal values</b>: 0 for the nearest solution and 1 for all possible solutions.
 
<dl>
  <dt> <b>Example:</b> 
  <dd>  This example sets the nearest solution mode to create the combined curve
 <code>hybCombCurve</code> closest to the first curve.
 <pre>
 hybCombCurve.<font color="red">NearestSolution</font> = 1
 </pre>
 </dl>
</dl>
</dl>
<a name="SolutionTypeCombine"><dt>

<table><tr><td>o Property <b>SolutionTypeCombine</b>(<td>) As <script type="text/javascript"> activateLink('long','long')</script> </table></dt>
<dl>
  <dd>
 Returns or sets whether the curves that create the combined curve are or should be
 extruded along normals to the curve planes or along given directions.
 <br><b>Role</b>: The curves that make up the combined curve are each extruded along
 a direction. This direction can be the normal to the curve plane, or can be set to
 a given direction. This is valid for the two curves altogether.
 <br><b>Legal values</b>: 0 for the normal to the curve planes (default mode),
 1 for given directions
 
<dl>
  <dt> <b>Example:</b> 
  <dd>  This example sets that the combined curve <code>hybCombCurve</code> should be created
 by extruding the two curves along the normals to their planes.
 <pre>
 hybCombCurve.<font color="red">SolutionTypeCombine</font> = 0
 </pre>
</dl>
</dl>

</body>
<hr><p><i>
Copyright &#169; 1999-2011, Dassault Syst&#232;mes. All rights reserved.</i></p>
</html>
