<html>
<head>
 <meta name="Generator" content="mihGene v1.1">
 <meta http-equiv="Expires" content="Tue, 04 Dec 1993 21:29:02 GMT">
 <title>CATGSMIDLItf HybridShapeLoft (Object)</title>
<link rel="Stylesheet" type="text/css" href="../../../caav5.css">
<script language="Javascript" src="../_index/jslink.js"></script> 
<script language="Javascript" src="jsFwLink.js"></script> 
<script language="Javascript" type="text/javascript" src="../_index/jsTree.js"></script>  
</head>
<body>
<pre><a href="../_index/main.htm">All Frameworks</a>  <a href="../_index/tree.htm">Object Hierarchy</a>  <a href="../CATGSMIDLItf.htm">This Framework</a>  <a href="../_index/CAAHomeIdx.htm">Indexes</a>  <script type="text/javascript"> 
 var test=locateObject('HybridShapeLoft','interface','0'); 
 if(test==1){ 
     document.write("<a href=\"#\" onclick=\"openLinkNP('HybridShapeLoft','interface','0');return false\">Previous</a> "); 
 } 
 test=locateObject('HybridShapeLoft','interface','1'); 
 if(test==1){ 
     document.write("<a href=\"#\" onclick=\"openLinkNP('HybridShapeLoft','interface','1');return false\">Next</a> "); 
 } 
 </script> 
</pre>
<hr>
<h1>HybridShapeLoft<font size=-1> (Object)</font></h1>
<script type="text/javascript" > 
 generatedFatherClass('interface_HybridShapeLoft_20035','HybridShapeLoft','0');</script>
<b><i> Represents the hybrid shape loft surface feature object.</i></b><br>

 <b>Role</b>: To access the data of the hybrid shape loft surface feature object.
 <br>This data includes:
 <ul>
 <li>The spine</li>
 <li>The tangent surfaces to the start and end sections</li>
 <li>Guide curves, sections, and couplings</li>
 </ul>
 <p>Use the  CATIAHybridShapeFactory to create a HybridShapeLoft object.
 <p>  LICENSING INFORMATION: Creation of volume result requires GSO License
 <br> if GSO License is not granted , settting of Volume context has not effect 
 <p>Use the  CATIAHybridShapeFactory to create a HybridShapeLoft object.
 <dl>
  <dt> <b>See also:</b> 
  <dd> <a href="#" onClick="openLink('HybridShapeFactory','');return false">HybridShapeFactory</a>
</dl>
<hr>
<dl>
 <h2><a name="PropertyIndex"></a>Property Index</h2>
 <dt>
    <a href="#AreaLaw"><b>AreaLaw</b></a>
<dd>  Gets or sets the optional area law for multi-sections element definition.
 <dt>
    <a href="#AreaLawTolerance"><b>AreaLawTolerance</b></a>
<dd>  Gets or sets the tolerance applied to area law.
 <dt>
    <a href="#BooleanOperation"><b>BooleanOperation</b></a>
<dd>  Gets or sets the boolean operation for closed lofted surface.
 <dt>
    <a href="#CanonicalDetection"><b>CanonicalDetection</b></a>
<dd>  Returns or sets whether canonical surfaces of the lofted surface are detected.
 <dt>
    <a href="#CompEndSectionTangent"><b>CompEndSectionTangent</b></a>
<dd>  Returns or sets whether the tangent surface to the end section of the lofted surface is computed.
 <dt>
    <a href="#CompStartSectionTangent"><b>CompStartSectionTangent</b></a>
<dd>  Returns or sets whether the tangent surface to the start section of the lofted surface is computed.
 <dt>
    <a href="#Context"><b>Context</b></a>
<dd>  Returns or sets the context on Loft feature.
 <dt>
    <a href="#Relimitation"><b>Relimitation</b></a>
<dd>  Returns or sets the relimitation type between sections of the loft.
 <dt>
    <a href="#SectionCoupling"><b>SectionCoupling</b></a>
<dd>  Returns or sets the type of coupling between sections of the loft.
 <dt>
    <a href="#SmoothAngleThreshold"><b>SmoothAngleThreshold</b></a>
<dd>  Returns or sets the angular threshold under which discontinuities (moving frame,
 tangency net on reference surface) will be smoothed.
 <dt>
    <a href="#SmoothAngleThresholdActivity"><b>SmoothAngleThresholdActivity</b></a>
<dd>  Returns or sets whether a angular threshold is allowed or not during lofting operation in order to smooth it.
 <dt>
    <a href="#SmoothDeviation"><b>SmoothDeviation</b></a>
<dd>  Returns or sets the deviation value (length) 
 allowed during lofting operation in order to smooth it.
 <dt>
    <a href="#SmoothDeviationActivity"><b>SmoothDeviationActivity</b></a>
<dd>  Returns or sets whether a deviation is allowed or not during lofting operation in order to smooth it.
</dl>
<dl>
 <h2><a name="MethodIndex"></a>Method Index</h2>
 <dt>
    <a href="#AddGuide"><b>AddGuide</b></a>
<dd>  Adds a guide curve to the lofted surface.
 <dt>
    <a href="#AddGuideWithTangent"><b>AddGuideWithTangent</b></a>
<dd>  Adds a guide curve and a tangent surface to the lofted surface.
 <dt>
    <a href="#AddSectionToLoft"><b>AddSectionToLoft</b></a>
<dd>  Retrieves a loft section.
 <dt>
    <a href="#GetAreaLawToleranceParameter"><b>GetAreaLawToleranceParameter</b></a>
<dd>  Gets the tolerance parameter applied to area law.
 <dt>
    <a href="#GetFacesForClosing"><b>GetFacesForClosing</b></a>
<dd>  Gets start and end faces if the tangent is a computed tangent surface to the 
   start section or end section, from the lofted surface.
 <dt>
    <a href="#GetGuide"><b>GetGuide</b></a>
<dd>  Gets informations about the guide at a specified position in the list  of the lofted surface.
 <dt>
    <a href="#GetNbOfGuides"><b>GetNbOfGuides</b></a>
<dd>  Returns the number of guides in the loft object.
 <dt>
    <a href="#GetSectionFromLoft"><b>GetSectionFromLoft</b></a>
<dd>  Retrieves a loft section information.
 <dt>
    <a href="#GetSpine"><b>GetSpine</b></a>
<dd>  Gets the spine of the lofted surface.
 <dt>
    <a href="#GetStartAndEndSectionTangent"><b>GetStartAndEndSectionTangent</b></a>
<dd>  Gets the start and end section tangents of the lofted surface.
 <dt>
    <a href="#InsertCoupling"><b>InsertCoupling</b></a>
<dd>  Inserts a coupling to the loft.
 <dt>
    <a href="#InsertCouplingPoint"><b>InsertCouplingPoint</b></a>
<dd>  Inserts a coupling point to a coupling of the lofted surface.
 <dt>
    <a href="#InsertSectionToLoft"><b>InsertSectionToLoft</b></a>
<dd>  Inserts a loft section.
 <dt>
    <a href="#ModifyGuideCurve"><b>ModifyGuideCurve</b></a>
<dd>  Modifies the curve of a guide from the lofted surface.
 <dt>
    <a href="#ModifySectionCurve"><b>ModifySectionCurve</b></a>
<dd>  Modifies the curve of section from the lofted surface.
 <dt>
    <a href="#ModifySectionOrient"><b>ModifySectionOrient</b></a>
<dd>  Modifies the orientation of the curve of a section from the lofted surface.
 <dt>
    <a href="#RemoveFaceForClosing"><b>RemoveFaceForClosing</b></a>
<dd>  Removes face used to close the lofted surface.
 <dt>
    <a href="#RemoveGuide"><b>RemoveGuide</b></a>
<dd>  Removes a guide curve from the lofted surface.
 <dt>
    <a href="#RemoveGuideTangent"><b>RemoveGuideTangent</b></a>
<dd>  Removes a tangent surface of a guide from the lofted surface.
 <dt>
    <a href="#RemoveSection"><b>RemoveSection</b></a>
<dd>  Removes a loft section from the lofted surface.
 <dt>
    <a href="#RemoveSectionPoint"><b>RemoveSectionPoint</b></a>
<dd>  Removes a closing point of a section from the lofted surface.
 <dt>
    <a href="#RemoveSectionTangent"><b>RemoveSectionTangent</b></a>
<dd>  Removes the tangent surface of a section from the lofted surface.
 <dt>
    <a href="#SetEndFaceForClosing"><b>SetEndFaceForClosing</b></a>
<dd>  Sets a face to the end section from the lofted surface.
 <dt>
    <a href="#SetEndSectionTangent"><b>SetEndSectionTangent</b></a>
<dd>  Sets a tangent surface to the end section from the lofted surface.
 <dt>
    <a href="#SetSpine"><b>SetSpine</b></a>
<dd>  Sets the spine to the lofted surface.
 <dt>
    <a href="#SetStartFaceForClosing"><b>SetStartFaceForClosing</b></a>
<dd>  Sets a face to the start section from the lofted surface.
 <dt>
    <a href="#SetStartSectionTangent"><b>SetStartSectionTangent</b></a>
<dd>  Sets a tangent surface to the start section from the lofted surface.
</dl>
 <h2><a name="Properties"></a>Properties</h2> <br>
<a name="AreaLaw"><dt>

<table><tr><td>o Property <b>AreaLaw</b>(<td>) As <script type="text/javascript"> activateLink('Reference','Reference')</script> </table></dt>
<dl>
  <dd>
 Gets or sets the optional area law for multi-sections element definition. The law is a length law.
</dl>
<a name="AreaLawTolerance"><dt>

<table><tr><td>o Property <b>AreaLawTolerance</b>(<td>) As <script type="text/javascript"> activateLink('double','double')</script> </table></dt>
<dl>
  <dd>
 Gets or sets the tolerance applied to area law. The value is in mm.
</dl>
<a name="BooleanOperation"><dt>

<table><tr><td>o Property <b>BooleanOperation</b>(<td>) As <script type="text/javascript"> activateLink('long','long')</script> </table></dt>
<dl>
  <dd>
 Gets or sets the boolean operation for closed lofted surface.
 TO BE USED ONLY for Part Loft (closed loft).
      BooleanOperation = 1 : No boolean operation.
                       = 2 : Union  boolean operation.
                       = 3 : Removal boolean operation.
 This example retrieves in <code>BoolOp</code> the type of boolean operation 
 for the <code>Loft</code> hybrid shape feature.
 <pre>
 Dim BoolOp
 BoolOp = Loft.<font color="red">BooleanOperation</font>
 </pre>
 </dl>
</dl>
<a name="CanonicalDetection"><dt>

<table><tr><td>o Property <b>CanonicalDetection</b>(<td>) As <script type="text/javascript"> activateLink('long','long')</script> </table></dt>
<dl>
  <dd>
 Returns or sets whether canonical surfaces of the lofted surface are detected.
 <br><b>Legal values</b>:
 <dl>
 <dt>0</dt>
 <dd>No detection of canonical surface is performed</dd>
 <dt>1</dt>
 <dd>Detection of planar surfaces only is performed</dd>
 <dt>2</dt>
 <dd>Detection of canonical surfaces is performed</dd>
 </dl>
</dl>
<a name="CompEndSectionTangent"><dt>

<table><tr><td>o Property <b>CompEndSectionTangent</b>(<td>) As <script type="text/javascript"> activateLink('long','long')</script> </table></dt>
<dl>
  <dd>
 Returns or sets whether the tangent surface to the end section of the lofted surface is computed.
 <br><b>Legal values</b>:
 <dl>
 <dt>1</dt>
 <dd>The tangent to the end section is computed</dd>
 <dt>2</dt>
 <dd>The tangent to the end section is not computed</dd>
 </dl>
</dl>
<a name="CompStartSectionTangent"><dt>

<table><tr><td>o Property <b>CompStartSectionTangent</b>(<td>) As <script type="text/javascript"> activateLink('long','long')</script> </table></dt>
<dl>
  <dd>
 Returns or sets whether the tangent surface to the start section of the lofted surface is computed.
 <br><b>Legal values</b>:
 <dl>
 <dt>1</dt>
 <dd>The tangent to the start section is computed</dd>
 <dt>2</dt>
 <dd>The tangent to the start section is not computed</dd>
 </dl>
</dl>
<a name="Context"><dt>

<table><tr><td>o Property <b>Context</b>(<td>) As <script type="text/javascript"> activateLink('long','long')</script> </table></dt>
<dl>
  <dd>
 Returns or sets the context on Loft feature. 
 <br><b>Legal values</b>:
 <ul>
 <li><b>0</b> This option creates Lofted surface.</li>
 <li><b>1</b> This option creates Lofted volume.</li>
 </ul>
 <br> Note: Setting volume result requires GSO License. 
 <dl>
 <dt><b>Example</b>:
 <dd>
 This example retrieves in <code>oContext</code> the context
 for the <code>Loft</code> hybrid shape feature.
 <pre>
 Dim oContext
 Set oContext = Loft.<font color="red">Context</font>
 </pre>
 </dl>
</dl>
<a name="Relimitation"><dt>

<table><tr><td>o Property <b>Relimitation</b>(<td>) As <script type="text/javascript"> activateLink('long','long')</script> </table></dt>
<dl>
  <dd>
 Returns or sets the relimitation type between sections of the loft.
 <br>NOT YET IMPLEMENTED.
 <br><b>Legal values</b>:
 <dl>
 <dt>1</dt>
 <dd>The loft will be swept along the spine, then relimited by the start section and the end section</dd>
 <dt>2</dt>
 <dd>The loft will be swept along the spine.
   <ul>
     <li>If the spine is a user spine, then the loft is limited by the spine extremities</li>
     <li>If the spine is a computed spine, then the loft is limited:
     <ul>
       <li>By the start section and the end section, if there is no guide</li>
       <li>By the guides extremities, if there are guides</li>
     </li>
     </ul>
   </ul>
 </dd>
 <dt>3</dt>
 <dd>The loft will be swept along the spine, then relimited by the first section,  
   <ul>
     <li>If the spine is a user spine, then the loft is limited by the spine extremity opposite to the first section</li>
     <li>If the spine is a computed spine, then the loft is limited:
       <ul>
          <li>By the last section, if there is no guide</li>
          <li>By the guides extremities opposite to the first section, if there are guides</li>
       </ul>
     </li>
   </ul>
 </dd>
 <dt>4</dt>
 <dd>The loft will be swept along the spine, then relimited by the last section,  
   <ul>
     <li>If the spine is a user spine, then the loft is limited by the spine extremity opposite to the last section</li>
     <li>If the spine is a computed spine, then the loft is limited:
       <ul>
          <li>By the first section, if there is no guide</li>
          <li>By the guides extremities opposite to the last section, if there are guides</li>
       </ul>
     </li>
    </ul>
  </dd>
  </dl>
</dl>
<a name="SectionCoupling"><dt>

<table><tr><td>o Property <b>SectionCoupling</b>(<td>) As <script type="text/javascript"> activateLink('long','long')</script> </table></dt>
<dl>
  <dd>
 Returns or sets the type of coupling between sections of the loft.
 <br><b>Legal values</b>:
 <dl>
 <dt>1</dt>
 <dd>The curves will be coupled according to the curvilinear abscissa ratio</dd>
 <dt>2</dt>
 <dd>if each curve has the same number of tangency 
 discontinuity points, then these points will be coupled,
 otherwise an error message is displayed</dd>
 <dt>3</dt>
 <dd>if each curve has the same number 
 of tangency and curvature discontinuity points,
 then tangency discontinuity points will be coupled,
 and after curvature discontinuity points will be coupled,
 otherwise an error message is displayed</dd>
 <dt>4</dt>
 <dd>if each curve has the same number of vertices, 
 then these points will be coupled,
 otherwise an error message is displayed</dd>
 </dl>
</dl>
<a name="SmoothAngleThreshold"><dt>

<table><tr><td>o Property <b>SmoothAngleThreshold</b>(<td>) As <script type="text/javascript"> activateLink('double','double')</script> </table></dt>
<dl>
  <dd>
 Returns or sets the angular threshold under which discontinuities (moving frame,
 tangency net on reference surface) will be smoothed.
</dl>
<a name="SmoothAngleThresholdActivity"><dt>

<table><tr><td>o Property <b>SmoothAngleThresholdActivity</b>(<td>) As <script type="text/javascript"> activateLink('boolean','boolean')</script> </table></dt>
<dl>
  <dd>
 Returns or sets whether a angular threshold is allowed or not during lofting operation in order to smooth it.
 <br><b>Legal values</b>:
 <dl>
 <dt>TRUE</dt>
 <dd>The angular threshold value is used during the lofting operation</dd>
 <dt>FALSE</dt>
 <dd>The angular threshold value is not used during the lofting operation</dd>
 </dl>
</dl>
<a name="SmoothDeviation"><dt>

<table><tr><td>o Property <b>SmoothDeviation</b>(<td>) As <script type="text/javascript"> activateLink('double','double')</script> </table></dt>
<dl>
  <dd>
 Returns or sets the deviation value (length) 
 allowed during lofting operation in order to smooth it.
</dl>
<a name="SmoothDeviationActivity"><dt>

<table><tr><td>o Property <b>SmoothDeviationActivity</b>(<td>) As <script type="text/javascript"> activateLink('boolean','boolean')</script> </table></dt>
<dl>
  <dd>
 Returns or sets whether a deviation is allowed or not during lofting operation in order to smooth it.
 <br><b>Legal values</b>:
 <dl>
 <dt>TRUE</dt>
 <dd>The deviation value is used during the lofting operation</dd>
 <dt>FALSE</dt>
 <dd>The deviation value is not used during the lofting operation</dd>
 </dl>
</dl>
 <h2><a name="Methods"></a>Methods</h2> <br>
<a name="AddGuide"><dt>

<table><tr><td>o Sub <b>AddGuide</b>(<td><script type="text/javascript"> activateLink('Reference','Reference')</script> <td><tt>iGuide</tt>)</table></dt>
<dl>
  <dd>
 Adds a guide curve to the lofted surface.
   
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iGuide</tt>
   <dd>     The guide curve to be added<br>
 <br>Sub-element(s) supported (see </dd>
</dl>
<a href="#" onClick="openLink('Boundary','');return false">Boundary</a> object):  
<a href="#" onClick="openLink('TriDimFeatEdge','');return false">TriDimFeatEdge</a> and 
<a href="#" onClick="openLink('BiDimFeatEdge','');return false">BiDimFeatEdge</a>.
</dl>
</dl>
<a name="AddGuideWithTangent"><dt>

<table><tr><td>o Sub <b>AddGuideWithTangent</b>(<td><script type="text/javascript"> activateLink('Reference','Reference')</script> <td><tt>iGuide</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('Reference','Reference')</script> <td><tt>iTangent</tt>)</table></dt>
<dl>
  <dd>
 Adds a guide curve and a tangent surface to the lofted surface.
   
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iGuide</tt>
   <dd>     The guide curve to be added<br>
 <br>Sub-element(s) supported (see </dd>
</dl>
<a href="#" onClick="openLink('Boundary','');return false">Boundary</a> object):  
<a href="#" onClick="openLink('TriDimFeatEdge','');return false">TriDimFeatEdge</a> and 
<a href="#" onClick="openLink('BiDimFeatEdge','');return false">BiDimFeatEdge</a>.   
    <dt><tt> iTangent</tt>
   <dd>     The tangent surface to be added.
     The guide curve must be layed on the tangent<br>
 <br>Sub-element(s) supported (see </dd>
<a href="#" onClick="openLink('Boundary','');return false">Boundary</a> object):  
<a href="#" onClick="openLink('Face','');return false">Face</a>.
</dl>
</dl>
<a name="AddSectionToLoft"><dt>

<table><tr><td>o Sub <b>AddSectionToLoft</b>(<td><script type="text/javascript"> activateLink('Reference','Reference')</script> <td><tt>iCrv</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('long','long')</script> <td><tt>iOri</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('Reference','Reference')</script> <td><tt>iPoint</tt>)</table></dt>
<dl>
  <dd>
 Retrieves a loft section. 
 
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iCrv</tt>
   <dd>   Reference to the curve
 </dd>
    <dt><tt> iOri</tt>
   <dd>   Orientation
 </dd>
    <dt><tt> iPoint</tt>
   <dd>    Reference to the Closing Point</dd>
</dl>
</dl>
</dl>
<a name="GetAreaLawToleranceParameter"><dt>

<table><tr><td>o Func <b>GetAreaLawToleranceParameter</b>(<td>) As <script type="text/javascript"> activateLink('Length','Length')</script> </table></dt>
<dl>
  <dd>
 Gets the tolerance parameter applied to area law.
</dl>
<a name="GetFacesForClosing"><dt>

<table><tr><td>o Sub <b>GetFacesForClosing</b>(<td><script type="text/javascript"> activateLink('Reference','Reference')</script> <td><tt>oStartFace</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('Reference','Reference')</script> <td><tt>oEndFace</tt>)</table></dt>
<dl>
  <dd>
 Gets start and end faces if the tangent is a computed tangent surface to the 
   start section or end section, from the lofted surface.
 The section must have been set as a face. 
   
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> oStartFace</tt>
   <dd>      start face used to close the loft.  
   </dd>
    <dt><tt> oEndFace</tt>
   <dd>      end face used to close the loft.</dd>
</dl>
</dl>
</dl>
<a name="GetGuide"><dt>

<table><tr><td>o Sub <b>GetGuide</b>(<td><script type="text/javascript"> activateLink('long','long')</script> <td><tt>iPos</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('Reference','Reference')</script> <td><tt>oGuide</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('Reference','Reference')</script> <td><tt>oGuideTangent</tt>)</table></dt>
<dl>
  <dd>
 Gets informations about the guide at a specified position in the list  of the lofted surface.
   
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iPos</tt>
   <dd>      position of the guide in the list where the information is retrieved.
   </dd>
    <dt><tt> oGuide</tt>
   <dd>      the guide curve.
   </dd>
    <dt><tt> oGuideTangent</tt>
   <dd>      the tangent corresponding to the guide curve.</dd>
</dl>
</dl>
</dl>
<a name="GetNbOfGuides"><dt>

<table><tr><td>o Func <b>GetNbOfGuides</b>(<td>) As <script type="text/javascript"> activateLink('long','long')</script> </table></dt>
<dl>
  <dd>
 Returns the number of guides in the loft object.
 
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> oSize</tt>
   <dd>     Number of guides in the loft.
 <dl>
 <dt><b>Example</b>:
 <dd>
 This example retrieves the number of guides
 in the <code>hybShpLoft</code> hybrid shape Loft.
 <pre>
 Dim oSize As  long
 oSize = hybShpLoft.<font color="red">GetNbOfGuides</font>
 </pre>
 </dl></dd>
</dl>
</dl>
</dl>
<a name="GetSectionFromLoft"><dt>

<table><tr><td>o Sub <b>GetSectionFromLoft</b>(<td><script type="text/javascript"> activateLink('long','long')</script> <td><tt>iRank</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('Reference','Reference')</script> <td><tt>oCrv</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('long','long')</script> <td><tt>oOri</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('Reference','Reference')</script> <td><tt>oPoint</tt>)</table></dt>
<dl>
  <dd>
 Retrieves a loft section information. 
 
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iRank</tt>
   <dd>   The index of the section
 </dd>
    <dt><tt> oCrv</tt>
   <dd>   The reference to the curve
 </dd>
    <dt><tt> oOri</tt>
   <dd>   The orientation value
 </dd>
    <dt><tt> oPoint</tt>
   <dd>   The reference to the point</dd>
</dl>
</dl>
</dl>
<a name="GetSpine"><dt>

<table><tr><td>o Sub <b>GetSpine</b>(<td><script type="text/javascript"> activateLink('long','long')</script> <td><tt>oSpineType</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('Reference','Reference')</script> <td><tt>oSpine</tt>)</table></dt>
<dl>
  <dd>
 Gets the spine of the lofted surface.
   
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> oSpineType</tt>
   <dd>      type of spine = 1 : User defined spine.
                    = 2 : Automatically computed spine.
   </dd>
    <dt><tt> oSpine</tt>
   <dd>      curve used as a spine, if the spine is user defined one.</dd>
</dl>
</dl>
</dl>
<a name="GetStartAndEndSectionTangent"><dt>

<table><tr><td>o Sub <b>GetStartAndEndSectionTangent</b>(<td><script type="text/javascript"> activateLink('Reference','Reference')</script> <td><tt>oStartSectionTangent</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('Reference','Reference')</script> <td><tt>oEndSectionTangent</tt>)</table></dt>
<dl>
  <dd>
 Gets the start and end section tangents of the lofted surface.
   
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> oStartSectionTangent</tt>
   <dd>      tangent surface at start section.
   </dd>
    <dt><tt> oEndSectionTangent</tt>
   <dd>      tangent surface at end section.</dd>
</dl>
</dl>
</dl>
<a name="InsertCoupling"><dt>

<table><tr><td>o Sub <b>InsertCoupling</b>(<td><script type="text/javascript"> activateLink('long','long')</script> <td><tt>iPosition</tt>)</table></dt>
<dl>
  <dd>
 Inserts a coupling to the loft.
 
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iPosition</tt>
   <dd>    The position of the coupling in the list of couplings.
   If 0 is specified, the coupling is inserted at the end of the list.
 <br>Sub-element(s) supported (see </dd>
</dl>
<a href="#" onClick="openLink('Boundary','');return false">Boundary</a> object):  
<a href="#" onClick="openLink('Vertex','');return false">Vertex</a>.
</dl>
</dl>
<a name="InsertCouplingPoint"><dt>

<table><tr><td>o Sub <b>InsertCouplingPoint</b>(<td><script type="text/javascript"> activateLink('long','long')</script> <td><tt>iCouplingIndex</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('long','long')</script> <td><tt>iPosition</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('Reference','Reference')</script> <td><tt>iPoint</tt>)</table></dt>
<dl>
  <dd>
 Inserts a coupling point to a coupling of the lofted surface.
 
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iCouplingIndex</tt>
   <dd>    The index of the coupling in the list of coupling where the point wil be inserted.
 </dd>
    <dt><tt> iPosition</tt>
   <dd>    The position of the coupling point in the list of coupling points.
   If 0 is specified, the coupling point is inserted at the end of the list.
 </dd>
    <dt><tt> iPoint</tt>
   <dd>   The point to be inserted. The point must be layed on the section with the same position.
 <br>Sub-element(s) supported (see </dd>
</dl>
<a href="#" onClick="openLink('Boundary','');return false">Boundary</a> object):  ScVertex.
</dl>
</dl>
<a name="InsertSectionToLoft"><dt>

<table><tr><td>o Sub <b>InsertSectionToLoft</b>(<td><script type="text/javascript"> activateLink('boolean','boolean')</script> <td><tt>iType</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('Reference','Reference')</script> <td><tt>iCrv</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('long','long')</script> <td><tt>iOri</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('Reference','Reference')</script> <td><tt>iPoint</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('Reference','Reference')</script> <td><tt>iSectionRef</tt>)</table></dt>
<dl>
  <dd>
 Inserts a loft section. 
 
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iType</tt>
   <dd>	 iType if set to true section is added After and iType if set to false section is added Before iSectionRef
 </dd>
    <dt><tt> iCrv</tt>
   <dd>   Reference to the curve
 </dd>
    <dt><tt> iOri</tt>
   <dd>   Orientation
 </dd>
    <dt><tt> iPoint</tt>
   <dd>    Reference to the Closing Point 
 </dd>
    <dt><tt> iSectionRef</tt>
   <dd>	iSectionRef is the section before and after which section is added.</dd>
</dl>
</dl>
</dl>
<a name="ModifyGuideCurve"><dt>

<table><tr><td>o Sub <b>ModifyGuideCurve</b>(<td><script type="text/javascript"> activateLink('Reference','Reference')</script> <td><tt>iGuide</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('Reference','Reference')</script> <td><tt>iNewGuide</tt>)</table></dt>
<dl>
  <dd>
 Modifies the curve of a guide from the lofted surface.
   
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iGuide</tt>
   <dd>      guide curve to be replaced.
   </dd>
    <dt><tt> iNewGuide</tt>
   <dd>      new guide curve, will replace iGuide.</dd>
</dl>
</dl>
</dl>
<a name="ModifySectionCurve"><dt>

<table><tr><td>o Sub <b>ModifySectionCurve</b>(<td><script type="text/javascript"> activateLink('Reference','Reference')</script> <td><tt>iSection</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('Reference','Reference')</script> <td><tt>iNewSection</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('Reference','Reference')</script> <td><tt>oCurveSection</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('Reference','Reference')</script> <td><tt>oClosingPoint</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('long','long')</script> <td><tt>oPtDiag</tt>)</table></dt>
<dl>
  <dd>
 Modifies the curve of section from the lofted surface.
   
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iSection</tt>
   <dd>      section curve to be replaced.
   </dd>
    <dt><tt> iNewSection</tt>
   <dd>      section will replace iSection, can be a curve or a face
   </dd>
    <dt><tt> oCurveSection</tt>
   <dd>      if iSection is a face, oCurveSection is the boundary of the face.
      oCurveSection is used as section curve.
      if Part design, the face is used to close the Loft.
   </dd>
    <dt><tt> oClosingPoint</tt>
   <dd>      if iSection is a closed curve, oClosingPoint is a new closing point
      of iSection.
      if iSection is a face, oClosingPoint is a new closing point the boundary
      of iSection.
   </dd>
    <dt><tt> oPtDiag</tt>
   <dd>      Information on closing point = 0 : No closing point has been created nor retrieved. 
                                   = 1 : A closing point has been created as a vertex.
                                   = 2 : A closing point has been created as an extremum.
                                   = 3 : A closing point has been retrieved as an extremum.</dd>
</dl>
</dl>
</dl>
<a name="ModifySectionOrient"><dt>

<table><tr><td>o Sub <b>ModifySectionOrient</b>(<td><script type="text/javascript"> activateLink('Reference','Reference')</script> <td><tt>iSection</tt>,<tr><td></td><td><script type="text/javascript"> activateLink('long','long')</script> <td><tt>iOrient</tt>)</table></dt>
<dl>
  <dd>
 Modifies the orientation of the curve of a section from the lofted surface.
   
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iSection</tt>
   <dd>      section curve to be modified.
   </dd>
    <dt><tt> iOrient</tt>
   <dd>      orientation of the section curve =  1 : same orientation.
                                       = -1 : inverted orientation.
                                       =  2 : ko orientation.</dd>
</dl>
</dl>
</dl>
<a name="RemoveFaceForClosing"><dt>

<table><tr><td>o Sub <b>RemoveFaceForClosing</b>(<td><script type="text/javascript"> activateLink('Reference','Reference')</script> <td><tt>iSection</tt>)</table></dt>
<dl>
  <dd>
 Removes face used to close the lofted surface. 
   
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iSection</tt>
   <dd>        section curve.</dd>
</dl>
</dl>
</dl>
<a name="RemoveGuide"><dt>

<table><tr><td>o Sub <b>RemoveGuide</b>(<td><script type="text/javascript"> activateLink('Reference','Reference')</script> <td><tt>iGuide</tt>)</table></dt>
<dl>
  <dd>
 Removes a guide curve from the lofted surface.
   
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iGuide</tt>
   <dd>     The guide curve to be removed<br>
 <br>Sub-element(s) supported (see </dd>
</dl>
<a href="#" onClick="openLink('Boundary','');return false">Boundary</a> object):  
<a href="#" onClick="openLink('TriDimFeatEdge','');return false">TriDimFeatEdge</a> and 
<a href="#" onClick="openLink('BiDimFeatEdge','');return false">BiDimFeatEdge</a>.
</dl>
</dl>
<a name="RemoveGuideTangent"><dt>

<table><tr><td>o Sub <b>RemoveGuideTangent</b>(<td><script type="text/javascript"> activateLink('Reference','Reference')</script> <td><tt>iGuide</tt>)</table></dt>
<dl>
  <dd>
 Removes a tangent surface of a guide from the lofted surface.
   
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iGuide</tt>
   <dd>      guide curve of the guide from which the tangent will be removed.</dd>
</dl>
</dl>
</dl>
<a name="RemoveSection"><dt>

<table><tr><td>o Sub <b>RemoveSection</b>(<td><script type="text/javascript"> activateLink('Reference','Reference')</script> <td><tt>iSection</tt>)</table></dt>
<dl>
  <dd>
 Removes a loft section from the lofted surface.
 
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iSection</tt>
   <dd>    The loft section to remove<br>
 <br>Sub-element(s) supported (see </dd>
</dl>
<a href="#" onClick="openLink('Boundary','');return false">Boundary</a> object):  
<a href="#" onClick="openLink('TriDimFeatEdge','');return false">TriDimFeatEdge</a> and 
<a href="#" onClick="openLink('BiDimFeatEdge','');return false">BiDimFeatEdge</a>.
</dl>
</dl>
<a name="RemoveSectionPoint"><dt>

<table><tr><td>o Sub <b>RemoveSectionPoint</b>(<td><script type="text/javascript"> activateLink('Reference','Reference')</script> <td><tt>iSection</tt>)</table></dt>
<dl>
  <dd>
 Removes a closing point of a section from the lofted surface.
 The curve section must be closed curve. 
   
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iSection</tt>
   <dd>      section curve of the section from which the point will be removed.</dd>
</dl>
</dl>
</dl>
<a name="RemoveSectionTangent"><dt>

<table><tr><td>o Sub <b>RemoveSectionTangent</b>(<td><script type="text/javascript"> activateLink('Reference','Reference')</script> <td><tt>iSection</tt>)</table></dt>
<dl>
  <dd>
 Removes the tangent surface of a section from the lofted surface.
 The section must be the start section or the end section of the loft. 
   
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iSection</tt>
   <dd>      section curve of the section from which the tangent will be removed.</dd>
</dl>
</dl>
</dl>
<a name="SetEndFaceForClosing"><dt>

<table><tr><td>o Sub <b>SetEndFaceForClosing</b>(<td><script type="text/javascript"> activateLink('Reference','Reference')</script> <td><tt>iFace</tt>)</table></dt>
<dl>
  <dd>
 Sets a face to the end section from the lofted surface.
   
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iFace</tt>
   <dd>      The face to close the loft (Part design only).
 <br>Sub-element(s) supported (see </dd>
</dl>
<a href="#" onClick="openLink('Boundary','');return false">Boundary</a> object):  
<a href="#" onClick="openLink('Face','');return false">Face</a>.
</dl>
</dl>
<a name="SetEndSectionTangent"><dt>

<table><tr><td>o Sub <b>SetEndSectionTangent</b>(<td><script type="text/javascript"> activateLink('Reference','Reference')</script> <td><tt>iTangentSection</tt>)</table></dt>
<dl>
  <dd>
 Sets a tangent surface to the end section from the lofted surface.
   
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iTangentSection</tt>
   <dd>     The tangent surface to be added. The end curve section must lay on the surface.
 <br>Sub-element(s) supported (see </dd>
</dl>
<a href="#" onClick="openLink('Boundary','');return false">Boundary</a> object):  
<a href="#" onClick="openLink('Face','');return false">Face</a>.
</dl>
</dl>
<a name="SetSpine"><dt>

<table><tr><td>o Sub <b>SetSpine</b>(<td><script type="text/javascript"> activateLink('Reference','Reference')</script> <td><tt>iSpine</tt>)</table></dt>
<dl>
  <dd>
 Sets the spine to the lofted surface.
   
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iSpine</tt>
   <dd>     The curve to be added as a spine.
 <br>Sub-element(s) supported (see </dd>
</dl>
<a href="#" onClick="openLink('Boundary','');return false">Boundary</a> object):  
<a href="#" onClick="openLink('TriDimFeatEdge','');return false">TriDimFeatEdge</a> and 
<a href="#" onClick="openLink('BiDimFeatEdge','');return false">BiDimFeatEdge</a>.
</dl>
</dl>
<a name="SetStartFaceForClosing"><dt>

<table><tr><td>o Sub <b>SetStartFaceForClosing</b>(<td><script type="text/javascript"> activateLink('Reference','Reference')</script> <td><tt>iFace</tt>)</table></dt>
<dl>
  <dd>
 Sets a face to the start section from the lofted surface.
   
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iFace</tt>
   <dd>      The face to close the loft (Part design only).
 <br>Sub-element(s) supported (see </dd>
</dl>
<a href="#" onClick="openLink('Boundary','');return false">Boundary</a> object):  
<a href="#" onClick="openLink('Face','');return false">Face</a>.
</dl>
</dl>
<a name="SetStartSectionTangent"><dt>

<table><tr><td>o Sub <b>SetStartSectionTangent</b>(<td><script type="text/javascript"> activateLink('Reference','Reference')</script> <td><tt>iTangentSection</tt>)</table></dt>
<dl>
  <dd>
 Sets a tangent surface to the start section from the lofted surface.
   
<dl>
  <dt> <b>Parameters:</b>
  <dd>
    <dl>
    <dt><tt> iTangentSection</tt>
   <dd>      The tangent surface to be added. The start curve section must lay on the surface.
 <br>Sub-element(s) supported (see </dd>
</dl>
<a href="#" onClick="openLink('Boundary','');return false">Boundary</a> object):  
<a href="#" onClick="openLink('Face','');return false">Face</a>.
</dl>
</dl>

</body>
<hr><p><i>
Copyright &#169; 1999-2011, Dassault Syst&#232;mes. All rights reserved.</i></p>
</html>
